### ISSUE TITLE
Static build needs libopenh264.dll

### ISSUE THREAD

**Issue by yonizaf** [rdp/ffmpeg-windows-build-helpers#100]
The ffmpeg I built with current script complains abount needing libopenh264.dll when it's not there (to do anything, not just when using that lib). It shouldn't work that way, as the idea of a static build should be a single portable EXE, without the need to worry about dll files.

**Comment by rdp** [comment]
could you try with the latest please? (nuke your sandbox folder first). Thanks!

**Comment by yonizaf** [comment]
tried, still the same.

**Comment by rdp** [comment]
make sure you are doing a git pull and have the latest [?]

**Comment by rdp** [comment]
(and nuke sandbox, thanks)

**Comment by yonizaf** [comment]
looks like it's working now. thanks.
