### ISSUE TITLE
Windows XP failure again...

### ISSUE THREAD

**Issue by nicolaasjan** [rdp/ffmpeg-windows-build-helpers#102]
With the ffmpeg version I built yesterday, the 32 bit binary throws the following error window on Windows XP:
"the procedure entry point _vsnprintf_s could not be located in the dynamic library msvcrt.dll"

version info (of the 64 bit version):

ffmpeg version N-77412-g3ff2bef Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/nico/san
dbox/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --pkg-config=pkg-config --disable-
w32threads --enable-gpl --enable-libsoxr --enable-fontconfig --enable-libass --e
nable-libutvideo --enable-libbluray --enable-iconv --enable-libtwolame --extra-c
flags=-DLIBTWOLAME_STATIC --enable-libzvbi --enable-libcaca --enable-libmodplug
--extra-libs=-lstdc++ --extra-libs=-lpng --enable-libvidstab --enable-libx265 --
enable-decklink --extra-libs=-loleaut32 --enable-libx264 --enable-libxvid --enab
le-libmp3lame --enable-version3 --enable-zlib --enable-librtmp --enable-libvorbi
s --enable-libtheora --enable-libspeex --enable-libopenjpeg --enable-gnutls --en
able-libgsm --enable-libfreetype --enable-libopus --enable-frei0r --enable-filte
r=frei0r --enable-libvo-aacenc --enable-bzlib --enable-libxavs --enable-libopenc
ore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroed
inger --enable-libvpx --enable-libilbc --enable-libwavpack --enable-libwebp --en
able-libgme --enable-dxva2 --enable-libdcadec --enable-avisynth --enable-gray --
enable-libopenh264 --extra-libs=-lpsapi --extra-cflags= --enable-static --disabl
e-shared --prefix=/home/nico/sandbox/mingw-w64-x86_64/x86_64-w64-mingw32 --enabl
e-nonfree --enable-libfdk-aac --disable-libfaac --enable-nvenc --enable-runtime-
cpudetect
  libavutil      55. 11.100 / 55. 11.100
  libavcodec     57. 18.100 / 57. 18.100
  libavformat    57. 20.100 / 57. 20.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 21.100 /  6. 21.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100

**Comment by rdp** [comment]
OK the most recently added thing was I believe
libopenh264
Could you try it without that for me?

**Comment by nicolaasjan** [comment]
OK,
I will try tomorrow (its almost bedtime now where I live).

**Comment by nicolaasjan** [comment]
I've just compiled without libopenh264, but it gives the same error...
"the procedure entry point _vsnprintf_s could not be located in the dynamic library msvcrt.dll"

version info of this one (64 bit version):

ffmpeg version N-77434-gb18230e Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/nico/san
dbox/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --pkg-config=pkg-config --disable-
w32threads --enable-gpl --enable-libsoxr --enable-fontconfig --enable-libass --e
nable-libutvideo --enable-libbluray --enable-iconv --enable-libtwolame --extra-c
flags=-DLIBTWOLAME_STATIC --enable-libzvbi --enable-libcaca --enable-libmodplug
--extra-libs=-lstdc++ --extra-libs=-lpng --enable-libvidstab --enable-libx265 --
enable-decklink --extra-libs=-loleaut32 --enable-libx264 --enable-libxvid --enab
le-libmp3lame --enable-version3 --enable-zlib --enable-librtmp --enable-libvorbi
s --enable-libtheora --enable-libspeex --enable-libopenjpeg --enable-gnutls --en
able-libgsm --enable-libfreetype --enable-libopus --enable-frei0r --enable-filte
r=frei0r --enable-libvo-aacenc --enable-bzlib --enable-libxavs --enable-libopenc
ore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroed
inger --enable-libvpx --enable-libilbc --enable-libwavpack --enable-libwebp --en
able-libgme --enable-dxva2 --enable-libdcadec --enable-avisynth --enable-gray --
extra-libs=-lpsapi --extra-cflags= --enable-static --disable-shared --prefix=/ho
me/nico/sandbox/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-nonfree --enable-li
bfdk-aac --disable-libfaac --enable-nvenc --enable-runtime-cpudetect
  libavutil      55. 11.100 / 55. 11.100
  libavcodec     57. 19.100 / 57. 19.100
  libavformat    57. 20.100 / 57. 20.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 21.100 /  6. 21.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100

I see that libavcodec has a higher version number.

**Comment by rdp** [comment]
OK searching for usages I see

libcaca-0.99.beta19/caca/string.c.bak
348:#if defined(HAVE_VSNPRINTF_S)
349:    vsnprintf_s(buf, bufsize, _TRUNCATE, format, args);

libcaca-0.99.beta19/caca/string.c
348:#if defined(HAVE_VSNPRINTF_S)
349:    vsnprintf_s(buf, bufsize, _TRUNCATE, format, args);

libcaca-0.99.beta19/config.h.in
181:/* Define to 1 if you have the `vsnprintf_s' function. */
182:#undef HAVE_VSNPRINTF_S

libcaca-0.99.beta19/config.h
182:/* Define to 1 if you have the `vsnprintf_s' function. */
183:#define HAVE_VSNPRINTF_S 1

libcaca-0.99.beta19/configure.ac
126:AC_CHECK_FUNCS(signal ioctl snprintf sprintf_s vsnprintf vsnprintf_s
getenv putenv strcasecmp htons)

libcaca-0.99.beta19/config.status
1206:D["HAVE_VSNPRINTF_S"]=" 1"

libcaca-0.99.beta19/config.log
1279:configure:16654: checking for vsnprintf_s
1338:| #define HAVE_VSNPRINTF_S 1
1497:| #define HAVE_VSNPRINTF_S 1
1590:| #define HAVE_VSNPRINTF_S 1
1652:| #define HAVE_VSNPRINTF_S 1
1745:| #define HAVE_VSNPRINTF_S 1
1807:| #define HAVE_VSNPRINTF_S 1
1865:| #define HAVE_VSNPRINTF_S 1
1932:| #define HAVE_VSNPRINTF_S 1
2006:| #define HAVE_VSNPRINTF_S 1
2099:| #define HAVE_VSNPRINTF_S 1
2171:| #define HAVE_VSNPRINTF_S 1
2265:| #define HAVE_VSNPRINTF_S 1
2343:| #define HAVE_VSNPRINTF_S 1
2437:| #define HAVE_VSNPRINTF_S 1
2500:| #define HAVE_VSNPRINTF_S 1
2594:| #define HAVE_VSNPRINTF_S 1
2657:| #define HAVE_VSNPRINTF_S 1
2751:| #define HAVE_VSNPRINTF_S 1
2814:| #define HAVE_VSNPRINTF_S 1
2908:| #define HAVE_VSNPRINTF_S 1
2971:| #define HAVE_VSNPRINTF_S 1
3065:| #define HAVE_VSNPRINTF_S 1
3132:| #define HAVE_VSNPRINTF_S 1
3226:| #define HAVE_VSNPRINTF_S 1
3402:ac_cv_func_vsnprintf_s=yes
3788:#define HAVE_VSNPRINTF_S 1

libcaca-0.99.beta19/configure
16651:for ac_func in signal ioctl snprintf sprintf_s vsnprintf vsnprintf_s
getenv putenv strcasecmp htons

libcaca-0.99.beta19/win32/config.h
63:#define HAVE_VSNPRINTF_S 1

openh264/codec/common/src/crt_util_safe_x.cpp
69:  iRc = vsnprintf_s (pBuffer, iSizeOfBuffer, _TRUNCATE, kpFormat,
pArgPtr);
85:  int32_t iRc = vsnprintf_s (pBuffer, iSizeOfBuffer, _TRUNCATE,
kpFormat, pArgPtr);


could you try disabling libcaca as well as openh264?
Not sure what changed though i did bump the gcc version recently.

**Comment by nicolaasjan** [comment]
This one works! :)
Thanks for your time to investigate.
(libcaca seems pretty useless to me anyway)

version info:

ffmpeg version N-77444-gd3b6a9a Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --arch=x86 --target-os=mingw32 --cross-prefix=/home/nico/sandbo
x/mingw-w64-i686/bin/i686-w64-mingw32- --pkg-config=pkg-config --disable-w32thre
ads --enable-gpl --enable-libsoxr --enable-fontconfig --enable-libass --enable-l
ibutvideo --enable-libbluray --enable-iconv --enable-libtwolame --extra-cflags=-
DLIBTWOLAME_STATIC --enable-libzvbi --enable-libmodplug --extra-libs=-lstdc++ --
extra-libs=-lpng --enable-libvidstab --enable-libx265 --enable-decklink --extra-
libs=-loleaut32 --enable-libx264 --enable-libxvid --enable-libmp3lame --enable-v
ersion3 --enable-zlib --enable-librtmp --enable-libvorbis --enable-libtheora --e
nable-libspeex --enable-libopenjpeg --enable-gnutls --enable-libgsm --enable-lib
freetype --enable-libopus --enable-frei0r --enable-filter=frei0r --enable-libvo-
aacenc --enable-bzlib --enable-libxavs --enable-libopencore-amrnb --enable-libop
encore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger --enable-libvpx --
enable-libilbc --enable-libwavpack --enable-libwebp --enable-libgme --enable-dxv
a2 --enable-libdcadec --enable-avisynth --enable-gray --extra-libs=-lpsapi --ext
ra-cflags= --enable-static --disable-shared --prefix=/home/nico/sandbox/mingw-w6
4-i686/i686-w64-mingw32 --enable-nonfree --enable-libfdk-aac --disable-libfaac -
-enable-nvenc --enable-runtime-cpudetect
  libavutil      55. 11.100 / 55. 11.100
  libavcodec     57. 20.100 / 57. 20.100
  libavformat    57. 20.100 / 57. 20.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 21.101 /  6. 21.101
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100

**Comment by rdp** [comment]
if you add openh264 back in does it still fail?

**Comment by nicolaasjan** [comment]
With  '--enable-libopenh264' it works as well! :)

version info:

ffmpeg version N-77449-g57787f5 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --arch=x86 --target-os=mingw32 --cross-prefix=/home/nico/sandbo
x/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32- --pkg-config=pkg-config -
-disable-w32threads --enable-gpl --enable-libsoxr --enable-fontconfig --enable-l
ibass --enable-libutvideo --enable-libbluray --enable-iconv --enable-libtwolame
--extra-cflags=-DLIBTWOLAME_STATIC --enable-libzvbi --enable-libmodplug --extra-
libs=-lstdc++ --extra-libs=-lpng --enable-libvidstab --enable-libx265 --enable-d
ecklink --extra-libs=-loleaut32 --enable-libx264 --enable-libxvid --enable-libmp
3lame --enable-version3 --enable-zlib --enable-librtmp --enable-libvorbis --enab
le-libtheora --enable-libspeex --enable-libopenjpeg --enable-gnutls --enable-lib
gsm --enable-libfreetype --enable-libopus --enable-frei0r --enable-filter=frei0r
 --enable-libvo-aacenc --enable-bzlib --enable-libxavs --enable-libopencore-amrn
b --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger --
enable-libvpx --enable-libilbc --enable-libwavpack --enable-libwebp --enable-lib
gme --enable-dxva2 --enable-libdcadec --enable-avisynth --enable-gray --enable-l
ibopenh264 --extra-libs=-lpsapi --extra-cflags= --enable-static --disable-shared
 --prefix=/home/nico/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --e
nable-nonfree --enable-libfdk-aac --disable-libfaac --enable-nvenc --enable-runt
ime-cpudetect
  libavutil      55. 11.100 / 55. 11.100
  libavcodec     57. 20.100 / 57. 20.100
  libavformat    57. 20.100 / 57. 20.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 21.101 /  6. 21.101
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100

**Comment by rdp** [comment]
OK I made a small change now could you do a favor and try git master to see
if it works in XP now? :)

**Comment by nicolaasjan** [comment]
With the latest script ffmpeg.exe gives the same error again... :(

**Comment by rdp** [comment]
I ended up reverting to libcaca beta 18 or some odd to get this to work,
and I did report a bug upstream to them. Nothing I tried seemed to work.
Such is life :)
-roger-

**Comment by rdp** [comment]
Their official response was (for google followers): Exactly for such cases we add emulation-code to our libmingwex.a.  To
have it within the .def file for msvcrt is for sure nothing we want.
Instead we should add an emulation-code for it, as we did already for
Instead we should add an emulation-code for it, as we did already for
other such functions.  See in our crt the sec_api folder.
