### ISSUE TITLE
Configuring cross_compile_ffmpeg.sh through Windows bat parameters

### ISSUE THREAD

**Issue by nistvan86** [rdp/ffmpeg-windows-build-helpers#103]
I'm trying to assign custom parameters to `cross_compile_ffmpeg.sh` via the `build_locally_with_various_option_prompts.bat` file. I've seen that the first three parameters are actually submitted to the bash script when calling the bash.exe after Cygwin is installed, but parameters added to the bat call doesn't work.

I've also tried creating a similar batch script like `build_locally_gpl_32_bit_option.bat` with the content:
`@build_locally_with_various_option_prompts -d "--compiler-flavors=win64 --high-bitdepth=y --build-intel-qsv=y --disable-nonfree=n --sandbox-ok=y"` but this doesn't work either. Seems like only the first parameter is used, the others are omitted.

The only thing worked so far is duplicating the `build_locally_with_various_option_prompts.bat` file and directly inserting the switches into the call of the bash script, but this is not really elegant. If you update the bat file, I have to merge it to my own file.

Can this be simplified somehow?

**Comment by rdp** [comment]
try removing those quotes around "--compiler-flavors=win64 --high-bitdepth=y --build-intel-qsv=y --disable-nonfree=n --sandbox-ok=y" maybe?

**Comment by rdp** [comment]
OK looks like it was only "taking" the first 3 parameters, bumped it the manual way to like 13 now, let me know if not enough or not working
