### ISSUE TITLE
Use local paths instead of downloading scripts

### ISSUE THREAD

**Issue by AndiDog** [rdp/ffmpeg-windows-build-helpers#105]
You're downloading from `https://raw.githubusercontent.com/rdp/ffmpeg-windows-build-helpers/master/patches/...` everywhere in the scripts. What's the sense it that - it means you can't do local edits and always have to push to GitHub first; also other people can't make any edits directly.

**Comment by rdp** [comment]
The rationale is that this way people can just download the
"cross_compile_ffmpeg.sh" script and run it, and not have to clone the
initial git repo.
Though I guess they have to have git installed anyway, to checkout
things...hmm...

**Comment by AndiDog** [comment]
You're right, I actually just found out that I used the script in that way before.

Maybe a function `local_or_download` would be enough, which takes the script's name, and if it doesn't exist locally, it's downloaded automatically.

**Comment by rdp** [comment]
good idea, will implement it sometime, or patch welcome.

**Comment by rdp** [comment]
OK I discovered that accidentally curl can do this: 8c2490b79ebcc so that is hopefully enough to be able to test local .diff files now ? :)
