### ISSUE TITLE
Add libtool-bin to the missing packages-list for ubuntu/debian

### ISSUE THREAD

**Issue by withmorten** [rdp/ffmpeg-windows-build-helpers#106]
Running ./quick_cross_compile_ffmpeg_fdk_aac_and_x264_using_packaged_mingw64.sh on a debian 8.x produces the following, even with libtool installed:

    Could not find the following execs: libtool
    on ubuntu: sudo apt-get install gcc-mingw-w64-i686 g++-mingw-w64-i686 yasm make automake autoconf git pkg-config libtool
    Install the missing packages before running this script.

A quick google revealed that the libtool binary is actually in libtool-bin, yet is not a dependency of libtool. After installing libtool-bin the script runs fine.

**Comment by rdp** [comment]
attempted in 11f3061 thanks for your contribution
