### ISSUE TITLE
Unknown option "--enable-libvo-aacenc"

### ISSUE THREAD

**Issue by damdinsharav** [rdp/ffmpeg-windows-build-helpers#107]
I am trying to compile on Ubuntu 14.04 but aforementioned error is occurring.

**Comment by damdinsharav** [comment]
https://www.ffmpeg.org/index.html#news

FFMPEG dropped support for libvo-aacenc.

**Comment by AurelioSilver** [comment]
Remove --enable-libvo-aacenc from line 1394.
config_options="$init_options ...

Then it should compile again.

**Comment by damdinsharav** [comment]
Thank you. Also latest commit has removed libvo-aacenc so I'm closing.
