### ISSUE TITLE
configure: error: Unable to link pthread functions

### ISSUE THREAD

**Issue by Phane7** [rdp/ffmpeg-windows-build-helpers#108]
`checking how to hardcode library paths into programs... immediate

checking if i686-w64-mingw32-gcc supports --param inline-unit-growth=3000... yes

checking if i686-w64-mingw32-gcc supports -std=c89... yes

checking if i686-w64-mingw32-gcc supports -std=iso9899:199409... yes

checking if i686-w64-mingw32-gcc supports -std=c99... yes

checking if i686-w64-mingw32-g++ supports -std=c++98... yes

checking for pthread_create in -lpthread... no

configure: error: Unable to link pthread functions

`
Not sure what's causing this issue, but deleting sandbox and starting over got me the same result trying to compile both 32 and 64 bit versions with non-free libraries.

Edit: It appears to be while configuring zbvi-0.2.35. I get one warning:

configure: WARNING: if you wanted to set the --build type, don't use --host.  If a cross compiler is detected then cross compile mode will be used

then a slew of "checking" lines and then the error.

**Comment by rdp** [comment]
full output please?

**Comment by Phane7** [comment]
[log.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/125570/log.txt)

**Comment by rdp** [comment]
are you using the latest of the script?

**Comment by Phane7** [comment]
The one from 5 days ago, yes.

**Comment by Phane7** [comment]
This is still happening for me with the latest script.  Any ideas on how to fix it?

**Comment by rdp** [comment]
hmm builds OK here in OS X, could you try the latest and also try it in an ubuntu VM for me?

**Comment by Phane7** [comment]
Seems to be working with the latest version after rm -Fr sandbox on Linux Mint.

**Comment by Phane7** [comment]
Seems to be working again with the latest version after rm -Rf sandbox

**Comment by rdp** [comment]
ffmpeg config.log file please (that's where it's failing, right?) I have
run into this issue but only on occasion so not able to pin it down yet :|

**Comment by Inkeliz** [comment]
I have the same problem with 64 Bits.
The 32 Bits work fine.

I'm using this:
`--enable-iconv --enable-libtwolame --extra-cflags=-DLIBTWOLAME_STATIC --enable-libmodplug --extra-libs=-lstdc++ --extra-libs=-lpng --enable-decklink --extra-libs=-loleaut32 --enable-libmp3lame --enable-version3 --enable-zlib --enable-librtmp --enable-bzlib --enable-libwebp --enable-avisynth --enable-libopenh264`

The problem appear here:
```
checking for x86_64-w64-mingw32-g++ option to produce PIC... -DDLL_EXPORT -DPIC
checking if x86_64-w64-mingw32-g++ PIC flag -DDLL_EXPORT -DPIC works... yes
checking if x86_64-w64-mingw32-g++ static flag -static works... yes
checking if x86_64-w64-mingw32-g++ supports -c -o file.o... yes
checking if x86_64-w64-mingw32-g++ supports -c -o file.o... (cached) yes
checking whether the x86_64-w64-mingw32-g++ linker (/cygdrive/c/Users/lucas/Downloads/ffmpeg-windows-build-helpers-master2/ffmpeg-windows-build-helpers-master/native_build/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking if x86_64-w64-mingw32-gcc supports --param inline-unit-growth=3000... yes
checking if x86_64-w64-mingw32-gcc supports -std=c89... yes
checking if x86_64-w64-mingw32-gcc supports -std=iso9899:199409... yes
checking if x86_64-w64-mingw32-gcc supports -std=c99... yes
checking if x86_64-w64-mingw32-g++ supports -std=c++98... yes
checking for pthread_create in -lpthread... no
configure: error: Unable to link pthread functions
```

**Comment by Inkeliz** [comment]
_Wrong fix:_

Remove the:
```
build_zvbi() {
  download_and_unpack_file http://sourceforge.net/projects/zapping/files/zvbi/0.2.35/zvbi-0.2.35.tar.bz2
  cd zvbi-0.2.35
    apply_patch https://raw.githubusercontent.com/rdp/ffmpeg-windows-build-helpers/master/patches/zvbi-win32.patch
    apply_patch https://raw.githubusercontent.com/rdp/ffmpeg-windows-build-helpers/master/patches/zvbi-ioctl.patch
    export LIBS=-lpng
    generic_configure " --disable-dvb --disable-bktr --disable-nls --disable-proxy --without-doxygen" # thanks vlc contribs!
    unset LIBS
    cd src
      do_make_and_make_install
    cd ..
#   there is no .pc for zvbi, so we add --extra-libs=-lpng to FFmpegs configure TODO there is a .pc file it just doesn't get installed [?]
#   sed -i.bak 's/-lzvbi *$/-lzvbi -lpng/' "$PKG_CONFIG_PATH/zvbi.pc"
  cd ..
}
```

For now this work.
_I will check and try fix it in correctly way._

**Comment by rdp** [comment]
config.log file please?

**Comment by jftuga** [comment]
I still see this problem on Ubuntu 16.04.

**Comment by rdp** [comment]
do you have a file libpthread.a ?
