### ISSUE TITLE
Freetype url is not working from Russia

### ISSUE THREAD

**Issue by Scratch-net** [rdp/ffmpeg-windows-build-helpers#109]
Since I first started to use this script I could not ever download
http://download.savannah.gnu.org/releases/freetype/freetype-2.5.5.tar.gz
Probably because of some country IP restrictions. Maybe we could use some other url that will be available for everyone?

**Comment by Scratch-net** [comment]
https://download.videolan.org/contrib/freetype-2.5.5.tar.gz seems to work fine from here

**Comment by rdp** [comment]
adopted in 6fc349e thanks for your contribution
