### ISSUE TITLE
ffmpeg build error

### ISSUE THREAD

**Issue by bmccoy11** [rdp/ffmpeg-windows-build-helpers#112]
Waited overnight for this script to do its magic, only to wake up to this error:

Makefile:2: config.mak: No such file or directory
Makefile:64: /common.mak: No such file or directory
Makefile:106: /libavutil/Makefile: No such file or directory
Makefile:106: /library.mak: No such file or directory
Makefile:108: /doc/Makefile: No such file or directory
Makefile:195: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
configuring ffmpeg_git_with_fdk_aac (/cygdrive/d/Brendan/Documents/GitHub/ffmpeg-windows-build-helpers/native_build/ffmpeg_local_builds/sandbox/x86_64/ffmpeg_git_with_fdk_aac) as $ PATH=/cygdrive/d/Brendan/Documents/GitHub/ffmpeg-windows-build-helpers/native_build/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/bin:/usr/bin:/cygdrive/c/Users/Brendan/bin/bin:/cygdrive/c/Program Files (x86)/Git/bin:/cygdrive/c/Program Files (x86)/Git/share/vim/vim74:/cygdrive/c/Users/Brendan/bin/vendor/conemu-maximus5:/cygdrive/c/Users/Brendan/bin/vendor/conemu-maximus5/ConEmu:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files (x86)/Python 2.7:/cygdrive/c/Program Files (x86)/Python 2.7/Scripts:/cygdrive/c/Program Files (x86)/Python34:/cygdrive/c/Program Files (x86)/Python34/Scripts:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/Common Files/Avid:/cygdrive/c/Program Files/Common Files/Avid:/cygdrive/c/Program Files (x86)/QuickTime/QTSystem:/cygdrive/c/Program Files (x86)/Common Files/Acronis/SnapAPI:/cygdrive/c/Android/platform-tools:/cygdrive/c/Program Files (x86)/Windows Live/Shared:/cygdrive/c/Program Files (x86)/Go/bin:/cygdrive/c/Program Files (x86)/Git/cmd:/cygdrive/c/Program Files (x86)/Skype/Phone:/cygdrive/c/Program Files/OpenVPN/bin:/cygdrive/c/Program Files (x86)/nodejs:/cygdrive/c/ProgramData/chocolatey/bin:/cygdrive/c/Ruby22-x64/bin:/cygdrive/c/Program Files/ISC BIND 9/bin:/cygdrive/c/Users/Brendan/bin:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 8/VC/vcpackages:/cygdrive/c/Users/Brendan/AppData/Roaming/npm:/cygdrive/c/RubyDevTools:/cygdrive/c/Program Files (x86)/Microsoft VS Code/bin:/cygdrive/c/Program Files/ffmpeg/bin:/cygdrive/c/Users/Brendan/bin ./configure --arch=x86_64 --target-os=mingw32 --cross-prefix=/cygdrive/d/Brendan/Documents/GitHub/ffmpeg-windows-build-helpers/native_build/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --pkg-config=pkg-config --disable-w32threads --enable-gpl --enable-libsoxr --enable-fontconfig --enable-libass --enable-libutvideo --enable-libbluray --enable-iconv --enable-libtwolame --extra-cflags=-DLIBTWOLAME_STATIC --enable-libzvbi --enable-libcaca --enable-libmodplug --extra-libs=-lstdc++ --extra-libs=-lpng --enable-libvidstab --enable-libx265 --enable-decklink --extra-libs=-loleaut32 --enable-libx264 --enable-libxvid --enable-libmp3lame --enable-version3 --enable-zlib --enable-librtmp --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libopenjpeg --enable-gnutls --enable-libgsm --enable-libfreetype --enable-libopus --enable-frei0r --enable-filter=frei0r --enable-bzlib --enable-libxavs --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger --enable-libvpx --enable-libilbc --enable-libwavpack --enable-libwebp --enable-libgme --enable-dxva2 --enable-libdcadec --enable-avisynth --enable-gray --enable-libopenh264 --extra-libs=-lpsapi --extra-cflags= --enable-static --disable-shared  --prefix=/cygdrive/d/Brendan/Documents/GitHub/ffmpeg-windows-build-helpers/native_build/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-nonfree --enable-libfdk-aac --disable-libfaac --enable-nvenc  --enable-runtime-cpudetect
Unknown option "--enable-libdcadec".
See ./configure --help for available options.`

**Comment by Warblefly** [comment]
According to an FFmpeg developers' mailing list post made very recently, external linking against libdcadec has been disabled because the code has been merged internally.

**Comment by rdp** [comment]
OK attempted to remove the --enable-libdcadec FWIW
