### ISSUE TITLE
building a "fuller" x264.exe

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#113]
Hello.  
I'm not sure if this is useful, or even whether GPLs permit it (advice welcomed), however I managed to luck my way into building an x264 (post ffmpeg build) which (i) is able to read and create MP4 containers (ii) uses LAVF to decode almost any input format (eg .mpg, .mp4) that LAVF can handle.
The script to build it is run after a variation of your script as it depends on an ffmpeg already being built. It is a terrible terrible kludge, not cleaned up at all, and some of the file/folder copies should be rationalised. 
It is just for debugging and trying to understand your script, really. However it does point to the kinds of things which need to be considered to build a "fuller" x264.exe as at March 2016, eg it seemed that the configure file for x264 has a number of non-obvious fixed dependencies, eg things like
- pkg-config had to be copied from /usr/bin/pkg-config into the cross-compiler folder with a different name based on a cross_prefix, since the toolchain build script didn't generage a pkg-config and that the x264 makefile depends on it
- setup of PKG_CONFIG_PATH and PKG_CONFIG_LIBDIR
- copying ffmpeg sources and libraries into specific folders that the x264 makefile checks for
- copying gpac sources into a specific folder and a .a file to specific place with a specific name
- using a custom configure_flags to point to the right places

Would it be useful to post the script (even though it's "incompatible") so a variation could be incorporated into yours ? No is an OK answer.

**Comment by rdp** [comment]
It's an OK build it'll be a GPL end distributable.  That's an interesting
idea hmm...

**Comment by hydra3333** [comment]
OK, example uploaded here.  A total hack.
[example.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/195121/example.txt)

**Comment by hydra3333** [comment]
OK, the matching slightly updated toolchain build script and the matching kludge of an ffmpeg build script based on yours (used by me to try to learn linux bash scripting) which has a couple of slightly updated sources.
[abcd-mingw-w64-build-3.6.7-v9.sh.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/195543/abcd-mingw-w64-build-3.6.7-v9.sh.txt)
[abcd_cross_compile_ffmpeg-v9 .sh.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/195546/abcd_cross_compile_ffmpeg-v9.sh.txt)

**Comment by rdp** [comment]
OK I took this as a good example and plugged a new option into the script that hopefully does this, thank you for your contribution
