### ISSUE TITLE
Build fails vector-gen: not found

### ISSUE THREAD

**Issue by falkben** [rdp/ffmpeg-windows-build-helpers#114]
Had been working up until 3/25.  Pulled the recent commits from github.  Not entirely sure what the problem is.  Attached full log.  Attempting to build x64 version.

[screen.log.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/196144/screen.log.txt)

This is on a debian box running jessie.

**Comment by rdp** [comment]
oops, I broke it, pull and try the latest...

**Comment by falkben** [comment]
Yup, fixed!  Had to delete the sandbox folder, but after that it worked. Thanks!
