### ISSUE TITLE
lots of download

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#115]
Hello.  Just a thought, the script currently consumes a LOT of download especially when building both 32/64 bits and x264 and (eg ffmpeg source code x 4 etc).

In Australia we have capped plans (both speed and for Gb of download, it's expensive over here) and so that hurts a bit.

Would it be possible to consider another approach, eg one download for each source file at the start of the script and then, say, a "local copy from the single download source folder into a local working folder" as required ?  It'd use a tad extra disk space but that's cheap and plentiful.  In the end it'd probably speed up the script too since downloads are slow.

Thanks.

**Comment by rdp** [comment]
Hmm I imagine it downloads quite a bit for the gcc build (but most of it
required)...hmm
You could try adding a

--depth 1

to the git clone option and see if that decreases bandwidth required
everywhere [?]

Is there any one particular thing that consumes a lot of bandwidth I wonder?

**Comment by rdp** [comment]
For now, if bandwidth is prohibitive you could rent a VM in the US, build
it there, then copy it over, as well, FWIW.
Cheers!

**Comment by rdp** [comment]
OK closing as "pull request welcome" thank you
