### ISSUE TITLE
trouble compiling openh264

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#116]
Hello.  Got this error today.
> Doing git fetch openh264 in case it affects the desired branch [24916a652ee5d3]
> abcd: git fetch
> done downloading openh264, about to do: update_to_desired_git_branch_or_revision . 24916a652ee5d3
> abcd: entered: update_to_desired_git_branch_or_revision
> ~/Desktop/abcd/ffmpeg-windows-build-helpers-master/sandbox/win32/openh264 ~/Desktop/abcd/ffmpeg-windows-build-helpers-master/sandbox/win32/openh264
> we are about to do git checkout'ing 24916a652ee5d3
> abcd: git checkout 24916a652ee5d3
> error: pathspec '24916a652ee5d3' did not match any file(s) known to git.

Then saw this.
> https://ffmpeg.org/pipermail/ffmpeg-devel/2016-March/190984.html
> Mon Mar 7 18:05:41 CET 2016
> Now FFmpeg requires openh264 at least at version 1.6.

I wonder, something I did, or does the script need an update ?

**Comment by rdp** [comment]
was that with any changes to the script?
I tried it today and it seemed to be able to checkout that branch (now
whether that git commit is an OK version of openh264 I don't know...)

**Comment by hydra3333** [comment]
Yes. I must have done something wrong although I thought I didn't touch that bit. Sorry.

**Comment by rdp** [comment]
seems to work ok here now...
