### ISSUE TITLE
curl SSL certificate verification problem

### ISSUE THREAD

**Issue by falkben** [rdp/ffmpeg-windows-build-helpers#119]
Having a problem with curl and SSL.  Maybe the attached log will help?

[log.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/213390/log.txt)

**Comment by rdp** [comment]
do you still get this? I had an OK build today with 15.10
I wonder if it's just an issue with that one server hrm...

**Comment by falkben** [comment]
This issue doesn't seem to be a problem any longer.  However, it's still not building the second time I run it.  I have to clear out my "sandbox" folder each time.

**Comment by falkben** [comment]
It doesn't look like my other issue is related to this curl SSL verification - closing.
