### ISSUE TITLE
build-x264-with-libav doesn't work

### ISSUE THREAD

**Issue by kajott** [rdp/ffmpeg-windows-build-helpers#121]
The option --build-x264-with-libav=y doesn't have any influence: The "x264" and "x264_with_libav" builds are identical. This is due to an issue in x264's configure script:
```
checking for sws_init_context(0,0,0); in libswscale/swscale.h... no
Failed commandline was:
--------------------------------------------------
/home/martin/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-gcc conftest.c -m32  -Wall -I. -I$(SRCPATH) -march=i686 -mfpmath=sse -msse -msse2 -std=gnu99 -mpreferred-stack-boundary=5   -lswscale -lavutil  -lshell32 -m32   -Wl,--large-address-aware -Wl,--dynamicbase,--nxcompat,--tsaware -o conftest
conftest.c: In function 'main':
conftest.c:2:19: warning: ignoring return value of 'sws_init_context', declared with attribute warn_unused_result [-Wunused-result]
 int main (void) { sws_init_context(0,0,0); return 0; }
                   ^
/home/martin/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/lib/../lib/libavutil.a(log.o): In function `av_log_default_callback':
/home/martin/ffmpeg-windows-build-helpers/sandbox/win32/ffmpeg_git_with_fdk_aac/libavutil/log.c:321: undefined reference to `pthread_mutex_lock'
/home/martin/ffmpeg-windows-build-helpers/sandbox/win32/ffmpeg_git_with_fdk_aac/libavutil/log.c:360: undefined reference to `pthread_mutex_unlock'
collect2: error: ld returned 1 exit status
--------------------------------------------------
Failed program was:
--------------------------------------------------
#include <libswscale/swscale.h>
int main (void) { sws_init_context(0,0,0); return 0; }
--------------------------------------------------
```
As can be seen, the configure script's test program for libswscale fails to build because the dependency to libpthread isn't resolved. x264 doesn't want to use the FFmpeg libraries at all if swscale doesn't work, so the build ends up identical to the non-FFmpeg one.

I fixed it locally by editing configure.sh and adding
`SWSCALE_LIBS="$SWSCALE_LIBS -lpthread"`
at the appropriate place to sandbox/{win32,x86_64}/x264_with_libav_normal_bitdepth/configure.sh, deleting the associated "already_configured" files and running cross_compile_ffmpeg.sh again, but it would be nice if there was a generic fix for that issue.

**Comment by rdp** [comment]
x264 doesn't use ffmpeg and allows configure to just ignore the failed
directive? ai ai...I'll look at this sometime, thanks for the note.

**Comment by rdp** [comment]
Could you try it with 4501bd0 please?

**Comment by kajott** [comment]
4501bd0 didn't help; in fact, it made it worse ;) But now that I know where to look, I can propose a fix that should actually work (at least it did for me):
```
diff --git a/cross_compile_ffmpeg.sh b/cross_compile_ffmpeg.sh
index 0dc1412..65e1710 100755
--- a/cross_compile_ffmpeg.sh
+++ b/cross_compile_ffmpeg.sh
@@ -573,7 +573,7 @@ build_libx264() {
     # they don't know how to use a normal pkg-config when cross compiling, so specify some manually: (see their mailing list for a request...)
     export LAVF_LIBS="$LAVF_LIBS $(pkg-config --libs libavformat libavcodec libavutil libswscale)"
     export LAVF_CFLAGS="$LAVF_CFLAGS $(pkg-config --cflags libavformat libavcodec libavutil libswscale)"
-    export SWSCALE_LIBS="$SWSCALE_LIBS -lpthread"
+    export SWSCALE_LIBS="$SWSCALE_LIBS $(pkg-config --libs libswscale)"
   fi
 
   local x264_profile_guided=n # or y -- haven't gotten this proven yet...TODO
```

**Comment by rdp** [comment]
That makes good sense.
Dang thought I had it but looks like I misread the file sizes (LOL guess
high bitdepth also increases file size quite a bit).
OK try it now with 28774a539ed82ab
Cheers!
-roger-

**Comment by kajott** [comment]
Yes, 28774a5 is exactly what I meant.
Thanks for the quick reaction times, and keep up the good work!

**Comment by birdty** [comment]
hey rodger I am adding some perl code to my github repositories checkout bibliopolis
https://github.com/birdty

It will eventually be an onlinebook seller platform

**Comment by rdp** [comment]
perl FTW :)

**Comment by birdty** [comment]
ftw does that mean for the win?

**Comment by rdp** [comment]
yep
