### ISSUE TITLE
Debian 8 - Missing requirement

### ISSUE THREAD

**Issue by N0N0** [rdp/ffmpeg-windows-build-helpers#122]
for Debian 8.4.0 package 'ed' has to be added in the errorinfo of cross_compie_XXXX.sh

**Comment by rdp** [comment]
OK put a note in the README, if that's what you were asking for... :)

**Comment by N0N0** [comment]
You understood me^^ thank you.

Btw. Script just completed 3h ago on a fresh installed debian 8.0.2 x64 server vm. Thank you very much for that :)
