### ISSUE TITLE
CentOS 7.2 - libbs2b-3.1.0.tar.lzma and libsndfile

### ISSUE THREAD

**Issue by cjplay93** [rdp/ffmpeg-windows-build-helpers#123]
Downloaded and ran yesterday after a fresh "yum update" doing a KDE install of CentOS 7.2 (1511)

I got a handful of errors when the libbs2b-3.1.0.tar.lzma file came.  From corrupt download to "unable to open".  I changed it to the tar.gz file from Sourceforge and the load completed successfully.

Also, it got to libsndfile and asked me to load it.  Even after a yum install libsndfile*, it failed.  I tried another run with the "build_libsndfile" commented-out and it still asked me to install it for libbbs2b.

Great script, btw.  I've used it a few times now.

**Comment by rdp** [comment]
OK changed the libbs2b to .tar.gz

What do you mean by "asked you to load" libsndfile?Do you have wine
installed perhaps?

**Comment by cjplay93** [comment]
I will check on wine, but doubtful.  When libbs2b runs its compile, it can't see libsndfile and asks for its installation before failing.  If I run the configure for libbs2b outside of the script, it finishes fine.  I have tried root and not root in both cases.  I am running in a VM.

Thanks,
Chris Henderson, +1 562-309-1907, chrihend@cisco.com

**Comment by rdp** [comment]
Odd. libsndfile compiled and installed OK (cross compile wise)? you should
not need to yum install anything libsndfile related FWIW, that's just for
the linux side of things :)

**Comment by rdp** [comment]
please reopen if you run into this still/again :)
