### ISSUE TITLE
crash burn error building vp8, unknown type name mode_t

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#126]
Hello. Under vanilla ubuntu 16.04, the script crashes when trying to build libvpx (log below).  Suggestions welcome. The only thing I changed in the script was to comment out build  libutvideo like this #build_libutvideo since it refused to build.

making /home/u/Desktop/efgh/ffmpeg-windows-build-helpers-master/sandbox/win32/libvpx_git as $ PATH=/home/u/Desktop/efgh/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/bin:$PATH make  -j 2

    [CREATE] vpx_scale_rtcd.h
    [CREATE] vpx_dsp_rtcd.h
    [CREATE] vp8_rtcd.h
    [CREATE] vp9_rtcd.h
    [CREATE] vp10_rtcd.h
    [DEP] test/test_intra_pred_speed.cc.d
...snip...
    [CC] vp8/common/x86/loopfilter_x86.c.o
    [CC] vp8/common/mfqe.c.o
    [CC] vp8/common/postproc.c.o
    [CC] vp8/common/x86/idct_blk_mmx.c.o
    [CC] vp8/common/x86/idct_blk_sse2.c.o
    [CC] vp8/vp8_cx_iface.c.o
    [CC] vp8/encoder/bitstream.c.o
In file included from ./vp8/common/threading.h:69:0,
                 from vp8/encoder/onyx_int.h:25,
                 from vp8/encoder/encodemv.h:15,
                 from vp8/encoder/bitstream.c:13:
/home/u/Desktop/efgh/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/include/semaphore.h:152:8: error: unknown type name 'mode_t'
        mode_t mode,
        ^
Makefile:152: recipe for target 'vp8/encoder/bitstream.c.o' failed
make[1]: *** [vp8/encoder/bitstream.c.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ./vp8/common/threading.h:69:0,
                 from ./vp8/encoder/onyx_int.h:25,
                 from vp8/vp8_cx_iface.c:21:
/home/u/Desktop/efgh/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/include/semaphore.h:152:8: error: unknown type name 'mode_t'
        mode_t mode,
        ^
Makefile:152: recipe for target 'vp8/vp8_cx_iface.c.o' failed
make[1]: *** [vp8/vp8_cx_iface.c.o] Error 1
Makefile:17: recipe for target '.DEFAULT' failed
make: *** [.DEFAULT] Error 2
u@ubuntu:~/Desktop/efgh/ffmpeg-windows-build-helpers-master$

**Comment by hydra3333** [comment]
my build line is this -
sudo ./cross_compile_ffmpeg.sh --gcc-cpu-count=2 --sandbox-ok=y --build-ffmpeg-shared=n --build-ffmpeg-static=y --disable-nonfree=n --build-x264-with-libav=y --build-intel-qsv=y --build-libmxf=n --build-mp4box=y --build-mplayer=n --build-vlc=y --git-get-latest=y --prefer-stable=n --high-bitdepth=n --compiler-flavors=multi --cflags=-march=sandybridge

**Comment by hydra3333** [comment]
It seems this could be related ?
https://groups.google.com/a/webmproject.org/forum/#!msg/codec-devel/2qFuBg8x3y0/wmL3z85gHgAJ

**Comment by rdp** [comment]
maybe we need to freeze it at a known good version :|

**Comment by hydra3333** [comment]
Sounds like a plan. Or, maybe, I notice you seem to apply some patches to some sources ... one of this links says this:

#include <sys/types.h>
...immediately before semaphore.h makes the compile-time error go away.

:)

**Comment by smoothstreams** [comment]
I can't wait for a fix and update.  I want to do an updated build :)

**Comment by rdp** [comment]
Seems the configure is even broken these days "unknown parameter --enable-web10" or some odd.
So I removed its unstable version for now, at least things build :)
and bumped the normal to 1.5.0
If you really want the git for vpx, let me know or send a pull request, thanks!

**Comment by Jan-E** [comment]
I tried to compile vpx 1.6.0 and stumbled into the same mode_t error, so maybe it is a good idea to resolve this anyway

**Comment by anonymous2ch** [comment]
You just need to add 1 line:
#include <sys/types.h>
before the last occurrence of the line:
#include <semaphore.h>
in the 'vp8/common/theading.h'

**Comment by Warblefly** [comment]
​
On Mon, Oct 3, 2016 at 10:43 AM, anonymous2ch <notifications@github.com>
 wrote:

> You just need to add 1 line:
> #include
> before the last occurrence of the line:
> #include
> in the 'vp8/common/theading.h'
>
This works for me. Also, the vp10 codec code is now in a separate branch in
the vpx tree (nextgen2 I think). The master branch holds vp8 and vp9.

--- vp8/common/threading.h.orig 2016-04-03 09:28:31.359000000 +0000
+++ vp8/common/threading.h 2016-04-03 09:29:11.699000000 +0000
@@ -66,6 +66,7 @@
 #include <unistd.h>

 #else
+#include <sys/types.h>
 #include <semaphore.h>
 #endif

​

**Comment by rdp** [comment]
Has this been fixed anywhere "upstream" anyone know?

**Comment by anonymous2ch** [comment]
Nope, it hasn't. I tried to compile libvpx from git just a few hours ago and run into this error.

**Comment by rdp** [comment]
OK I reported this to mingw-w64 at least, will just work around it for now, thanks all for youe help.

**Comment by rdp** [comment]
work around applied 8c2490b79ebc

**Comment by rdp** [comment]
I can confirm this still isn't fixed upstream :)

**Comment by rdp** [comment]
for followers, this can also mean you need/want to do a 
rm -rf sandbox/*/libvpx_git  cleared itself up once for me.
