### ISSUE TITLE
Unknown encoder 'libfdk_aac' error during encode despite --disable-nonfree=n

### ISSUE THREAD

**Issue by ogrgkyle** [rdp/ffmpeg-windows-build-helpers#129]
The --disable-nonfree=n option doesn't seem to work, because when I try an ffmpeg encode, it says Unknown encoder 'libfdk_aac'.

**Comment by rdp** [comment]
what's your output from
ffmpeg -codecs
?

**Comment by ogrgkyle** [comment]
Here's the output: http://pastebin.com/0zU1ZXd4

**Comment by rdp** [comment]
full output please?

**Comment by ogrgkyle** [comment]
I did `ffmpeg -codecs > output.txt` and that paste is the result.  What should I have done?

**Comment by rdp** [comment]
I need the first few lines that show the configure parameters

**Comment by ogrgkyle** [comment]
Here you go: http://pastebin.com/wE9NLi6f

**Comment by rdp** [comment]
that ffmpeg is I think may not one from my builds since they would list the
prefix, etc...

**Comment by ogrgkyle** [comment]
I built it by doing `./cross_compile_ffmpeg.sh --disable-nonfree=n`.  I pressed `n` for any yes/no options.  Maybe I should try again.

**Comment by rdp** [comment]
Are you running the one you built worth double checking

**Comment by ogrgkyle** [comment]
Ahhhh.... I think my Windows PATH variable is probably wrong, even though I thought I directed it to my new build.  I will have to check.  When I access ffmpeg.exe directly, libfdk_aac works:
http://pastebin.com/eHQ0D9hi

**Comment by ogrgkyle** [comment]
The path is correct, but maybe something else is conflicting with it.  I don't see anything, though.
