### ISSUE TITLE
Threading

### ISSUE THREAD

**Issue by mdalacu** [rdp/ffmpeg-windows-build-helpers#133]
I have succesfully comiled ffmpeg.exe on Ubuntu x64 16.04. Thank you very much.
I have thees warnings when encoding. I have compiled ffmpeg with the default options, only libzvbi was diabled, i could not compile with it.
```

 [h264 @ 007c1d20] Warning: not compiled with thread support, using thread emulation
[ac3 @ 04863020] Warning: not compiled with thread support, using thread emulation
```

**Comment by mdalacu** [comment]
I have deleted **--disable-w32threads** and now i do not have any warnings. No sideeffects that i can see.

**Comment by rdp** [comment]
seems somehow your pthreads is broken hmm...
ffmpeg config.log please?

**Comment by rdp** [comment]
well, reopen if you can provide more info (zvbi failing is also odd). Cheers!
