### ISSUE TITLE
gnutls-3.4.10 fails to download

### ISSUE THREAD

**Issue by bondurantdt** [rdp/ffmpeg-windows-build-helpers#134]
Line 962, the link for gnutls-3.4.10 is no longer valid.  Oddly enough it is not valid even directly on https://www.gnutls.org/download.html.  

Either way, changing this link in line 962 to ftp://ftp.ring.gr.jp/pub/net/gnupg/gnutls/v3.4/gnutls-3.4.10.tar.xz from their official mirror list resolves the problem.

(Compiled on Win10-64)

**Comment by rdp** [comment]
OK using the mirror you mentioned until gnutls can get their act together :|

**Comment by rdp** [comment]
OK gnutls normal download hopefully working and used again
