### ISSUE TITLE
Bitdefender will block the install

### ISSUE THREAD

**Issue by Inkeliz** [rdp/ffmpeg-windows-build-helpers#136]
I suggest add a note in page to disable the anti-virus software or similar software.

I use the Bitdefender and the Bitdefender have blocked the "i686-w64-mingw32\libstdc++-v3\a.exe".
I don't know why and not have any explanation about.

Bitdefender users: consider disable it or not will work. 👍

**Comment by rdp** [comment]
does bitdefender ... a least tell you it's blocking it or some notification?

**Comment by Inkeliz** [comment]
Bitdefender show a "pop-up" when block.

I found it in the "events":
![bitdefender](https://cloud.githubusercontent.com/assets/4644332/16357384/a1392076-3acb-11e6-803b-0220a1f0964c.png)

_The file [Location] is infected by Gen:Heur.SWF.1.
The virus have been blocked successful and now your PC is safe._


After this is impossible install.
You need disable the Bitdefender and need to extract the "ffmpeg-windows-build-helpers" to a new folder and start the ".bat" again.

**Comment by rdp** [comment]
hmm well hopefully the popup is enough for people [?]

**Comment by rdp** [comment]
OK popup is enough warning I think :)
