### ISSUE TITLE
libfontconfig.a(fccache.o):fccache.c:(.text+0x6b): undefined reference to `_mm_mfence'

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#137]
Hello.  I received an error and am not sure what to do next, please see below.
Vanilla Ubuntu 16.04 freshly installed into a VM and updated today and the latest script downloaded today as well.
Suggestions welcomed.

**Commandline:**
`sudo ./cross_compile_ffmpeg.sh --gcc-cpu-count=2 --sandbox-ok=y --build-ffmpeg-shared=n --build-ffmpeg-static=y --disable-nonfree=n --build-x264-with-libav=y --build-intel-qsv=y --build-libmxf=n --build-mp4box=y --build-mplayer=n --build-vlc=y --git-get-latest=y --prefer-stable=n --high-bitdepth=n --compiler-flavors=multi --cflags=-march=sandybridge`

**Copy of console output**
>   CC       fcstat.lo
>   CC       fcstr.lo
>   CC       fcweight.lo
>   CC       fcxml.lo
>   CC       ftglue.lo
> echo Generating fontconfig.def
> Generating fontconfig.def
> (echo EXPORTS; \
> (cat ../fontconfig/fontconfig.h ../src/fcdeprecate.h ../fontconfig/fcprivate.h ../fontconfig/fcfreetype.h || echo 'FcERROR ()' ) | \
> /bin/grep '^Fc[^ ]* *(' | /bin/sed -e 's/ *(.*$//' -e 's/^/	/' | \
> sort; \
> echo LIBRARY libfontconfig-1.dll; \
> echo VERSION 10.0) >fontconfig.def
>   CC       fcarch.o
>   CCLD     libfontconfig.la
>   CCLD     fcarch.exe
> make[3]: Leaving directory '/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/win32/fontconfig-2.11.94/src'
> make[2]: Leaving directory '/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/win32/fontconfig-2.11.94/src'
> Making all in fc-cache
> make[2]: Entering directory '/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/win32/fontconfig-2.11.94/fc-cache'
>   CC       fc-cache.o
>   CCLD     fc-cache.exe
> ../src/.libs/libfontconfig.a(fccache.o):fccache.c:(.text+0x6b): undefined reference to `_mm_mfence'
> ../src/.libs/libfontconfig.a(fccfg.o):fccfg.c:(.text+0x7): undefined reference to `_mm_mfence'
> ../src/.libs/libfontconfig.a(fcdefault.o):fcdefault.c:(.text+0x7): undefined reference to `_mm_mfence'
> ../src/.libs/libfontconfig.a(fcobjs.o):fcobjs.c:(.text+0x7): undefined reference to `_mm_mfence'
> ../src/.libs/libfontconfig.a(fcxml.o):fcxml.c:(.text+0x7): undefined reference to `_mm_mfence'
> collect2: error: ld returned 1 exit status
> Makefile:492: recipe for target 'fc-cache.exe' failed
> make[2]: *** [fc-cache.exe] Error 1
> make[2]: Leaving directory '/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/win32/fontconfig-2.11.94/fc-cache'
> Makefile:579: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/win32/fontconfig-2.11.94'
> Makefile:463: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by rdp** [comment]
Seems to compile OK, it "Just works"
what's your config.log for fontconfig?
I think I might be a version of ubuntu back, but you'd think that wouldn't
matter :|

**Comment by rdp** [comment]
OK appears to be the -march stuff, still investigating it... https://lists.libav.org/pipermail/libav-devel/2015-October/072425.html

**Comment by hydra3333** [comment]
Oh thank goodness, thank goodness, you found something.  My searching didn't reveal that link.
Ubuntu 15.10 is the same. Would have tried 15.04 (at least one of which worked for me in the past) but will wait for your advice.

**Comment by rdp** [comment]
Yeah took some digging.
Appears that it still fails even with mingw-w64 "git" version so recommend using -mtune=generic for now (which does work) or maybe something else, dunno :)

Will try and file something with mingw as well...

**Comment by rdp** [comment]
OK reported it here:

https://sourceforge.net/p/mingw-w64/mailman/message/35188208/

guess a workaround is to add an extra #include <intrin.h> or something like that...

or I guess for fontconfig I could have it *not* take modified CFLAGS? hmmm

**Comment by rdp** [comment]
OK worked around by not using cflags for fontconfig

**Comment by hydra3333** [comment]
Thank you !

**Comment by oyvindln** [comment]
Any particular reason this workaround commented out? I'm getting the same linking errors when using -march=xxx on a 32-bit build unless I uncomment the workaround.

**Comment by rdp** [comment]
Hmm it's definitely not clear why we would have to *set* the march setting what?
