### ISSUE TITLE
Could not find "nasm" (on Windows)

### ISSUE THREAD

**Issue by TheSHEEEP** [rdp/ffmpeg-windows-build-helpers#139]
When using the build_locally_with_various_option_prompts.bat, I get the following error after installing Cygwin:

> Could not find the following execs (svn is actually package subversion, makeinfo is actually package texinfo if you're missing them): nasm
> Install the missing packages before running this script.

Downloading and putting nasm executables manually fixes the problem and the script is able to continue.

**Comment by rdp** [comment]
OK could you try with the latest now?

**Comment by rdp** [comment]
closing assuming working now :)
