### ISSUE TITLE
Use single branch clone for speed

### ISSUE THREAD

**Issue by Scratch-net** [rdp/ffmpeg-windows-build-helpers#141]
Hi!
What about cloning only the needed branch which can be faster and save space? 
```
git clone <url> --branch <branch> --single-branch [<folder>]
```

**Comment by rdp** [comment]
for most dependencies that would work well...but some of them it's a bit more tricky, like there are "options" with x264 as to whether you want the stable branch or not, so at git clone time you'd have to take that into consideration, and for ffmpeg, what if people want to build a particular release, they might need "all branches" in that case (plus the fact that, typically...the git clone does not feel like the bottleneck to me, except possibly for ffmpeg...hmm...)

**Comment by Scratch-net** [comment]
Yeah, it's a more of a "nice to have for some of them" thing. At least for those that are hardcoded and can't be changed via configuration

**Comment by rdp** [comment]
there's another one it's like git clone depth or something like that...

**Comment by Scratch-net** [comment]
you are the boss :)

**Comment by rdp** [comment]
:) thanks for the discussion too
