### ISSUE TITLE
May be in my env. not sure

### ISSUE THREAD

**Issue by chrisgh1** [rdp/ffmpeg-windows-build-helpers#142]
I needed to add an option to curl --insecure it kept failing when trying to download from sourceforge for one of the packages.  I changed line 408 to 

  curl --insecure -4 $url -O || exit 1

from

  curl -4 $url -O || exit 1

**Comment by rdp** [comment]
what failure message?

**Comment by chrisgh1** [comment]
sorry about that turns out my router was dying and started doing some strange stuff.  I tested in another env. and everything works great.
