### ISSUE TITLE
isl-0.14.tar.bz2

### ISSUE THREAD

**Issue by jpham986** [rdp/ffmpeg-windows-build-helpers#144]
Just try to recompile ffmpeg - and notice that whenever it try to download isl-0.14.tar.bz2
the wget just take forever to download, then bzip2 reports that it couldn't open
so I check - and t he file size is 0

so can someone check if the size that host isl-0.14.tar.bz2 is ok? or where do I modify the download site in the script?

====================
trace

bzip2: Compressed file ends unexpectedly;
        perhaps it is corrupted?  *Possible* reason follows.
bzip2: No error
        Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

pax: End of archive volume 1 reached
ATTENTION! pax archive volume change required.

Ready for archive volume: 1
Input archive name or "." to quit pax.
Archive name >

**Comment by rdp** [comment]
hmm I've had similar problems before but with dependencies not the other
stuff.
the host is ftp://gcc.gnu.org or some odd...hmm... anyway I put in a tiny
thing that might help, giv eit a shot

**Comment by rdp** [comment]
I bumped the isl version, give it a gander

**Comment by rdp** [comment]
ping me if comes back reliably

**Comment by jpham986** [comment]
still doesn't work - still stuck on downloading isl

**Comment by jpham986** [comment]
perhaps it is the site that host isl is having problem, is there other
reliable site that you should use
instead of the current one ?

**Comment by jpham986** [comment]
here is the error when it time out

[24/54]: Installing mpc... done
[25/54]: Downloading isl-0.12.2.tar.bz2... ./mingw-w64-build-3.6.7.local:
line 482: exit: unable to download ftp://gcc.gnu.org/pub/g
cc/infrastructure/isl-0.12.2.tar.bz2: numeric argument required
failure building 64 bit gcc? recommend nuke sandbox (rm -rf sandbox) and
start over...
done with local build...check output above to see if successfull..
if not successful you might try re running the script, it "should" pick up
where it left off.

**Comment by rdp** [comment]
does it work now? you say it is sporadic?

**Comment by jpham986** [comment]
it is never sporadic - it always fail when downloading isl
I just download the latest, and yes it seems to stuck on isl, and no doubt
fail

perhaps you should change the cygwin hosting site to something else ?
where would I change it in the code - is there a constant on top somewehre

thanks

**Comment by rdp** [comment]
interesting, ftp must not be working from your location for "whatever
reason" try the latest please?

**Comment by jpham986** [comment]
The latest version works !!!

thanks - what is the change ?

**Comment by jpham986** [comment]
I speak too soon, I saw isl download but the rest doesnt download
cloog couldnt be download

[image: Inline image 1]

**Comment by rdp** [comment]
OK try latest :)

**Comment by jpham986** [comment]
latest has a problem
on download phtread

here is the trace

[45/54]: Building gcc... done
[46/54]: Installing gcc... done
[47/54]: Downloading pthreads-w32-2-9-1-release.tar.gz...

and it just sit there...been like that for the last couple hour

thanks

**Comment by jpham986** [comment]
it finally timed out , it seems to build (?) but also time out on curl
getting zlib
here's the trace


thanks

===================================================================================================
[45/54]: Building gcc... done
[46/54]: Installing gcc... done
[47/54]: Downloading pthreads-w32-2-9-1-release.tar.gz...
./mingw-w64-build-3.6.7.local: line 482: exit: unabl
urceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.tar.gz: numeric
argument required
Done building (or already built) MinGW-w64 cross-compiler(s) successfully...
Wed Aug 31 19:46:08 PDT 2016


**************Starting 64-bit builds...
Downloading (via git clone) dlfcn-win32_git from
https://github.com/dlfcn-win32/dlfcn-win32.git
Cloning into 'dlfcn-win32_git.tmp'...
remote: Counting objects: 288, done.
Receiving objects:  38remote: Total 288 (delta 0), reused 0 (delta 0),
pack-reused 288% 110/288)
Receiving objects: 100% (288/288), 74.85 KiB | 0 bytes/s, done.
Resolving deltas: 100% (150/150), done.
Checking connectivity... done.
done git cloning to dlfcn-win32_git
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Updating to latest dlfcn-win32_git git version [origin/master]...
Already up-to-date.
got no code changes, not forcing reconfigure for that...
configuring dlfcn-win32_git
(/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/x86_
64/dlfcn-win32_git) as $
PATH=/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cro
ss_compilers/mingw-w64-x86_64/bin:/usr/bin:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Windows/system32:/cygdrive/c/Win
dows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program
Files (x86)/QuickTime
/QTSystem:/cygdrive/c/Program Files (x86)/NVIDIA
Corporation/PhysX/Common:/cygdrive/c/Program
Files/Git/cmd:/cygdrive/c/MinGW/bin:/c
ygdrive/c/Program Files/x264:/cygdrive/c/Program Files
(x86)/crimson:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/Windows
Perfor
mance Toolkit:/cygdrive/c/Program Files/Microsoft SQL
Server/110/Tools/Binn:/cygdrive/c/Users/aba/.dnx/bin:/cygdrive/c/Program
Files
/Microsoft DNX/Dnvm:/cygdrive/c/Users/aba/.dnx/bin:/cygdrive/c/Program
Files/GPAC:/cygdrive/c/Program Files/ffmpeg ./configure --dis
able-shared --enable-static
--cross-prefix=/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_build
s/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-
--prefix=/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native
_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
testing compiler:
/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers
/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc -shared -o tmptest.dll
tmptest.c
prefix:
/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64
-x86_64/x86_64-w64-mingw32
libdir: ${prefix}/lib
incdir: ${prefix}/include
ar:
/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64
-x86_64/bin/x86_64-w64-mingw32-ar
cc:
/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64
-x86_64/bin/x86_64-w64-mingw32-gcc
ranlib:
/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64
-x86_64/bin/x86_64-w64-mingw32-ranlib
strip:
/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64
-x86_64/bin/x86_64-w64-mingw32-strip
static: yes
shared: no
wine:
doing preventative make clean
rm -f \
        dlfcn.o \
        libdl.dll libdl.a libdl.def libdl.dll.a libdl.lib libdl.exp \
        tmptest.c tmptest.dll \
        test.exe testdll.dll

making
/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/x86_64/dlfcn-win32_git
as
$
PATH=/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-
x86_64/bin:$PATH make  -j 28

/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/
bin/x86_64-w64-mingw32-gcc -o dlfcn.o -c dlfcn.c -Wall -O3
-fomit-frame-pointer
/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/
bin/x86_64-w64-mingw32-ar cru libdl.a dlfcn.o
/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/
bin/x86_64-w64-mingw32-ranlib libdl.a
make installing
/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/x86_64/dlfcn-win3
2_git as $
PATH=/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/m
ingw-w64-x86_64/bin:$PATH make install
mkdir -p
/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w6
4-x86_64/x86_64-w64-mingw32/include
install -m 644 dlfcn.h
"/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_com
pilers/mingw-w64-x86_64/x86_64-w64-mingw32/include"
mkdir -p
/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w6
4-x86_64/x86_64-w64-mingw32/lib
cp libdl.a
/cygdrive/g/ffmpeg_work/ffmpeg-windows_6/ffmpeg_w/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-
w64-x86_64/x86_64-w64-mingw32/lib
downloading
https://sourceforge.net/projects/libpng/files/zlib/1.2.8/zlib-1.2.8.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
  0   349    0     0    0     0      0      0 --:--:-- --:--:--
--:--:--     0
  0 15255    0     0    0     0      0      0 --:--:--  0:00:01
--:--:--     0
  0   343    0     0    0     0      0      0 --:--:--  0:00:01
--:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:05:01
--:--:--     0
curl: (28) Connection timed out after 300104 milliseconds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
  0 15170    0     0    0     0      0      0 --:--:-- --:--:--
--:--:--     0
  0 15254    0     0    0     0      0      0 --:--:--  0:00:01
--:--:--     0
  0   343    0     0    0     0      0      0 --:--:--  0:00:01
--:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:05:01
--:--:--     0
curl: (28) Connection timed out after 300049 milliseconds
done with local build...check output above to see if successfull..
if not successful you might try re running the script, it "should" pick up
where it left off.

if you want more advanced configuration (like building mplayer or mp4box,
10-bit, etc)
open
G:\ffmpeg_work\ffmpeg-windows_6\ffmpeg_w\native_build\windows\ffmpeg_local_builds\cygwin_local_install\cygwin.bat
(which sets up the path for you)
then cd to
G:\ffmpeg_work\ffmpeg-windows_6\ffmpeg_w\native_build\windows\ffmpeg_local_builds
and run the script manually yourself wi

**Comment by jpham986** [comment]
but then - I rerun the build, and it seems to pick up stuff again
I'll let you know what happens

thanks

**Comment by rdp** [comment]
OK I have hopefully fixed the pthreads issue.
The other one appears to be "normal" https not ftp so I'm glad it
restarted.  I've also made the script "retry" more now, in case that helps
here.
Try with the latest.
Cheers!

**Comment by jpham986** [comment]
one of the thing make it stop (I did a few retry) is the encrypt package
I email the ftp site - but no one seems to be looking into it

its
ftp://ftp.gnutls.org/gcrypt/gnutls/v3.4/gnutls-3.4.14.tar.xz


can't seems to access,  even with  firefox

**Comment by rdp** [comment]
Yeah that ftp does work from my side FWIW.
Anyway, tried to change it to http, try the latest! :)

**Comment by jpham986** [comment]
latest
seems more verbose output, also can you turn off make error ignore, would
be nice
to catch errors and sent it to you

thanks


here's some errors

==============================================================================

make clean in palm ...
po_MemPtrNew.c:44:20: fatal error: pocore.h: No such file or directory
 #include "pocore.h"
                    ^
compilation terminated.
po_MemChunkFree.c:44:20: fatal error: pocore.h: No such file or directory
 #include "pocore.h"
                    ^
compilation terminated.
po_FileTell.c:44:20: fatal error: pocore.h: No such file or directory
 #include "pocore.h"
                    ^
compilation terminated.
po_FileOpen.c:44:20: fatal error: pocore.h: No such file or directory
 #include "pocore.h"
                    ^
compilation terminated.
po_FileWrite.c:44:20: fatal error: pocore.h: No such file or directory
 #include "pocore.h"
                    ^
compilation terminated.
po_FileSeek.c:44:20: fatal error: pocore.h: No such file or directory
 #include "pocore.h"
                    ^
compilation terminated.
po_FileReadLow.c:44:20: fatal error: pocore.h: No such file or directory
 #include "pocore.h"
                    ^
compilation terminated.
po_FileClose.c:44:20: fatal error: pocore.h: No such file or directory
 #include "pocore.h"
                    ^
compilation terminated.
po_atof.c:42:28: fatal error: PceNativeCall.h: No such file or directory
 #include "PceNativeCall.h"
                            ^
compilation terminated.
po_sio.c:42:28: fatal error: PceNativeCall.h: No such file or directory
 #include "PceNativeCall.h"
                            ^
compilation terminated.
po_core.c:47:20: fatal error: pocore.h: No such file or directory
 #include "pocore.h"
                    ^
compilation terminated.
po_setjmp.c:44:28: fatal error: PceNativeCall.h: No such file or directory
 #include "PceNativeCall.h"
                            ^
compilation terminated.
make clean in palm/pocore ...
arm_flite.c:43:24: fatal error: palm_flite.h: No such file or directory
 #include "palm_flite.h"
                        ^
compilation terminated.
pealstub.c:25:22: fatal error: pealstub.h: No such file or directory
 #include "pealstub.h"
                      ^
compilation terminated.
make clean in palm/arm_flite ...
/bin/sh: line 3: -MM: command not found
/bin/sh: line 3: -MM: command not found
/bin/sh: line 3: -MM: command not found
make clean in palm/m68k_flite ...
flop.c:55:24: fatal error: palm_flite.h: No such file or directory
 #include "palm_flite.h"
                        ^
compilation terminated.
make clean in palm/flop ...
make clean in palm/include ...

**Comment by rdp** [comment]
Odd, iti seems to be failing on flite, but working OK here.  Care to nuke it
rm -rf sandbox/*/*flite*

and try it again?

**Comment by jpham986** [comment]
iwll do - everytime I download
I put the whole directory in it new folder

seems to be stuck here now

already did make libxml2-2.9.4 ...
downloading
ftp://ftp.videolan.org/pub/videolan/libbluray/0.7.0/libbluray-0.7.0.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
  0  583k    0     0    0     0      0      0 --:--:--  0:38:50
--:--:--     0

**Comment by jpham986** [comment]
this next one - netcdf

build_netcdf() {
  # used for sofalizer filter
  download_and_unpack_file
ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.4.1.tar.gz
  cd netcdf-4.4.1
    generic_configure --disable-netcdf-4 --disable-dap # its dependencies
were *hard* LOL
    do_make_and_make_install
  cd ..
}

go to unidat.ucar.edu and try to click on the netcdf-4.4.1 link and it is
lock up

http://www.unidata.ucar.edu/downloads/netcdf/index.jsp

perhaps the ffmpeg build should download everything into one dir
otherwise, there are no warranty that the code will be able to be build  at
some later date

**Comment by jpham986** [comment]
also  at line 976 - the ftp videolan bluray doesn't work
change to https works

# generic_download_and_make_and_install
ftp://ftp.videolan.org/pub/videolan/libbluray/0.7.0/libbluray-0.7.0.tar.bz2
  generic_download_and_make_and_install
https://download.videolan.org/pub/videolan/libbluray/0.7.0/libbluray-0.7.0.tar.bz2

**Comment by jpham986** [comment]
I email the folks at unicar - they tested it out - and it works on their
site
but when I try - the unicar blocked me - probably I'm on a comcast domain ?

somehow I find the archive site that host netcdf :)

so I mod the code

build_netcdf() {
  # used for sofalizer filter
  #download_and_unpack_file
ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.4.1.tar.gz
  download_and_unpack_file
http://gfd-dennou.org/arch/ucar/unidata/pub/netcdf/netcdf-4.4.1.tar.gz
  cd netcdf-4.4.1
    generic_configure --disable-netcdf-4 --disable-dap # its dependencies
were *hard* LOL
    do_make_and_make_install
  cd ..
}

and the http  gfd-dennou-org seems to work

**Comment by jpham986** [comment]
Question - I create another folder then run the build_locally_ .bat
and looking at the log, cygwin setup.exe seems to want to write to the
previous
dir - is there someplace that cygwin setup.exe keeps it log or table ?
I think that log or file needs to be delete

**Comment by rdp** [comment]
Cygwin reusing its install dir should be OK...I guess I don't use cygwin
too much :)

**Comment by rdp** [comment]
OK I adopted those two http fixes, try 'er again...

**Comment by jpham986** [comment]
I think cygwin setup.exe writes to windows registry, because last time I
write to g:/ffmpeg_work/f8/ etc
and just download the latest patch to g:/ffmpeg_work/f9/  etc

and the trace shows


Downloading cygwin setup executable...some error warning messages are
expected from the cygwin install...
Starting cygwin install, version 2.876
User has backup/restore rights
Current Directory:
G:\ffmpeg_work\f8\ffmpeg-windows-build-helpers-master\native_build\windows\ffmpeg_local_builds\cygwin_
Could not open service McShield for query, start and stop. McAfee may not
be installed, or we don't have access.
root:
G:\ffmpeg_work\f9\bhelper\native_build\windows\ffmpeg_local_builds\cygwin_local_install
system
Selected local directory:
G:\ffmpeg_work\f8\ffmpeg-windows-build-helpers-master\native_build\windows\ffmpeg_local_builds\
net: Direct
site: http://mirrors.xmission.com/cygwin/
io_stream_cygfile: fopen(/etc/setup/installed.db) failed 2 No such file or
directory
io_stream_cygfile: fopen(/etc/setup/timestamp) failed 2 No such file or
directory
Adding required dependency autoconf2.1: Selecting version 2.13-12 for
installation.
===========================================================================
notice the f8 - so what I did is abort , change f8 to f8x and run and it
would pick up
the new files f9


so when you run that setup_x86, is there any options to init a new cygwin
install setup ?

**Comment by rdp** [comment]
Does cygwin still install to a new directory OK?

**Comment by jpham986** [comment]
only if I rename the previous directory -  from f8 to f8xx then run the
script on my new dir
then it install ok


in build_locally_xxxx.bat  can you add autogen package
and gcc-fortran

during the build, I notice the configuration is looking for those

**Comment by jpham986** [comment]
after about 6hrs - the whole ffmpeg compile fine

thanks

**Comment by rdp** [comment]
OK maybe cygwin doesn't support it, dang.
I think autogen is included in some other package req. already [?]

**Comment by jpham986** [comment]
No, you have to add autogen - autoconf and etc doesn't load that
in

**Comment by rdp** [comment]
I'm afraid I don't understand fully...

**Comment by rdp** [comment]
no complaints for awhile anyway, reopen if you can help me figure it out :)
