### ISSUE TITLE
Not building libxml2

### ISSUE THREAD

**Issue by FallingSnow** [rdp/ffmpeg-windows-build-helpers#145]
Updating to 2.9.4 fixed the issue.
Build log is located at https://jenkins.sparling.us/job/ffmpeg/job/w64-x86_64/2/console.

**Comment by FallingSnow** [comment]
If you would like me to give you a pull request just let me know.

**Comment by rdp** [comment]
OK bumped it, if it helps (not sure if I've seen that failure before odd). thanks!
