### ISSUE TITLE
Feature Request: optionally, only build libdvbtee and its dependencies

### ISSUE THREAD

**Issue by mkrufky** [rdp/ffmpeg-windows-build-helpers#146]
Latest versions of `ffmpeg-windows-build-helpers` require much more disk space for the cross build than older versions.

I am probably the only person who would actually benefit directly from this request, but if there were an option to easily cross build only `libdvbtee` and it's dependencies, it would make life much easier for me to test cross builds always using the latest version of your scripts.

In fact, if such an option could be added, I would use `ffmpeg-windows-build-helpers` on my continuous integration server, add the cross-build to my build matrix for automatic testing of each push or pull request to `libdvbtee` on github.

Would it be a lot of work to add this option?  ...or should it be a separate script?

**Comment by rdp** [comment]
I'm torn on this one.
FWIW you can make a supah fast build by putting
build_dvbtee
right as the first line under
build_dependencies
with an "exit" underneath there :)

**Comment by mkrufky** [comment]
That sounds good enough for me - I will give it a try.  Thank you :-D

**Comment by mkrufky** [comment]
working well for me - thanks again
