### ISSUE TITLE
Build fails due to unset cloog_ver variable in mingw-w64-build-3.6.7

### ISSUE THREAD

**Issue by konradci** [rdp/ffmpeg-windows-build-helpers#148]
Build fails during execution of  **mingw-w64-build-3.6.7**  with an error 

> Downloading cloog-.tar.gz... ./mingw-w64-build-3.6.7.local: line 482: exit: unable to download ftp://gcc.gnu.org/pub/gcc/infrastructure/cloog-.tar.gz: numeric argument required

which is caused by unset **cloog_ver** variable.

**Comment by lordcrc** [comment]
This has been fixed in https://github.com/rdp/ffmpeg-windows-build-helpers/commit/5778183dc06d3a099c8f9f4cdcc9f552a8c3642d

**Comment by rdp** [comment]
assuming fixed, ping me if otherwise
