### ISSUE TITLE
Non-root build exits with error when trying to install outside of sandbox

### ISSUE THREAD

**Issue by Ekerim** [rdp/ffmpeg-windows-build-helpers#149]
Cmd Line:
./cross_compile_ffmpeg.sh --disable-nonfree=n --build-mp4box=y --compiler-flavors=win64 --enable-gpl=n

Error:
make installing /home/user/Compile/ffmpeg-windows-build-helpers/sandbox/x86_64/ffmpeg_git_with_fdk_aac_lgpl as $ PATH=/home/user/Compile/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH make install 
mkdir: cannot create directory ‘/usr/local/share/doc’: Permission denied
doc/Makefile:144: recipe for target 'install-html' failed
make: *** [install-html] Error 1

**Comment by lordcrc** [comment]
This seems to be related to the commit https://github.com/rdp/ffmpeg-windows-build-helpers/commit/01559b194b227f4308a935c162f5a6d451426cde which is also related to issue https://github.com/rdp/ffmpeg-windows-build-helpers/issues/147

Try commenting out line 1552, my build worked fine after that.

**Comment by Ekerim** [comment]
I'll try it out. Thx.

**Comment by lordcrc** [comment]
See my comment on the commit to make sure you comment out the correct line :)

**Comment by Ekerim** [comment]
I can confirm that the build works with line 1552 commented out.
Thanks for your quick answer :)

**Comment by lordcrc** [comment]
Great, I spent a bit more time hunting that one down :P
