### ISSUE TITLE
Build doing well, but the generated ffmpeg.exe miss all the GPL codecs !

### ISSUE THREAD

**Issue by feedzapper** [rdp/ffmpeg-windows-build-helpers#150]
Doing a Build with w64Bit.
enable_gpl=y
generated ffmpeg.exe only include :

ffmpeg version N-81185-g61d302d Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/
fmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-
w64-mingw32- --pkg-config=pkg-config --disable-w32threads --enable-librubberband
 --enable-gpl
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 51.100 / 57. 51.100
  libavformat    57. 44.100 / 57. 44.100
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 49.100 /  6. 49.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100

I miss ALL the codecs in ffmpeg.exe :-(

**Comment by nschlia** [comment]
This is related to #147, see this comment for a work around:

https://github.com/rdp/ffmpeg-windows-build-helpers/issues/147#issuecomment-236329986
