### ISSUE TITLE
Windows 10 bash

### ISSUE THREAD

**Issue by jaromanda** [rdp/ffmpeg-windows-build-helpers#151]
Can this script be used in the bash shell in Windows 10 anniversary update linux environment?

**Comment by rdp** [comment]
if it has all the needed packages (gcc, git, mercurial, etc. etc.) ...
which it might dunno

**Comment by rdp** [comment]
There is already a "cygwin" option if that is helpful

**Comment by jaromanda** [comment]
I know there's a cygwin option, just wondering about the new possibility - I'll give it a go myself if noone else has tried

**Comment by jaromanda** [comment]
FYI: Other than a certificate issue with curl when trying to get vamp-plugin-sdk-2.6.tar.gz, the script works perfectly in Windows 10 bash

**Comment by rdp** [comment]
OK vamp issue hopefully worked around now if you want to test it

**Comment by jaromanda** [comment]
Works great now

**Comment by rdp** [comment]
OK added note in the README, thanks for testing that, might be an awesome option for people that want the speed of cross compile but don't want to fire up a VM :)
