### ISSUE TITLE
curl kept exiting (could not find revocation file)

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#153]
Script kept stopping.  Curl was exiting (could not find revocation file or something like that).
system: UBUNTU 16.04, updated.
Changed curl to curl -k and it worked.
Recommend consider doing that in the script normally, to minimize dependencies.

**Comment by OrenShalmy** [comment]
Which of the curl commands did you add the -k to?
Thanks.

**Comment by hydra3333** [comment]
Every one that I could find.
I must look into CURL and how/where to obtain the missing/outdated cert revocation file (if that's what it was), but adding to -k to curl got me over the hump and it built fine.  I'll remove the -k and run it all again just to find the line it gagged on.
Updated with -k :-
[cross_compile_ffmpeg.sh.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/410868/cross_compile_ffmpeg.sh.txt)

**Comment by rdp** [comment]
this is the equivalent of --insecure

hmm...I've heard of a handful of broken distro's needing it, but do I want
to turn it on globally...hmm...yeah why not

**Comment by hydra3333** [comment]
`sudo ./cross_compile_ffmpeg.sh --gcc-cpu-count=2 --sandbox-ok=y --build-ffmpeg-shared=n --build-ffmpeg-static=y --disable-nonfree=n --build-x264-with-libav=y --build-intel-qsv=y --build-libmxf=n --build-mp4box=y --build-mplayer=n --build-vlc=y --git-get-latest=y --prefer-stable=n --high-bitdepth=n --compiler-flavors=multi --cflags='-march=sandybridge -O3'`

without the -k results in

```
install -m 644 openh264-static.pc /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/pkgconfig/openh264.pc
downloading https://code.soundsoftware.ac.uk/attachments/download/1520/vamp-plugin-sdk-2.6.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by rdp** [comment]
Oh the vamp plugin.  Somebody else complained about that one too (windows 10 bash) so I have changed its download location for now, give it a shot?

**Comment by rdp** [comment]
I just changed the vamp download location, make sure you on the latest?

**Comment by hydra3333** [comment]
OK. It works. Thank you very much.
