### ISSUE TITLE
query

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#154]
I wonder if this improvement in fftw is likely to have an effect ?

https://github.com/dubhater/vapoursynth-mvtools/issues/20#issuecomment-239095078
> fuchanghao commented 4 hours ago
> now new fftw 3.3.5 have AVX2 optimization.

**Comment by rdp** [comment]
hmm seems it's "disabled by default" and untested...plus only used by sofalizer so...I'll wait on this one a bit, but I did bump the version to 3.3.5 if anybody wants to give it a gander and if they notice speed improvements and it is backward compatible with "all hardware" we could enable it for sure :)
