### ISSUE TITLE
CMake Error on Lubuntu 16.04.1 with ./cross_compile_ffmpeg.sh --disable-nonfree=n

### ISSUE THREAD

**Issue by ogrgkyle** [rdp/ffmpeg-windows-build-helpers#155]
CMake Error: The source directory "/home/philip/Desktop/ffmpeg-windows-build-helpers/sandbox/x86_64" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by rdp** [comment]
OK hopefully fixed try again thanks!
