### ISSUE TITLE
cross_compile_ffmpeg.sh cmake error fix 

### ISSUE THREAD

**Issue by omegadragon** [rdp/ffmpeg-windows-build-helpers#156]
https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/cross_compile_ffmpeg.sh#L703
line 703 cd lib_ebur128_git needs to be changed to  cd libebur128_git
and 
https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/cross_compile_ffmpeg.sh#L1099
line 1099 cd mfx_dispatch_git_lu_zero to cd mfx_dispatch_git 
i get a successful build with these changes. :)
on ubuntu 15.10

**Comment by rdp** [comment]
OK hopefully fixed, thank you
