### ISSUE TITLE
https://github.com/jiixyj/libebur128.git is checked out into wrong folder

### ISSUE THREAD

**Issue by macharats** [rdp/ffmpeg-windows-build-helpers#157]
I had to correct line 703 to
  do_git_checkout https://github.com/jiixyj/libebur128.git lib_ebur128_git
so it would find the folder it tries to cd into afterwards. Please correct your script.

I also found a similar problem on line 1098. I had to change it to
  do_git_checkout https://github.com/lu-zero/mfx_dispatch.git mfx_dispatch_git_lu_zero # whoever lu-zero is?

**Comment by rdp** [comment]
could you check if this is still a problem in git master?

**Comment by rdp** [comment]
seems fixed
