### ISSUE TITLE
ISL unable to download isl-0.12.2.tar.bz2 (new)

### ISSUE THREAD

**Issue by jpham986** [rdp/ffmpeg-windows-build-helpers#158]
I download the latest version, ISL seems to be stuck still 

here is the new error msg

[24/54]: Installing mpc... done
[25/54]: Downloading isl-0.12.2.tar.bz2... ./mingw-w64-build-3.6.7.local: line 482: exit: unable to download ftp://gcc.gnu.org/pub/g
cc/infrastructure/isl-0.12.2.tar.bz2: numeric argument required
failure building 64 bit gcc? recommend nuke sandbox (rm -rf sandbox) and start over...
done with local build...check output above to see if successfull..
if not successful you might try re running the script, it "should" pick up where it left off.

if you want more advanced configuration (like building mplayer or mp4box, 10-bit, etc)
open g:\ffmpeg_work\ffmpeg_win\ffmpeg-windows-build-helpers-master\native_build\windows\ffmpeg_local_builds\cygwin_local_install\cyg
win.bat
(which sets up the path for you)
then cd to g:\ffmpeg_work\ffmpeg_win\ffmpeg-windows-build-helpers-master\native_build\windows\ffmpeg_local_builds and run the script
 manually yourself with -h

**Comment by rdp** [comment]
hopefully fixed now, please reopen if this is not the case
