### ISSUE TITLE
FFmpeg now includes nvenc v7 SDK header

### ISSUE THREAD

**Issue by Collisionc** [rdp/ffmpeg-windows-build-helpers#159]
As of a week ago, the header is now included due to being behind a double registration wall.

https://github.com/FFmpeg/FFmpeg/commit/325e56479ff64c884f3bcccf922a7f7163488b89

--enable-nvenc is replaced with --disable-nvenc, which is now autodetected.

**Comment by rdp** [comment]
that is good news updated in 0b29a18
