### ISSUE TITLE
just a query: old version gcc - 4.9.3 ?

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#160]
Just seeking clarification:

The gcc site https://gcc.gnu.org/ says 

> GCC 6.2 released [2016-08-22]
> GCC 4.9.4 released [2016-08-03]
> GCC 5.4 released [2016-06-03]
> 2015 ACM Software System Award [2016-04-29]
> GCC 6.1 released [2016-04-27]
> Heterogeneous Systems Architecture support [2016-01-27]
> Heterogeneous Systems Architecture 1.0 support was added to GCC, contributed by Martin Jambor, Martin Liška and Michael Matz from SUSE.
> GCC 5.3 released [2015-12-04]
> GCC 5.2 released [2015-07-16]
> GCC 4.9.3 released [2015-06-26]
> GCC 4.8.5 released [2015-06-23]
> GCC 5.1 released [2015-04-22]

Which seems funny since 4.9.4 is release "in the middle" of newer versions.
I assume newer gcc versions than 4.9.3 won't compile some sources at all ?  
Wasn't there a slightly newer version that worked ?
(IIRC, some GCC defaults changed significantly in one or more of the higher versions and that and/or something related broke the compilation of a range of sources.)

Not sure if this "fix" helps:
https://wiki.gentoo.org/wiki/Upgrading_from_gcc-4.x_to_gcc-5.x

Zeranoe's build seems to use gcc 5.4.0.

Thanks.

**Comment by rdp** [comment]
I could never get x86_64 to link right with 6.x [though I haven't tried
6.2] so use 5.4
I think 4.9.x might be "faster" than 5.x but don't know exactly yet :|

**Comment by hydra3333** [comment]
Just a thought ... Not sure if this "fix" helps:
https://wiki.gentoo.org/wiki/Upgrading_from_gcc-4.x_to_gcc-5.x

**Comment by rdp** [comment]
I thought there was a better speed with 4.x and 6.x than 5.x (and can't get 6.x to work right yet)...so yeah, I guess.
