### ISSUE TITLE
ftp.uindata.ucar.edu (netcdf) doesn't like PASV anymore

### ISSUE THREAD

**Issue by StephKoenig** [rdp/ffmpeg-windows-build-helpers#162]
... so hangs grabbing netcdf-4.4.1.tar.gz and eventually times out @ 5mins with:
"curl: (13) Bad PASV/EPSV response: 500"

To solve I added 

--disable-epsv --ftp-skip-pasv-ip

To the CURL command line on 435, which I know is crappy and bodgy but worked for me quick.

You'll have a better way by adding the options in build_netcdf

**Comment by rdp** [comment]
OK somebody else with ftp problems gave me a suggested fix, should be in
now :)

**Comment by StephKoenig** [comment]
Awesome thanks!
