### ISSUE TITLE
gcc compiler errors with cpu-type CFLAGS (-march) 

### ISSUE THREAD

**Issue by feedzapper** [rdp/ffmpeg-windows-build-helpers#164]
I got compiler errors with GCC 4.9.3 and also GCC 5.4.0 if i set the CFLAG "-march=" with the new cpu-typing ones. e.g. sandybridge ,haswell, broadwell.
the old cpu-typing  <=(GCC 4.8.x) still works with the newer GCC version (core-avx2, core-avx-i)
Where is the problem ?
The newer GCC should support this ?

**Comment by rdp** [comment]
what compile errors?

**Comment by feedzapper** [comment]
configuring zlib-1.2.8 (/home/freetz/ffmpeg-windows-build-helpers/sandbox/x86_64/zlib-1.2.8) as $ PATH=/home/freetz/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games ./configure --static --prefix=/home/freetz/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
Checking for gcc...
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.

**Comment by rdp** [comment]
script parameters used and zlib config.log file please?

**Comment by feedzapper** [comment]
build_dvbtee=n
build_libmxf=n
build_mp4box=n
build_mplayer=n
build_vlc=n
git_get_latest=y
prefer_stable=y
build_intel_qsv=y
disable_nonfree=n # have no value by default to force user selection
original_cflags='-march=haswell -O2 -pipe' #  be careful, these override 
# if you specify a march it needs to first so x264's configure will use it :|
build_x264_with_libav=n
ffmpeg_git_checkout_version=release/3.1
build_ismindex=n
enable_gpl=y

the rest is unchanged in the script...

zlib configure.log :
--------------------
./configure --static --prefix=/home/freetz/ffmpeg-windows-build-helpers/sandbox/
cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
Thu Sep 22 13:26:21 CEST 2016
Checking for gcc...
=== ztest21640.c ===
extern int getchar();
int hello() {return getchar();}
===
gcc -c ztest21640.c
... using gcc

Checking for obsessive-compulsive compiler options...
=== ztest21640.c ===
int foo() { return 0; }
===
gcc -c -march=haswell -O2 -pipe ztest21640.c
ztest21640.c:1:0: error: bad value (haswell) for -march= switch
 int foo() { return 0; }
 ^
(exit code 1)
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
--------------------

**Comment by feedzapper** [comment]
ok, i got it for myself

local gcc compiler version was 4.8.3 on ubuntu 14.04 LTS
I updated them to gcc 5.4.1. 
Now it seems to work

**Comment by rdp** [comment]
thanks for the update
