### ISSUE TITLE
ffplay.exe dose not exist

### ISSUE THREAD

**Issue by MusabTM** [rdp/ffmpeg-windows-build-helpers#166]
build script dose not generate ffplay any more since ffplay code updated to use sdl2 not sdl.. and when i cross-compiled sdl2  for windows it asks for direct3d 11. 
how i can build it..
i tried this :
http://stackoverflow.com/questions/3813115/cross-compiling-direct3d-on-linux-with-mingw
and tools from :
https://code.google.com/archive/p/lib2a/
 but it did not work

**Comment by rdp** [comment]
OK good to know

**Comment by rdp** [comment]
kind of fixed
