### ISSUE TITLE
Using Bash on windows 10

### ISSUE THREAD

**Issue by tinba12** [rdp/ffmpeg-windows-build-helpers#167]
If you are using a directory path with a space it fails 
/mnt/c/Users/My User Name
but 
/mnt/c/Users/My_User_Name
will work

**Comment by rdp** [comment]
I'll have to put in an error when it does that...
Did you run into this issue? https://github.com/rdp/ffmpeg-windows-build-helpers/issues/165

**Comment by rdp** [comment]
OK things have changed quite bit, let me know if still failing...
