### ISSUE TITLE
libfaac has been removed from ffmpeg

### ISSUE THREAD

**Issue by Collisionc** [rdp/ffmpeg-windows-build-helpers#168]
--disable-libfaac can now be removed. :) 

https://github.com/FFmpeg/FFmpeg/commit/dc0f711459e0c682bf9f94ba38d26736e90cff45

**Comment by nschlia** [comment]
Anyone able to remove --disable-libfaac from this line:

https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/cross_compile_ffmpeg.sh#L1510

That'll fix it.

**Comment by blisbell** [comment]
[https://github.com/rdp/ffmpeg-windows-build-helpers/pull/171]
This should fix it.

**Comment by rdp** [comment]
OK merged now, thanks!
