### ISSUE TITLE
Bulid error mfx_dispatch_git

### ISSUE THREAD

**Issue by blisbell** [rdp/ffmpeg-windows-build-helpers#170]
Makefile:671: recipe for target 'src/libmfx_la-main.lo' failed
make: *** [src/libmfx_la-main.lo] Error 1

can not continue. Buliding in linux sandbox with non-free x64 only.

**Comment by rdp** [comment]
is there more output?

**Comment by blisbell** [comment]
well noe im getting this
Updating to latest mfx_dispatch_git git version [origin/master]...

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'htpc@htpc.(none)')

**Comment by blisbell** [comment]
ok found problem it is being worded on.
[https://github.com/lu-zero/mfx_dispatch/issues/37](url)

**Comment by blisbell** [comment]
ok never mind he removed last commit that broke it
