### ISSUE TITLE
nvenc_hevc

### ISSUE THREAD

**Issue by FallingSnow** [rdp/ffmpeg-windows-build-helpers#173]
Can you use `ffmpeg-windows-build-helpers` to build a windows ffmpeg with `nvenc_hevc` support?

**Comment by blisbell** [comment]
as of this commit [https://github.com/rdp/ffmpeg-windows-build-helpers/commit/0b29a188440ef29b858c3fea6348c0deefbda824] it is included I think you need to chose y on non-free though.

**Comment by FallingSnow** [comment]
Yup, that worked thank you.
