### ISSUE TITLE
Fast compile config request (for linux)

### ISSUE THREAD

**Issue by FloridaStream** [rdp/ffmpeg-windows-build-helpers#174]
Please provide any bash config file to fast compile in linux.
Im' trying to compile, but its run for hours =(

I can compile ffmpeg for android in minutes, what diferences?

**Comment by rdp** [comment]
it's native_build/quick_cross_compile_ffmpeg_fdk_aac_and_x264_using_packaged_mingw64.sh if that helps [?] if not please reopen thanks!
