### ISSUE TITLE
Feature request amd vce encoding? 

### ISSUE THREAD

**Issue by blisbell** [rdp/ffmpeg-windows-build-helpers#175]
As the tittle says is there anyway to include this in the build process yet i cant find any info for in but some chatter about it. i read it is included in ffmpeg just cant find build flags. and required depends.

**Comment by rdp** [comment]
I don't seem to see a configure option for it yet, so this one might be tricky...

**Comment by rdp** [comment]
OK maybe with funding I could do this, but since it's not in ffmpeg mainline closing for now...
