### ISSUE TITLE
libebur128 doesn't get statically linked into ffmpeg.exe anymore?

### ISSUE THREAD

**Issue by o-p-p** [rdp/ffmpeg-windows-build-helpers#176]
Is it me or is something broken? Tried checking out libebur128 v1.1.0 directly, still nothing, Windoze wants to have libebur128.dll now??

**Comment by FloridaStream** [comment]
+1

**Comment by o-p-p** [comment]
Hmm, only 3.1.5 up on zeranoe as well. And then there's this: 
https://patchwork.ffmpeg.org/patch/1155/

WTH is going on? Isnt't all this <quote>
"3.2 was released on 2016-10-27. It is the latest stable FFmpeg release from the 3.2 release branch, which was cut from master on 2016-10-26."
and
"3.1.5 was released on 2016-10-22. It is the latest stable FFmpeg release from the 3.1 release branch, which was cut from master on 2016-06-26."
</quote>
"master cutting" bad enough? Someone should really get a f***ing clue out there ... =:-(((

**Comment by Mr-Jake** [comment]
I get the same error.

The script appears to compile correctly, but when ffmpeg.exe is executed there is an error box saying **libebur128.dll** can't be found.

**Comment by FloridaStream** [comment]
**Search** for `libebur128.dll` in `ffmpeg-windows-build-helpers` folder, or on your named compilation folder, copy  to your `ffmpeg.exe` and run :)

**Comment by kgp700** [comment]
I think many people doesn't want to make dynamically linked
Can not make statically linked anymore?

**Comment by rdp** [comment]
OK hopefully fixed, thanks for the report (see also https://github.com/jiixyj/libebur128/issues/56 )
Thanks!
you'll need to nuke your sandbox basically unfortunately or manually delete **/*libebur*.dll.a
Cheers!
