### ISSUE TITLE
ISL fails configuring due to GMP being compiled with "--disable-shared"...

### ISSUE THREAD

**Issue by DeadSix27** [rdp/ffmpeg-windows-build-helpers#177]
... which is the default option in mingw-w64-build-3.6.7.local at #build gmp

This is the same as the post I did on the forums, just In case some coders only check the issues and not forums: https://ffmpeg.zeranoe.com/forum/viewtopic.php?f=5&t=4782&p=11661#p11661

In short, configuring isl fails with various errors, but the main error is probably:

"configure:17450: error: gmp library too old"

See full build.log: https://paste.ubuntu.com/23418592/

Also not sure if this is relevant but it also says:
"error: CPU you selected does not support x86-64 instruction set"

Despite it being compiled on a 64 bit cpu:

`Linux box 4.8.0-26-generic #28-Ubuntu SMP Tue Oct 18 14:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by FloridaStream** [comment]
U cant try `gcc 4.9.3 (GCC)`?

**Comment by DeadSix27** [comment]
@FloridaStream Well I could, but that's not the issue. As I need 5+

**Comment by rdp** [comment]
I think this is issue #75 let me try it with the work around you suggested...

**Comment by DeadSix27** [comment]
Completely offtopic; but random question: Is there a way to get std::mutex mutex working in this helper?
Trying to cross compile vapoursynth but fail during std::mutex check. According to this: http://stackoverflow.com/a/17560210
It's now in MinGW-w64 ? But you use git don't you? Shouldn't it be a build with support for that then?

**Comment by rdp** [comment]
I'm using mingw-w64 git so if you do a complete fresh build and it doesn't
work, it's probably not in mingw-w64 yet FWIW
I wonder if others out there build vapoursynth on mingw and/or windows at
all...

**Comment by DeadSix27** [comment]
In the end I just downloaded the prebuilt WINDOWS binary of their site and created my own library files using dlltool etc and made  pkg config.. since it's such a insanely annoying procedure to compile that.. (Same goes for python) 
Works fine. So that's one way to work around that..
Altho I'm not sure how the licenses handle redistributing of binaries.
Will need to read into it, otherwise I'll just have to keep the auto-compiler outputs for some stuff private.

**Comment by rdp** [comment]
can anyone confirm this fix works now?

**Comment by rdp** [comment]
I guess they just use MSVC to prebuild their binaries...

**Comment by DeadSix27** [comment]
> can anyone confirm this fix works now?
Works for me... : P.. but ye.:

**Comment by mxalbert1996** [comment]
@DeadSix27 To get std::mutex working I think you need to build mingw with the included winpthreads while mingw-w64-build-3.6.7 uses external pthreads-w32 defaultly. However, if you just want to use vapoursynth I think using official binaries is a better choice considering the python stuff.

**Comment by rdp** [comment]
OK guess it's working now, thanks for the fix link
