### ISSUE TITLE
build_libebur128 function requires LDFLAGS='-static' for a static ffmpeg build

### ISSUE THREAD

**Issue by tompegios** [rdp/ffmpeg-windows-build-helpers#178]
If LDFLAGS='-static' is added to the "build_libebur128" function then the libebur128.dll is not required. the "sed" command used to modify CMakeLists.txt can also be removed. Also libebur128.dll.a doesn't need to be deleted.
I had set LDFLAGS and CFLAGS at the beginning of the script but that was a waste of time as both flags get changed may times during the running of the script, may I suggest that the original state of the compile flags be saved when special flags are needed to build a module and then restored before the next module is built.

Thank you for a great script, without it would not be able to build ffmpeg on my own.

**Comment by kgp700** [comment]
How to add LDFLAGS='-static' flag to the "build_libebur128" function?

**Comment by tompegios** [comment]
use any unix editor ( eol is linefeed only) and edit cross_compile_ffmpeg.sh, look for "build_libebur128() {" without quotes.  insert new line after the line "build_libebur128() {"  and add "export LDFLAGS='-static'" without double quotes. Look for the line that begins with "sed -i.bak" and add a "#" at the beginning of the line. It should look like this

build_libebur128() {
export LDFLAGS='-static'
  do_git_checkout https://github.com/jiixyj/libebur128.git
  cd libebur128_git
#    sed -i.bak 's/ SHARED / STATIC /' ebur128/CMakeLists.txt # no option for STATIC only [?] so removed shared LOL
    do_cmake_and_install "-DENABLE_INTERNAL_QUEUE_H:BOOL=ON"
    # can't add -lspeexdsp to its .pc file, it doesn't have one, so just add to ffmpeg configure flags <sigh> XXXX remove once ebur bumped and it doesn't have that dependency as much [?]
  cd ..
}
 
remember to put "export" in if front of LDFLAGS='-static' or else the flag will be local to the build script and not passed on to ./configure or make unless configure is called out as follows ./configure LDFLAGS='-static' -whatever_parameteter_you_need_to_set

**Comment by tompegios** [comment]
there was suppose to be a pound sign in front of  -sed -i.bak

**Comment by tompegios** [comment]
you need to edit cross_compile_ffmpeg.sh with a unix compatible editor.
Look for
build_libebur128() { and change :
build_libebur128() {
  do_git_checkout https://github.com/jiixyj/libebur128.git
  cd libebur128_git
    sed -i.bak 's/ SHARED / STATIC /' ebur128/CMakeLists.txt # no option
for STATIC only [?] so removed shared LOL
    do_cmake_and_install "-DENABLE_INTERNAL_QUEUE_H:BOOL=ON"
    # can't add -lspeexdsp to its .pc file, it doesn't have one, so just
add to ffmpeg configure flags <sigh> XXXX remove once ebur bumped and it
doesn't have that dependency as much [?]
  cd ..
}


to :

build_libebur128() {
export LDFLAGS='-static'
  do_git_checkout https://github.com/jiixyj/libebur128.git
  cd libebur128_git
#    sed -i.bak 's/ SHARED / STATIC /' ebur128/CMakeLists.txt # no option
for STATIC only [?] so removed shared LOL
    do_cmake_and_install "-DENABLE_INTERNAL_QUEUE_H:BOOL=ON"
    # can't add -lspeexdsp to its .pc file, it doesn't have one, so just
add to ffmpeg configure flags <sigh> XXXX remove once ebur bumped and it
doesn't have that dependency as much [?]
  cd ..
}

good luck

**Comment by FloridaStream** [comment]
Awesome @tompegios waiting next fix by @rdp . :heart_eyes:

**Comment by rdp** [comment]
this should be fixed now, did I miss anything?

**Comment by tompegios** [comment]
Can't find a attachment to see what has been changed but it's only a
trivial change anyways.

Would you also consider another change, on connection refused curl exits
with an error and --retry 50 does nothing for connection refused error.

Consider changing
"curl -4 "$url" --retry 50 -O -L --fail || exit 1 "
to
"until curl -4 "$url" --retry 50 -O -L --fail; do sleep 120; done"

This will wait 120 seconds before re-executing the curl command if there
was an error ( choose any wait time you think is reasonable ) .CNTRL ^C
will still break you out of the loop if needed.
On the minus side this tries forever even if the error is file not found.
but connection refused is the error I see all the time.

Regards
Tom Pegios
