### ISSUE TITLE
[38/54]: Building all-gcc... error

### ISSUE THREAD

**Issue by rzcat** [rdp/ffmpeg-windows-build-helpers#181]
need help, i was stuck at [38/54]: Building all-gcc... error
running on Fedora 24, ive already tried many times only to get the same result(yes, i deleted the sandbox folder every time after error and restart)
the build.log file is too big to post here (over 3MB) heres the last part of it:

	In file included from ./tm.h:23:0,
					 from ../../source/gcc-4.9.3/gcc/cp/except.c:27:
	../../source/gcc-4.9.3/gcc/config/i386/mingw32.h:139:3: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
	   "%{mthreads:-lmingwthrd} -lmingw32 \
	   ^
	In file included from ../../source/gcc-4.9.3/gcc/cp/except.c:1013:0:
	cfns.gperf: In function ‘const char* libc_name_p(const char*, unsigned int)’:
	cfns.gperf:101:1: error: ‘const char* libc_name_p(const char*, unsigned int)’ redeclared inline with ‘gnu_inline’ attribute
	cfns.gperf:26:14: note: ‘const char* libc_name_p(const char*, unsigned int)’ previously declared here
	cfns.gperf: At global scope:
	cfns.gperf:26:14: warning: inline function ‘const char* libc_name_p(const char*, unsigned int)’ used but never defined
	Makefile:1058: recipe for target 'cp/except.o' failed
	make[1]: *** [cp/except.o] Error 1
	make[1]: Leaving directory '/test_build/ffmpeg-windows-build-helpers/sandbox/cross_compilers/pkgs/gcc/build/gcc'
	Makefile:3968: recipe for target 'all-gcc' failed
	make: *** [all-gcc] Error 2

**Comment by rdp** [comment]
possibly a gcc bug FWIW https://github.com/mxe/mxe/issues/1361

**Comment by rzcat** [comment]
thanks for the quick response
according to the link given above, should i go to patch this bug somehow, or just simply wait for a new GCC version, with this already been fixed?
I don't quite understand how to deal with this bug😓

**Comment by rzcat** [comment]
Finally I managed to finish compiling exe on Win2k8 r2, while Fedora still getting stuck
It took me over a week to finish running the script. at first, time was wasted mostly on downloading and git cloning packages, for any interruption happened, such as incompleted downloading job due to low internet connection quality, the script would delete everything and report error (stuck)
In order to speed up, I had to pre-download everything via proxy and locate them on a LAN ftp server to feed the modified script.
The script is a good learning material, thanks.
There's an ffmpeg_g.exe beside ffmpeg.exe, what's the _g one?

**Comment by rdp** [comment]
_g is the one "with debug symbols still present" (and a larger executable)
for using in gdb etc.

**Comment by rdp** [comment]
It should recover if there are failures during building dependencies but not so much when building gcc (I assume that's where your failure was)?  That one is a borrowed code but if I get too many reports I will fix it, thank you for the report.
