### ISSUE TITLE
Problem compiling ffmpeg version n2.7.7

### ISSUE THREAD

**Issue by FloridaStream** [rdp/ffmpeg-windows-build-helpers#182]
I can't compile ffmpeg with this comand line, can u help me? 

`./cross_compile_ffmpeg.sh --build-ffmpeg-static=y --ffmpeg-git-checkout-version=n2.7.7 --build-intel-qsv=n --compiler-flavors=win64 --gcc-cpu-count=2
`
If i compile last version, I dont get problems.

Why I need old ffmpeg? Because version 2.8+ have problens with dvb_subtitle image based.
I make changes in 2.8 and 3,x to work with dvb_subtitles image based, but have bugs and don't work as great, because this, I need a version less than 2.8, **2.7.7**.

How i can compile old ffmpeg versions? @rdp
Running on Centos OS 5 x64 bit.

**Comment by o-p-p** [comment]
https://ffmpeg.org/bugreports.html

**Comment by FloridaStream** [comment]
This don't help @o-p-p my problem is compiling with `ffmpeg-windows-build-helpers`. I have problems with pkg-config and gnutls. =(

**Comment by FloridaStream** [comment]
fixexd, i downloaded last build of `ffmpeg-windows-build-helpers` and with command:

```
./configure --arch=x86_64 --target-os=mingw32 --cross-prefix=/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --pkg-config=pkg-config --disable-w32threads --extra-cflags=-DLIBTWOLAME_STATIC --enable-runtime-cpudetect --extra-cflags=-O3 --enable-static --disable-shared --prefix=/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-nonfree  --disable-ffplay --disable-ffserver  --disable-ffprobe --enable-nonfree --disable-doc
```

work on n2.7.7 version.
U can customize the command line as your neeb, bye.
