### ISSUE TITLE
OpenCL support was not enabled in this build

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#183]
Hello. This
https://ffmpeg.org/ffmpeg-filters.html#unsharp-1
says
> opencl If set to 1, specify using OpenCL capabilities, only available if FFmpeg was configured with --enable-opencl
however when I run a homebuilt ffmpeg with this
`"c:\0-homebuilt-x64\ffmpeg.exe" -i "movie.mp4" -i "audio.WAV" -map_metadata -1 -map 0:v -map 1:a -filter:v unsharp=luma_msize_x=5:luma_msize_y=5:luma_amount=0.5:chroma_msize_x=5:chroma_msize_y=5:chroma_amount=0.5:opencl=1 -c:v h264_nvenc -preset hq -rc:v constqp -global_quality 21 -profile:v high -level 4.1 -pixel_format yuv420p -movflags +faststart -c:a copy -y "movie.nvenc.mp4"`
it yields this
```
[Parsed_unsharp_0 @ 00000206cc6791e0] OpenCL support was not enabled in this build, cannot be selected
[AVFilterGraph @ 00000206cccd9e60] Error initializing filter 'unsharp' with args 'luma_msize_x=5:luma_msize_y=5:luma_amount=0.5:chroma_msize_x=5:chroma_msize_y=5:chroma_amount=0.5:opencl=1'
Error opening filters!
```
How would I enable opencl=1 in a build ?

**Comment by rdp** [comment]
so you want to be able to use opencl?  I tried once and it seemed to be "very bound" to the type of graphics card you have: https://trac.ffmpeg.org/wiki/HWAccelIntro#OpenCL (i.e. if you build it against Nvidia headers, suddenly it doesn't work on machines without nvidia cards in them)...let me know if you get it working, that would be interesting...I haven't purused it much since it's only useful for the unsharp filter currently, I think...

**Comment by mirh** [comment]
[OpenCL ICD loader](https://github.com/KhronosGroup/OpenCL-ICD-Loader) has also been open-sourced. 
Together with the [headers](https://github.com/KhronosGroup/OpenCL-Headers) already being such, I don't see how vendor bounds might be "inserted".

**Comment by hydra3333** [comment]
OK and thank you for your comment.
From another source (deadsix27) I found a way to build in opencl icd loader for 64bit and link to the nvidia opencl dll for 32bit.

**Comment by rdp** [comment]
patches welcome! :)

**Comment by mirh** [comment]
I still fail to see what nvidia has to do with this, if you can [just](https://github.com/DeadSix27/python_cross_compile_script/issues/12#issuecomment-295781106) link/build/all to khronos dll.

**Comment by hydra3333** [comment]
yes, that was the link.   well, for me the ICD bits wouldn't build 32bit, which is where I took the lazy approach and copied the nvidia DLL from windows and did things with that - it seemed to work which is why I left it that way ... that's where nvidia came in.

ok, a patch to be submitted in the next week or so.

about the nvidia stuff, I gave up (not smart enough & too lazy) trying to build ffmpeg static with 
--enable-libnpp for the scale_npp filter (it kept wanting nvidia sdk DLLs to load at runtime, no instructions and googling didn't help)
--enable-cuda-sdk (the nvidia .cu compiler would only support a well out of date gcc, let alone me then try to link static)

**Comment by schmidthubert** [comment]
Is that scale_npp fiddling still necessary? I thought this one
https://patchwork.ffmpeg.org/patch/3944/
is already inside ffmpeg now so normal filtering as in "-vf scale" should do the trick it as well now? (I haven't tried it personally yet, very busy here with other things, that's just from my bookmarks!)
Search "ffmpeg -h full" for "filter_hw_device", it should be in there ...

As for OpenCL that's just a few extra lines:

`build_opencl() {`
`  rm -fr OpenCL`
`  do_git_checkout https://github.com/KhronosGroup/OpenCL-Headers.git OpenCL`
`  cd OpenCL`
`    mkdir -p $mingw_w64_x86_64_prefix/include/CL`
`    rm -f $mingw_w64_x86_64_prefix/include/CL/*`
`    cp -vf opencl12/CL/*.h $mingw_w64_x86_64_prefix/include/CL/`
`	$mingw_w64_x86_64_prefix/../bin/gendef $(pwd)/../../../patches/OpenCL$bits_target.dll`
`	$mingw_w64_x86_64_prefix/bin/dlltool -l libOpenCL.a -d OpenCL$bits_target.def -k -A`
`	cp -vf libOpenCL.a $mingw_w64_x86_64_prefix/lib`
`  cd ..`
`}`

Or checkout maybe 
https://github.com/jb-alvarado/media-autobuild_suite
for building ffmpeg for 32+64 bit (gcc 7.2.0 msys2) Windoze exe's ...
which seems to have opencl, opengl and still libnpp as well in it's ffmpeg_options.txt: 

`# Lines starting with this character are ignored`
`--enable-avisynth`
`--enable-gcrypt`
`--enable-libmp3lame`
`--enable-libopus`
`--enable-libvorbis`
`--enable-libvpx`
`--enable-libx264`
`--enable-libx265`
`--enable-cuda`
`--enable-cuvid`
`--enable-schannel`
`# Zeranoe`
`--enable-decklink`
`--enable-fontconfig`
`--enable-frei0r`
`--enable-gnutls`
`--enable-libass`
`--enable-libbluray`
`--enable-libbs2b`
`--enable-libcaca`
`--enable-libfreetype`
`--enable-libfribidi`
`--enable-libgme`
`--enable-libgsm`
`--enable-libilbc`
`--enable-libmfx`
`--enable-libmodplug`
`--enable-libopencore-amrnb`
`--enable-libopencore-amrwb`
`--enable-libopenjpeg`
`--enable-librtmp`
`--enable-libsoxr`
`--enable-libspeexv
`--enable-libtheora`
`--enable-libtwolame`
`--enable-libvidstab`
`--enable-libvo-amrwbenc`
`--enable-libwavpack`
`--enable-libwebp`
`--enable-libxavs`
`--enable-libxvid`
`--enable-libzimg`
`--enable-openssl`
`--enable-libsnappy`
`--enable-gpl`
`# Full`
`--enable-opencl`
`--enable-opengl`
`--enable-libcdio`
`--enable-libfdk-aac`
`--enable-libkvazaar`
`--enable-librubberband`
`--enable-libssh`
`--enable-libtesseract`
`--enable-libzvbi`
`--enable-chromaprint`
`--enable-libopenh264`
`--enable-libopenmpt`
`--enable-libnpp`
`--enable-libzmq`
`--enable-libmysofa`

**Comment by hydra3333** [comment]
Thankyou, I will look into these to see where I'm going wrong:
https://patchwork.ffmpeg.org/patch/3944/
and
https://github.com/jb-alvarado/media-autobuild_suite

My goal was to have a fully static ffmpeg build without any extra DLL dependencies.  
IIRC npp is for 64bit only, based on only 64bit nvidia npp dll's being available ? but I'd need to go back and check.
I can get the npp stuff to build in an "almost static 64bit ffmpeg" via the usual known methods however in order to run on windows 10 it then required DLLs only found in the sdk after installing the cuda_sdk.  The rest of 64bit ffmpeg could be built static but when run in win10 it threw an error looking for one or more of those DLLs.  :(    
Doesn't jb's suite IIRC require you to have pre-installed the relevant cuda sdk, and I'm unsure if the resulting builds fully static or not.

Yes "build_opencl() {" is the non-ICD-loader way I use to build 32-bit ffmpeg with openCL, which requires copying a windows DLL.   deadsix27 in her/his repository showed the other non-DLL-copying ICD method which works for 64 bit but not with my 32 bit attempts.

**Comment by schmidthubert** [comment]
>Doesn't jb's suite IIRC require you to have pre-installed the relevant cuda sdk,
>and I'm unsure if the resulting builds fully static or not.
it doesn't complain here about missing dlls, nor does it crash, I just built it. npp IS in there as well ...

[opencl]
>but not with my 32 bit attempts.
check my code for build_opencl(), and check your system, there are TWO dlls .... Good Luck! :-)

**Comment by hydra3333** [comment]
> it doesn't complain here about missing dlls, nor does it crash, I just built it. npp IS in there as well ...
Righty ho, thank you muchly.
I am a dummy and will shoot right over to jb's to have a look.

> check my code for build_opencl(), and check your system, there are TWO dlls .... Good Luck! :-)
:) Thanks !  Yes, I'd got both 32 bit and 64 bit to build that way; deadsix27's ICD loader method doesn't depend on those DLLs to build ;)

**Comment by schmidthubert** [comment]
That  "loader method" does just about the same, please "follow the code", he's just cooking with water as well ... ;-)
As for npp again: right, it's inside the 64bit ffmpeg.exe only, and ffmpeg -h full (when using the 32bit executable) doesn't contain the "nppscale AVOptions" help-section, right .

**Comment by hydra3333** [comment]
OK will look at that code.
From jb's:
```
libnpp (needs CUDA SDK installed)
needs non-free license
```

**Comment by schmidthubert** [comment]
I just added 

set CUDA_PATH=
set CUDA_PATH_v8=

to my batch (I don't have v9 RC installed, waiting for v9 Final), and using npp doesn't complain about anything missing but there's hardly any advantage to "vf -scale [..]" ie. scaling something down from 1920 to 1280 is 283fps (npp) ->260fps (vf -scale), so this is pretty much useless or hardly noticable .... CUVID doesn't seem to work here, waiting for ffmpeg patches (search google for "cuvid filter_complex" for some discussion). That's the reason why there's resize+crop for nvenc, so if you must scale then just use THAT instead of npp to get max fps out of your card ...

**Comment by hydra3333** [comment]
> npp ... there's hardly any advantage to "vf -scale [..]" ie. scaling something down from 1920 to 1280 is 283fps (npp) ->260fps (vf -scale), so this is pretty much useless or hardly noticable .... 

Ooh, there's a nice find.

> That's the reason why there's resize+crop for nvenc, so if you must scale then just use THAT instead of npp to get max fps out of your card

And, great advice too !   Thank you very much.

**Comment by mirh** [comment]
The guy [here](https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/15) claims no problem into building the 32 bit loader (I'm not sure if due to merits of his PR or not, but still)

**Comment by hydra3333** [comment]
righty, thank you, i'll give the 32 bit loader build another whirl tonight then.

**Comment by schmidthubert** [comment]
OK, I got npp scaling working at PROPER speed now. :-) :-) 

There was/is something VERY IMPORTANT missing on the cmdline, which is adding "-hwaccel_output_format cuvid" or "-hwaccel_output_format cuda" if the parameter "-hwaccel cuvid" is already used.  You can check out the following post(s)/thread(s) or the actual sourcecode etc, if interested: 

https://ffmpeg.org/pipermail/ffmpeg-devel/2017-June/212565.html
https://patchwork.ffmpeg.org/patch/4032/

Sorry, but like I said previously, I've been very busy with more important things lately so could't really follow the actual ffmpeg development. >:-(( Trying to catch up a little now. ;) So here's what you need on the cmdline to get npp working with PROPER speed, and some fps numbers as well. These tests are *a  completely different encode*(!!!) now, so don't get confused by my earlier fps numbers! 

`00.[339fps]: ffmpeg -y -hwaccel cuvid -hwaccel_output_format cuvid -c:v h264_cuvid -i INFILE -c:v h264_nvenc [...encoding-parameters...] [[optional]-f format] OUTFILE[.ext]`
`01.[338fps]: ffmpeg -y -hwaccel cuda  -hwaccel_output_format cuda  -c:v h264_cuvid -i INFILE -c:v h264_nvenc [...encoding-parameters...] [[optional]-f format] OUTFILE[.ext]`
`02.[357fps]: ffmpeg -y -hwaccel cuvid -hwaccel_output_format cuvid -c:v h264_cuvid -i INFILE -vf "hwupload,scale_npp=w=1280:h=-1:format=yuv420p,hwdownload" -c:v h264_nvenc [...encoding-parameters...] [[optional]-f format] OUTFILE[.ext]`
`03.[383fps]: ffmpeg -y -hwaccel cuda  -hwaccel_output_format cuda  -c:v h264_cuvid -i INFILE -vf "hwupload,scale_npp=w=1280:h=-1:format=yuv420p,hwdownload" -c:v h264_nvenc [...encoding-parameters...] [[optional]-f format] OUTFILE[.ext]`
`04.[312fps]: ffmpeg -y -hwaccel cuvid -hwaccel_output_format cuvid -i INFILE -vf "hwupload,scale_npp=w=1280:h=-1:format=yuv420p,hwdownload" -c:v h264_nvenc [...encoding-parameters...] [[optional]-f format] OUTFILE[.ext]`
`05.[304fps]: ffmpeg -y -hwaccel cuda  -hwaccel_output_format cuda  -i INFILE -vf "hwupload,scale_npp=w=1280:h=-1:format=yuv420p,hwdownload" -c:v h264_nvenc [...encoding-parameters...] [[optional]-f format] OUTFILE[.ext]`
`06.[300fps]: ffmpeg -y -hwaccel cuvid -hwaccel_output_format cuvid -i INFILE -vf "hwupload_cuda,scale_npp=w=1280:h=-1:format=yuv420p,hwdownload" -c:v h264_nvenc [...encoding-parameters...] [[optional]-f format] OUTFILE[.ext]`
`07.[290fps]: ffmpeg -y -hwaccel cuda  -hwaccel_output_format cuda  -i INFILE -vf "hwupload_cuda,scale_npp=w=1280:h=-1:format=yuv420p,hwdownload" -c:v h264_nvenc [...encoding-parameters...] [[optional]-f format] OUTFILE[.ext]`
`[-]`
`08.[220fps]: ffmpeg -y -hwaccel cuvid -hwaccel_output_format cuvid -i INFILE -vf "scale=1280:-1" -c:v h264_nvenc [...encoding-parameters...] [[optional]-f format] OUTFILE[.ext]`
`09.[220fps]: ffmpeg -y -hwaccel cuvid -hwaccel_output_format cuda  -i INFILE -vf "scale=1280:-1" -c:v h264_nvenc [...encoding-parameters...] [[optional]-f format] OUTFILE[.ext]`
`10.[220fps]: ffmpeg -y -hwaccel cuvid -i INFILE -vf "scale=1280:-1" -c:v h264_nvenc [...encoding-parameters...] [[optional]-f format] OUTFILE[.ext]`
`[-]`
`11.[225fps]: ffmpeg -y -i INFILE -vf "scale=1280:-1" -c:v h264_nvenc [...encoding-parameters...] [[optional]-f format] OUTFILE[.ext]`

Now don't ask me why "-hwaccel_output_format cuvid" is even working even if's not in that mentioned patch but this npp subject has cost me enough time for the moment already now so feel free to investigate further by YOURSELF. Good Luck! :-)

**Comment by schmidthubert** [comment]
[Post Updated]

**Comment by hydra3333** [comment]
Beaut.  I am interested and will follow up on your info.  Nice work, thank you.

Busy ... OK, at the risk of it not being your scene, wishing you an idyllic mental image of 

a laid back deck chair under a tall palm tree 
on a still tropical beach with white crushed coral sand
in comfy white shorts 
with a bunch of pretty people taking turns gently massaging the feet and the ego
whilst sipping spiced rum'n'coke
for free

**Comment by schmidthubert** [comment]
LOL, nice, ta! ...  :)

**Comment by schmidthubert** [comment]
Just for completeness: 
`-hwaccel_output_format nv12`
or
`-hwaccel_output_format yuv420p`
[...]
will work here as well (depending on what format is used in the filter) ... There are many examples out there howto use filters, try google ...  ;) Another very good reference/read up here:  https://wiki.libav.org/Hardware/vaapi

**Comment by hydra3333** [comment]
@rdp 
> patches welcome! :)

well, ok :)  
I reckon this won't be useful, however since you suggested it, a proposed patch which hopefully adds opencl via code from KHRONOS git (there's a couple of patches you'd need to copy separately.

[rdp_add_openCL.diff.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/1253394/rdp_add_openCL.diff.txt)

The above patch hasn't been tested however mine with larger diff below has.

only for completeness, a larger patch which adds in a range of dependency builds and aligns with some other peoples' configure/build flags for various dependencies (mostly deadsix27's settings), and which builds bitdepths slightly differently ; there's a matching toolchain build file as well but it's based on yours.  yes it's a kludge for the x264 etc building which I know is incorrect but I live with it since I don't mind wasting cpu time overnight.

[rdp_cross_compile_ffmpeg_full.diff.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/1253403/rdp_cross_compile_ffmpeg_full.diff.txt)

**Comment by schmidthubert** [comment]
>-hwaccel_output_format {format}

"cuvid" for {format} doesn't make any sense at all. Actually it should throw an error, strange... At least for "invalid" formats it will log something if running ffmpeg in debug-mode, if I read the code right. What should be used here for {format} is one of the strings "ffmpeg -pix_fmts" is offering. So since "cuda" comes up as "H" ("Hardware accelerated format") then that's the fastest and explains the fps numbers here. :smiley_cat:

**Comment by hydra3333** [comment]
Hmm, thank you noted that 
`-hwaccel_output_format cuda` 
or 
`-hwaccel_output_format <format>` 
where <format> is one of the results of 
`ffmpeg -pix_fmts`
is technically valid whilst 
`-hwaccel_output_format cuvid`
may break at any time into the future.

**Comment by schmidthubert** [comment]
Yes, that 'cuda' format option seems good, that's what should be used. Here's the warning from the log when say "-hwaccel_output_format IDONTKNOW" is used:

`Unrecognised hwaccel output format: IDONTKNOWInput #0, matroska,webm, from 'D:\test.mkv':`

But it's just a warning and continues then, so not a real problem.  If 'cuda' is used then there's simply no entry at the logs same position. 

As for the accepted pix_fmts there's this:

`vf_scale_npp.c:`
`[...]`
`static const enum AVPixelFormat supported_formats[] = {`
`    AV_PIX_FMT_YUV420P,`
`    AV_PIX_FMT_NV12,`
`    AV_PIX_FMT_YUV444P,`
`};`
`[...]`

Anything else will not work.

**Comment by rboy1** [comment]
So does the latest RDP script support CUVID and NPP?
