### ISSUE TITLE
32bit build failure. libpng - configure: error: memset not found in libc

### ISSUE THREAD

**Issue by dellisj** [rdp/ffmpeg-windows-build-helpers#184]
Hi,

On a Windows 7 64bit PC with Cygwin the build_locally_lgpl_64_bit_option.bat works fine.

Attempts to build any 32 bit version of FFmpeg fails.  I've tried modifying the build_locally_gpl_32_bit_option.bat file with the same parameters as the 64 bit version - except for the 32 bit part.  This did not work either.

I also tried building on a 32 bit Windows 7 PC and had the same error:- 

doing git co master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
got no code changes, not forcing reconfigure for that...
already did make zimg_git ...
already did make google-snappy-32d6d7d ...
configuring libpng-1.5.26 (/cygdrive/c/Users/davellis/ffmpeg-windows-build-helpe
rs/native_build/windows/ffmpeg_local_builds/sandbox/win32/libpng-1.5.26) as $ PA
TH=/cygdrive/c/Users/davellis/ffmpeg-windows-build-helpers/native_build/windows/
ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-i686/bin:/usr/bin:/cygdriv
e/c/PROGRA~2/Borland/CBUILD~1/Bin:/cygdrive/c/PROGRA~2/Borland/CBUILD~1/Projects
/Bpl:/cygdrive/c/Program Files (x86)/Integrity/IntegrityClient10/bin:/cygdrive/c
/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Clie
nt:/cygdrive/c/windows/system32:/cygdrive/c/windows:/cygdrive/c/windows/System32
/Wbem:/cygdrive/c/windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Fi
les/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/In
tel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/In
tel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/In
tel/Intel(R) Management Engine Components/IPT:/cygdrive/c/PROGRA~2/INTEGR~1/Tool
kit/mksnt:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/90/Tools/binn:/cy
gdrive/c/Program Files (x86)/WebEx/Productivity Tools:/cygdrive/c/Program Files
(x86)/Sennheiser/SoftphoneSDK ./configure --host=i686-w64-mingw32 --prefix=/cygd
rive/c/Users/davellis/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_l
ocal_builds/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --disable-sh
ared --enable-static
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for i686-w64-mingw32-strip... i686-w64-mingw32-strip
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for i686-w64-mingw32-gcc... i686-w64-mingw32-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether i686-w64-mingw32-gcc accepts -g... yes
checking for i686-w64-mingw32-gcc option to accept ISO C89... none needed
checking whether i686-w64-mingw32-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of i686-w64-mingw32-gcc... gcc3
checking dependency style of i686-w64-mingw32-gcc... gcc3
checking build system type... i686-pc-cygwin
checking host system type... i686-w64-mingw32
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking how to print strings... printf
checking for ld used by i686-w64-mingw32-gcc... /cygdrive/c/Users/davellis/ffmpe
g-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/cross_c
ompilers/mingw-w64-i686/i686-w64-mingw32/bin/ld.exe
checking if the linker (/cygdrive/c/Users/davellis/ffmpeg-windows-build-helpers/
native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-i686/
i686-w64-mingw32/bin/ld.exe) is GNU ld... yes
checking how to run the C preprocessor... i686-w64-mingw32-gcc -E
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for gawk... (cached) gawk
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for BSD- or MS-compatible name lister (nm)... /cygdrive/c/Users/davelli
s/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/
cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-nm -B
checking the name lister (/cygdrive/c/Users/davellis/ffmpeg-windows-build-helper
s/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-i68
6/bin/i686-w64-mingw32-nm -B) interface... BSD nm
checking the maximum length of command line arguments... 8192
checking how to convert i686-pc-cygwin file names to i686-w64-mingw32 format...
func_convert_file_cygwin_to_w32
checking how to convert i686-pc-cygwin file names to toolchain format... func_co
nvert_file_noop
checking for /cygdrive/c/Users/davellis/ffmpeg-windows-build-helpers/native_buil
d/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mi
ngw32/bin/ld.exe option to reload object files... -r
checking for i686-w64-mingw32-objdump... i686-w64-mingw32-objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|
^x86 DLL
checking for i686-w64-mingw32-dlltool... i686-w64-mingw32-dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_imp
lib
checking for i686-w64-mingw32-ar... i686-w64-mingw32-ar
checking for archiver @FILE support... @
checking for i686-w64-mingw32-strip... (cached) i686-w64-mingw32-strip
checking for i686-w64-mingw32-ranlib... i686-w64-mingw32-ranlib
checking command to parse /cygdrive/c/Users/davellis/ffmpeg-windows-build-helper
s/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-i68
6/bin/i686-w64-mingw32-nm -B output from i686-w64-mingw32-gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for i686-w64-mingw32-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... no
checking for i686-w64-mingw32-as... i686-w64-mingw32-as
checking for i686-w64-mingw32-dlltool... (cached) i686-w64-mingw32-dlltool
checking for i686-w64-mingw32-objdump... (cached) i686-w64-mingw32-objdump
checking for objdir... .libs
checking if i686-w64-mingw32-gcc supports -fno-rtti -fno-exceptions... no
checking for i686-w64-mingw32-gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if i686-w64-mingw32-gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if i686-w64-mingw32-gcc static flag -static works... yes
checking if i686-w64-mingw32-gcc supports -c -o file.o... yes
checking if i686-w64-mingw32-gcc supports -c -o file.o... (cached) yes
checking whether the i686-w64-mingw32-gcc linker (/cygdrive/c/Users/davellis/ffm
peg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/cross
_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld.exe) supports shared libraries
... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for ANSI C header files... (cached) yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for C/C++ restrict keyword... __restrict
checking for working strtod... yes
checking for memset... no
configure: error: memset not found in libc
done with local build...check output above to see if successfull..
if not successful you might try re running the script, it "should" pick up where
 it left off.

if you want more advanced configuration (like building mplayer or mp4box, 10-bit
, etc)
open C:\Users\davellis\ffmpeg-windows-build-helpers\native_build\windows\ffmpeg_
local_builds\cygwin_local_install\cygwin.bat
(which sets up the path for you)
then cd to C:\Users\davellis\ffmpeg-windows-build-helpers\native_build\windows\f
fmpeg_local_builds and run the script manually yourself with -h
like $ cd /cygdrive/c/.../ffmpeg_local_builds $ ./cross_compile_ffmpeg.sh -h
Press any key to continue . . .

Any ideas?  

Thanks

**Comment by rdp** [comment]
I guess your work around for now is linux VM or windows 10 bash shell :|

**Comment by rdp** [comment]
OK it just worked for me OK here, what OS exactly?

**Comment by dellisj** [comment]
Sorry for the delayed reply.
I'm using Windows 7 Enterprise 32bit and 64bit and still see the same issue with a fresh install of Cygwin etc.
