### ISSUE TITLE
Multiple bitdepth compatible x265 build

### ISSUE THREAD

**Issue by nistvan86** [rdp/ffmpeg-windows-build-helpers#185]
Is it possible to build an ffmpeg binary which contains a multiple bitdepth compatible x265? (possible the same with x264, i didn't check if it supports that)

Encoder info should look like this (grabbed it from the net, so sadly don't know how it's made):
`x265 [info]: build info [Mac OS X][clang 7.0.2][64 bit] 8bit+10bit+12bit`

Currently a high bitdepth build with your tool results in this (current build on my PC):
`x265 [info]: build info [Windows][GCC 4.9.3][64 bit] 10bit`

**Comment by nistvan86** [comment]
Quick googling revealed that the x265 multi-library interface is the key to make this happen https://patches.libav.org/patch/57523/

Here I've found some instructions on how to build this. http://x265.readthedocs.io/en/default/api.html#build-implications

**Comment by rzcat** [comment]
hi, would you mind send me a copy of your compiled result?
Win64+libx265 10bit
I've met some problems #181 while compiling, and updating to Fedora 25 doesnt change anything
and i also think a multiple bitdepth compatible x265 build would be handy

**Comment by rdp** [comment]
It's unclear how to make ffmpeg actually "use" this one or that one,
though, unfortunately :

**Comment by nistvan86** [comment]
@rdp in my understanding, with a multi bitdepth build the used x265 sub-library is depending on the pixel format being used. When compiled with 10bit x265 only, ffmpeg doesn't have any choice than to use that when you specify libx265 as a video encoder (and imo, the encoder automatically does the pixel format conversion in the background). But if there are multiple bitdepth options available, you should explicitly convert pixel formats so the correct encoder is triggered. eg. if the input is a 8bit video file, and you want to encode it as 10bit x265, you have to add `-pix_fmt yuv420p10le`.

@rzcat i see you could finally compile it on a Windows box. Anyway, i don't know how could i send you a private message here. Didn't Github had that feature in the past?

**Comment by nistvan86** [comment]
Here's an example on this: https://bitbucket.org/multicoreware/x265/issues/171/10-bit-compression-through-ffmpeg-pix_fmt#comment-21053195

**Comment by rdp** [comment]
Yeah I'm not sure of how to actually use it, yours could be spot on :)

**Comment by rzcat** [comment]
Yep I have my own compiled successfully, thanks
And I also couldn't find a way to send private msg here😰
With the high bit depth flag enabled, the binary result coming from rdp's script does have both 8bit+10bit, though you have to choose -pix_fmt yourself, default is 10bit

**Comment by nistvan86** [comment]
@rzcat well, i hoped that you are right and that's the only thing I've missed, but adding `-pix_fmt yuv420p` to my encoder command line still encodes 10bit video.  MPC-HC says `Video: HEVC 1280x720 25fps [V: hevc main 10, yuv420p10le, 1280x720]`.

**Comment by MaverickTse** [comment]
Actually the x265 source code already contains facilities to build a static executable supporting multi-bit depth.... look for multilib.sh

The following is the content taken from /build/linux/multilib.sh
```
#!/bin/sh

mkdir -p 8bit 10bit 12bit

cd 12bit
cmake ../../../source -DHIGH_BIT_DEPTH=ON -DEXPORT_C_API=OFF -DENABLE_SHARED=OFF -DENABLE_CLI=OFF -DMAIN12=ON
make ${MAKEFLAGS}

cd ../10bit
cmake ../../../source -DHIGH_BIT_DEPTH=ON -DEXPORT_C_API=OFF -DENABLE_SHARED=OFF -DENABLE_CLI=OFF
make ${MAKEFLAGS}

cd ../8bit
ln -sf ../10bit/libx265.a libx265_main10.a
ln -sf ../12bit/libx265.a libx265_main12.a
cmake ../../../source -DEXTRA_LIB="x265_main10.a;x265_main12.a" -DEXTRA_LINK_FLAGS=-L. -DLINKED_10BIT=ON -DLINKED_12BIT=ON
make ${MAKEFLAGS}

# rename the 8bit library, then combine all three into libx265.a
mv libx265.a libx265_main.a

uname=`uname`
if [ "$uname" = "Linux" ]
then

# On Linux, we use GNU ar to combine the static libraries together
ar -M <<EOF
CREATE libx265.a
ADDLIB libx265_main.a
ADDLIB libx265_main10.a
ADDLIB libx265_main12.a
SAVE
END
EOF

else

# Mac/BSD libtool
libtool -static -o libx265.a libx265_main.a libx265_main10.a libx265_main12.a 2>/dev/null
```

seems not that difficult to integrate with this repo.

**Comment by MaverickTse** [comment]
tried, but cannot get cmake to work. keep complaining cannot find the 10bit lib.... even though I symlink the lib in the current folder and mingw lib folder

**Comment by rdp** [comment]
Are there command line parameters to use this from x265.exe?

**Comment by MaverickTse** [comment]
http://x265.readthedocs.io/en/default/cli.html
--output-depth

**Comment by rdp** [comment]
OK my guess is that ffmpeg isn't "smart enough" to use/select the appropriate multiple bit depth x265 unfortunately, let me know if you can figure out if it can or not, until then we'll use the "build two separate exe's" unfortunately I guess...

**Comment by shivSD** [comment]
How do you build/compile x265 for 10 bit .. is there any build configuration file that needs to be changed for 10 bit ?

cd x265/build/linux
./make-Makefiles.bash
make
make install

Gives me 8-bit x265.

x265 [info]: HEVC encoder version 2.3+33-0b7d54dbb71a
x265 [info]: build info [Linux][GCC 4.8.4][64 bit] 8bit

Please let me know if I'm missing something here to get 10bit x265 binary & so
