### ISSUE TITLE
[Feature] Add option to build L-Smash and L-Smash Works

### ISSUE THREAD

**Issue by MaverickTse** [rdp/ffmpeg-windows-build-helpers#186]
L-Smash: https://github.com/l-smash/l-smash
L-Smash Works: https://github.com/VFR-maniac/L-SMASH-Works

It would be nice to see if these two tools get integrated with this build script as an option. While l-smash is easy to build, LSW is difficult as it depends on both FFmpeg libraries and l-smash.

The Avisynth part may not be built on native Linux, but hopefully Vapoursynth plugin and AviUtl plugin (32bit only) can be integrated.

**Comment by MaverickTse** [comment]
Submitted pull request:
https://github.com/rdp/ffmpeg-windows-build-helpers/pull/187

**Comment by rdp** [comment]
thanks for your contribution
