### ISSUE TITLE
[Feature] MPV/VapourSynth/Python etc

### ISSUE THREAD

**Issue by DeadSix27** [rdp/ffmpeg-windows-build-helpers#188]
I've been working on a fork myself for probably weeks and with some work-arrounds got mpv compiled with all bells and whistles including lua/python/vapoursynth support and now recently saw the LSMash feature, is that compiling vapoursynth properly? As I still struggle to do that. I use self made dlltool based lib files based on the official binary.

I can work on a pull request if you'd like (but thats gonna take a while as I did add quite a lot to the script.
And completely replaced the old imo irrelevant MPlayer with MPV.

(also added other stuff thats not relevant to ffmpeg at all tho, wget & curl for private use, which I could add as well if you think thats worth adding)

Id have to adapt the functions and create an entirely new one just for mpv as that uses wscript rather than cmake/configure

On the other hand, if there is no way to compile Vapoursynth properly maybe a automatic binary download of github including the processing with dlltool could be ok too, its all in the realms of GPL and can be very optionally enabled etc.

Same goes for Python, as cross-compiling python is a freaking nightmare (which is needed for vapoursynth compilation, if we use the dlltool vapoursynth libs we wouldnt even have to bother with python)

EDIT: Note, the fork is not on my github, as I didn't bother commiting every single change..

EDIT2: Note, I compile almost all mpv libs of git-master and VapourSynth would be part of that too. 
As previously mentioned it's gonna take a while to make a proper pull request especially since my dev machine is currently not working. So by now I just wait for your opinion on this.

EDIT3: As a suggestion, what could also be done, is add somewhat of a basic plugin support in the script to include submodules. 
(Plugin sounds a bit over-doing, what I really mean is just a line loading bash files of "plugins/" subfolder or something.)

**Comment by rdp** [comment]
sure

**Comment by MaverickTse** [comment]
@DeadSix27 
Personally I rarely use VapourSynth, I add the LS/LSW feature because I want the AviUtl plugin to be build in one go with FFmpeg. (Actually it is due to Zeranoe's site blocking all bots and installer that force me to make another build bot...)
So I didn't test if the vapoursynth plugin actually works, I can only it builds and AviUtl plugin works fine.

**Comment by DeadSix27** [comment]
@MaverickTse 
Ah okay, ye i figured that, I need VapourSynth for MPV to use SVP & Python/Lua plugin support.
So I use self-made libraries which I could easily automate in the script.

**Comment by rdp** [comment]
If you just need an installer location you could create a sourceforge and
upload zeranoe builds to that maybe :)

**Comment by MaverickTse** [comment]
@rdp Actually I'm already using Dropbox. The problem is I don't want to do it by hand, I want it automated, but Zeranoe's server is too shabby and have to block all bots.
This is quite a problem as most people don't want to(and can't) build programs themselves, and the only Windows binary DL link on FFmpeg official site points to Zeranoe only.

**Comment by DeadSix27** [comment]
Well I began to offer binaries not so long ago https://files.dsix.tech/binaries/amd64/

**Comment by MaverickTse** [comment]
@DeadSix27 I bet most end-user don't need nightlies, so a weekly or monthly (working) build would be enough... but no one take a step further: put it on torrent

**Comment by DeadSix27** [comment]
What do you mean by put it on torrent? 

Oh and its mainly for personal use. I like to have bleeding edge stuff and all the features enabled in my stuff just in case I ever need them.
MPV is also my main Video Player now and replaces MPC so I needed it to work properly and be very up to date whenever I use it, so I began compiling it for myself every night automated.

**Comment by MaverickTse** [comment]
@DeadSix27 I mean using the bit-torrent method to distribute the binary. Many linux distros are doing this (even Win10 update is doing this). Then we don't need to worry if a single server is down, or that server is blocking some region.

A personal bleeding edge build is fine, but there are many devs need to maintain software packages that include FFmpeg and its associate. The end-user would only care about the final package in working condition, so nightlies are not preferred from a package manager standpoint.

**Comment by DeadSix27** [comment]
Oh In that way, well I still have to say, this is mainly for personal use, you can compare it to zeranoe's nightly builds in fact. He offers them too, nightly yet they're bleeding edge. Same goes for my MPV/ffmpeg builds.

**Comment by rdp** [comment]
It is possible to automate sourceforge (scp upload) though unfortunately
not super easy.  Yeah if you need super up to date builds then build them
yourself no problem there :)

**Comment by rdp** [comment]
OK let me know when pull request ready.  The LSW plugin seems to be building OK now FWIW.

**Comment by rdp** [comment]
Does it need python to link against it?  I guess if there's a specific version you need (and it has to build to a windows version) I could look at it :)

**Comment by DeadSix27** [comment]
@rdp I'm currently  very busy :) I'm working on it from time to time, i finished the lib download code.

And about the python version, it doesn't matter anymore, afaik VapourSynth requires C++11 and mutex which our mingw doesn't have. 

Either way, don't expect the pull request to come soon, but it will come! :p Just gonna take a bit.
(work etc)

**Comment by rdp** [comment]
no rush of course :)

**Comment by MaverickTse** [comment]
I have forked and made a few changes. See if you guys interested:

- auto use aria2c (v1.30 or above) for faster download (tar balls and zip only)
- enabled winpthreads (I guess this is needed for C++11 concurrency features)
- use GCC 5
- added a separate packaging script

still under test and may break any time however

**Comment by DeadSix27** [comment]
@MaverickTse I use GCC5 anyway, isn't that default?

**Comment by DeadSix27** [comment]
@MaverickTse  "--gcc-ver=5.4.0" I use 5.4 on rdps script, it does work, but i guess you mean default?

**Comment by MaverickTse** [comment]
@DeadSix27 you have edited the script.
