### ISSUE TITLE
Error occured when enabled build l-smash

### ISSUE THREAD

**Issue by kgp700** [rdp/ffmpeg-windows-build-helpers#189]
I don't know what is problem...

INSTALL	libavutil/hwcontext_vdpau.h
INSTALL	libavutil/imgutils.h
INSTALL	libavutil/intfloat.h
INSTALL	libavutil/intreadwrite.h
INSTALL	libavutil/lfg.h
INSTALL	libavutil/log.h
INSTALL	libavutil/macros.h
INSTALL	libavutil/mathematics.h
INSTALL	libavutil/mastering_display_metadata.h
INSTALL	libavutil/md5.h
INSTALL	libavutil/mem.h
INSTALL	libavutil/motion_vector.h
INSTALL	libavutil/murmur3.h
INSTALL	libavutil/opt.h
INSTALL	libavutil/parseutils.h
INSTALL	libavutil/pixdesc.h
INSTALL	libavutil/pixelutils.h
INSTALL	libavutil/pixfmt.h
INSTALL	libavutil/random_seed.h
INSTALL	libavutil/rc4.h
INSTALL	libavutil/rational.h
INSTALL	libavutil/replaygain.h
INSTALL	libavutil/ripemd.h
INSTALL	libavutil/samplefmt.h
INSTALL	libavutil/sha.h
INSTALL	libavutil/sha512.h
INSTALL	libavutil/spherical.h
INSTALL	libavutil/stereo3d.h
INSTALL	libavutil/threadmessage.h
INSTALL	libavutil/time.h
INSTALL	libavutil/timecode.h
INSTALL	libavutil/timestamp.h
INSTALL	libavutil/tree.h
INSTALL	libavutil/twofish.h
INSTALL	libavutil/version.h
INSTALL	libavutil/xtea.h
INSTALL	libavutil/tea.h
INSTALL	libavutil/lzo.h
INSTALL	libavutil/avconfig.h
INSTALL	libavutil/ffversion.h
INSTALL	libavutil/libavutil.pc
Done! You will find 32 bit  non_free=n binaries in /home/kgpbuild/ffmpegbuild5/sandbox/win32/ffmpeg_git/*.exe
2016. 12. 17. (토) 21:05:19 KST
Cloning L-Smash Works Repo
Downloading (via git clone) lsw from https://github.com/VFR-maniac/L-SMASH-Works.git
Cloning into 'lsw.tmp'...
remote: Counting objects: 5422, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 5422 (delta 4), reused 0 (delta 0), pack-reused 5411
Receiving objects: 100% (5422/5422), 2.45 MiB | 771.00 KiB/s, done.
Resolving deltas: 100% (3455/3455), done.
Checking connectivity... done.
done git cloning to lsw
doing git co master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Updating to latest lsw git version [origin/master]...
Already up-to-date.
got no code changes, not forcing reconfigure for that...
Building LSW VapourSynth plugin
configuring VapourSynth (/home/kgpbuild/ffmpegbuild5/sandbox/win32/lsw/VapourSynth) as $ PATH=/home/kgpbuild/ffmpegbuild5/sandbox/cross_compilers/mingw-w64-i686/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games ./configure --prefix=/home/kgpbuild/ffmpegbuild5/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --cross-prefix=/home/kgpbuild/ffmpegbuild5/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-
/home/kgpbuild/ffmpegbuild5/sandbox/win32/lsw/VapourSynth /home/kgpbuild/ffmpegbuild5/sandbox/win32/lsw/VapourSynth
/home/kgpbuild/ffmpegbuild5/sandbox/win32/lsw/VapourSynth
CFLAGS/LDFLAGS checking...
checking for liblsmash...
checking for libavformat...
error: libavformat checking failed.
error: libavformat/avformat.h might not be installed or some libs missing.

**Comment by rdp** [comment]
there should be a relevant config.log file somewhere?

**Comment by MaverickTse** [comment]
The test that works on my VM:

```
--build-ffmpeg-static=y \
--disable-nonfree=y \
--build-intel-qsv=n \
--sandbox-ok=y \
--compiler-flavors=win32 \
--build-libmxf=n \
--build-mp4box=n \
--build-mplayer=n \
--build-vlc=n \
--build-lsw=y \
--build-ismindex=n \
--build-dvbtee=n \
--build-x264-with-libav=n \
--prefer-stable=y \
--high-bitdepth=y \
--enable-gpl=y
```
Did you set --enable-gpl to n ?

**Comment by MaverickTse** [comment]
I can now replicate this problem... don't know why I have no problem when testing. Working on a fix.

**Comment by MaverickTse** [comment]
patch
https://github.com/rdp/ffmpeg-windows-build-helpers/pull/190/commits/119b2e51a706e443bb7debca082fdd2b264640dd

my bad for missing an 's'

**Comment by kgp700** [comment]
That's so simple problem:)
Thanks
I will try it.

**Comment by kgp700** [comment]
It's still not fixed...
I did apply your patch but
error message was same... nothing changed...
I don't know reason why Building LSW VapourSynth plugin after ffmpeg build done....
It's normal situation?

**Comment by MaverickTse** [comment]
What!? Wait a moment and let me build it again

**Comment by MaverickTse** [comment]
using
`./cross_compile_ffmpeg.sh \
--build-ffmpeg-static=y \
--disable-nonfree=y \
--build-intel-qsv=n \
--sandbox-ok=y \
--compiler-flavors=win32 \
--build-libmxf=n \
--build-mp4box=n \
--build-mplayer=n \
--build-vlc=n \
--build-lsw=y \
--build-ismindex=n \
--build-dvbtee=n \
--build-x264-with-libav=y \
--prefer-stable=y \
--high-bitdepth=n \
--enable-gpl=y`
Built successfully 
![screenshot from 2016-12-26 21-28-18](https://cloud.githubusercontent.com/assets/10569988/21482788/72ddc834-cbb3-11e6-8905-a40a2a59b475.png)

but VapourSynth Plugin is having a strange name (from the icon, you can tell it is Win32 binary)
![screenshot from 2016-12-26 21-34-44](https://cloud.githubusercontent.com/assets/10569988/21482793/7c492c42-cbb3-11e6-973f-8cacc1a602f6.png)

LSW plugins MUST be built AFTER FFmpeg because they need some libs from FFmpeg (libavresample is one of them)

**Comment by MaverickTse** [comment]
Just found out that a Win64 build after Win32 build FAILED with a mysterious missing libavformat
![screenshot from 2016-12-26 22-21-59](https://cloud.githubusercontent.com/assets/10569988/21483227/dcbfef56-cbb9-11e6-8ed0-ab83cf38df7b.png)
but from the log of FFmpeg, libavformat was certainly built.

**Comment by MaverickTse** [comment]
adding --target-os=mingw to VPS LSW configure string restore the correct filename but Win64 build still fails

**Comment by MaverickTse** [comment]
The culprit is found in an unexpected place: Intel Quick Sync
```
./cross_compile_ffmpeg.sh \
--build-ffmpeg-static=y \
--disable-nonfree=y \
--build-intel-qsv=n \
--sandbox-ok=y \
--compiler-flavors=win64 \
--build-libmxf=n \
--build-mp4box=n \
--build-mplayer=n \
--build-vlc=n \
--build-lsw=y \
--build-ismindex=n \
--build-dvbtee=n \
--build-x264-with-libav=y \
--prefer-stable=n \
--high-bitdepth=y \
--enable-gpl=y
```
built vaporsynth x64 LSW plugin successfully.

in the log when x64 failed to build, there are the lines:
```
libavutil.a(hwcontext_qsv.o): In function `qsv_transfer_data_from':
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:577: undefined reference to `MFXVideoVPP_RunFrameVPPAsync'
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:588: undefined reference to `MFXVideoCORE_SyncOperation'
/home/mavtse/Downloads/buildbot/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libavutil.a(hwcontext_qsv.o): In function `qsv_transfer_data_to':
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:616: undefined reference to `MFXVideoVPP_RunFrameVPPAsync'
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:627: undefined reference to `MFXVideoCORE_SyncOperation'
/home/mavtse/Downloads/buildbot/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libavutil.a(hwcontext_qsv.o): In function `qsv_frames_uninit':
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:135: undefined reference to `MFXVideoVPP_Close'
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:136: undefined reference to `MFXClose'
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:141: undefined reference to `MFXVideoVPP_Close'
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:142: undefined reference to `MFXClose'
/home/mavtse/Downloads/buildbot/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libavutil.a(hwcontext_qsv.o): In function `qsv_device_free':
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:668: undefined reference to `MFXClose'
/home/mavtse/Downloads/buildbot/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libavutil.a(hwcontext_qsv.o): In function `qsv_init_internal_session':
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:405: undefined reference to `MFXInit'
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:412: undefined reference to `MFXVideoCORE_SetHandle'
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:450: undefined reference to `MFXVideoVPP_Init'
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:419: undefined reference to `MFXVideoCORE_SetFrameAllocator'
/home/mavtse/Downloads/buildbot/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libavutil.a(hwcontext_qsv.o): In function `qsv_device_init':
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:105: undefined reference to `MFXVideoCORE_GetHandle'
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:119: undefined reference to `MFXQueryIMPL'
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:121: undefined reference to `MFXQueryVersion'
/home/mavtse/Downloads/buildbot/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libavutil.a(hwcontext_qsv.o): In function `qsv_device_create':
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:759: undefined reference to `MFXInit'
/home/mavtse/Downloads/buildbot/sandbox/x86_64/ffmpeg_git_x26x_high_bitdepth/libavutil/hwcontext_qsv.c:765: undefined reference to `MFXVideoCORE_SetHandle'
collect2: error: ld returned 1 exit status
1
```
Suggesting integration of QuickSync with FFmpeg may be having obscure problem (or the .pc file for libavutil is missing some linker flags) that require further investigation.

So there are a few ways to work around this and need @rdp to comment on:

1. If --enable-qsv is y, skip building LSW
2. If --enable-qsv is y, rebuild FFmpeg before building LSW
3. Fix the FFmpeg-QSV integration first

Which one would you guys prefer?

**Comment by rdp** [comment]
OK I did take some time to try and address this, check it :)

**Comment by MaverickTse** [comment]
Works great! Loves you man!
may be also submit a patch to FFmpeg?

**Comment by rdp** [comment]
Yeah I should, though I don't exactly know how to make it work right in
ffmpeg :(
