### ISSUE TITLE
Build failed after git updates from Dec 31, 2016 

### ISSUE THREAD

**Issue by nschlia** [rdp/ffmpeg-windows-build-helpers#192]
32 bit build fails:
```
08:19:10 sed: Cannot read /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/pkgconfig/libavutil.pc: File or directory not found
08:19:10 sed: Cannote read /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/pkgconfig/libswresample.pc: File or directory not found
```
64 bit build fails:
```
08:19:11 configuring dlfcn-win32_git (/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/x86_64/dlfcn-win32_git) as $ PATH=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin:/opt/mxe/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games ./configure --disable-shared --enable-static --cross-prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32- --prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
08:19:11 testing compiler: /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32-gcc -shared -o tmptest.dll tmptest.c
08:19:11 ./configure: 163: ./configure: /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32-gcc: not found
08:19:11 /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32-gcc could not create shared file with Windows API functions.
08:19:11 Make sure your MinGW system is working properly.
08:19:11 configuring dlfcn-win32_git (/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/x86_64/dlfcn-win32_git) as $ PATH=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin:/opt/mxe/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games ./configure --disable-shared --enable-static --cross-prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32- --prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
08:19:11 testing compiler: /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32-gcc -shared -o tmptest.dll tmptest.c
08:19:11 ./configure: 163: ./configure: /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32-gcc: not found
08:19:11 /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32-gcc could not create shared file with Windows API functions.
08:19:11 Make sure your MinGW system is working properly.
```
Build commands:
```
./cross_compile_ffmpeg.sh --gcc-cpu-count=4 --disable-nonfree=n --build-ffmpeg-static=n --build-ffmpeg-shared=y --compiler-flavors=multi --sandbox-ok=y --git-get-latest=y --high-bitdepth=n
./cross_compile_ffmpeg.sh --gcc-cpu-count=4 --disable-nonfree=n --build-ffmpeg-static=n --build-ffmpeg-shared=y --compiler-flavors=multi --sandbox-ok=y --git-get-latest=y --high-bitdepth=y
```
I deleted the whole sandbox and ran a freshly built. Same result.

**Comment by hydra3333** [comment]
+1
win32 builds OK, win64 fails with the message above.
`x86_64-w64-mingw32-gcc could not create shared file with Windows API functions.`

**Comment by rzcat** [comment]
compiled on a Win2k8r2 before, re-run the script for x265 2.2, Win64 builds OK (and fast)
running the script from scratch on Fedora 25 with gcc 6.3.1, same error with https://github.com/rdp/ffmpeg-windows-build-helpers/issues/181
commands: 
	--disable-nonfree=y --high-bitdepth=y --compiler-flavors=win64
Havent tried Win32 builds as Win32 x265 doesnt support asm when high bit depth is enabled

**Comment by nschlia** [comment]
Strange enough win32 builds for you. Because I did not have time to suspend the build it failed again with the same errors this morning. I then reverted to https://github.com/rdp/ffmpeg-windows-build-helpers/commit/083a16395942ff29a67eccd648a064f6ea36d118 and now the build runs through. So whatever the reason is, it does not seem to have to do with the other sources but the script.

If I find the time I'll try to find out which particular commit broke the build.

**Comment by MaverickTse** [comment]
For the x64 build, it is certainly due to wrong cross_prefix string and I have submitted a pull request just now: https://github.com/rdp/ffmpeg-windows-build-helpers/pull/193

the i686 one also fails for some components so I reverted the two lines involving cross_prefix to the old version

**Comment by nschlia** [comment]
@MaverickTse: Thanks! I just completed my tests, I'll post them anyway:

Now I checked out all commits one after the other and compiled. Seems that the latest https://github.com/rdp/ffmpeg-windows-build-helpers/commit/f157632806fec7f96fe1bf97b6bac02d21fea1d7 breaks the build. All checkouts compiled fine but the latter.

Interesting, though, that the 32 bit build went through fine this time. But 64 bit failed, still.

```
./cross_compile_ffmpeg.sh --gcc-cpu-count=4 --disable-nonfree=n --build-ffmpeg-static=n --build-ffmpeg-shared=y --compiler-flavors=multi --sandbox-ok=y --git-get-latest=y --high-bitdepth=n
...
08:13:42 configuring dlfcn-win32_git (/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/x86_64/dlfcn-win32_git) as $ PATH=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin:/var/lib/jenkins/bin:/var/lib/jenkins/bin:/opt/mxe/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games ./configure --disable-shared --enable-static --cross-prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32- --prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
08:13:42 testing compiler: /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32-gcc -shared -o tmptest.dll tmptest.c
08:13:42 ./configure: 163: ./configure: /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32-gcc: not found
08:13:42 /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32-gcc could not create shared file with Windows API functions.
08:13:42 Make sure your MinGW system is working properly.
```
Also should have mentioned my build environment:

MXE GCC: gcc version 4.9.3 (GCC)

jenkins@compilearsch:$ cat /proc/version
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19)

Running as Virtual Box VM with 8 GB Memory (Intel i5/4 cores)

**Comment by MaverickTse** [comment]
@nschlia 
While I don't know the point of doing --build-ffmepg-shared=y, I have run a lengthy test similar to yours:
```
./cross_compile_ffmpeg.sh \
--build-ffmpeg-static=n \
--build-ffmpeg-shared=y \
--disable-nonfree=n \
--build-intel-qsv=n \
--sandbox-ok=y \
--compiler-flavors=multi \
--build-libmxf=n \
--build-mp4box=n \
--build-mplayer=n \
--build-vlc=n \
--build-lsw=y \
--build-ismindex=n \
--build-dvbtee=n \
--build-x264-with-libav=n \
--prefer-stable=y \
--high-bitdepth=n \
--enable-gpl=y
```
There's another change when I test: removing the double-building of ffmpeg in the l-smash work section. Though, by default LSW should not be built unless specified explicitly and therefore not related to your problem.

So far it builds 32 and 64 fine on my Ubuntu machine.

Your log suggests the building failed just right after starting to build the toolchain. So please double check if cross_prefix is correct, and... please help to check if my patch is correct **(maybe typo that i missed)**

You may need to clean EVERYTHING, including the jenkins buildbot's cache if it has any, and reboot once.

**Comment by nschlia** [comment]
@MaverickTse:
Dunno why I added --build-ffmepg-shared=y, guess because in I played around with static and shared builds in the beginning...
Test compile is running now (deleted workspace so it gets freshily checked out). Only difference is that I added --gcc-cpu-count=4.

**Comment by nschlia** [comment]
32 bits: OK
32 bits fails:

```
12:33:25 **************Starting 64-bit builds...
12:33:25 Downloading (via git clone) dlfcn-win32_git from https://github.com/dlfcn-win32/dlfcn-win32.git
12:33:25 Klone nach 'dlfcn-win32_git.tmp'...

12:33:26 done git cloning to dlfcn-win32_git

12:33:26 doing git co master
12:33:26 Bereits auf 'master'
12:33:26 Ihr Branch ist auf dem selben Stand wie 'origin/master'.
12:33:26 Updating to latest dlfcn-win32_git git version [origin/master]...
12:33:26 Already up-to-date.
12:33:26 got no code changes, not forcing reconfigure for that...
12:33:26 configuring dlfcn-win32_git (/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/x86_64/dlfcn-win32_git) as $ PATH=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin:/var/lib/jenkins/bin:/var/lib/jenkins/bin:/opt/mxe/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games ./configure --disable-shared --enable-static --cross-prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32- --prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
12:33:26 testing compiler: /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32-gcc -shared -o tmptest.dll tmptest.c
12:33:26 ./configure: 163: ./configure: /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32-gcc: not found
12:33:26 /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64/bin/bin/x86_64-w64-mingw32-gcc could not create shared file with Windows API functions.
12:33:26 Make sure your MinGW system is working properly.
12:33:26 Build step 'Shell ausführen' marked build as failure
```

**Comment by MaverickTse** [comment]
This is puzzling, can you post your current ```cross_compile_ffmpeg.sh``` ?

**Comment by nschlia** [comment]
I guess I found it, check this line out:

12:33:26 ./configure: 163: ./configure: /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-x86_64**/bin/bin/**x86_64-w64-mingw32-gcc: not found

Notice the bin/bin? :)

That's in line 1874  cross_prefix="$path_addition/bin/x86_64-w64-mingw32-", in 1855 there's a similar change for 32 bit "cross_prefix="$path_addition/i686-w64-mingw32-"" without the extra bin...

**Comment by MaverickTse** [comment]
That's what my pull request is all about... are you using a simple `git clone` to get this repo? The pull request is not merged yet and the changes will not show up with a simple `git clone`

**Comment by nschlia** [comment]
Oops, no, I did not see there was a pull request. You mean https://github.com/rdp/ffmpeg-windows-build-helpers/pull/193? I can update to that an rebuild.

**Comment by nschlia** [comment]
I patched cross_compile_ffmpeg.sh, I did not revert the changes to the last commit but only removed the extra bin/. The build is OK now.

I cannot say why the 32 bit build failed on me in the first place, even after deleting the sandbox and once deleting the whole checkout. The last five or so times it went through.

**Comment by rdp** [comment]
OK I put back in the path_addition stuff, so should be good now, give it a whirl :)

**Comment by nschlia** [comment]
Close is OK, compiles went through with the latest changes (deleted workspace and let Jenkins do a fresh git pull).
