### ISSUE TITLE
suggested changes to build with OpenCL and CUDA/CUVID

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#197]
Hello, a linux newbie here.   I tried a roughie hack to build ffmpeg with OpenCL and with nvidia's CUVID/CUDA.   Unfortunately, it requires the user to copy some Windows files by hand (Opencl dll's and some nvidia codec SDK headers and libs) into pre-prepared folders.

Are you able to incorporate any parts of the hack into your script so as to have an ffmpeg with OpenCL and CUDA/CUVID built if chosen ? (lines with "2017." denote start and end of hacks).

Attached is the hack.
[cross_compile_ffmpeg_opencl_cuda_cuvid.sh.TXT](https://github.com/rdp/ffmpeg-windows-build-helpers/files/707505/cross_compile_ffmpeg_opencl_cuda_cuvid.sh.TXT)

Of interest, on ubuntu 16.04 I added a bunch of comments and references and then had to take them all out again because the script threw an error along the lines of premature eof found, as if the script was reaching a size limit of some kind and the last few lines in the script were discarded.

Thanks.

**Comment by rdp** [comment]
Was it successful? You can test it by running with the nvidia sharp filter
I believe...

**Comment by hydra3333** [comment]
Well, it didn't crash with the unsharp video filter which supposedly uses OpenCL if you tell it to
`-filter:v yadif=0:0:0,unsharp=opencl=1:luma_msize_x=3:luma_msize_y=3:luma_amount=0.5:chroma_msize_x=3:chroma_msize_y=3:chroma_amount=0.5,setdar=dar=16/9`

OK, nvidia sharp filter I'm now off to search for "nvidia sharp filter" and try that ...

**Comment by hydra3333** [comment]
Oh.  May I suggest don;t bother with cuda/cuvid - the decoder spits a lot of errors and tends to crash.

**Comment by rdp** [comment]
any speedup?

**Comment by hydra3333** [comment]
Not for cuvid/cuda, way way way way too unreliable.
OpenCL results at  https://ffmpeg.zeranoe.com/forum/viewtopic.php?f=5&t=1787&p=11908#p11908
OpenCL gave Unsharp Mask a speedup - by a factor of 3x.  Huge.

**Comment by hydra3333** [comment]
Hello, I didn't find an nividia sharp filter inside ffmpeg ... can you please clarify ?

**Comment by rdp** [comment]
just the unsharp=opencl one

**Comment by hydra3333** [comment]
OK, I have been and it's reasonable for the money :) and the speed is great.

**Comment by hydra3333** [comment]
well well this
https://ffmpeg.org/pipermail/libav-user/2017-January/010042.html
says
> On Thu, Jan 12, 2017 at 8:19 PM, Morten Fugl <morten at sportcaster.dk> wrote:
> > When changing ffmpeg to support nvidia hw decoding, I followed this guide:
> > https://developer.nvidia.com/ffmpeg
> > The guide says "Copy the NVIDIA video header files to the respective include
> > folders", but which files should I copy to which folders?
> 
> If you use a recent Git master version of ffmpeg, you don't need to
> copy any headers anymore, cuda/cuvid decoding and nvenc encoding is
> supported out of the box.
> 
> - Hendrik

So, to build with cuda there is now no need to copy headers and whatnot any more, by the looks.
I must revisit m7y op-enl build script and update ot to specify build with CUDA as well
