### ISSUE TITLE
Does the script actually build nvenc support?

### ISSUE THREAD

**Issue by msmollin** [rdp/ffmpeg-windows-build-helpers#198]
Title pretty much says it all. It's mentioned in the readme, but I can't find any reference to downloading the NVENC SDK in the code?

**Comment by rdp** [comment]
it's included inline in ffmpeg these days...

**Comment by msmollin** [comment]
Finally got around to spinning up a VM and testing this out - it is indeed supported as you say! But, it's missing libnpp support. I'll open a new issue for that!

**Comment by jiangtiandao** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/commit/9f97c1aa51e7778c7b6fed02ab971b703908907f
@msmollin

**Comment by hydra3333** [comment]
you might want to do some research first
https://ffmpeg.zeranoe.com/forum/viewtopic.php?f=3&t=858&start=40#p11902
