### ISSUE TITLE
Cross compile build error on zimg_git

### ISSUE THREAD

**Issue by mtrandl** [rdp/ffmpeg-windows-build-helpers#200]
make[1]: Entering directory '/home/user/ffmpeg-windows-build-helpers-master/sandbox/x86_64/zimg_git'
  CXX      dummy.lo
  CXX      src/zimg/colorspace/libzimg_internal_la-operation_impl_x86.lo
  CXX      src/zimg/common/libzimg_internal_la-x86util.lo
In file included from src/zimg/colorspace/operation_impl_x86.cpp:4:0:
src/zimg/colorspace/operation.h:6:17: fatal error: cmath: No such file or directory
 #include <cmath>
                 ^
compilation terminated.
Makefile:2307: recipe for target 'src/zimg/colorspace/libzimg_internal_la-operation_impl_x86.lo' failed
make[1]: *** [src/zimg/colorspace/libzimg_internal_la-operation_impl_x86.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from src/zimg/common/x86util.cpp:3:0:
src/zimg/common/x86util.h:8:19: fatal error: cstdint: No such file or directory
 #include <cstdint>
                   ^
compilation terminated.
Makefile:2314: recipe for target 'src/zimg/common/libzimg_internal_la-x86util.lo' failed
make[1]: *** [src/zimg/common/libzimg_internal_la-x86util.lo] Error 1
make[1]: Leaving directory '/home/user/ffmpeg-windows-build-helpers-master/sandbox/x86_64/zimg_git'
Makefile:3075: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by rdp** [comment]
hmm built OK here, mind trying again, and if that doesn't work, nuke your sandbox/*/zimg_git and try it yet again? Thanks!

**Comment by rdp** [comment]
I'm not getting this, mind nuking your sandbox and trying again?

**Comment by mtrandl** [comment]
Noticed the following message, snipped from a larger list.
pax: Unable to create gcc-4.9.3/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/subtract_with_carry_01/operators/: Is a directory

Could be the older version of pax on this distro does not extract certain files with certain characters, and unable to determine how to get pax to extract everything.

Instead modified a couple of the scripts to use tar and not download and overwrite a modified mingw-w64-build-3.6.7.local. The build went through this time and ended with a build error on libvpx.
The scripts at this point were using gcc-6.3.0. Noticed the change back to gcc-4.9.3, and the build went through. Good.


What are the _g files?
ffmpeg_g.exe

To use the shared ffmpeg, which folder is used?
_shared			with all subfolders?
_shared.installed	bin subfolder only or all?

**Comment by Mitra-M** [comment]
Hi,
Thank you for this great script.

This is the first time that I'd like to compile ffmpeg using this script.
and I have no knowledge about bash/cygwin.

After run the build_locally_with_various_option_prompts.bat , I get this error too:
`make[1]: Entering directory '/home/user/ffmpeg-windows-build-helpers-master/sandbox/x86_64/zimg_git'
CXX dummy.lo
CXX src/zimg/colorspace/libzimg_internal_la-operation_impl_x86.lo
CXX src/zimg/common/libzimg_internal_la-x86util.lo
In file included from src/zimg/colorspace/operation_impl_x86.cpp:4:0:
src/zimg/colorspace/operation.h:6:17: fatal error: cmath: No such file or directory
#include 
^
compilation terminated.`

Above you said to mtrandl :"nuke your sandbox/*/zimg_git and try it yet again"

I do not know what is nuke and how can I do it.

please guide me to solve this problem.
(sorry for my bad English)

OS: Windows 8.1

**Comment by rdp** [comment]
still failing? it worked for me here just now...but that was OS X hmm...

**Comment by rdp** [comment]
are you using windows bash then?

**Comment by Mitra-M** [comment]
@rdp, 
I noticed that your script has no problem , It was my mistake.
My problem was solved, thank you very much.

**Comment by rdp** [comment]
what was the problem and how did you fix it, for followers? Thanks!
