### ISSUE TITLE
Build Failing, Trying to "Install"

### ISSUE THREAD

**Issue by arrmo** [rdp/ffmpeg-windows-build-helpers#202]
Hi,

I apologize if I'm just doing something wrong, but trying to run the cross-compile script (just to build), it fails in the end, as below. Note that this is building in Linux (Ubuntu 16.04 LTS).

make[1]: Entering directory '/mnt/ProgSSD/ffmpeg-windows-build-helpers/sandbox/x86_64/fdk-aac_git'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libfdk-aac.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libfdk-aac.so.1.0.0 /usr/local/lib/libfdk-aac.so.1.0.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libfdk-aac.so.1.0.0': Permission denied
Makefile:702: recipe for target 'install-libLTLIBRARIES' failed
make[1]: *** [install-libLTLIBRARIES] Error 1
make[1]: Leaving directory '/mnt/ProgSSD/ffmpeg-windows-build-helpers/sandbox/x86_64/fdk-aac_git'
Makefile:1573: recipe for target 'install-am' failed

It seems that it's trying to install (to Linux)?

Thanks!

**Comment by rdp** [comment]
Weird, would you nuke sandbox and try again?

**Comment by arrmo** [comment]
Sure, but ... dang it! Killed sandbox, started over ... but now I get this,
Error, "5.3.0" is not a valid option for --gcc-ver. The valid options are: 6.3.0 4.9.3 svn

Is this "normal"?

Thanks!

**Comment by rdp** [comment]
Were you using the gcc compiler script manually?

**Comment by arrmo** [comment]
Nope - just the cross-compile script. And just re-pulled from git, to make sure it's current (it is).

**Comment by arrmo** [comment]
If it helps, just checked gcc (gcc --version),
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by rdp** [comment]
nuke your sandbox/win32/*fdk* folder and run it again, post full output (FWIW it works OK here...)

**Comment by arrmo** [comment]
Hi,

I did above (entire sandbox), but did it again - along with another git fetch (to make sure it's current). It's working again now, thanks!
