### ISSUE TITLE
script exits when compiling SDL2-2.0.5 (it used to work!)

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#204]
Oh dear.  
An unchanged script which I've used to thankfully build a few successful ffmpeg's :) and now I see a compilation fail with SDL2-2.0.5 ?  
Ubuntu 16.04 VM - unchanged from the last successful build.  Sandbox was nuked before running the script.
Since everything else was unchanged, the obvious thing to consider is - did SDL2-2.0.5 change in a broken way ?
Suggestions very much welcomed.

> + echo 'making /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/win32/SDL2-2.0.5 as $ PATH=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/bin:$PATH make  -j 2'
> making /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/win32/SDL2-2.0.5 as $ PATH=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/bin:$PATH make  -j 2
> + echo
> 
> + '[' '!' -f configure ']'
> + nice make -j 2
> /bin/bash build-scripts/mkinstalldirs build
> /bin/bash build-scripts/updaterev.sh
> mkdir -p -- build
>   CC     build/SDL_assert.lo
>   CC     build/SDL_error.lo
>   CC     build/SDL_hints.lo
>   CC     build/SDL_log.lo
> src/SDL_log.c:309:12: warning: 'consoleAttached' defined but not used [-Wunused-variable]
>  static int consoleAttached = 0;
>             ^
> src/SDL_log.c:312:15: warning: 'stderrHandle' defined but not used [-Wunused-variable]
>  static HANDLE stderrHandle = NULL;
>                ^
>   CC     build/SDL_atomic.lo
>   CC     build/SDL_spinlock.lo
>   CC     build/SDL_audio.lo
>   CC     build/SDL_audiocvt.lo
> ...

>   CC     build/SDL_diskaudio.lo
>   CC     build/SDL_dummyaudio.lo
>   CC     build/SDL_windows.lo
>   CC     build/SDL_xinput.lo
> In file included from src/core/windows/SDL_xinput.c:24:0:
> src/core/windows/SDL_xinput.h:113:3: error: conflicting types for 'XINPUT_GAMEPAD_EX'
>  } XINPUT_GAMEPAD_EX;
>    ^
> In file included from src/core/windows/SDL_xinput.h:29:0,
>                  from src/core/windows/SDL_xinput.c:24:
> /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/include/xinput.h:182:3: note: previous declaration of 'XINPUT_GAMEPAD_EX' was here
>  } XINPUT_GAMEPAD_EX, *PXINPUT_GAMEPAD_EX;
>    ^
> In file included from src/core/windows/SDL_xinput.c:24:0:
> src/core/windows/SDL_xinput.h:119:3: error: conflicting types for 'XINPUT_STATE_EX'
>  } XINPUT_STATE_EX;
>    ^
> In file included from src/core/windows/SDL_xinput.h:29:0,
>                  from src/core/windows/SDL_xinput.c:24:
> /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/include/xinput.h:192:3: note: previous declaration of 'XINPUT_STATE_EX' was here
>  } XINPUT_STATE_EX, *PXINPUT_STATE_EX;
>    ^
> Makefile:547: recipe for target 'build/SDL_xinput.lo' failed
> make: *** [build/SDL_xinput.lo] Error 1
> make: *** Waiting for unfinished jobs....
> + exit 1
>

**Comment by hydra3333** [comment]
Here's the full console output:

> + download_and_unpack_file http://libsdl.org/release/SDL2-2.0.5.tar.gz SDL2-2.0.5
> + url=http://libsdl.org/release/SDL2-2.0.5.tar.gz
> ++ basename http://libsdl.org/release/SDL2-2.0.5.tar.gz
> + output_name=SDL2-2.0.5.tar.gz
> + output_dir=SDL2-2.0.5
> + [[ -z SDL2-2.0.5 ]]
> + '[' '!' -f SDL2-2.0.5/unpacked.successfully ']'
> + echo 'downloading http://libsdl.org/release/SDL2-2.0.5.tar.gz'
> downloading http://libsdl.org/release/SDL2-2.0.5.tar.gz
> + [[ -f SDL2-2.0.5.tar.gz ]]
> + curl -4 http://libsdl.org/release/SDL2-2.0.5.tar.gz --retry 50 -O -L --fail
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 4110k  100 4110k    0     0  1790k      0  0:00:02  0:00:02 --:--:-- 1790k
> + tar -xf SDL2-2.0.5.tar.gz
> + touch SDL2-2.0.5/unpacked.successfully
> + rm SDL2-2.0.5.tar.gz
> + cd SDL2-2.0.5
> + generic_configure ''
> + local extra_configure_options=
> + do_configure '--host=i686-w64-mingw32 --prefix=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --disable-shared --enable-static '
> + local 'configure_options=--host=i686-w64-mingw32 --prefix=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --disable-shared --enable-static '
> + local configure_name=
> + [[ '' = '' ]]
> + configure_name=./configure
> ++ pwd
> + local cur_dir2=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/win32/SDL2-2.0.5
> ++ basename /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/win32/SDL2-2.0.5
> + local english_name=SDL2-2.0.5
> ++ get_small_touchfile_name already_configured '--host=i686-w64-mingw32 --prefix=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --disable-shared --enable-static  ./configure'
> ++ local beginning=already_configured
> ++ local 'extra_stuff=--host=i686-w64-mingw32 --prefix=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --disable-shared --enable-static  ./configure'
> +++ echo -- --host=i686-w64-mingw32 --prefix=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --disable-shared --enable-static ./configure -DDECLSPEC=
> +++ /usr/bin/env md5sum
> ++ local 'touch_name=already_configured_cc9e6bd17113455f19dbe877af8303f2  -'
> +++ echo 'already_configured_cc9e6bd17113455f19dbe877af8303f2  -'
> +++ sed 's/ //g'
> ++ touch_name=already_configured_cc9e6bd17113455f19dbe877af8303f2-
> ++ echo already_configured_cc9e6bd17113455f19dbe877af8303f2-
> + local touch_name=already_configured_cc9e6bd17113455f19dbe877af8303f2-
> + '[' '!' -f already_configured_cc9e6bd17113455f19dbe877af8303f2- ']'
> + echo 'configuring SDL2-2.0.5 (/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/win32/SDL2-2.0.5) as $ PKG_CONFIG_PATH=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/pkgconfig PATH=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/bin:$PATH ./configure --host=i686-w64-mingw32 --prefix=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --disable-shared --enable-static '
> configuring SDL2-2.0.5 (/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/win32/SDL2-2.0.5) as $ PKG_CONFIG_PATH=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/pkgconfig PATH=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/bin:$PATH ./configure --host=i686-w64-mingw32 --prefix=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --disable-shared --enable-static 
> + '[' -f bootstrap ']'
> + [[ ! -f ./configure ]]
> + [[ ! -f ./configure ]]
> + rm -f 'already_*'
> + ./configure --host=i686-w64-mingw32 --prefix=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --disable-shared --enable-static
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... i686-w64-mingw32
> checking how to print strings... printf
> checking for i686-w64-mingw32-gcc... i686-w64-mingw32-gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.exe
> checking for suffix of executables... .exe
> checking whether we are cross compiling... yes
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether i686-w64-mingw32-gcc accepts -g... yes
> checking for i686-w64-mingw32-gcc option to accept ISO C89... none needed
> checking for a sed that does not truncate output... /bin/sed
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for fgrep... /bin/grep -F
> checking for ld used by i686-w64-mingw32-gcc... /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld
> checking if the linker (/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld) is GNU ld... yes
> checking for BSD- or MS-compatible name lister (nm)... /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-nm -B
> checking the name lister (/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-nm -B) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 1572864
> checking whether the shell understands some XSI constructs... yes
> checking whether the shell understands "+="... yes
> checking how to convert x86_64-unknown-linux-gnu file names to i686-w64-mingw32 format... func_convert_file_nix_to_w32
> checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
> checking for /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld option to reload object files... -r
> checking for i686-w64-mingw32-objdump... i686-w64-mingw32-objdump
> checking how to recognize dependent libraries... pass_all
> checking for i686-w64-mingw32-dlltool... i686-w64-mingw32-dlltool
> checking how to associate runtime and link libraries... func_cygming_dll_for_implib
> checking for i686-w64-mingw32-ar... i686-w64-mingw32-ar
> checking for archiver @FILE support... @
> checking for i686-w64-mingw32-strip... i686-w64-mingw32-strip
> checking for i686-w64-mingw32-ranlib... i686-w64-mingw32-ranlib
> checking for gawk... no
> checking for mawk... mawk
> checking command to parse /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-nm -B output from i686-w64-mingw32-gcc object... ok
> checking for sysroot... no
> checking for i686-w64-mingw32-mt... no
> checking for mt... mt
> configure: WARNING: using cross tools not prefixed with host triplet
> checking if mt is a manifest tool... no
> checking how to run the C preprocessor... i686-w64-mingw32-gcc -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for dlfcn.h... yes
> checking for i686-w64-mingw32-as... i686-w64-mingw32-as
> checking for i686-w64-mingw32-dlltool... (cached) i686-w64-mingw32-dlltool
> checking for i686-w64-mingw32-objdump... (cached) i686-w64-mingw32-objdump
> checking for objdir... .libs
> checking if i686-w64-mingw32-gcc supports -fno-rtti -fno-exceptions... no
> checking for i686-w64-mingw32-gcc option to produce PIC... -DDLL_EXPORT -DPIC
> checking if i686-w64-mingw32-gcc PIC flag -DDLL_EXPORT -DPIC works... yes
> checking if i686-w64-mingw32-gcc static flag -static works... yes
> checking if i686-w64-mingw32-gcc supports -c -o file.o... yes
> checking if i686-w64-mingw32-gcc supports -c -o file.o... (cached) yes
> checking whether the i686-w64-mingw32-gcc linker (/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld) supports shared libraries... yes
> checking dynamic linker characteristics... Win32 ld.exe
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... no
> checking whether to build static libraries... yes
> checking for i686-w64-mingw32-gcc... (cached) i686-w64-mingw32-gcc
> checking whether we are using the GNU C compiler... (cached) yes
> checking whether i686-w64-mingw32-gcc accepts -g... (cached) yes
> checking for i686-w64-mingw32-gcc option to accept ISO C89... (cached) none needed
> checking for i686-w64-mingw32-g++... i686-w64-mingw32-g++
> checking whether we are using the GNU C++ compiler... yes
> checking whether i686-w64-mingw32-g++ accepts -g... yes
> checking how to run the C++ preprocessor... i686-w64-mingw32-g++ -E
> checking for ld used by i686-w64-mingw32-g++... /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld
> checking if the linker (/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld) is GNU ld... yes
> checking whether the i686-w64-mingw32-g++ linker (/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld) supports shared libraries... yes
> checking for i686-w64-mingw32-g++ option to produce PIC... -DDLL_EXPORT -DPIC
> checking if i686-w64-mingw32-g++ PIC flag -DDLL_EXPORT -DPIC works... yes
> checking if i686-w64-mingw32-g++ static flag -static works... yes
> checking if i686-w64-mingw32-g++ supports -c -o file.o... yes
> checking if i686-w64-mingw32-g++ supports -c -o file.o... (cached) yes
> checking whether the i686-w64-mingw32-g++ linker (/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld) supports shared libraries... yes
> checking dynamic linker characteristics... Win32 ld.exe
> checking how to hardcode library paths into programs... immediate
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether make sets $(MAKE)... yes
> checking for i686-w64-mingw32-windres... i686-w64-mingw32-windres
> checking for an ANSI C-conforming const... yes
> checking for inline... inline
> checking for working volatile... yes
> checking for GCC -MMD -MT option... yes
> checking for linker option --no-undefined... yes
> checking for ANSI C header files... (cached) yes
> checking for sys/types.h... (cached) yes
> checking stdio.h usability... yes
> checking stdio.h presence... yes
> checking for stdio.h... yes
> checking for stdlib.h... (cached) yes
> checking stddef.h usability... yes
> checking stddef.h presence... yes
> checking for stddef.h... yes
> checking stdarg.h usability... yes
> checking stdarg.h presence... yes
> checking for stdarg.h... yes
> checking malloc.h usability... yes
> checking malloc.h presence... yes
> checking for malloc.h... yes
> checking for memory.h... (cached) yes
> checking for string.h... (cached) yes
> checking for strings.h... (cached) yes
> checking for inttypes.h... (cached) yes
> checking for stdint.h... (cached) yes
> checking ctype.h usability... yes
> checking ctype.h presence... yes
> checking for ctype.h... yes
> checking math.h usability... yes
> checking math.h presence... yes
> checking for math.h... yes
> checking iconv.h usability... yes
> checking iconv.h presence... yes
> checking for iconv.h... yes
> checking signal.h usability... yes
> checking signal.h presence... yes
> checking for signal.h... yes
> checking for size_t... yes
> checking for M_PI in math.h... yes
> checking for working memcmp... no
> checking for working strtod... no
> checking for pow... yes
> checking for mprotect... yes
> checking for malloc... yes
> checking for calloc... yes
> checking for realloc... yes
> checking for free... yes
> checking for getenv... yes
> checking for setenv... no
> checking for putenv... yes
> checking for unsetenv... no
> checking for qsort... yes
> checking for abs... yes
> checking for bcopy... no
> checking for memset... yes
> checking for memcpy... yes
> checking for memmove... yes
> checking for strlen... yes
> checking for strlcpy... no
> checking for strlcat... no
> checking for strdup... yes
> checking for _strrev... yes
> checking for _strupr... yes
> checking for _strlwr... yes
> checking for strchr... yes
> checking for strrchr... yes
> checking for strstr... yes
> checking for itoa... yes
> checking for _ltoa... yes
> checking for _uitoa... no
> checking for _ultoa... yes
> checking for strtol... yes
> checking for strtoul... yes
> checking for _i64toa... yes
> checking for _ui64toa... yes
> checking for strtoll... yes
> checking for strtoull... yes
> checking for atoi... yes
> checking for atof... yes
> checking for strcmp... yes
> checking for strncmp... yes
> checking for _stricmp... yes
> checking for strcasecmp... yes
> checking for _strnicmp... yes
> checking for strncasecmp... yes
> checking for vsscanf... yes
> checking for vsnprintf... yes
> checking for fseeko... yes
> checking for fseeko64... yes
> checking for sigaction... no
> checking for setjmp... no
> checking for nanosleep... no
> checking for sysconf... no
> checking for sysctlbyname... no
> checking for pow in -lm... yes
> checking for atan... yes
> checking for atan2... yes
> checking for acos... yes
> checking for asin... yes
> checking for ceil... yes
> checking for copysign... yes
> checking for cos... yes
> checking for cosf... yes
> checking for fabs... yes
> checking for floor... yes
> checking for log... yes
> checking for pow... (cached) yes
> checking for scalbn... yes
> checking for sin... yes
> checking for sinf... yes
> checking for sqrt... yes
> checking for sqrtf... yes
> checking for tan... yes
> checking for tanf... yes
> checking for iconv_open in -liconv... no
> checking for iconv... no
> checking for struct sigaction.sa_sigaction... no
> checking for GCC builtin atomic operations... yes
> checking for GCC -mmmx option... yes
> checking for GCC -m3dnow option... yes
> checking for GCC -msse option... yes
> checking for Altivec with GCC altivec.h and -maltivec option... no
> checking for Altivec with GCC -maltivec option... no
> checking for Altivec with GCC altivec.h and -faltivec option... no
> checking for Altivec with GCC -faltivec option... no
> checking for GCC -Wall option... yes
> checking for necessary GCC -Wno-multichar option... no
> checking Windows compiler... yes
> checking Windows CE... no
> checking for GCC -mpreferred-stack-boundary option... yes
> checking for EGL support... no
> checking for OpenGL ES v2 headers... no
> checking d3d9.h usability... yes
> checking d3d9.h presence... yes
> checking for d3d9.h... yes
> checking d3d11_1.h usability... yes
> checking d3d11_1.h presence... yes
> checking for d3d11_1.h... yes
> checking ddraw.h usability... yes
> checking ddraw.h presence... yes
> checking for ddraw.h... yes
> checking dsound.h usability... yes
> checking dsound.h presence... yes
> checking for dsound.h... yes
> checking dinput.h usability... yes
> checking dinput.h presence... yes
> checking for dinput.h... yes
> checking dxgi.h usability... yes
> checking dxgi.h presence... yes
> checking for dxgi.h... yes
> checking xaudio2.h usability... no
> checking xaudio2.h presence... no
> checking for xaudio2.h... no
> checking xinput.h usability... yes
> checking xinput.h presence... yes
> checking for xinput.h... yes
> checking for main in -lmingw32... yes
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating sdl2-config
> config.status: creating sdl2-config.cmake
> config.status: creating SDL2.spec
> config.status: creating sdl2.pc
> config.status: creating include/SDL_config.h
> config.status: executing libtool commands
> config.status: executing sdl2_config commands
> config.status: executing summary commands
> SDL2 Configure Summary:
> Building Static Libraries
> Enabled modules : atomic audio video render events joystick haptic power filesystem threads timers file loadso cpuinfo assembly
> Assembly Math   : mmx 3dnow sse
> Audio drivers   : disk dummy directx
> Video drivers   : dummy opengl directx
> Input drivers   :
> Using libudev   : NO
> Using dbus      : NO
> Using ime       : NO
> Using ibus      : NO
> Using fcitx     : NO
> + touch -- already_configured_cc9e6bd17113455f19dbe877af8303f2-
> + echo 'doing preventative make clean'
> doing preventative make clean
> + nice make clean -j 2
> rm -rf build
> rm -rf gen
> if test -f test/Makefile; then (cd test; make clean); fi
> + do_make_and_make_install
> + local extra_make_options=
> + do_make ''
> + local 'extra_make_options= -j 2'
> ++ pwd
> + local cur_dir2=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/win32/SDL2-2.0.5
> ++ get_small_touchfile_name already_ran_make ' -j 2'
> ++ local beginning=already_ran_make
> ++ local 'extra_stuff= -j 2'
> +++ echo -- -j 2 -DDECLSPEC=
> +++ /usr/bin/env md5sum
> ++ local 'touch_name=already_ran_make_ac0d0964c655d66db873c74be0db491c  -'
> +++ echo 'already_ran_make_ac0d0964c655d66db873c74be0db491c  -'
> +++ sed 's/ //g'
> ++ touch_name=already_ran_make_ac0d0964c655d66db873c74be0db491c-
> ++ echo already_ran_make_ac0d0964c655d66db873c74be0db491c-
> + local touch_name=already_ran_make_ac0d0964c655d66db873c74be0db491c-
> + '[' '!' -f already_ran_make_ac0d0964c655d66db873c74be0db491c- ']'
> + echo
> 
> + echo 'making /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/win32/SDL2-2.0.5 as $ PATH=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/bin:$PATH make  -j 2'
> making /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/win32/SDL2-2.0.5 as $ PATH=/home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/bin:$PATH make  -j 2
> + echo
> 
> + '[' '!' -f configure ']'
> + nice make -j 2
> /bin/bash build-scripts/mkinstalldirs build
> /bin/bash build-scripts/updaterev.sh
> mkdir -p -- build
>   CC     build/SDL_assert.lo
>   CC     build/SDL_error.lo
>   CC     build/SDL_hints.lo
>   CC     build/SDL_log.lo
> src/SDL_log.c:309:12: warning: 'consoleAttached' defined but not used [-Wunused-variable]
>  static int consoleAttached = 0;
>             ^
> src/SDL_log.c:312:15: warning: 'stderrHandle' defined but not used [-Wunused-variable]
>  static HANDLE stderrHandle = NULL;
>                ^
>   CC     build/SDL_atomic.lo
>   CC     build/SDL_spinlock.lo
>   CC     build/SDL_audio.lo
>   CC     build/SDL_audiocvt.lo
>   CC     build/SDL_audiodev.lo
>   CC     build/SDL_audiotypecvt.lo
>   CC     build/SDL_mixer.lo
>   CC     build/SDL_wave.lo
>   CC     build/SDL_cpuinfo.lo
>   CC     build/SDL_dynapi.lo
>   CC     build/SDL_clipboardevents.lo
>   CC     build/SDL_dropevents.lo
>   CC     build/SDL_events.lo
>   CC     build/SDL_gesture.lo
>   CC     build/SDL_keyboard.lo
>   CC     build/SDL_mouse.lo
>   CC     build/SDL_quit.lo
>   CC     build/SDL_touch.lo
>   CC     build/SDL_windowevents.lo
>   CC     build/SDL_rwops.lo
>   CC     build/SDL_haptic.lo
>   CC     build/SDL_gamecontroller.lo
>   CC     build/SDL_joystick.lo
>   CC     build/e_atan2.lo
>   CC     build/e_log.lo
>   CC     build/e_pow.lo
>   CC     build/e_rem_pio2.lo
>   CC     build/e_sqrt.lo
>   CC     build/k_cos.lo
>   CC     build/k_rem_pio2.lo
>   CC     build/k_sin.lo
>   CC     build/k_tan.lo
>   CC     build/s_atan.lo
>   CC     build/s_copysign.lo
>   CC     build/s_cos.lo
>   CC     build/s_fabs.lo
>   CC     build/s_floor.lo
>   CC     build/s_scalbn.lo
>   CC     build/s_sin.lo
>   CC     build/s_tan.lo
>   CC     build/SDL_power.lo
>   CC     build/SDL_d3dmath.lo
>   CC     build/SDL_render.lo
>   CC     build/SDL_yuv_mmx.lo
>   CC     build/SDL_yuv_sw.lo
>   CC     build/SDL_render_d3d.lo
>   CC     build/SDL_render_d3d11.lo
>   CC     build/SDL_render_gl.lo
> src/render/direct3d11/SDL_render_d3d11.c:152:9: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
>  #pragma GCC diagnostic ignored "-Wunused-const-variable"
>          ^
>   CC     build/SDL_shaders_gl.lo
>   CC     build/SDL_render_gles.lo
>   CC     build/SDL_render_gles2.lo
>   CC     build/SDL_shaders_gles2.lo
>   CC     build/SDL_render_psp.lo
>   CC     build/SDL_blendfillrect.lo
>   CC     build/SDL_blendline.lo
>   CC     build/SDL_blendpoint.lo
>   CC     build/SDL_drawline.lo
>   CC     build/SDL_drawpoint.lo
>   CC     build/SDL_render_sw.lo
>   CC     build/SDL_rotate.lo
>   CC     build/SDL_getenv.lo
>   CC     build/SDL_iconv.lo
>   CC     build/SDL_malloc.lo
>   CC     build/SDL_qsort.lo
>   CC     build/SDL_stdlib.lo
>   CC     build/SDL_string.lo
>   CC     build/SDL_thread.lo
>   CC     build/SDL_timer.lo
>   CC     build/SDL_RLEaccel.lo
>   CC     build/SDL_blit.lo
>   CC     build/SDL_blit_0.lo
>   CC     build/SDL_blit_1.lo
>   CC     build/SDL_blit_A.lo
>   CC     build/SDL_blit_N.lo
>   CC     build/SDL_blit_auto.lo
>   CC     build/SDL_blit_copy.lo
>   CC     build/SDL_blit_slow.lo
>   CC     build/SDL_bmp.lo
>   CC     build/SDL_clipboard.lo
>   CC     build/SDL_egl.lo
>   CC     build/SDL_fillrect.lo
>   CC     build/SDL_pixels.lo
>   CC     build/SDL_rect.lo
>   CC     build/SDL_shape.lo
>   CC     build/SDL_stretch.lo
>   CC     build/SDL_surface.lo
>   CC     build/SDL_video.lo
>   CC     build/SDL_nullevents.lo
>   CC     build/SDL_nullframebuffer.lo
>   CC     build/SDL_nullvideo.lo
>   CC     build/SDL_diskaudio.lo
>   CC     build/SDL_dummyaudio.lo
>   CC     build/SDL_windows.lo
>   CC     build/SDL_xinput.lo
> In file included from src/core/windows/SDL_xinput.c:24:0:
> src/core/windows/SDL_xinput.h:113:3: error: conflicting types for 'XINPUT_GAMEPAD_EX'
>  } XINPUT_GAMEPAD_EX;
>    ^
> In file included from src/core/windows/SDL_xinput.h:29:0,
>                  from src/core/windows/SDL_xinput.c:24:
> /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/include/xinput.h:182:3: note: previous declaration of 'XINPUT_GAMEPAD_EX' was here
>  } XINPUT_GAMEPAD_EX, *PXINPUT_GAMEPAD_EX;
>    ^
> In file included from src/core/windows/SDL_xinput.c:24:0:
> src/core/windows/SDL_xinput.h:119:3: error: conflicting types for 'XINPUT_STATE_EX'
>  } XINPUT_STATE_EX;
>    ^
> In file included from src/core/windows/SDL_xinput.h:29:0,
>                  from src/core/windows/SDL_xinput.c:24:
> /home/u/Desktop/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/mingw-w64-i686/include/xinput.h:192:3: note: previous declaration of 'XINPUT_STATE_EX' was here
>  } XINPUT_STATE_EX, *PXINPUT_STATE_EX;
>    ^
> Makefile:547: recipe for target 'build/SDL_xinput.lo' failed
> make: *** [build/SDL_xinput.lo] Error 1
> make: *** Waiting for unfinished jobs....
> + exit 1
>

**Comment by hydra3333** [comment]
but ... looking at the website ...
 http://libsdl.org/release/SDL2-2.0.5.tar.gz was last changed on 2016-10-20 04:18

Now very confused ... :( :(

**Comment by hydra3333** [comment]
Hmm.
Recovered an ubuntu VM which use to work, nuked only the win32 and x86_64 subfolders in the sandbox, and that appears to work.

**Comment by rdp** [comment]
I think it was a change "upstream" in mingw-w64.
Maybe I can use a fixed version of theirs...hmm...

**Comment by hydra3333** [comment]
Thank you.
In the meantime I needed (well, desired) an interim build, so using the VM with the old working mingw, i needed to build gendef for OpenCL, but couldn't.  Hence a total dirty hack to do that:
[make_gendef.sh.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/785472/make_gendef.sh.txt)

Would it be possible to make gendef by default in your script ?
Only a couple of lines to change : 
```
      #nice ./$zeranoe_script_name $zeranoe_script_options --build-type=win32 || exit 1
      nice ./$zeranoe_script_name $zeranoe_script_options --build-type=win32 --enable-gendef || exit 1
	  # ---------- 2017.01.15 for opencl build testing - end

      #nice ./$zeranoe_script_name $zeranoe_script_options --build-type=win64 || exit 1 
      nice ./$zeranoe_script_name $zeranoe_script_options --build-type=win64 --enable-gendef || exit 1 

```

**Comment by Mr-Jake** [comment]
I did not save my log, but I believe I got the same similar error using the current helper script. The compile would error at SDL2-2.0.5 and the last lines either contained "GAMEPAD" or "JOYSTICK".

I had a December 2016 version of the helper script on my computer and it compiles without error.

My machine is Windows 7 running cygwin and I was compiling the Windows XP compatible 32 bit build.

**Comment by rdp** [comment]
clear sandbox and try again?

**Comment by abrotzge** [comment]
I do have the same problem, clear sandbox doesn't help. Any other ideas?

**Comment by rdp** [comment]
did you git pull the latest, I presume yes?

On Wed, Feb 22, 2017 at 9:40 AM, Alexander Brotzge <notifications@github.com

**Comment by abrotzge** [comment]
Yes I pulled the latest. I'm using a VM with Ubuntu 14.04. The last time I tried to compile ffmpeg within this setup, about a month ago, everything worked as expected.

**Comment by vredez** [comment]
Same issue here, but since I don't need ffplay, disabling the SDL2 build (commenting out the according lines) works around it for now.

**Comment by abrotzge** [comment]
thanks, workaround is fine for now!

**Comment by Mr-Jake** [comment]
Could the commit made on February 1 be causing the problem?

Feb 1 [commit e78f60f4def169b1ccbb5cfed827855a307132c1] hopefully fix sdl2 for latest mingw... 
[https://github.com/rdp/ffmpeg-windows-build-helpers/commit/e78f60f4def169b1ccbb5cfed827855a307132c1](url)

Older versions of the script compile without any issues.

**Comment by rdp** [comment]
you can test by removing +     apply_patch https://raw.githubusercontent.com/rdp/ffmpeg-windows-build-helpers/master/patches/sdl2.xinput.diff
 line

**Comment by Mr-Jake** [comment]
Sorry, I have not been able to test it yet.

**Comment by hydra3333** [comment]
Changed my variation of your fabulous script to it to compile with 4.9.4 per your latest change and it now works without error.
[img]http://i1303.photobucket.com/albums/ag149/british-retro/new-years_zpsnfgwybs0.gif~original[/img]

Suggest close this issue.

**Comment by rdp** [comment]
well...good to hear wish I understood it fully :|
