### ISSUE TITLE
build error SDL_xinput

### ISSUE THREAD

**Issue by falkben** [rdp/ffmpeg-windows-build-helpers#207]
Attached build output.  On a fresh sandbox folder.  This is an issue that is repeatable.  

[output.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/807413/output.txt)

**Comment by rzcat** [comment]
Try commenting out line 1146 of the script, which is dont patch sdl2.xinput.diff. This may get you bypass the error.
I believe this error happens after I did a **dnf update**, before the update, my Fedora wouldnt run into this error

**Comment by falkben** [comment]
I tried commenting out that line and it still returns that error.

Here's the final bit of the standard output when it reaches the error:

  CC     build/SDL_windowsclipboard.lo
In file included from src/core/windows/SDL_xinput.c:24:0:
src/core/windows/SDL_xinput.h:113:3: error: conflicting types for 'XINPUT_GAMEPA                                                                                                                                           D_EX'
 } XINPUT_GAMEPAD_EX;
   ^
In file included from src/core/windows/SDL_xinput.h:29:0,
                 from src/core/windows/SDL_xinput.c:24:
/home/ben/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/                                                                                                                                           include/xinput.h:182:3: note: previous declaration of 'XINPUT_GAMEPAD_EX' was he                                                                                                                                           re
 } XINPUT_GAMEPAD_EX, *PXINPUT_GAMEPAD_EX;
   ^
In file included from src/core/windows/SDL_xinput.c:24:0:
src/core/windows/SDL_xinput.h:119:3: error: conflicting types for 'XINPUT_STATE_                                                                                                                                           EX'
 } XINPUT_STATE_EX;
   ^
In file included from src/core/windows/SDL_xinput.h:29:0,
                 from src/core/windows/SDL_xinput.c:24:
/home/ben/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/                                                                                                                                           include/xinput.h:192:3: note: previous declaration of 'XINPUT_STATE_EX' was here
 } XINPUT_STATE_EX, *PXINPUT_STATE_EX;
   ^
Makefile:547: recipe for target 'build/SDL_xinput.lo' failed
make: *** [build/SDL_xinput.lo] Error 1
make: *** Waiting for unfinished jobs....

**Comment by rdp** [comment]
hopefully worked around now.

**Comment by rdp** [comment]
I haven't run into this for awhile, care to blow away the sandbox and try
again?

**Comment by falkben** [comment]
I'm not currently building FFMPEG and have no ability to test at the moment.  Thank you for checking up on this though.
