### ISSUE TITLE
libtool installed but reports as missing in quick build

### ISSUE THREAD

**Issue by falkben** [rdp/ffmpeg-windows-build-helpers#208]
When I attempt to do the quick build, it fails saying that libtool is missing, but Debian reports that libtool is already installed.  However, when I try to run libtool, it says command not found.

`native_build/quick_cross_compile_ffmpeg_fdk_aac_and_x264_using_packaged_mingw64.sh`

[output_quickbiuld.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/807427/output_quickbiuld.txt)

**Comment by rdp** [comment]
running libtool works on the command line?

**Comment by falkben** [comment]
libtool binary is missing (does not run from command line), but apt reports that the package is installed.  It seems that on Debian (using 8.7) I need to install libtool-bin in order to run the libtool command.

**Comment by rdp** [comment]
thanks!
