### ISSUE TITLE
ffmpeg build script not able to build libzvbi

### ISSUE THREAD

**Issue by rboy1** [rdp/ffmpeg-windows-build-helpers#21]
When I try to build the zvbi library using the function:

build_zvbi() {
  generic_download_and_install http://sourceforge.net/projects/zapping/files/zvbi/0.2.35/zvbi-0.2.35.tar.bz2/download zvbi-0.2.35 
}

I get an error while compiling:
conv.c:29:22 Fatal error: langinfo.h, no such file or directory

I searched for langinfo.h for mingw-w64 but couldn't find the file.

Any idea how to fix this issue?

Thanks,

**Comment by voltagex** [comment]
What is the status of this? Is upstream fixed or is the patch still needed?

**Comment by rdp** [comment]
looks like they did have a newer release out (0.2.35 or something) but it seemed to still need the patches.  Feel free to complain to them though...

**Comment by voltagex** [comment]
Looks like the project died around 2013.
