### ISSUE TITLE
Libnettle 3.1 was not found.

### ISSUE THREAD

**Issue by karthiDe** [rdp/ffmpeg-windows-build-helpers#212]
| #define HAVE_FSEEKO 1
| #define _DARWIN_USE_64_BIT_INODE 1
| #define STDC_HEADERS 1
| #define HAVE_CPUID_H 1
| #define ENABLE_PADLOCK 1
| /* end confdefs.h.  */
|
|          #include <unistd.h>
| int
| main ()
| {
|
|                  getentropy(0, 0);
|
|   ;
|   return 0;
| }
configure:9060: result: no
configure:9115: checking for NETTLE
configure:9123: $PKG_CONFIG --exists --print-errors "nettle >= 3.1"
Requested 'nettle >= 3.1' but version of Nettle is 2.4
You may find new versions of Nettle at http://www.lysator.liu.se/~nisse/nettle
configure:9126: $? = 1
configure:9141: $PKG_CONFIG --exists --print-errors "nettle >= 3.1"
Requested 'nettle >= 3.1' but version of Nettle is 2.4
You may find new versions of Nettle at http://www.lysator.liu.se/~nisse/nettle
configure:9144: $? = 1
Requested 'nettle >= 3.1' but version of Nettle is 2.4
You may find new versions of Nettle at http://www.lysator.liu.se/~nisse/nettle
configure:9172: result: no
configure:9175: error:
  ***
  *** Libnettle 3.1 was not found.

**Comment by karthiDe** [comment]
Please resolve

**Comment by rdp** [comment]
#117 help?

**Comment by rdp** [comment]
closing no response...

**Comment by rzcat** [comment]
`sudo dnf install pkg-config`
may the problem
