### ISSUE TITLE
libpng-1.5.26.tar.xz url not correct

### ISSUE THREAD

**Issue by mikemyers9** [rdp/ffmpeg-windows-build-helpers#215]
https://download.sourceforge.net/libpng/libpng-1.5.26.tar.xz url is not valid anymore
correct one is https://sourceforge.net/projects/libpng/files/libpng15/older-releases/1.5.26/libpng-1.5.26.tar.xz/download
or rather 
https://sourceforge.net/projects/libpng/files/libpng15/1.5.28/libpng-1.5.28.tar.xz/download

**Comment by rdp** [comment]
It actually works OK here.  Sourceforge however is a bit
flakey...hmm...maybe someday I'll shift it all somewhere else...

**Comment by DeadSix27** [comment]
@rdp I've shifted a few (especially xiphs) to github. I can take a look at some others and libpng maybe they have a official repo on github now-adays as well (a lot of libraries used to be on sourceforge but now have official github repos)

**Comment by mikemyers9** [comment]
thanks
