### ISSUE TITLE
x265 shared syntax

### ISSUE THREAD

**Issue by mikemyers9** [rdp/ffmpeg-windows-build-helpers#216]
x265 has
"-DENABLE_SHARED=OFF"
instead of the correct -DENABLE_SHARED=bool:OFF
so it fails to link

**Comment by mikemyers9** [comment]
in case global shared is disabled

**Comment by rdp** [comment]
Mine is working here, what is the failure?

**Comment by mikemyers9** [comment]
The linux build guide has -DENABLE_SHARED=bool:OFF, but that doesn't seem to work with mingw, but "-DENABLE_SHARED=OFF" does, so it's indeed the correct one for mingw.
