### ISSUE TITLE
gmplib.org down

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#223]
Hello.  Unable to build cross-compilers, gmplilb.org seems to be down.

Are there reliable mirrors ?

**Comment by DeadSix27** [comment]
ftp://ftp.gnu.org/gnu/gmp/
ftp://ftp.gnu.org/old-gnu/Manuals/gmp/html_mono/gmp.html
https://www.google.com/search?q=gnu+mp+lib+mirror

**Comment by hydra3333** [comment]
Beaut, thanks.  
Did search with not much in the way of understandable results.
This did the trick https://ftp.gnu.org/gnu/gmp/ and https://ftp.gnu.org/gnu/ for some things too.
