### ISSUE TITLE
--enable-libbs2b needs to be added to the ffmpeg build options ? 

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#225]
https://github.com/FFmpeg/FFmpeg/commit/f810c469223b92da97505f8b1475b04388cf9308
> Bauer stereo to binaural transformation, which improves headphone listening of   stereo audio records.
>   +To enable compilation of this filter you need to configure FFmpeg with
>  +@code{--enable-libbs2b}.

Looks as if --enable-libbs2b needs to be added to the ffmpeg build options ?

**Comment by rdp** [comment]
oops that is embarrassing, see e7ccea1 thanks!
