### ISSUE TITLE
Importerror: no module named site

### ISSUE THREAD

**Issue by Atemu** [rdp/ffmpeg-windows-build-helpers#230]
After cloning x265 the `cross_compile_ffmpeg.sh` script says "Importerror: no module named site" and exits.

After a bit of research I found out that the python path and/or the python home variables seem to be set wrong.

Exporting `PYTHONPATH=/usr/lib/python2.7` and `PYTHONHOME=/usr/` fixed the issue for me and the script continued.

**Comment by rdp** [comment]
Thanks for the fix.
