### ISSUE TITLE
libfdk_aac HE-AACv2 corrupted output

### ISSUE THREAD

**Issue by BiatuAutMiahn** [rdp/ffmpeg-windows-build-helpers#233]
Host: Ubuntu 16.10 x64

After compiling, I notice that when encoding with HE-AACv2 profile, with or without any additional params the output is completely trashed.

I will test with previous versions

**Comment by BiatuAutMiahn** [comment]
Seems to be the libfdk_aac git. Commenting out the git, and uncommenting the archive v0.1.0

**Comment by rdp** [comment]
Yeah sorry if it's not a compile failure I'm not much help (though I have heard that the native aac encoder is pretty good these days FWIW...)
