### ISSUE TITLE
ERROR: libmysofa not found

### ISSUE THREAD

**Issue by feedzapper** [rdp/ffmpeg-windows-build-helpers#235]
Okok, daily (hourly) changes in "libmysofa / git" thats not so pretty. compiling with GCC 4.9.4 - sometimes with "fatal erros" and sometimes compiling goes right, but now i got "ERROR: libmysofa not found"
libmysofa.a still exists in the sandbox/crossxxxx directory

**Comment by rdp** [comment]
Yeah I got libmysofa not found this morning when doing a shared build (32
or 64 bit)...odd...

**Comment by Reino17** [comment]
Latest commit should fix that. See https://github.com/hoene/libmysofa/issues/31.

**Comment by feedzapper** [comment]
thats it ! 👍

**Comment by miguelapg** [comment]
This error is happening again.

Please, can you fix it?

Thank you very much

Mapg

**Comment by rdp** [comment]
may have actually been caused by not cmake configuring mysofa as "static" ... odd...
