### ISSUE TITLE
wrong point to the patch directory ..

### ISSUE THREAD

**Issue by feedzapper** [rdp/ffmpeg-windows-build-helpers#236]
with the new scripts i got the error :

Building win64 x86_64 cross compiler...
curl: (37) Couldn't open file /patches/mingw-w64-build-r22.local

because wrong initial path to the patch directory in the cross_compile_ffmpeg.sh script
i changed :
patch_dir="$(pwd)/../../../patches"
to :
patch_dir="$(pwd)/patches"

:-)

**Comment by Reino17** [comment]
'_cross_compile_ffmpeg.sh_' resides in '_ffmpeg-windows-build-helpers-master\native_build\windows\ffmpeg_local_builds_'.
The patch-dir is '_ffmpeg-windows-build-helpers-master\patches_' (3 levels up), so `patch_dir="$(pwd)/../../../patches"` should work. Unless you moved the patch-dir yourself to '_ffmpeg-windows-build-helpers-master\native_build\windows\ffmpeg_local_builds\patches_' that is.

@rdp I see now you (blindly?) merged all my commits. You're of course free to do so, but I just wanna say; I never push changes before I have tested it locally. But above all, my fork works on my (old) system to compile WinXP- and old system compatible FFmpeg builds. I absolutely haven't tested it on a modern system! Compiling 64bit builds I haven't tested either.

**Comment by feedzapper** [comment]
i forgot to mentioned, that i do the build with ubuntu 14.04 - not using windows with cygwin ..
download with git clone ...
well - now ist works for me
in the meanwhile some erros occurred  while compiling with the changed scripts (static / 64bit build)
needs to install "GPERF" and updated to newer "CMAKE" suc cesfully.
now i got errors compiling "libsamplerate" :

``configuring libsamplerate_git (/home/freetz/ffmpeg-windows-build-helpers/sandbox/win64/libsamplerate_git) as $ PKG_CONFIG_PATH=/home/freetz/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/home/freetz/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --host=x86_64-w64-mingw32 --prefix=/home/freetz/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --disable-shared --enable-static
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
configure.ac:54: error: macro PKG_INSTALLDIR is not defined; is a m4 file missing?
m4/ax_require_defined.m4:35: AX_REQUIRE_DEFINED is expanded from...
configure.ac:54: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
./cross_compile_ffmpeg.sh: Zeile 320: ./configure: Datei oder Verzeichnis nicht gefunden
``
