### ISSUE TITLE
make in build_fribidi() failed

### ISSUE THREAD

**Issue by walkere** [rdp/ffmpeg-windows-build-helpers#237]
sorry don't have enough experience to know why.
-debug enabled output-:

make[1]: Leaving directory '/home/walke/ffmpeg-windows-build-helpers/sandbox/win64/fribidi_git'

making /home/walke/ffmpeg-windows-build-helpers/sandbox/win64/fribidi_git as $ PATH=/home/walke/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH make  -j 8

(cd lib && make  fribidi-unicode-version.h)
make[1]: Entering directory '/home/walke/ffmpeg-windows-build-helpers/sandbox/win64/fribidi_git/lib'
make[2]: Entering directory '/home/walke/ffmpeg-windows-build-helpers/sandbox/win64/fribidi_git/gen.tab'
make  gen-unicode-version.exe
make[3]: Entering directory '/home/walke/ffmpeg-windows-build-helpers/sandbox/win64/fribidi_git/gen.tab'
cd .. && make  config.h
make[4]: Entering directory '/home/walke/ffmpeg-windows-build-helpers/sandbox/win64/fribidi_git'
make[4]: Leaving directory '/home/walke/ffmpeg-windows-build-helpers/sandbox/win64/fribidi_git'
  CC       gen-unicode-version.o
  CCLD     gen-unicode-version.exe
make[3]: Leaving directory '/home/walke/ffmpeg-windows-build-helpers/sandbox/win64/fribidi_git/gen.tab'
./gen-unicode-version.exe ./unidata/ReadMe.txt ./unidata/BidiMirroring.txt gen-unicode-version.c > fribidi-unicode-version.h \
|| (rm -f fribidi-unicode-version.h && false)
./gen-unicode-version.exe: Invalid argument
Makefile:721: recipe for target 'fribidi-unicode-version.h' failed
make[2]: *** [fribidi-unicode-version.h] Error 1
make[2]: Leaving directory '/home/walke/ffmpeg-windows-build-helpers/sandbox/win64/fribidi_git/gen.tab'
Makefile:804: recipe for target 'fribidi-unicode-version.h' failed
make[1]: *** [fribidi-unicode-version.h] Error 2
make[1]: Leaving directory '/home/walke/ffmpeg-windows-build-helpers/sandbox/win64/fribidi_git/lib'
Makefile:939: recipe for target 'lib/fribidi-unicode-version.h' failed
make: *** [lib/fribidi-unicode-version.h] Error 2

**Comment by rdp** [comment]
does it work for 32 bit?

**Comment by walkere** [comment]
Does it work for 32 bit? Sorry don't know because 32 fails at build_lame() before getting to build_fribidi()

Running WSL Ubuntu 16.04.2 LTS

using --high-bitdepth=y

Btw did change: 
patch_dir="$(pwd)/patches"

**Comment by MiKE41** [comment]
Doesn't work for me either. ./cross_compile_ffmpeg.sh --build-ffmpeg-static=y --disable-nonfree=n --sandbox-ok=y --compiler-flavors=win32

[build.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/1154547/build.txt)

**Comment by Lazinezz** [comment]
Same here, doesnt work too, i had to...

Replace this,
build_fribidi() {
  do_git_checkout https://github.com/behdad/fribidi.git
  cd fribidi_git

With this,
build_fribidi() {
  download_and_unpack_file http://fribidi.org/download/fribidi-0.19.7.tar.bz2
  cd fribidi-0.19.7

and only then it will work...dont know why tho...see attached text file.

[Build Fribidi.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/1155149/Build.Fribidi.txt)
