### ISSUE TITLE
curl: (37) Couldn't open file /patches/mingw-w64-build-r22.local

### ISSUE THREAD

**Issue by ogrgkyle** [rdp/ffmpeg-windows-build-helpers#238]
Using this command:
`./cross_compile_ffmpeg.sh --disable-nonfree=n --high-bitdepth=y`
I get this error message on both Lubuntu and Windows 10 bash:
`curl: (37) Couldn't open file /patches/mingw-w64-build-r22.local`

**Comment by Qowy** [comment]
+1

**Comment by rdp** [comment]
Should be fixed now, thanks!

**Comment by user7415** [comment]
It seems that i have the same problem.

I generally do:

mkdir -p ~/opt/ffmpeg-cross-compile
cd ~/opt/ffmpeg-cross-compile
wget https://raw.githubusercontent.com/rdp/ffmpeg-windows-build-helpers/master/cross_compile_ffmpeg.sh -O cross_compile_ffmpeg.sh -O cross_compile_ffmpeg.sh
chmod u+x cross_compile_ffmpeg.sh
apt-get install subversion curl texinfo g++ bison flex cvs yasm automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev mercurial unzip pax nasm gperf autogen libtool-bin ed -y

then
./cross_compile_ffmpeg.sh

on debian but I face the same problem :(
