### ISSUE TITLE
Failed to build zimg

### ISSUE THREAD

**Issue by epilsits** [rdp/ffmpeg-windows-build-helpers#241]
I'm building on a fresh and updated Ubuntu 16.04.2 LTS, repo was cloned clean today. The build fails with a bunch of these errors. Please let me know if you need any more info.

```
from src/zimg/resize/resize_impl_avx512.cpp:11:
src/zimg/resize/resize_impl_avx512.cpp:697:36: error: invalid conversion from 'int' to '_MM_PERM_ENUM' [-fpermissive]
   c = _mm512_shuffle_epi32(coeffs, _MM_SHUFFLE(3, 3, 3, 3));
```

**Comment by Warblefly** [comment]
On Sat, Jul 22, 2017 at 3:15 PM, Erik Pilsits <notifications@github.com>
wrote:

> I'm building on a fresh and updated Ubuntu 16.04.2 LTS, repo was cloned
> clean today. The build fails with a bunch of these errors. Please let me
> know if you need any more info.
>
> from src/zimg/resize/resize_impl_avx512.cpp:11:
> src/zimg/resize/resize_impl_avx512.cpp:697:36: error: invalid conversion from 'int' to '_MM_PERM_ENUM' [-fpermissive]
>    c = _mm512_shuffle_epi32(coeffs, _MM_SHUFFLE(3, 3, 3, 3));
>
>
> ​
I get this too, and have reported it as a comment in the Zimg GitHub
repository. Backing out the most recent changes works for me. I'm
using 7e8b0f52e69e9c6c6d61d590cc45ca5e5e6a7caa
​

**Comment by epilsits** [comment]
Thank you! Seems zimg fixed their code and it compiles cleanly now without any changes here.

**Comment by rdp** [comment]
Thanks!
