### ISSUE TITLE
line 314:  ./configure not found

### ISSUE THREAD

**Issue by aspecialkey** [rdp/ffmpeg-windows-build-helpers#243]
hello, i'm trying to compile from linux mint to windows x64.
after successfully compilation of some modules and a lot of time I get this error:

`sed: kann Makefile.am nicht lesen: Datei oder Verzeichnis nicht gefunden
configuring snappy_git (/home/mint/ffmpeg-windows-build-helpers/sandbox/win64/snappy_git) as $ 
PKG_CONFIG_PATH=/home/mint/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/home/mint/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --host=x86_64-w64-mingw32 --prefix=/home/mint/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --disable-shared --enable-static 
autoreconf: 'configure.ac' or 'configure.in' is required
./cross_compile_ffmpeg.sh: Zeile 314: ./configure: Datei oder Verzeichnis nicht gefunden
`

Could someone help me? Or has someone an idea how to fix my problem?

**Comment by DeadSix27** [comment]
Snappy switched to cmake recently.

@rdp you can use the patch I added in this commit: https://github.com/DeadSix27/python_cross_compile_script/commit/65dec4870fa7d508e9c4ec07c074b851f175e79b  I build based on this PR: https://github.com/google/snappy/pull/48

Until snappy adds proper switches to disable tests and shared builds and add a proper static build.

**Comment by DeadSix27** [comment]
@aspecialkey In the meanwhile, you can try this: 
```bash
build_libsnappy() {
  do_git_checkout https://github.com/google/snappy.git
  cd snappy_git
    apply_patch https://raw.githubusercontent.com/DeadSix27/python_cross_compile_script/master/patches/snappy/0001-snappy-remove-tests-and-shared.patch -p1
    do_cmake_and_install
  cd ..
}
```
Make sure to delete your snappy_git folder before.

**Comment by aspecialkey** [comment]
thanks @DeadSix27 it seem to solve the problem
but now I run into the next error:

`configuring libsamplerate_git (/home/mint/ffmpeg-windows-build-helpers/sandbox/win64/libsamplerate_git) as $ PKG_CONFIG_PATH=/home/mint/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/home/mint/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --host=x86_64-w64-mingw32 --prefix=/home/mint/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --disable-shared --enable-static 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
configure.ac:54: error: macro PKG_INSTALLDIR is not defined; is a m4 file missing?
m4/ax_require_defined.m4:35: AX_REQUIRE_DEFINED is expanded from...
configure.ac:54: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1`

any idea?

**Comment by aspecialkey** [comment]
Or which linux should I take to compile ffmpeg for windows with the script, it's no problem to create a vm?

**Comment by rdp** [comment]
awesome I'll use it :) open a new ticket for that libsamplerate failure, thanks!

**Comment by songbaoer** [comment]
i used the updated cross-compile-ffmpeg.sh ,but failed to downloading vamp-plugin-sdk-2.7.1.tar.gz, thanks for any suggestion!

**Comment by rdp** [comment]
Seems OK here, try again?

**Comment by songbaoer** [comment]
in fact, i updated the cross-compile-ffmpeg.sh after you fix snappy, but still didn't work and prompted failed to downloading vamp-plugin-sdk-2.7.1.tar.gz

**Comment by rdp** [comment]
What exact error message?
