### ISSUE TITLE
configuring libsamplerate_git

### ISSUE THREAD

**Issue by aspecialkey** [rdp/ffmpeg-windows-build-helpers#244]
I've used a fresh ubuntu 14.04.5  to compile to win64.
I installed cmake 3.2 because 3.0 or higher is required.

now I get this message:

`
configuring libsamplerate_git (/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/win64/libsamplerate_git) as $ PKG_CONFIG_PATH=/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --host=x86_64-w64-mingw32 --prefix=/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --disable-shared --enable-static 
autoreconf: Entering directory .'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
configure.ac:54: error: macro PKG_INSTALLDIR is not defined; is a m4 file missing?
m4/ax_require_defined.m4:35: AX_REQUIRE_DEFINED is expanded from...
configure.ac:54: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
./cross_compile_ffmpeg.sh: Zeile 314: ./configure: Datei oder Verzeichnis nicht gefunden
`

Has someone an idea to solve this issue?

**Comment by feedzapper** [comment]
updated :
automake to 1.15.1
autoconf to 2.69
libtool to 2.4.6

:-)

**Comment by DeadSix27** [comment]
I am curious, why a fresh 14.04.5 and not 17.04 or 16.04 lts?

Also, what is your automake version? Use this to find out:
```bash
$ automake --version
automake (GNU automake) 1.15
```

**Comment by aspecialkey** [comment]
hello guys,
I've try it with 14.04 because in the readme was mentioned that it will not work with 16.10
Now I've done it with 17.04 and everything works perfectly :)  (without any patch)

I'm happy… thanks for your hints!
