### ISSUE TITLE
Build error on libsamplerate

### ISSUE THREAD

**Issue by kgp700** [rdp/ffmpeg-windows-build-helpers#246]
Hi.
I get following error when build libsamplerate

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
configure.ac:54: error: macro PKG_INSTALLDIR is not defined; is a m4 file missing?
m4/ax_require_defined.m4:35: AX_REQUIRE_DEFINED is expanded from...
configure.ac:54: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
./cross_compile_ffmpeg.sh: line 314: ./configure: No such file or directory

I tried to find about this issue
I see this one - http://redmine.audacious-media-player.org/issues/248
This error caused by pkg-config version (PKG_INSTALLDIR not present in pkg-config < 0.27)
It required pkg-config 0.27 or higher
My pkg-config version is 0.26
I try to update pkg-config but I couldn't
My ubuntu version is 14.04 LTS

Problem is pkg-config 0.26-1ubuntu4 version is lastest version for 14.04 LTS
(https://launchpad.net/pkg-config/+packages)

I don't know how to resolve it... 
Update ubuntu version? or 
Can I force install pkg-config 0.27 or higher version on ubuntu 14.04 LTS?

**Comment by rdp** [comment]
OK see also https://github.com/rdp/ffmpeg-windows-build-helpers/issues/244 I have attempted to fix it by downgrading samplerate for now...
