### ISSUE TITLE
ffmpeg next version changes - nasm ?

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#247]
Just browsing ffmpeg changelog and saw these
```
- scale_cuda CUDA based video scale filter
- The x86 assembler default switched from yasm to nasm, pass
     --x86asmexe=yasm to configure to restore the old behavior.
```

We already know x264 has a dependency on nasm 2.13.1 or greater and that nasm has to be built manually in some cases (al la something like this)
```
#------------------------------------------------------------------------------------------------
# 2017.05.26 x264 has a new dependency on nasm 2.13.1 or greater ... 
# before we do anything, build NASM if need be
set -x
if [[ ! -d "nasm-2.13.01" ]]; then
   echo "Downloading nasm 2.13.01"
   url="http://www.nasm.us/pub/nasm/releasebuilds/2.13.01/nasm-2.13.01.tar.xz"
   rm -f "nasm-2.13.01.tar.xz"
   curl -4 -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Cache-Control: max-age=0' "$url" --retry 50 -L --output "nasm-2.13.01.tar.xz" --fail # -L means "allow redirection" or some odd :|
   tar -xf "nasm-2.13.01.tar.xz" || unzip "nasm-2.13.01.tar.xz"
   echo "Configuring nasm 2.13.01"
   cd nasm-2.13.01
      ./autogen.sh
      ./configure --prefix=/usr --exec_prefix=/usr --enable-sections --enable-lto 
      echo "Make nasm 2.13.01"
      make 
      echo "Installing nasm 2.13.01"
      sudo make install # sudo so it copies into /usr folder tree
   cd ..
   echo "Done Building and Installing nasm 2.13.01"
fi
set +x
#read -p "After nasm build, press Enter to continue"
#------------------------------------------------------------------------------------------------
```

Could/should the build script be modified to also build the newer nasm ?

Any ideas what has to be changed in the build script to build and/or enable "scale_cuda  CUDA based video scale filter" ?  Even a pointer where to look to attempt such a thing.  Googling nowadays for ffmpeg related things yields tonnes of chaff going back years.

> version <next>:
> - deflicker video filter
> - doubleweave video filter
> - lumakey video filter
> - pixscope video filter
> - oscilloscope video filter
> - config.log and other configuration files moved into ffbuild/ directory
> - update cuvid/nvenc headers to Video Codec SDK 8.0.14
> - afir audio filter
> - scale_cuda CUDA based video scale filter
> - librsvg support for svg rasterization
> - crossfeed audio filter
> - spec compliant VP9 muxing support in MP4
> - remove the libnut muxer/demuxer wrappers
> - remove the libschroedinger encoder/decoder wrappers
> - surround audio filter
> - sofalizer filter switched to libmysofa
> - Gremlin Digital Video demuxer and decoder
> - headphone audio filter
> - superequalizer audio filter
> - roberts video filter
> - The x86 assembler default switched from yasm to nasm, pass
>   --x86asmexe=yasm to configure to restore the old behavior.
> - additional frame format support for Interplay MVE movies
> - support for decoding through D3D11VA in ffmpeg
> - limiter video filter
> - libvmaf video filter
> - Dolby E decoder and SMPTE 337M demuxer

**Comment by rdp** [comment]
you could check the "configure" script and see if it's mentioned in there.  The part that required a newer nasm was actually disabled recently FWIW...though nasm itself has been required for like two years...hopefully ffmpeg doesn't need the newest version?...

**Comment by hydra3333** [comment]
ok thanks for the pointer, I'll look in the configure script.  
kinda obvious I should have done that, however it's worth asking in case smart people had invented that wheel already :)
