### ISSUE TITLE
how to cross compile ffmpeg with nvidia cuda_sdk and libnpp

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#249]
I know this is cross-site posting, but thought it's relevant here too plus someone may read this here if they don't visit zeranoe's site.

https://ffmpeg.zeranoe.com/forum/viewtopic.php?f=5&t=5109&p=12505#p12505

Newbie alert.  Googled an issue but couldn't find a solution. So, I am seeking advice from someone who may already have invented this particular wheel or be able to provide pointers on where to next.

**Goal:**
To cross compile ffmpeg with nvidia cuda_sdk and libnpp under mingw64 so the final .exe runs under windows 10 x64
eg using something like this on the ffmpeg configure commandline 
`--enable-cuda-sdk --enable-filter=scale_cuda --extra-cflags=-I/usr/cuda_8.0.61/cuda/include --extra-ldflags=-L/usr/cuda_8.0.61/cuda/lib/x64`

**Issue:**
Using a version of rdp's fantastic cross-compile script, which is based on Zeranoe's toolchain, with the above flags it eventually yields this error:
```
CC	libavfilter/vf_scale_cuda.o
NVCC	libavfilter/vf_scale_cuda.ptx
ERROR: No supported gcc/g++ host compiler found, but clang-3.8 is available.
       Use 'nvcc -ccbin clang-3.8' to use that instead.
ffbuild/common.mak:95: recipe for target 'libavfilter/vf_scale_cuda.ptx' failed
make: *** [libavfilter/vf_scale_cuda.ptx] Error 1
```
Any suggestions on where to from here to cross-compile it ?

**Roughie Process so far:**
1. Install this package under an ubuntu 17.04 VM, to get access to the nvcc compiler. It isn't the latest version, but should still work.
`sudo apt-get install -y nvidia-cuda-toolkit`
2. This isn't enough, we also *need* the *Windows* libs and includes, so download the relevant cuda toolkit exe under Windows 10
from the nvidia developer site, https://developer.nvidia.com/cuda-downloads 
cuda_8.0.61_win10.exe
3. Then run cuda_8.0.61_win10.exe in Windows 10. 
It'll extract the files to a temporary folder before it then tries to install the stuff.
After it's finished extracting and then whilst it's figuring out how to install, copy the full extracted folder tree to another place so we have our own copy if it.
After our own folder copies have finished, cancel the installation.
4. Locate folders cuda/include and cuda/lib/x64 in the newly copied folder tree and copy them to somewhere else alongside one another.
Then also locate folders /npp/include and /npp/lib/x64 and also copy them to somewhere else alongside one another.
5. Back under Linux Ubuntu, use sudo to create folder cuda_8.0.61 under /usr and then set permissions on it sort of like this
[code]sudo mkdir /usr/cuda_8.0.61
chmod +777 -R /usr/cuda_8.0.61[/code]
6. Copy those 4 folder trees we copied earlier, from Windows to the Ubuntu box to become like these
[code]/usr/cuda_8.0.61/cuda/include
/usr/cuda_8.0.61/cuda/lib/x64 
/usr/cuda_8.0.61/npp/include 
/usr/cuda_8.0.61/npp/lib/x64[/code]
7. Now we should be able to type nvcc  and see it try to compile something and fail which is OK
By now the necessary folders and whatnot exist (well, nearly) for ffmpeg to be built (cross-compiled) with cuda sdk.
8. Edit the ffmpeg cross-compile build script and add these flags to the ffmpeg configure, to cross-compile stuff with the cuda sdk
[code]--enable-cuda-sdk --enable-filter=scale_cuda --extra-cflags=-I/usr/cuda_8.0.61/cuda/include --extra-ldflags=-L/usr/cuda_8.0.61/cuda/lib/x64 [/code]
9. Then if you're game, also add these flags to the ffmpeg cross-compile configure line
[code]--enable-libnpp --extra-cflags=-I/usr/cuda_8.0.61/npp/include --extra-ldflags=-L/usr/cuda_8.0.61/npp/lib/x64[/code]
10. Try to cross-compile ffmpeg and see how the luck holds. [i](edit: it blows up, hence this post)[/i]

_edit: interesting info here.  i think i'm stuck_
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862522

**Comment by rdp** [comment]
doesn't look familiar...

**Comment by hydra3333** [comment]
OK.  That link https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862522
Seems to indicate cross-compiling cuda-sdk is nigh impossible for my purposes (building ffmpeg with a variation of your script under gcc 7.1.0).
Oh well, off to try building libnpp now ...

**Comment by schmidthubert** [comment]
No need to reinvent the wheel, see https://github.com/rdp/ffmpeg-windows-build-helpers/issues/199 and https://github.com/rdp/ffmpeg-windows-build-helpers/issues/183. Feel free to make a patch for @rdp though ... ;-)

**Comment by hydra3333** [comment]
yes, duplicates, sorry, this can be closed

**Comment by rboy1** [comment]
So does the latest RDP script support NPP? (looks like CUDA and CUVID are automagically enabled)

**Comment by schmidthubert** [comment]
For scale_npp and/or scale_cuda with --enable-cuda-sdk enabled try [jb's suite](https://github.com/jb-alvarado/media-autobuild_suite) :information_desk_person:

**Comment by hydra3333** [comment]
yes go to jb's is the best option for baking in NPP and CUDA library stuff to deliver CUDA featured filters eg VF_SCALE_CUDA etc.  
There's issues in "installing" the cuda sdk in linux for cross-compiling - and on top of that NVIDIA does not support the relevant gcc nor a matching nvcc (iirc).  see top post.
jb's is a windows build environment where that all can be done ... I used jb's successfully so it can't be that hard.

**Comment by ValZapod** [comment]
@hydra3333 We do not need CUDA SDK anymore. And it is even now not --enable-nonfree. Everything is now done with clang after commit that reimplemeted the SDK: https://github.com/FFmpeg/FFmpeg/commit/01994c93db43e50c01349203a76c0b7111d1d2f3
https://github.com/m-ab-s/media-autobuild_suite/issues/1320

Were there any tests and assembly comparisons?

**Comment by hydra3333** [comment]
Thanks !

Just to clarify, when a static ffmpeg is cross-compiled and then ffmpeg.exe is copied to and run on Win10x64, what dependencies need to be installed in Win10 (if any) for ffmpeg.exe to run correctly ?

To check - when cross-compiling ffmpeg on Ubuntu to run under Win10x64, is all that is necessary is to install clang and add "--enable-cuda-llvm" to the build options ? In which case I do not need to install the nvidia SDK nor use "--enable-cuda-nvcc" (and instead use "--enable-cuda-llvm") ?

**Comment by rdp** [comment]
I think it's some nvidia dll's :)
