### ISSUE TITLE
Serious encoding performance drop x265 build with DENABLE_ASSEMBLY=OFF

### ISSUE THREAD

**Issue by kgp700** [rdp/ffmpeg-windows-build-helpers#250]
It's too much encoding performance drop with DENABLE_ASSEMBLY=OFF
(Almost 20fps+ loss..)

I think we need find way for build without DENABLE_ASSEMBLY=OFF

Anybody no idea?

**Comment by rdp** [comment]
It's off "by default" for 64 bit builds.  It doesn't even build without it
for 32-bit (that I'm aware of anyway...)
You could ask the x265 people about it...I don't know too much here, sorry!

**Comment by konyzulphrea** [comment]
Haven't you tried to modify DENABLE_ASSEMBLY=OFF to DENABLE_ASSEMBLY=ON for Windows 64-bit build? 

I think we shall try later. I have modified a script for x265 8-bit+10-bit+12-bit in actual based on these talks.

**Comment by konyzulphrea** [comment]
I have put the being on my branch, you can try in 64-bit environment since the assembly may be for 64-bit environment only.

**Comment by rdp** [comment]
OK to close?

**Comment by kgp700** [comment]
sorry. I see late
OK to close
