### ISSUE TITLE
Building 'libcurl.dll' with statically built dependencies

### ISSUE THREAD

**Issue by Reino17** [rdp/ffmpeg-windows-build-helpers#251]
I've updated [build_libcurl()](https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/cross_compile_ffmpeg.sh#L1448-L1450) to the latest version and I've successfully built an all static '_curl.exe_' with the already installed GnuTLS in my script:
```bash
build_libcurl() {
  download_and_unpack_file https://curl.haxx.se/download/curl-7.54.1.tar.gz
  cd curl-7.54.1
    export PKG_CONFIG="pkg-config --static"
    generic_configure "--without-ssl --with-gnutls --without-ca-bundle --with-ca-fallback"
    do_make
    unset PKG_CONFIG
  cd ..
}
```
```
curl.exe -V
curl 7.54.1 (i686-w64-mingw32) libcurl/7.54.1 GnuTLS/3.5.14 zlib/1.2.11
Release-Date: 2017-06-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM SSL libz TLS-SRP HTTPS-proxy
```
So far so good. Now I wanted to build a shared '_libcurl.dll_' using the same statically built dependencies:
```bash
build_libcurl() {
  download_and_unpack_file https://curl.haxx.se/download/curl-7.54.1.tar.gz
  cd curl-7.54.1
    export PKG_CONFIG="pkg-config --static"
    do_configure "--host=$host_target --prefix=$mingw_w64_x86_64_prefix --disable-static --without-ssl --with-gnutls --without-ca-bundle --with-ca-fallback"
    do_make
    unset PKG_CONFIG
  cd ..
}
```
But this didn't work out as I expected:
```
[...]
  CC       vtls/libcurl_la-gskit.lo
  CC       vtls/libcurl_la-mbedtls.lo
  CCLD     libcurl.la

*** Warning: This system cannot link to static lib archive /cygdrive/m/ffm
peg-windows-build-helpers-master/native_build/windows/ffmpeg_local_builds/
sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/libgnutls.la.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have.

*** Warning: [...]/libgmp.la.
[...]

*** Warning: linker path does not have real file for library -lhogweed.
[...]

*** Warning: linker path does not have real file for library -lnettle.
[...]

*** Warning: linker path does not have real file for library -lz.
[...]
*** The inter-library dependencies that have been dropped here will be
*** automatically added whenever a program is linked with this library
*** or is declared to -dlopen it.

*** Since this library must not contain undefined symbols,
*** because either the platform does not support them or
*** it was explicitly requested with -no-undefined,
*** libtool will only create a static version of it.

[...]

  CC       ../lib/curl-nonblock.o
  CC       ../lib/curl-warnless.o
  CCLD     curl.exe
curl-slist_wc.o:slist_wc.c:(.text+0x20): undefined reference to `_imp__curl_slist_append'
curl-slist_wc.o:slist_wc.c:(.text+0x7d): undefined reference to `_imp__curl_slist_free_all'
curl-slist_wc.o:slist_wc.c:(.text+0xa3): undefined reference to `_imp__curl_slist_free_all'
curl-tool_cb_dbg.o:tool_cb_dbg.c:(.text+0x97): undefined reference to `_imp__curl_mfprintf'
curl-tool_cb_dbg.o:tool_cb_dbg.c:(.text+0x171): undefined reference to `_imp__curl_msnprintf'
[...]
```
I've tried numerous options, but all without success.
Does anyone know if it's possible at all to compile a shared '_libcurl.dll_' using statically built dependencies?

---
Next I've tried building the dependencies shared. This worked for gmp ('_libgmp-10.dll_'), nettle ('_libnettle-6.dll_' and '_libhogweed-4.dll_') and gnutls ('_libgnutls-30.dll_'), but no matter what, I couldn't get zlib to compile a shared library. So I had to add `--without-zlib` to GnuTLS- and libcurl's configure-line.
This proved successful, but not in the way I expected. The resulting '_libcurl.dll_' still relies on the previously mentioned dependency dlls. I was expecting a '_libcurl.dll_' that would have all dependencies integrated/imported.
I've looked through all the available libcurl configure-options, but does anyone know if it's possible at all with this setup to compile a '_libcurl.dll_' that has zlib and GnuTLS integrated?

**Comment by rdp** [comment]
Is the link path setup well? I assume it is hmmm

**Comment by Reino17** [comment]
I guess so.
Running `./configure ... --disable-static` is all going well, but it's `make` that somehow can't link to the static library. Maybe '_Makefile_' needs some editing.

I've also posted this issue on the [Curl mailing list](https://curl.haxx.se/mail/lib-2017-08/index.html#27), but so far without success.
I'm still too much of a newbie to find out how to fix this and why this is happening in the first place.

**Comment by rdp** [comment]
--enable-shared maybe?

**Comment by Reino17** [comment]
Never mind this.
I haven't figured out how to compile 1 large '_libcurl.dll_'. Hack, maybe it's even impossible with the tools we're using.
It's not important to me anymore.
