### ISSUE TITLE
Question libffmpeg

### ISSUE THREAD

**Issue by BiatuAutMiahn** [rdp/ffmpeg-windows-build-helpers#265]
can I use this build script to compile a dll of ffmpeg?

**Comment by rdp** [comment]
Yes there's a build shared parameter to the script

On Thursday, September 28, 2017, BiatuAutMiahn <notifications@github.com>
wrote:
> can I use this build script to compile a dll of ffmpeg?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/nhvounQ8XyMbjul87QZ6MizAvo9QBJNHn8TDjfyP_yB4yrHBDEnrebjBLU-kbmFnRfSTd0I5ddL3scVSDXqcRDKeg9nB1F8FeHXoqlIWBHcppYuwbaM5K0vPgs6SezDfBGm9Ls4KemuOa1SuHlysxEsI8Ckxhg=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0OMVVYgJB-qWdgTML4-81QrDh9SEks5snDKDgaJpZM4PoCXx.gif>

**Comment by BiatuAutMiahn** [comment]
ok, what about an all in one static ffmpeg lib?

**Comment by rdp** [comment]
I've never looked into libs though if you do a static build you should find
filled like libavcodec.a somewhere or other...

On Thursday, September 28, 2017, BiatuAutMiahn <notifications@github.com>
wrote:
> ok, what about an all in one static ffmpeg lib?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/hK4hwhdMYMqt2jjPDs01fnUdIiYX1A3dWbxVdem6sMRhuHJrsxecHoFXTZj7gVhdv8Tw4yBzASQUQYz-V9ZApLGBEzM5JX6Te4tEjklT-NBkfP24Ngj1nZ2DZiD-GNii7T06XzA45dQpK8shy584rEflZ5eLGQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0KdUYh9HR7yQQwhOaBKCIz9rZetcks5snFv8gaJpZM4PoCXx.gif>

**Comment by rdp** [comment]
please reopen if still needed, thank you
