### ISSUE TITLE
FFMpeg build breaking trying to compile Intel Quicksync MFX

### ISSUE THREAD

**Issue by rboy1** [rdp/ffmpeg-windows-build-helpers#269]
When trying to build it gives the following error:

> Updating to latest mfx_dispatch_git git version [origin/master]...
> Already up-to-date.
> got no code changes, not forcing reconfigure for that...
> 
> making /ffmpeg/sandbox/win32/mfx_dispatch_git as $ PATH=/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/bin:$PATH make  -j 4
> 
>  cd . && /bin/bash /ffmpeg/sandbox/win32/mfx_dispatch_git/missing automake-1.15 --foreign
> configure.ac:37: error: required file './compile' not found
> configure.ac:37:   'automake --add-missing' can install 'compile'
> Makefile:480: recipe for target 'Makefile.in' failed
> make: *** [Makefile.in] Error 1
> 

Any suggestions?

**Comment by rboy1** [comment]
So I found the patch, you need modify the function

```
build_intel_quicksync_mfx() { # i.e. qsv
  do_git_checkout https://github.com/lu-zero/mfx_dispatch.git # lu-zero??
  cd mfx_dispatch_git
    if [[ ! -f "configure" ]]; then
      autoreconf -fiv || exit 1
    fi
    generic_configure_make_install
  cd ..
}
```
to add the line `automake --add-missing || exit 1` like this

```
build_intel_quicksync_mfx() { # i.e. qsv
  do_git_checkout https://github.com/lu-zero/mfx_dispatch.git # lu-zero??
  cd mfx_dispatch_git
    if [[ ! -f "configure" ]]; then
      autoreconf -fiv || exit 1
      automake --add-missing || exit 1
    fi
    generic_configure_make_install
  cd ..
}
```

**Comment by rdp** [comment]
OK thanks for the tip f5b6d53
