### ISSUE TITLE
FFMpeg build failing for 16.04 libbs2b

### ISSUE THREAD

**Issue by rboy1** [rdp/ffmpeg-windows-build-helpers#270]
Looks like ffmpeg just won't build these days. Earlier there was an issue with libburay which had to be resolved manually by editing the lib file (guess that's a libbluray issue). After that MFX was broken which required an update to the ffmpeg build script issue #269 

After that it quit again and here the log from ffbuild/config.log:

> require_pkg_config libbs2b libbs2b bs2b.h bs2b_open
> use_pkg_config libbs2b libbs2b bs2b.h bs2b_open
> check_pkg_config libbs2b libbs2b bs2b.h bs2b_open
> pkg-config --exists --print-errors libbs2b
> check_func_headers bs2b.h bs2b_open -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/bs2b -L/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib -lbs2b -lm
> check_ld cc -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/bs2b -L/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib -lbs2b -lm
> check_cc -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/bs2b -L/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib
> BEGIN /tmp/ffconf.y6zrFJrT/test.c
>     1	#include <bs2b.h>
>     2	#include <stdint.h>
>     3	long check_bs2b_open(void) { return (long) bs2b_open; }
>     4	int main(void) { int ret = 0;
>     5	 ret |= ((intptr_t)check_bs2b_open) & 0xFFFF;
>     6	return ret; }
> END /tmp/ffconf.y6zrFJrT/test.c
> /ffmpeg/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-gcc -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U__STRICT_ANSI__ -D__USE_MINGW_ANSI_STDIO=1 -D__printf__=__gnu_printf__ -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -mtune=generic -O3 -DLIBTWOLAME_STATIC -DMODPLUG_STATIC -DCACA_STATIC -mtune=generic -O3 -std=c11 -fomit-frame-pointer -pthread -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -DLIBXML_STATIC -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/freetype2 -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libpng16 -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libxml2 -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/fribidi -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/freetype2 -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libpng16 -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -DLIBXML_STATIC -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libxml2 -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/freetype2 -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libpng16 -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/bs2b -L/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib -c -o /tmp/ffconf.y6zrFJrT/test.o /tmp/ffconf.y6zrFJrT/test.c
> /ffmpeg/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-gcc -Wl,--large-address-aware -Wl,--nxcompat,--dynamicbase -Wl,--as-needed -Wl,--pic-executable,-e,_mainCRTStartup -I/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/bs2b -L/ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib -o /tmp/ffconf.y6zrFJrT/test.exe /tmp/ffconf.y6zrFJrT/test.o -lbs2b -lm
> /ffmpeg/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/libbs2b.a(bs2b.o):bs2b.c:(.text+0xd): undefined reference to `rpl_malloc'
> collect2: error: ld returned 1 exit status
> ERROR: libbs2b not found using pkg-config

Has anyone been able to this to build recently ? Any suggestions on how to fix this issue? Is this a script issue or ffmpeg itself is broken?

**Comment by rboy1** [comment]
Here is a temporary work around:

AC_FUNC_MALLOC is not a cross compiler friendly option. After removing AC_FUNC_MALLOC  from configure.ac it started compiling okay.

**Comment by rboy1** [comment]
Here is the patch I created:
```
--- configure.ac	2017-10-17 11:00:06.523022647 -0700
+++ configure-new.ac	2017-10-17 11:00:47.010739514 -0700
@@ -27,7 +27,6 @@
 AC_TYPE_SIZE_T
 
 # Checks for library functions.
-AC_FUNC_MALLOC
 AC_CHECK_FUNCS([strrchr])
 
 AC_CONFIG_FILES([libbs2b.pc
```

**Comment by rdp** [comment]
hmm could you try again?  I get past configure these days anyway...

**Comment by rdp** [comment]
Not sure why it's suddenly failing these days, but attempted fix in 724b490

**Comment by rdp** [comment]
useful ref: https://github.com/LLNL/ior/issues/4

**Comment by rboy1** [comment]
Yes that's where I found the tip originally. Thanks
