### ISSUE TITLE
Script does not work in case of Cygwin already installed

### ISSUE THREAD

**Issue by vitalyga** [rdp/ffmpeg-windows-build-helpers#271]
subj

**Comment by rdp** [comment]
how does it fail?

**Comment by vitalyga** [comment]
It detects that Cygwin already installed so it skips downloading Cygwin but then it tries to run cygwin's utilities from the ffmpeg_local_builds folder but fails because the folder is empty.

You can see it from the code snapshot below:
`) ELSE (
	ECHO Cygwin already installed.
)
ECHO.
REM want wget etc. so override path here by prepending. Probably need/want to do this anyway...
REM   since we're messing with the PATH
SET PATH=%cd%\ffmpeg_local_builds\cygwin_local_install\bin;%PATH%

CD ffmpeg_local_builds`

Also, I'm not so sure it bug or not, but the script tries to download Cygwin "setup-x86.exe" file despite that for 64-bit system is more suitable "setup-x86_64.exe" file.

**Comment by rdp** [comment]
patch welcome :)

**Comment by rdp** [comment]
and...removed it :)
