### ISSUE TITLE
Directory does not exist

### ISSUE THREAD

**Issue by rgvassar** [rdp/ffmpeg-windows-build-helpers#272]
I'm getting the following error running the script:

> The directory that should contain system headers does not exist:
> /media/sf_ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/mingw/include

When I look in the folder, I see that there is a mingw-w64-i686/i686-w64-mingw32/include, but the folder it's looking for doesn't exist. Any ideas?

**Comment by rdp** [comment]
what OS?

**Comment by rgvassar** [comment]
Linux Mint 18.2 x64

**Comment by rdp** [comment]
have you tried nuking the sandbox and trying again?

**Comment by rgvassar** [comment]
Yes, it's been 4 or 5 tries now. I'll make a virtual machine with Ubuntu tonight and let you know how it goes.

**Comment by rgvassar** [comment]
Worked fine on Ubuntu. It must be something specific with Linux Mint.
