### ISSUE TITLE
Stuck at building speexdsp

### ISSUE THREAD

**Issue by nicholaelaw** [rdp/ffmpeg-windows-build-helpers#274]
While most building problems could be solved by running `libtoolize` first, I've encountered something I don't know how to fix:

```
./configure: line 12974: syntax error near unexpected token `FFT,'
./configure: line 12974: `  PKG_CHECK_MODULES(FFT, fftw3f)'
```

This happens while building `speexdsp`. Any idea how to fix it?

**Comment by AurelioSilver** [comment]
Had the same issue and this helped me:
Enter the "speexdsp_git" directory
Type:
./autogen.sh
./configure 
run ./cross_compile_ffmpeg.sh again

I also installed the latest pkg-config from source.

**Comment by Reino17** [comment]
```diff
--- cross_compile_ffmpeg.sh.bak 2017-11-24 13:40:25.718750000 +0100
+++ cross_compile_ffmpeg.sh     2017-11-24 13:43:17.500000000 +0100
@@ -347,6 +347,9 @@
     if [[ ! -f $configure_name && -f bootstrap.sh ]]; then # fftw wants to only run this if no configure :|
       ./bootstrap.sh
     fi
+    if [[ ! -f $configure_name && -f autogen.sh ]]; then
+      ./autogen.sh
+    fi
     if [[ ! -f $configure_name ]]; then
       autoreconf -fiv # a handful of them require this to create ./configure :|
     fi
```

**Comment by rdp** [comment]
Is this still happening?

**Comment by nicholaelaw** [comment]
Will test later. Workstation's SSD failed so have to redo the environment.

**Comment by rdp** [comment]
seems working OK here, feel free to reopen
