### ISSUE TITLE
Add support for hardware acelleration

### ISSUE THREAD

**Issue by rboy1** [rdp/ffmpeg-windows-build-helpers#276]
There are lots of hardware acceleration features missing from this script. The default build of ffmpeg includes many additional flags like

--enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2

Can the script be updated to uses these hardware features?

**Comment by rboy1** [comment]
Some additional details:
https://trac.ffmpeg.org/wiki/HWAccelIntro

**Comment by schmidthubert** [comment]
Most of these switches are not necessarily needed anymore because they're autodetected now unless you manually disable them ...

**Comment by rboy1** [comment]
Interesting point, I was comparing the switches shown by the stock build of ffmpeg vs what shows up when doing a build with this RDP script. If the switches are enabled automatically shouldn't they show up when you run ffmpeg and it shows you a list of available features/flags?

**Comment by schmidthubert** [comment]
Run "ffmpeg -hwaccels" and it will show you what you can use on your platform.

**Comment by rboy1** [comment]
For examples these are the switches show by the stock build of ffmpeg when it's run, (latest nightly build)

```
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enabl
e-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopu
s --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-
libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-z
lib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --e
nable-dxva2 --enable-avisynth --enable-libmfx
```

If the switches are autoenabled, shouldn't they should up like when an ffmpeg build using the RDP script is run?

Is there any downside to including these flags in the default script? It seems to build just fine with the flags (I ran a quick test build).

**Comment by schmidthubert** [comment]
No, lots of switches will not show up. Use "ffmpeg -h full" etc ...

**Comment by schmidthubert** [comment]
>Is there any downside to including these flags in the default script
Not as far as I know ...

**Comment by rboy1** [comment]
Okay I'm going to run a few comparisons, was just curious as to why these flags shows up with the default nightly build of windows on the ffmpeg site.

**Comment by schmidthubert** [comment]
Some people just stick with what they used once and don't always follow. Adding them doesn't hurt but infact doesn't DO anything either. Certain people just want to have the longest (config line showing up) you know??

**Comment by schmidthubert** [comment]
OTOH you could go and complain to the ffmpeg developers as to why they don't explicitly show all "capabilities" with "ffmpeg -buildconf" even if not all switches have been manually added during configure. So you've got a point there too, so tell them ... ;-)

**Comment by rboy1** [comment]
You're correct the options that shows up with -h full and -hwaccel are identical for the builds without and with the flag above.

I guess I'll close this ticket. Thanks for your insight.

Where should I give this feedback to ffmpeg? I know only of the ticket site.

**Comment by schmidthubert** [comment]
ffmpeg users or developers mailing list, but I wouldn't go there with this one TBH ... 
http://ffmpeg.org/mailman/listinfo/

**Comment by rdp** [comment]
There have been some patch proposals for more hwaccel but I haven't been
able to wrap my head around them (I know nvenc is already in there...)
