### ISSUE TITLE
fribidi URL in cross_compile_ffmpeg.sh no longer resolves

### ISSUE THREAD

**Issue by djbacklund** [rdp/ffmpeg-windows-build-helpers#277]
The URL (https://www.fribidi.org/download/fribidi-0.19.7.tar.bz2) for fribidi in cross_compile_ffmpeg.sh no longer resolves to a file. Instead it redirects to the fribidi GitHub page.

Perhaps the build script could be updated to pull from the git repository or changed to an alternate URL? For my purposes, I changed it to https://ftp.osuosl.org/pub/blfs/conglomeration/fribidi/fribidi-0.19.7.tar.bz2 to get a successful build.

**Comment by DeadSix27** [comment]
Sadly the project currently does not build of git either, most reliable alternative mirror would be:
http://pkgs.fedoraproject.org/repo/pkgs/fribidi/fribidi-0.19.7.tar.bz2/6c7e7cfdd39c908f7ac619351c1c5c23/fribidi-0.19.7.tar.bz2

**Comment by schmidthubert** [comment]
https://github.com/fribidi/fribidi/releases works for me ...

**Comment by DeadSix27** [comment]
@schmidthubert what does work for you? The URL? Of course it does, But it's not compile able.

See: `https://github.com/fribidi/fribidi/issues/28#issuecomment-344826192`

**Comment by rdp** [comment]
OK hopefully fixed it...
