### ISSUE TITLE
what's going wrong here with x265, while compiling ??

### ISSUE THREAD

**Issue by feedzapper** [rdp/ffmpeg-windows-build-helpers#278]
my newest compile breaks with the building of  "x265" code (ubuntu 14.04 LTS)
missing patch file location ??

still at hg b24454f3ff6de650aab6835e291837fc4e2a4466 x265
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   400  100   400    0     0  10.8M      0 --:--:-- --:--:-- --:--:-- 10.8M
applying patch libx265_git_declspec.diff
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- x265-extras.h.bak  2017-07-09 11:52:49.515625000 +0200
|+++ x265-extras.h      2017-07-09 18:16:17.468750000 +0200
--------------------------
File to patch:

**Comment by DeadSix27** [comment]
@feedzapper It fails to apply a patch to x265, because that patch is not necessary anymore.

@rdp X265 patches are not needed anymore: https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/cross_compile_ffmpeg.sh#L1331
The extras file is gone, this issue got fixed upstream.

**Comment by feedzapper** [comment]
thanks, i cut this entry ..
now it works again :-)

**Comment by rdp** [comment]
OK hopefully fixed in  7d73d14634a0 thank you for the report
