### ISSUE TITLE
x265: Build fails because patch can't find removed file x265-extras.h

### ISSUE THREAD

**Issue by WolfVision** [rdp/ffmpeg-windows-build-helpers#283]
The file x265-extras.h was removed from the x265 master branch after the code was merged in the file x265.h (commit: http://hg.videolan.org/x265/rev/563cbe1f4a21). Now the patch "libx265_git_declspec.diff" always fails to apply. I assume, this patch is now obsolete and can be removed from the build script

**Comment by WolfVision** [comment]
Sorry, this was already reported in https://github.com/rdp/ffmpeg-windows-build-helpers/issues/278. Will close the issue.

**Comment by rdp** [comment]
Hopefully fixed now, thanks for the report
