### ISSUE TITLE
Recent addition of AMF to ffmpeg

### ISSUE THREAD

**Issue by DeadSix27** [rdp/ffmpeg-windows-build-helpers#285]
I tried implementing it myself but the static builds still fail, figured maybe you have an idea:

```
libavcodec/libavcodec.a(amfenc_h264.o): In function `AMFVariantAssignInt64':
include/AMF/core/Variant.h:1315: undefined reference to `AMFVariantClear'
include/AMF/core/Variant.h:1315:(.text.unlikely+0x85): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `AMFVariantClear'
......
collect2: error: ld returned 1 exit status
```

Thought maybe defining AMF_CORE_STATIC helps, https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/c7f29fec2326a253d319bb569cbc183b24504df9/amf/public/common/AMFFactory.cpp#L38

But no luck and I'm not that versed in c(++) so I'm not sure what the actual problem is.

See: https://github.com/DeadSix27/python_cross_compile_script/commit/e9cdde6e3778a7c1b78a9a363a7cb2ca25707196

on how to add the headers to the toolchain.

**Comment by rdp** [comment]
I run into that relocation thing "all the time" but to date still haven't
really figured it out, it's like an almost random link time failure..

**Comment by DeadSix27** [comment]
@rdp Same, but i think it's actually an issue just surfacing because of another issue, e.g the undefined reference to AMFVariantClear.

**Comment by DeadSix27** [comment]
@rdp https://github.com/GPUOpen-LibrariesAndSDKs/AMF/commit/cd231d58671db78d0fe0961354a2ba0bf03c1423

Fixed it, AMF support seems to work now (for me). I can make a PR if you want so you can test yourself too.

**Comment by rdp** [comment]
Sure.
