### ISSUE TITLE
zimg >= 2.6.2 not found using pkg-config

### ISSUE THREAD

**Issue by Phane7** [rdp/ffmpeg-windows-build-helpers#287]
Using Linux Mint 18.2 with uname -r 4.10.0-40-generic.  It gets to the part where it tries to compile ffmpeg proper and bombs out with:

"ERROR: zimg >= 2.6.2 not found using pkg-config"

It goes on to tell me the procedure for error reporting info for ffmpeg (if I feel it's a configure error), and I'm not sure if it's ffmpeg's fault or the script.

**Comment by rdp** [comment]
I thought I fixed it yesterday pull??

On Sunday, December 3, 2017, Phane7 <notifications@github.com> wrote:
> Using Linux Mint 18.2 with uname -r 4.10.0-40-generic. It gets to the
part where it tries to compile ffmpeg proper and bombs out with:
>
> "ERROR: zimg >= 2.6.2 not found using pkg-config"
>
> It goes on to tell me the procedure for error reporting info for ffmpeg
(if I feel it's a configure error), and I'm not sure if it's ffmpeg's fault
or the script.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/yfm2DRFM6fQMScUncLUUTLAInVEOZwplslN0izvhER6NGsCNLzZ_4wwxGQuOYZKN_HXTQNy9gBk4AihT-uBIvjPc8D-KamsUah7OBDd7SLvvdcksUmWUeWANoys_PVJ1ZNf8Aw80kXeQIy2GBGDQa5tqlOYIvA=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0Lw4sT2gciJHkbYg4AUBzIQbu-qVks5s8xxTgaJpZM4Qz6mj.gif>

**Comment by Phane7** [comment]
My bad, I was using git clone instead of pull and didn't notice it bombed out with a fatal error.

Now it bombs with "error: Your local changes to the folowing files would be overwritten at checkout: Makefile.am"

**Comment by rdp** [comment]
pull and try again.
But when it's building what does it fail?
