### ISSUE TITLE
Script hangs when building libmysofa

### ISSUE THREAD

**Issue by raytiley** [rdp/ffmpeg-windows-build-helpers#288]
Sorry for weird initial post... 

Trying to run the script on a fresh ubuntu VM and the script hangs when  building `libmysofa` Specificlaly the `sed` command here: https://github.com/rdp/ffmpeg-windows-build-helpers/commit/cf08ea12f02e366d0b1f2d43f1ea805e41bcdcbf#diff-6aa78e200c567e3c5cf63806768b2be3R1160 never finishes... it just hangs indefinitely. I'm not really sure what the sed command is trying to do, so not sure where to start fixing it.

Thanks

**Comment by Phane7** [comment]
I'm having the same issue.  Purged the directory and tried again, still happens.

**Comment by rdp** [comment]
That's weird, looks like it was the sed but I could have sworn that was
working a few days ago.  Oh well, pull!

**Comment by Phane7** [comment]
Works fine now, thanks.
