### ISSUE TITLE
Issue at GCC compilation step

### ISSUE THREAD

**Issue by LeRatierBretonnien** [rdp/ffmpeg-windows-build-helpers#29]
Hello, 
i just try your script, and i am facing an error at the GCC compilation step : 

...
checking for version 0.10 of ISL... no
checking for version 0.11 of ISL... no
configure: error: Unable to find a usable ISL.  See config.log for details.

I am using OpenSuse 13.1 64 bits. Any idea on how to fix it ?

**Comment by drewbitt** [comment]
I hate to re-open such an old issue but I also have this on OpenSUSE 64-bit Leap 42.3 so I'll hop on this old OpenSUSE issue

error part of build.log https://spit.mixtape.moe/view/a4cf53ea
config.log for isl https://spit.mixtape.moe/view/370bbf4f

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/4.9/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada,go,d --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.9 --enable-ssp --disable-libssp --disable-libvtv --disable-plugin --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --enable-linker-build-id --enable-linux-futex --program-suffix=-4.9 --without-system-libunwind --with-arch-32=i686 --with-tune=generic --with-multilib-list=m64,m32,mx32 --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 4.9.4 (SUSE Linux) 

I have libisl at usr/lib64/libisl.so.10 /usr/lib64/libisl.so.10.2.2

**Comment by drewbitt** [comment]
I have deleted sandbox and tried again if that's what you mean

**Comment by rdp** [comment]
Hmm would you mind digging into it and figuring out why it thinks libisl
isn't working? It's functioning OK for me here Ubuntu FWIW...
