### ISSUE TITLE
[WORKAROUND] ERROR: zimg >= 2.7.0 not found using pkg-config

### ISSUE THREAD

**Issue by Ekerim** [rdp/ffmpeg-windows-build-helpers#291]
I tried to do a clean build today from newly cloned repo and ran across this issue with zimg.
I found an earlier issue that mentioned zimg and a similar error, but that was in reference to v2.6.0 of zimg.
It seems the dependency is now v2.7.0+

[output.log](https://github.com/rdp/ffmpeg-windows-build-helpers/files/1582003/output.log)

Hopefully this is an easy issue to solve.

Merry Christmas in advance.

**Comment by nschlia** [comment]
Same for me...

**Comment by nschlia** [comment]
Temporary fix:

Change line 624 of cross_compile_ffmpeg.sh from

do_git_checkout https://github.com/sekrit-twc/zimg.git zimg_git c1689d4b9abbf4becadcbd4f436e2f3b2bf1c2f1

to

do_git_checkout https://github.com/sekrit-twc/zimg.git zimg_git 8e87f5a4b88e16ccafb2e7ade8ef454aeac19094

and run cross_compile_ffmpeg.sh again,

This will update libzimg to this commit (and to V2.7.x)

https://github.com/sekrit-twc/zimg/commit/8e87f5a4b88e16ccafb2e7ade8ef454aeac19094

After I did that ffmpeg was compiled successfully.

**Comment by hydra3333** [comment]
it seems to have been fixed with the latest ffmpeg in git

**Comment by nschlia** [comment]
Can't be fixed, the last commit to cross_compile_ffmpeg.sh is 12 days old, my work around just five...

**Comment by rdp** [comment]
hopefully fixed in c5e2eaad1bcba26992a2b thanks for the tip!
