### ISSUE TITLE
libavdevice fails build with "--enable-gpl=n --git-get-latest=y --disable-nonfree=n"

### ISSUE THREAD

**Issue by Ekerim** [rdp/ffmpeg-windows-build-helpers#293]
Building ffmpeg without libfdk_aac works good now when the workaround was found to my other issue with zimg, however, building with libfdk_aac fails.

[output.log](https://github.com/rdp/ffmpeg-windows-build-helpers/files/1584037/output.log)

If I weren't so clueless I would try to help find a solution but now I'm not so I post instead :) hoping for the kindness of strangers.

Merry Christmas

**Comment by rdp** [comment]
Seemed to work fine for me just now, try er again! re open if still fails, thanks.
