### ISSUE TITLE
Cross-compile fails in "libavcodec/libx264.c: In function ‘X264_frame’"

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#294]
more info rather than bug
Cross-compile fails in "libavcodec/libx264.c: In function ‘X264_frame’"

For the time being, the latest ffmpeg git won't cross-compile with the latest x264 git
https://trac.ffmpeg.org/ticket/6932

If you use x264 commit e9a5903edf8ca59ef20e6f4894c196f135af735e then it works (until ffmpeg is changed in the near future to use the new api, then you'll have to look at using a newer x264 commit).

**Comment by rdp** [comment]
App ears they fixed it?

On Monday, December 25, 2017, hydra3333 <notifications@github.com> wrote:
> more info rather than bug
> Cross-compile fails in "libavcodec/libx264.c: In function ‘X264_frame’"
>
> For the time being, the latest ffmpeg git won;'t cross-compile with the
latest x264 git
> https://trac.ffmpeg.org/ticket/6932
>
> If you use x264 commit e9a5903edf8ca59ef20e6f4894c196f135af735e then it
works (until ffmpeg is changed in the near future to use the new api, then
you'll have to look at using a newer x264 commit).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/nxbnwe68W4QaA1tuMX48Jm90h2GTT4a_kVzqeF-NuCPJ4eOwV2uuQp72SJRvQIBUr9HMFCy332xxyUS6LwaW_CkyTjqAFuiLe3kbm27J3RfhWvu42lx9gD58Fr6jEnwVCe4sE94cV7OeLF2nccLH_OElNTdZ3A=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0KsAJWUH2Vnd91qyiLPd2sHKMmrVks5tEIgAgaJpZM4RMhIn.gif>

**Comment by hydra3333** [comment]
i guess so
