### ISSUE TITLE
Build fails because nasm-2.13 required

### ISSUE THREAD

**Issue by nschlia** [rdp/ffmpeg-windows-build-helpers#295]
Build fails again. This time because NASM 2.13 is required. Seriously? I am running Debian 9 that comes with NASM 2.12. Do we really need to update to a newer version than the one on stock? 

15:35:38 configuring x264_normal_bitdepth (/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/win32/x264_normal_bitdepth) as $ PKG_CONFIG_PATH=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/pkgconfig PATH=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-i686/bin:$PATH ./configure --host=i686-w64-mingw32 --enable-static --cross-prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32- --prefix=/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --enable-strip --disable-cli --disable-lavf --extra-cflags=-mtune=generic --extra-cflags=-O3

15:35:39 Found no assembler
15:35:39 Minimum version is nasm-2.13

**Comment by nschlia** [comment]
After update on NASM version 2.13.02 (latest from http://www.nasm.us/) and applying the fix #291 the build went through.

**Comment by rdp** [comment]
nasm req. hopefully fixed in 0cdc9d4 thank you for the report.
