### ISSUE TITLE
Running this on Raspberry Pi / Debian / Wheezy

### ISSUE THREAD

**Issue by dezi** [rdp/ffmpeg-windows-build-helpers#3]
Worked pretty nice. 

For libxavs I had to add the "--disable-asm" option to configure.

build_libxavs() {
  do_svn_checkout https://xavs.svn.sourceforge.net/svnroot/xavs/trunk xavs
  cd xavs
    export LDFLAGS='-lm'
    generic_configure "--disable-asm" # unfortunately this using --host isn't enough apparently...
    unset LDFLAGS
    do_make_install "CC=$(echo $cross_prefix)gcc AR=$(echo $cross_prefix)ar PREFIX=$mingw_w64_x86_64_prefix RANLIB=$(echo $cross_prefix)ranlib STRIP=$(echo $cross-prefix)strip"
  cd ..
}

**Comment by rdp** [comment]
see #658
