### ISSUE TITLE
Failing to compile on Debian; c2man missing

### ISSUE THREAD

**Issue by izumitelj** [rdp/ffmpeg-windows-build-helpers#302]
Hello, I'm trying to compile ffmpeg for Win x64 on stable Linux/Debian 9 (stretch) but after 1-2hrs I get following error and no executable at the end.
```
checking return type of signal handlers... void
checking for GLIB... no
checking for c2man... no
configure: error: c2man is required to build documentation
```
I've installed all dependencies suggested by the script:
`sudo apt-get install subversion curl texinfo g++ bison flex cvs yasm automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev mercurial unzip pax nasm gperf autogen bzip2 libtool-bin ed -y`

I've also tried searching for c2man in repository but I don't see any packages named like that. I've also tried disabling `--disable-docs`, also without success.

I'm compiling using default settings. I would appreciate any help. Thanks.

**Comment by izumitelj** [comment]
OK, I've just noticed this note in the instuctions:

> NB: works with Ubuntu distros that uses gcc 5.x but not 6.x (yet) (i.e. 16.10 it will not work yet).

And I'm using:

> gcc (Debian 6.3.0-18) 6.3.0 20170516

Could this be the problem and is there a workaround? Debian u 9 is stable for almost a year now.

**Comment by rdp** [comment]
How far does it get? Is it failing on a particular dependency?

On Sunday, February 18, 2018, izumitelj <notifications@github.com> wrote:
> OK, I've just noticed this note in the instuctions:
>
> NB: works with Ubuntu distros that uses gcc 5.x but not 6.x (yet) (i.e.
16.10 it will not work yet).
>
> And I'm using:
>
> gcc (Debian 6.3.0-18) 6.3.0 20170516
>
> Could this be the problem and is there a workaround? Debian u 9 is stable
for almost a year now.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/tiT_Jpzy2feebByTz7_AtITTBNQk_vKw-TQhW01gu718XRms6e_P5jErUO9tazFDKccJshfHlqXvS33FtoH3NfcHe2lzrDw7vSd2DQ6URZRvt23hWpkWmdGjTLBUPrBy6sv3n5fjinHzYct056ABPrsGnnmjbQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0Hor0NBZC1i68HXwmle6y2VAHFZ2ks5tWCJVgaJpZM4SJqkz.gif>

**Comment by hydra3333** [comment]
I was able to eventually avoid the issue and build it, by commenting out any stuff which tried to build "mp4client" within building the gpac mp4box.

VM with Ubuntu 17.10.1 gcc 7.3.

**Comment by rdp** [comment]
OK hopefully fixed in  7cf20fb thank you for the report.

**Comment by izumitelj** [comment]
@rdp seems like it's working fine now. I've now successfully compiled it on the same configuration. Thank you for the fix and other users for suggestions.

**Comment by izumitelj** [comment]
@rdp seems like it's working fine now. I've now successfully compiled it on the same configuration. Thank you for the fix and other users for suggestions.
