### ISSUE TITLE
[feature request] Possibility of adding libnpp support

### ISSUE THREAD

**Issue by MrShoenel** [rdp/ffmpeg-windows-build-helpers#304]
The title says it pretty much; I'd  be interested in having (conditional) `libnpp` support. Since `nvenc` is supported, it would be handy to have access to e.g. GPU scaling through libnpp.

I suppose one would need to install the CUDA SDK and link against their libraries? Where would be start with this?

**Comment by schmidthubert** [comment]
https://github.com/rdp/ffmpeg-windows-build-helpers/issues/249

**Comment by MrShoenel** [comment]
Okay, thanks!
