### ISSUE TITLE
Build fails because freetype-2.8.tar.bz2 not found

### ISSUE THREAD

**Issue by nschlia** [rdp/ffmpeg-windows-build-helpers#305]
Seems sourceforge has been updated to freetype-2.9.tar.bz2

The build now fails (here's just the first of the messages):

```
13:23:14 downloading https://sourceforge.net/projects/freetype/files/freetype2/2.8/freetype-2.8.tar.bz2
13:23:14   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
13:23:14                                  Dload  Upload   Total   Spent    Left  Speed

13:23:14   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
13:23:15 Warning: Transient problem: HTTP error Will retry in 1 seconds. 50 retries 
13:23:15 Warning: left.

```

**Comment by nschlia** [comment]
I take that one back, seems to be that Sourceforge has problems. The new links also do not work.

**Comment by hydra3333** [comment]
Yes I have seen a lot of sourceforge problems tonight.
This worked a minute ago

https://sourceforge.net/projects/freetype/files/freetype2/2.8.1/freetype-2.8.1.tar.bz2

**Comment by rdp** [comment]
Working OK now? I'd be happy to accept a pull request that gets it from
somewhere more stable like github (though I'm sure there are a ton of other
sourceforge downloads unfortunately)

**Comment by DeadSix27** [comment]
@rdp I added mirror support to my script now and primarily use http://fossies.org/ as backup mirror, they seem to be decent and so far every package matched the hash, however I don't really trust any source download unless its from the developers site, so I can't recommend them unless you add hash-checking, but uptime and speed -wise they're ok.

**Comment by hydra3333** [comment]
ok, download_and_unpack_file https://fossies.org/linux/misc/freetype-2.9.tar.bz2
but where to source the hash from ?

**Comment by DeadSix27** [comment]
@hydra3333 https://sourceforge.net/projects/freetype/files/freetype2/2.8.1/freetype-2.8.1.tar.bz2

**Comment by hydra3333** [comment]
yar.
