### ISSUE TITLE
theora build fails under Debian 9

### ISSUE THREAD

**Issue by nschlia** [rdp/ffmpeg-windows-build-helpers#306]
Started a fresh build (from scratch, empty directory). Build fails at Theora, it seems te executable it tries to run (vp3huff) is for Windows.

Build command:

./cross_compile_ffmpeg.sh --disable-nonfree=n --enable-gpl=y --build-ffmpeg-static=n --build-ffmpeg-shared=y --disable-nonfree=n --sandbox-ok=y --compiler-flavors=multi --build-intel-qsv=y --build-libmxf=n --build-mp4box=n --build-mplayer=n --build-vlc=n --build-lsw=n --build-ismindex=n --build-dvbtee=n --build-x264-with-libav=n --prefer-stable=y --high-bitdepth=n

```
09:29:00 make[3]: Verzeichnis „/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/win32/theora_git/doc/spec“ wird betreten
09:29:00   CC       vp3huff.o
09:29:02 fig2dev -L pdf -p 0 lflim.fig lflim.pdf09:29:02 i686-w64-mingw32-gcc -Wall -Wno-parentheses -O3 -fomit-frame-pointer -finline-functions -funroll-loops -mtune=generic -O3    vp3huff.c   -o vp3huff
09:29:02   CCLD     vp3huff.exe
09:29:02 ./vp3huff > vp3huff.tex
09:29:02 /bin/bash: ./vp3huff: Can not execute the binary file: Error in the format of the program file
09:29:02 Makefile:729: die Regel für Ziel „vp3huff.tex“ scheiterte
09:29:02 make[3]: *** [vp3huff.tex] Fehler 126
09:29:02 Makefile:432: die Regel für Ziel „all“ scheiterte
09:29:02 make: *** [all] Fehler 2
09:29:02 Build step 'Shell ausführen' marked build as failure
09:29:03 Finished: FAILURE
```

**Comment by nschlia** [comment]
Addendum... I started the compile several times over, suddenly Theora was build, but now it stops later on with:

make[2]: *** No rule to make target „twolame.1“ when it wants to build sandbox/win32/twolame_git/doc

**Comment by rdp** [comment]
interesting, wonder if vp fixed something, I've been unable to repro it to date anyway...

**Comment by nschlia** [comment]
I did that several times

Clean checkout (git clone https://github.com/rdp/ffmpeg-windows-build-helpers.git .) and run the above command. It fails at Theora with the above error. When I simply restart the build Theora builds successfully. Very strange.

But then libtwolame fails. And this is consistent. I can repeat as often as I want to. Running Debian 9.3.

**Comment by hydra3333** [comment]
The git https://github.com/njh/twolame hasn't been updated in a while, so it's not that.
twolame build just failed for me too, after I commented out this code in an effort to cleanup my hack of rdp's most wonderful script.  
```
    if [[ ! -f Makefile.am.bak ]]; then # Library only, front end refuses to build for some reason
      sed -i.bak "/^SUBDIRS/s/ frontend.*//" Makefile.am || exit 1 
    fi
```
So, I'm un-commenting-it and trying again to see how it goes ...
Along the journey I noticed a couple of things in my hack where I had to put kludges back in to make a fresh build work.

**Comment by rdp** [comment]
That is weird, I nuked it and "now" i'm getting

/bin/bash ../libtool  --tag=CC   --mode=link i686-w64-mingw32-gcc
-I../libtwolame/  -mtune=generic -O3 -DLIBTWOLAME_STATIC   -o stwolame.exe
simplefrontend.o audio_wave.o ../libtwolame/libtwolame.la -lm -lm
libtool: link: i686-w64-mingw32-gcc -I../libtwolame/ -mtune=generic -O3
-DLIBTWOLAME_STATIC -o stwolame.exe simplefrontend.o audio_wave.o
../libtwolame/.libs/libtwolame.a
make[1]: Leaving directory
'/home/rdp/ffmpeg-windows-build-helpers/sandbox/win32/twolame_git/simplefrontend'
Making all in doc
make[1]: Entering directory
'/home/rdp/ffmpeg-windows-build-helpers/sandbox/win32/twolame_git/doc'
Making all in html
make[2]: Entering directory
'/home/rdp/ffmpeg-windows-build-helpers/sandbox/win32/twolame_git/doc/html'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/rdp/ffmpeg-windows-build-helpers/sandbox/win32/twolame_git/doc/html'
make[2]: Entering directory
'/home/rdp/ffmpeg-windows-build-helpers/sandbox/win32/twolame_git/doc'
make[2]: *** No rule to make target 'twolame.1', needed by 'all-am'.  Stop.
make[2]: Leaving directory
'/home/rdp/ffmpeg-windows-build-helpers/sandbox/win32/twolame_git/doc'
Makefile:479: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory
'/home/rdp/ffmpeg-windows-build-helpers/sandbox/win32/twolame_git/doc'
Makefile:470: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1


OK the fix you described fixes it, thanks for the help, give it a shot now!

**Comment by rdp** [comment]
Do you get the theora failure with any kind of frequency? Is twolame still failing? If so try adding a cpu_count=1
 at the start of the build_xx method for them and does it still repro? How many cores here? Thanks!

**Comment by pet0ruk** [comment]
Exactly the same issue here with twolame failing to build - the script already has cpu_count=1 in it within the build_twolame() function.

**Comment by Reino17** [comment]
> That is weird, I nuked it and "now" i'm getting
> [...]
> make[2]: *** No rule to make target 'twolame.1', needed by 'all-am'. Stop.

That's not weird at all. You committed "[I'm ok with cli and docs :)](https://github.com/rdp/ffmpeg-windows-build-helpers/commit/40a48d228216add633593148ae2ededcec08ff4d)". Well, some of these weren't there just to shorten the compilationprocess, as you've just witnessed (maybe I should've documented it better).

'_Makefile.am_':
```
SUBDIRS = . libtwolame frontend simplefrontend doc tests
```
The error comes from trying to compile the doc-dir, so excluding that one should fix it:
```sh
if [[ ! -f Makefile.am.bak ]]; then # Exclude doc-dir, or building LibTwoLAME fails.
  sed -i.bak "/^SUBDIRS/s/ doc//" Makefile.am
fi
```
I prefer to compile only the most necessary stuff however, so:
```sh
if [[ ! -f Makefile.am.bak ]]; then # Library only.
  sed -i.bak "/^SUBDIRS/s/ frontend.*//" Makefile.am
fi
```

**Comment by nschlia** [comment]
The update triggered a Jenkins build which failed so I nuked the workspace and started a fresh build. The first build failed at Theora, again :) Restarted the build, Theora OK, libtwolame also OK, but now Sourceforge seems to be playing tricks on me, what a PITA. Unable to fetch opencore-amr-0.1.5.tar.gz...

**Comment by Warblefly** [comment]
On Thu, Mar 1, 2018 at 10:53 AM, Norbert Schlia <notifications@github.com>
wrote:

> The update triggered a Jenkins build which failed so I nuked the workspace
> and started a fresh build. The first build failed at Theora, again :)
> Restarted the build, Theora OK, libtwolame also OK, but now Sourceforge
> seems to be playing tricks on me, what a PITA. Unable to fetch
> opencore-amr-0.1.5.tar.gz...
>
​
Sourceforge is very unwell, it seems.

Theora often fails for me, too. Says something about "can't find path to
/lib". Recompiling fixes it.  Maybe a 'make -j n>1' issue? Not sure. Bit
busy but perseverance pays.

J
​

**Comment by nschlia** [comment]
Yup. Theora nags, but retrying helps and when it's once built it's OK.
On the other hand, the twolame problem is gone, which was a show stopper. So I'll close this.
Thanks for the help!

**Comment by rdp** [comment]
Does the theora thing go away if you add cpu_count=1?
Thanks to Reino for the patch to twolame, cheers all.

**Comment by nschlia** [comment]
Tried with cpu_count=4 and without that parameter. Same result. Will try with cpu_count=1, but I c
an't run the build now because SF seems down again. Will do ASAP.

**Comment by nschlia** [comment]
With cpu_count=1 same Thoara build problem.

**Comment by nschlia** [comment]
Build from scratch, now with cpu_count=1. This time it fail is when building leptonica. 

```
  CCLD     convertfilestops.exe
  CCLD     convertformat.exe
  CCLD     convertsegfilestopdf.exe
/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw/-w64-i686/bin/././libhome//gcc/i686-w64-mingw32/7.1.0/../..home//.jenkins.//ffmpeg../-windowsi686--buildw64-mingw32/bin-helpers//workspaceld:/sandbox cannot/cross_compilers find/mingw --w64ljpeg
-i686/bin/.jenkinscollect2: error: ld returned 1 exit status
./lib//ffmpeg-windows-build-helpers/workspacegcc//sandboxi686/-cross_compilersw64/-mingwmingw32-/w647.1.0-/i686./.bin//....//.lib.//gcc./.i686/-i686w64--w64mingw32-mingw32//7.1.0bin//.ld.:/ .cannot. /.find. /-.ljpeg.
/collect2: error: ld returned 1 exit status
i686-w64-mingw32/bin/ld: cannot find -ljpeg
collect2: error: ld returned 1 exit status
Makefile:2530: die Regel für Ziel „convertfilestops.exe“ scheiterte
make[2]: *** [convertfilestops.exe] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet...
Makefile:2534: die Regel für Ziel „convertformat.exe“ scheiterte
make[2]: *** [convertformat.exe] Fehler 1
Makefile:2526: die Regel für Ziel „convertfilestopdf.exe“ scheiterte
make[2]: *** [convertfilestopdf.exe] Fehler 1
/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-i686/bin/../lib/gcc/i686-w64-mingw32/7.1.0/../../../../i686-w64-mingw32/bin/ld: cannot find -ljpeg
collect2: error: ld returned 1 exit status
Makefile:2538: die Regel für Ziel „convertsegfilestopdf.exe“ scheiterte
make[2]: *** [convertsegfilestopdf.exe] Fehler 1
make[2]: Verzeichnis „/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/win32/leptonica_git/prog“ wird verlassen
Makefile:476: die Regel für Ziel „all-recursive“ scheiterte
make[1]: *** [all-recursive] Fehler 1
make[1]: Verzeichnis „/home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/win32/leptonica_git“ wird verlassen
Makefile:385: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```

**Comment by rdp** [comment]
Unable to repro the theora thing still unfortunately
