### ISSUE TITLE
building NV/CUDA query, some headers being removed ?

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#307]
Seeking advice ...

this patch seems to be removing headers to do with NV stuff https://patchwork.ffmpeg.org/patch/7735/

I wonder, like jb here https://github.com/jb-alvarado/media-autobuild_suite/commit/42df66ae62db312d854e1e2b94e6f8223440a7e6#commitcomment-27827282  does this now need to be "installed" before one can build ffmpeg with the NV/CUDA encoder stuff baked into ffmpeg ?

**Comment by rdp** [comment]
Are we supposed to clone

https://git.videolan.org/?p=ffmpeg/nv-codec-headers.git


in now or something? hmm will look into it.

**Comment by schmidthubert** [comment]
Yes. And then just follow the makefile of that git, nothing is built just a install(cp) job ... :+1:

**Comment by rdp** [comment]
hopefully got it, thanks for the tips/pointers.
