### ISSUE TITLE
libmp3lame build fails with inlining error

### ISSUE THREAD

**Issue by nschlia** [rdp/ffmpeg-windows-build-helpers#308]
When building libmp3lame it fails with several of these errors:

```
In file included from xmm_quantize_sub.c:37:0:
/usr/lib/gcc/i686-w64-mingw32/6.3-win32/include/xmmintrin.h:895:1: error: inlining failed in call to always_inline ‘_mm_set_ps1’: target specific option mismatch
 _mm_set_ps1 (float __F)
 ^~~~~~~~~~~
xmm_quantize_sub.c:74:21: note: called from here
     vec_sum._m128 = _mm_set_ps1(0);
                     ^~~~~~~~~~~~~~
```
See this for a complete list:
[fail.log](https://github.com/rdp/ffmpeg-windows-build-helpers/files/1771300/fail.log)

Probably due to the new gcc 7.1 compiler. It appears that adding a "-msse4.1" compile option fixes the problem. I am currently preparing a pull request with the fix.

**Comment by rdp** [comment]
what are your parameters to starting the script here?

**Comment by nschlia** [comment]
My usual parameters are (I know most are default, I should reduce them a bit):

./cross_compile_ffmpeg.sh --disable-nonfree=n --enable-gpl=y --build-ffmpeg-static=n --build-ffmpeg-shared=y --disable-nonfree=n --sandbox-ok=y --compiler-flavors=multi --build-intel-qsv=y --build-libmxf=n --build-mp4box=n --build-mplayer=n --build-vlc=n --build-lsw=n --build-ismindex=n --build-dvbtee=n --build-x264-with-libav=n --prefer-stable=y --high-bitdepth=n

**Comment by nschlia** [comment]
Update: 

After Sourceforge came to live again I nuked the sandbox and started a new build. 

First it stopped with the usual libtheora problem, after restart (without the patch) it stops with the aforementioned inling error. So this is confirmed now.

**Comment by nschlia** [comment]
This is weird: As mentioned in https://github.com/rdp/ffmpeg-windows-build-helpers/issues/312#issuecomment-370322626 my build directories were accessed via a symbolic link. After I moved everything to a real path libmp3lame was build without inlining error. It appears that using symbolic links here is no good idea.

I suggest we can close this.

**Comment by rdp** [comment]
That is a weird one.  Feel free to close it....

**Comment by nschlia** [comment]
Weirdo closed. :)
