### ISSUE TITLE
binutils build fails on Ubuntu 13.10

### ISSUE THREAD

**Issue by gcsx** [rdp/ffmpeg-windows-build-helpers#31]
Hello,

I'm trying to use a 100% fresh install of Ubuntu 13.10 hosted in VMware Workstation 10 on Windows 7 x64 to compile a x64 ffmpeg using your script but the compilation of binutils fails.

Here is the only informations I have : 

gcc -DHAVE_CONFIG_H -I. -I../../../source/binutils-2.24.51/binutils  -I. -I../../../source/binutils-2.24.51/binutils -I../bfd -I../../../source/binutils-2.24.51/binutils/../bfd -I../../../source/binutils-2.24.51/binutils/../include -DLOCALEDIR="\"/home/gc/sandbox/mingw-w64-x86_64/share/locale\"" -Dbin_dummy_emulation=bin_vanilla_emulation  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Werror -g -O2 -MT bucomm.o -MD -MP -MF .deps/bucomm.Tpo -c -o bucomm.o ../../../source/binutils-2.24.51/binutils/bucomm.c
../../../source/binutils-2.24.51/binutils/bucomm.c:130:7: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘VPARAMS’
 fatal VPARAMS ((const char *format, ...))
       ^
../../../source/binutils-2.24.51/binutils/bucomm.c:141:11: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘VPARAMS’
 non_fatal VPARAMS ((const char *format, ...))
           ^
There is no build-log.txt file anywhere.
The problem repeats after complete deletion of the sandbox.

Should I try another distrib? Which one did you used?

I'm downloading your precompiled toolchain. I'll update this as soon as I tried.

**Comment by rdp** [comment]
(if left pane works) for followers, nuking sandbox fixed this for me again today: 

orphan-labels -DSTACK_ALIGNMENT=32 -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -o common/x86/dct-32.o common/x86/dct-32.asm
yasm -I. -I. -O2 -DARCH_X86_64=0 -I./common/x86/ -f win32 -DPREFIX -Worphan-labels -DSTACK_ALIGNMENT=32 -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -o common/x86/bitstream-a.o common/x86/bitstream-a.asm
yasm -I. -I. -O2 -DARCH_X86_64=0 -I./common/x86/ -f win32 -DPREFIX -Worphan-labels -DSTACK_ALIGNMENT=32 -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -o common/x86/sad-a.o common/x86/sad-a.asm
yasm -I. -I. -O2 -DARCH_X86_64=0 -I./common/x86/ -f win32 -DPREFIX -Worphan-labels -DSTACK_ALIGNMENT=32 -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -o common/x86/pixel-32.o common/x86/pixel-32.asm
rm -f libx264.a
/Users/packrd/dev/ffmpeg-windows-build-helpers/sandbox/mingw-w64-i686/bin/i686-w64-mingw32-ar rc libx264.a  common/mc.o common/predict.o common/pixel.o common/macroblock.o common/frame.o common/dct.o common/cpu.o common/cabac.o common/common.o common/osdep.o common/rectangle.o common/set.o common/quant.o common/deblock.o common/vlc.o common/mvpred.o common/bitstream.o encoder/analyse.o encoder/me.o encoder/ratecontrol.o encoder/set.o encoder/macroblock.o encoder/cabac.o encoder/cavlc.o encoder/encoder.o encoder/lookahead.o common/threadpool.o common/win32thread.o common/x86/mc-c.o common/x86/predict-c.o common/opencl.o encoder/slicetype-cl.o common/x86/const-a.o common/x86/cabac-a.o common/x86/dct-a.o common/x86/deblock-a.o common/x86/mc-a.o common/x86/mc-a2.o common/x86/pixel-a.o common/x86/predict-a.o common/x86/quant-a.o common/x86/cpu-a.o common/x86/dct-32.o common/x86/bitstream-a.o common/x86/sad-a.o common/x86/pixel-32.o
/Users/packrd/dev/ffmpeg-windows-build-helpers/sandbox/mingw-w64-i686/bin/i686-w64-mingw32-ranlib libx264.a
/Users/packrd/dev/ffmpeg-windows-build-helpers/sandbox/mingw-w64-i686/bin/i686-w64-mingw32-gcc -o x264.exe   x264res.o x264.o input/input.o input/timecode.o input/raw.o input/y4m.o output/raw.o output/matroska.o output/matroska_ebml.o output/flv.o output/flv_bytestream.o filters/filters.o filters/video/video.o filters/video/source.o filters/video/internal.o filters/video/resize.o filters/video/cache.o filters/video/fix_vfr_pts.o filters/video/select_every.o filters/video/crop.o filters/video/depth.o input/avs.o input/thread.o libx264.a -lshell32 -m32   -Wl,--large-address-aware -Wl,--nxcompat -Wl,--dynamicbase 
libx264.a(osdep.o): In function `x264_threading_destroy':
/Users/packrd/dev/ffmpeg-windows-build-helpers/sandbox/win32/x264/common/osdep.c:68: undefined reference to `pthread_win32_thread_detach_np'
/Users/packrd/dev/ffmpeg-windows-build-helpers/sandbox/win32/x264/common/osdep.c:69: undefined reference to `pthread_win32_process_detach_np'
libx264.a(osdep.o): In function `x264_threading_init':
/Users/packrd/dev/ffmpeg-windows-build-helpers/sandbox/win32/x264/common/osdep.c:82: undefined reference to `ptw32_processInitialized'
/Users/packrd/dev/ffmpeg-windows-build-helpers/sandbox/win32/x264/common/osdep.c:84: undefined reference to `pthread_win32_process_attach_np'
collect2: error: ld returned 1 exit status
make: *** [x264.exe] Error 1

**Comment by Jan-E** [comment]
What happens if you rm -rf the x264 directory now and try to rebuild x264? I ran into the same errors when I tried this. I solved it by leaving out the --extra-cflags=-DPTW32_STATIC_LIB in the configure line.

There had been a change in the configure options for x264:
https://mailman.videolan.org/pipermail/x264-devel/2016-January/011538.html
[x264-devel] windows: Use native threads by default

After leaving out the --extra-cflags=-DPTW32_STATIC_LIB this is the result in config.h:

#define HAVE_WIN32THREAD 1
#define HAVE_THREAD 1
...
#define HAVE_BEOSTHREAD 0
#define HAVE_POSIXTHREAD 0

Another way to fix compilation is by explicitly including libpthread.a

--extra-cflags=-DPTW32_STATIC_LIB --extra-ldflags=-lpthread

I did not check yet if the end result differs between both fixes.

**Comment by rdp** [comment]
This just worked fine for me, does it still fail for you?
