### ISSUE TITLE
in ffmpeg cuda being renamed to ffnvcodec

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#311]
[FFmpeg-devel] [PATCH] configure: rename cuda to ffnvcodec
http://ffmpeg.org/pipermail/ffmpeg-devel/2018-March/226039.html

just a thought, configure needs to be updated when that's implemented

**Comment by schmidthubert** [comment]
Total rubbish and what a mess if was asked. "codec"?? That's something to be installed ... Looking fwd to even more complexity, thank you NV ... NOT! :-1:

**Comment by hydra3333** [comment]
I must have mis-read it ?

I thought it was a just "name change" by the ffmpeg maintaners to stop people trying to install cuda, given the prior change of now having to download and install separate nv headers.

**Comment by schmidthubert** [comment]
Yes it's just another name then but there's too many already. cuda,cuvid,nvenc,nvdec,scale_npp,scale_cuda and now ffnvcodec then. It's no surprise especially beginners don't know which is which and what is what. Also the documentation is lousy as for transcoding, this should be done much better IMO. But there's such and such programmers, some are very lazy ...

**Comment by hydra3333** [comment]
I'm a lazy old programmer :) 
well, I used to be one in the olden days.
Agreed, unless someone tells you which ones you need, it seems to be a bit of a mess.
