### ISSUE TITLE
building failed "./configure: fork: Permission denied"

### ISSUE THREAD

**Issue by anguoyang** [rdp/ffmpeg-windows-build-helpers#313]
I used native build on windows 10,  run"build_locally_shared_lgpl_64_bit_option.bat" directly with"enable quicksync", but with these errors:
downloading https://sourceforge.net/projects/opencore-amr/files/vo-amrwbenc/vo-amrwbenc-0.1.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15761  100 15761    0     0  15761      0  0:00:01 --:--:--  0:00:01 18263
100 15837  100 15837    0     0  15837      0  0:00:01  0:00:01 --:--:--  156k
100   363  100   363    0     0    181      0  0:00:02  0:00:02 --:--:--     0
100  594k  100  594k    0     0   198k      0  0:00:03  0:00:03 --:--:--  638k
configuring vo-amrwbenc-0.1.3 (/cygdrive/d/yanganguo/myproject/demo/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/win64/vo-amrwbenc-0.1.3) as $ PKG_CONFIG_PATH=/cygdrive/d/yanganguo/myproject/demo/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/cygdrive/d/yanganguo/myproject/demo/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --host=x86_64-w64-mingw32 --prefix=/cygdrive/d/yanganguo/myproject/demo/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --disable-shared --enable-static
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-w64-mingw32-strip... x86_64-w64-mingw32-strip
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for x86_64-w64-mingw32-gcc... x86_64-w64-mingw32-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-w64-mingw32-gcc accepts -g... yes
checking for x86_64-w64-mingw32-gcc option to accept ISO C89... none needed
checking dependency style of x86_64-w64-mingw32-gcc... gcc3
checking dependency style of x86_64-w64-mingw32-gcc... gcc3
checking for x86_64-w64-mingw32-gcc option to accept ISO C99... none needed
checking build system type... i686-pc-cygwin
checking host system type... x86_64-w64-mingw32
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by x86_64-w64-mingw32-gcc... /cygdrive/d/yanganguo/myproject/demo/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin/ld.exe
checking if the linker (/cygdrive/d/yanganguo/myproject/demo/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /cygdrive/d/yanganguo/myproject/demo/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-nm -B
checking the name lister (/cygdrive/d/yanganguo/myproject/demo/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 8192
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert i686-pc-cygwin file names to x86_64-w64-mingw32 format... func_convert_file_cygwin_to_w32
checking how to convert i686-pc-cygwin file names to toolchain format... func_convert_file_noop
checking for /cygdrive/d/yanganguo/myproject/demo/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin/ld.exe option to reload object files... -r
checking for x86_64-w64-mingw32-objdump... x86_64-w64-mingw32-objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for x86_64-w64-mingw32-dlltool... x86_64-w64-mingw32-dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for x86_64-w64-mingw32-ar... x86_64-w64-mingw32-ar
checking for archiver @FILE support... @
checking for x86_64-w64-mingw32-strip... (cached) x86_64-w64-mingw32-strip
checking for x86_64-w64-mingw32-ranlib... x86_64-w64-mingw32-ranlib
checking command to parse /cygdrive/d/yanganguo/myproject/demo/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-nm -B output from x86_64-w64-mingw32-gcc object... ok
checking for sysroot... no
checking for x86_64-w64-mingw32-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... x86_64-w64-mingw32-gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if x86_64-w64-mingw32-gcc supports -fno-rtti -fno-exceptions... no
checking for x86_64-w64-mingw32-gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if x86_64-w64-mingw32-gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if x86_64-w64-mingw32-gcc static flag -static works... yes
checking if x86_64-w64-mingw32-gcc supports -c -o file.o... yes
checking if x86_64-w64-mingw32-gcc supports -c -o file.o... (cached) yes
checking whether the x86_64-w64-mingw32-gcc linker (/cygdrive/d/yanganguo/myproject/demo/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
configure: creating ./config.status
      0 [main] sh 14416 fork: child -1 - CreateProcessW failed for 'D:\yanganguo\myproject\demo\ffmpeg-windows-build-helpers\native_build\windows\ffmpeg_local_builds\cygwin_local_install\bin\sh.exe', errno 13
./configure: fork: Permission denied
configure: error: write failure creating ./config.status

Done with local build. Check output above to see if successfull.
If not successful, then you could try to rerun the script. It "should" pick up where it left off.

If you want more advanced configuration (like building mplayer or mp4box, 10-bit, etc.), then open 'D:\yanganguo\myproject\demo\ffmpeg-windows-build-helpers\native_build\windows\ffmpeg_local_builds\cygwin_local_install\cygwin.bat' (which sets up the path for you). Then cd to 'D:\yanganguo\myproject\demo\ffmpeg-windows-build-helpers\native_build\windows\ffmpeg_local_builds' and run the script manually yourself with -h, like:
$ cd /cygdrive/c/.../ffmpeg_local_builds
$ ./cross_compile_ffmpeg.sh -h
Press any key to continue . . .

**Comment by anguoyang** [comment]
another similar question, how to disable amr in option? I actually dont need amr codec

**Comment by anguoyang** [comment]
I have tried --enable-libopencore-amrnb, it didnt work:
Error, unknown option: --enable-libopencore-amrnb

**Comment by rdp** [comment]
Disk space?

On Thursday, March 15, 2018, Jacky Yang <notifications@github.com> wrote:
> I have tried --enable-libopencore-amrnb, it didnt work:
> Error, unknown option: --enable-libopencore-amrnb
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/mg1njU9RaHZF18seoU8JSNNUUwsJ05rzZdarBzt97IBzalvIUshuU1KznaM3rHaboy_Z2emF-EBScep_xKYcujXQqrrsa3jwiDgijJDWXOOQ-L-v8T5WY52g1RX6SvQAfWSq9Jydu0qhZSDMzalgfgAWbw7n_Q=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0B8CuwrKOjjMYFayebKYY5d8MsEpks5texIygaJpZM4StGNp.gif>

**Comment by anguoyang** [comment]
@rdp my disk still have 1.6T free:)

**Comment by anguoyang** [comment]
I delete the option in build script, now it is OK, but with other errors, and I have to delete it one by one

**Comment by rdp** [comment]
any resolution?

**Comment by anguoyang** [comment]
@rdp I have solved all other errors after delete unused options, thank you

**Comment by rdp** [comment]
which option did you delete do you remember?

**Comment by danilogr** [comment]
Also having the same problem here. Please, let me know if you have any specific instructions on how to proceed here.

**Comment by rdp** [comment]
maybe "run as administrator" ? https://stackoverflow.com/questions/4479615/permission-denied-using-cygwin-in-windows but bash for windows is known to work...
