### ISSUE TITLE
decoding with h264_qsv is not correct

### ISSUE THREAD

**Issue by anguoyang** [rdp/ffmpeg-windows-build-helpers#314]
This question maybe not related with building, but I DO NOT know where to find the answer.
I compiled ffmpeg using the script successfully with intel quick sync support, and tried to decode it with "h264_qsv" , there is no error but the decoded image is not correct(only colorful stripes) , but if I use standard h264,it worked perfect, could anyone help me? thank you

**Comment by anguoyang** [comment]
I have debugged into the source code, the decoder status is correct, the only problem is the decoded image, as I have used ffmpeg for years, there is no problem on yuv-->rgb or drawing

**Comment by rdp** [comment]
possibly ask on ffmpeg-user mailing list...

**Comment by rdp** [comment]
Ever figure this out, for followers?
