### ISSUE TITLE
Tesseract requires autoconf-archive

### ISSUE THREAD

**Issue by djbacklund** [rdp/ffmpeg-windows-build-helpers#315]
Tesseract configure error on Ubuntu Artful in

./configure: line 4229: syntax error near unexpected token `-mavx,'
./configure: line 4229: `AX_CHECK_COMPILE_FLAG(-mavx, avx=1, avx=0)'

According to [Tesseract Issue 647](https://github.com/tesseract-ocr/tesseract/issues/647), autoconf-archive is now a prerequisite. After installing autoconf-archive, the configure and build works as expected.

You may want to add it to the prerequisite list at the top of your script.

**Comment by rdp** [comment]
Yeah I attempted to in this commit: https://github.com/rdp/ffmpeg-windows-build-helpers/commit/92619952cbaa1e1eb4eb9b312cc706ba993c98d0 though I wasn't sure of a better way or not...

**Comment by hexaltation** [comment]
Hello,
with commit  887a9d3 version on Ubuntu 16.04

`
./configure: line 4220: syntax error near unexpected token `-mavx,'
./configure: line 4220: `AX_CHECK_COMPILE_FLAG(-mavx, avx=true, avx=false)'
`
May we compile autoconf-archive from fresh sources as suggested in https://github.com/tesseract-ocr/tesseract/issues/777#issuecomment-361896845 instead of get it from aptitude, because it appears to be an old one.

`
sudo apt-get install autoconf-archive
autoconf-archive is already the newest version (20150925-1).
`

**Comment by rdp** [comment]
does nuking the tesseract folder so it has to run autogen again help?

On Thu, May 24, 2018 at 10:34 AM, Grégoire Cutzach <notifications@github.com

**Comment by Warblefly** [comment]
On Sat, Jun 2, 2018 at 2:25 PM taroxd <notifications@github.com> wrote:

> Fedora requires autoconf-archive, too.
>
> After dnf install autoconf-archive, I have successfully built tesseract
> but ffmpeg failed with tesseract not found using pkg-config. I am
> currently doing a clean build and looking into this issue
> ​.
>
> ​I suspect this commit to tesseract:

https://github.com/tesseract-ocr/tesseract/commit/e313ed1bb960b71e61b645f54373a694260985fb

**Comment by taroxd** [comment]
Thanks! I tried https://github.com/tesseract-ocr/tesseract/commit/f227f84231c6df8f596b19ad37a8bab80bd5ffac and it seems to work now.

**Comment by rdp** [comment]
so this is fixed now, via a change upstream?

**Comment by taroxd** [comment]
Yes. But I have no idea why this occurs.

**Comment by Warblefly** [comment]
On Sun, Jun 3, 2018 at 9:22 AM taroxd <notifications@github.com> wrote:

> Yes. But I have no idea why this occurs
>
The latest Git version of Tesseract hasn't removed this problem, so I'm
still using tree a2e72f258a3bd6811cae226a01802d891407409f

Odd.
J
​

**Comment by rdp** [comment]
OK pinned it, let me know if I screwed anything up...

**Comment by taroxd** [comment]
The latest version (git master) of tesseract seems to be fine now.

**Comment by rdp** [comment]
It still requires autoconf-archive yes? :)

**Comment by taroxd** [comment]
Probably. This should be added into the dependency list of Fedora (or CentOS?)

**Comment by crazybytes** [comment]
Thanks.
