### ISSUE TITLE
Can you support AV1(libaom)?

### ISSUE THREAD

**Issue by kgp700** [rdp/ffmpeg-windows-build-helpers#317]
Hi
FFmpeg now support libaom(AV1) with external library
https://www.ffmpeg.org/general.html#Alliance-for-Open-Media-libaom

Can you add to your build script ?

**Comment by copyliu** [comment]
I was created a pull request #316 , you can pull it if you want the av1 support

**Comment by kgp700** [comment]
OK 
Great thanks :)
I will try it.

**Comment by kgp700** [comment]
Nice working
Thanks:)
