### ISSUE TITLE
Support for multi-depth x264

### ISSUE THREAD

**Issue by Asterchades** [rdp/ffmpeg-windows-build-helpers#318]
Due to a number of mid-process crashes I've been attempting to acquire a new ffMPEG build in case whatever has been causing the problem has been remedied.  While looking around before building it myself to save some time, I discovered that - as of somewhere in or around December last year - x264 can be built in such a way that it supports both 8- and 10-bit encoding at the same time, as demonstrated by the official ffMPEG builds (which lack suitable VBR AAC support).

From what I can tell (and I'm open to being wrong as always) this is achieved basically by setting the "--bit-depth" compilation flag to be "all" instead of 8 or 10, which also appears to be the new default.  Left to its own devices your script will still compile an 8-bit-only x264 encoder, where forcing it to use the "all" setting on line 1,349 still results in a 10-bit-only x264 encoder (or a whole host of errors if you still have an existing 10-bit x264 compiled already).

As such, I can only assume that there are more parts to your script (or to the entire process) which are unnecessarily limiting the available pixel formats.  I cannot find them myself as I lack the necessary understanding of the inner workings of your script.  I understand that 8-bit only is still offered as a compatibility setting, but this seems like a better long-term option to strict 10-bit only.

**Comment by Reino17** [comment]
It's all because of:
https://github.com/rdp/ffmpeg-windows-build-helpers/blob/0cdc9d4f3f5262fd1bd24bb1bc78836cc54289d8/cross_compile_ffmpeg.sh#L1397
[8c2974255b01728](https://git.videolan.org/?p=x264.git;a=commit;h=8c2974255b01728d4eda2434cc1997c4a3ca5eff) is from 21-05-2017, while [Unify 8-bit and 10-bit CLI and libraries](https://git.videolan.org/?p=x264.git;a=commit;h=71ed44c7312438fac7c5c5301e45522e57127db4) is from 24-12-2017.

**Comment by Asterchades** [comment]
Well, that makes sense.  It's probably an obvious change required, but how would someone who's not hugely familiar with the whole Git/Linux deal go about changing that so it correctly grabs a more recent version for testing purposes?

**Comment by Asterchades** [comment]
I can appreciate your preference to waiting for the project lead to respond.  Cheers for the interim option, though - not that I can fully appreciate the differences (good or bad) between having LibAV involved or not.  It's enough to play around with for now which is what I was after.

Cheers also for the Cygwin tip, but I've given up trying to use Cygwin or WSL for compiling.  17 failed builds in WSL and a further 8 in Cygwin put me off it.  I've taken to running Ubuntu under VirtualBox - even with only half my cores and RAM it builds substantially faster and in only one try.

**Comment by Reino17** [comment]
I didn't know you're compiling on Ubuntu, but obviously in your situation a recent nasm version is required as well.

**Comment by Asterchades** [comment]
There doesn't appear to be a special command line for it, beyond setting the appropriate pixel format for the output.  When checking the encoder itself (ffmpeg -h encoder=libx264) either from the build provided by the ffMPEG website or using your script with modification it lists the following:

Supported pixel formats: yuv420p yuvj420p yuv422p yuvj422p yuv444p yuvj444p nv12 nv16 nv21 yuv420p10le yuv422p10le yuv444p10le nv20le

I suspect there's just some kind of internal logic that picks up whether you're using an 8-bit or 10-bit format, switching between the two pipelines as appropriate.  It's definitely capable of outputting either, though, based on your requested format, and it automatically adjusts the profile to match.  Test encodes seem to report and play back correctly both ways as well.

**Comment by schmidthubert** [comment]
ffmpeg.exe -h full > fullhelp_ffmpeg.txt then check section "libx264 AVOptions" there's "-x264opts(old switch)/-x264-params" where you pass your params to the x264 lib. So next is x264.exe -fullhelp > fullhelp_x264.txt where you find "--output-depth". Check [here](https://trac.ffmpeg.org/wiki/Encode/H.264) as well, good luck ... :+1:

**Comment by Reino17** [comment]
As Asterchades already points out:
```
ffmpeg.exe -hide_banner -h encoder=libx264 | find "formats"
    Supported pixel formats: yuv420p yuvj420p yuv422p yuvj422p yuv444p yuvj444p nv12 nv16 nv21 yuv420p10le yuv422p10le yuv444p10le nv20le
```
So therefor the following should work:
`ffmpeg.exe -i <input> -pix_fmt yuv420p10le -c:v libx264 <output>`

**Comment by schmidthubert** [comment]
Sure, "bare minimum" "just works" as well ... :smirk:

**Comment by schmidthubert** [comment]
Here the opposite of simple, just some examples(presets are for very good source only, but mostly useless otherwise):
https://lists.ffmpeg.org/pipermail/ffmpeg-user/2016-March/031225.html
https://superuser.com/questions/685647/create-an-ffmpeg-preset-file-from-x264-options
https://blog.archive.org/2013/02/09/new-mp4-h-264-derivative-technique-simpler-and-easy/
:+1: 
Obviously these are all older posts so there's no bitdepth setting used anywhere.

**Comment by Reino17** [comment]
Roger asks how to set the bit-depth in FFmpeg. Therefor I really don't understand the point of your "opposite of simple" post.
You talk about x264's `--output-depth` parameter, but have you actually tested it yourself?
```
ffmpeg.exe -i <input> -c:v libx264 -x264-params output-depth=10 <output>
[...]
[libx264 @ 05af1340] Error parsing option 'output-depth = 10'.
```

**Comment by schmidthubert** [comment]
No sorry, was just browsing the helpfiles. I don't use x264 personally anymore, a waste of energy, nvenc only now if it comes to video even for 3D encodes. If something doesn't work, and especially ffmpeg params really suck at times with all the ""', ":"' and "=" +separators (double-)dashes and bla etc, then please ask on the ffmpeg user list how it should be done properly. It sometimes takes hours to work something out and get it working, especially under Windoze ... :unamused:

**Comment by Asterchades** [comment]
> So therefor the following should work:
`ffmpeg.exe -i <input> -pix_fmt yuv420p10le -c:v libx264 <output>`

It does.  At least, it does for me.  Without specifying a pixel format it defaults to yuv420p (8-bit), but it most definitely allows you to switch to a 10-bit format.  MediaInfo then picks it up accordingly (figure it's best testing with a different program) and I can play it back using Potplayer and the LAV filters.

**Comment by rdp** [comment]
hrm it's that nasm requirement that is a pain hmm...

**Comment by Asterchades** [comment]
There's probably something I've missed, but when I built it I didn't have to install anything special.  I basically installed Ubuntu 17.10 in VirtualBox, ran an update/upgrade, ran the script, ran the command which you provided for dependencies, update/upgrade again and then it compiled both with and without modification.

Whether nasm was installed by that process I've no idea.  But I didn't specifically set out to install it.

**Comment by rdp** [comment]
16.04 seems to not have a new enough nasm, and 18.04 hasn't been released
yet.  I might be able to build a "local nasm" or some odd...why not right?
:)

**Comment by Asterchades** [comment]
Guessing by that it means my using 17.10 is why I have nasm.

If I'm reading correctly, 18.04 is due to release on the 26th - 3 weeks' time.  Unless you're expecting people to stick to 16.04 it may not be worth adding a local build.  But I guess it can't hurt anything either way.

**Comment by Reino17** [comment]
I'm not on Ubuntu, so I can't help you with that. I'm still on WinXP and although the latest Cygwin does have a new enough nasm for libx264, it doesn't support WinXP anymore, so I compiled it myself:
```sh
build_nasm() {
  download_and_unpack_file http://www.nasm.us/pub/nasm/releasebuilds/2.13.03/nasm-2.13.03.tar.xz
  cd nasm-2.13.03
    if [[ ! -f Makefile.in.bak ]]; then # Library only.
      sed -i.bak "/man1/d" Makefile.in
    fi
    do_configure "--prefix=/usr"
    # No '--prefix=$mingw_w64_x86_64_prefix', because NASM has to be built with Cygwin's GCC. Otherwise it can't read Cygwin paths and you'd get errors like "nasm: fatal: unable to open output file `/cygdrive/c/DOCUME~1/Admin/LOCALS~1/Temp/ffconf.Ld8518el/test.o'" while configuring FFmpeg for instance.
    # 'nasm.exe' and 'ndisasm.exe' will be installed in '/usr/bin' (Cygwin's bin map)
    do_make
    do_strip . --strip-unneeded
    do_make_install
  cd ..
}
```
Soon I'll push a lot of changes/updates to my fork.

**Comment by rdp** [comment]
Not sure where to go with this one, reopen if desired :)

**Comment by Krautmaster** [comment]
I use the custom FFMpeg to prepare my library to be Streamed with Emby or Plex. Sadly neither chrome or eg amazon stick can deal well with 10 but HEVC material, only 8 bit x264 is compatible in almost any device to be played directly without transcode. Using ur standard build script seem only to support 10 bit and not 8+10 in parallel which other FFMpeg exe do. What do I need to change to enable my FFMpeg to be capable to do both? Thx

**Comment by rdp** [comment]
I think modify it to not specify a bit?  I will look at it "eventually"
funding always welcome :)

**Comment by Krautmaster** [comment]
Haha that's an idea, for now I force 10 bit from early days (nightly build server). Will look into it as well. Guess it's default now that 10 Bit thing, but I'm currently not sure what platforms are fully capable of HEVC 10 bit, what 8 bit or what need to switch over to x264. Thanks for ur response and efford anyway. :)

**Comment by Krautmaster** [comment]
It's fine. I guess u can get rid of that high bit depth option or?

**Comment by rdp** [comment]
I think x265 still uses it or something...maybe...dunno :)

**Comment by Krautmaster** [comment]
Hm yeah, seems like. The 10 bit Pixel formats seems to be missing now but if I compile with high bit depth I can't set yuv420p to do eg 4.0 main x265 (eg for some older fire Tvs which only support main 4.0)

**Comment by rdp** [comment]
OK I think I got it set to bit depth "all" now, enjoy.

**Comment by Krautmaster** [comment]
oh that sounds good. I guess i need to compile with the option high bit depth = 1

**Comment by rdp** [comment]
x264 ignores the high bit depth setting now and just does both :)
