### ISSUE TITLE
cross_compile_ffmpeg.sh:  50: cross_compile_ffmpeg.sh: Syntax Error: "(" unexpected (expecting "}")

### ISSUE THREAD

**Issue by CV01HatsuneASD** [rdp/ffmpeg-windows-build-helpers#319]
I tried to close fix it by closing the function with "}" in a new line before line 50, but it didn't. Can you figure out what causes this kind of issue?

**Comment by rdp** [comment]
what os?

**Comment by thejustsoul** [comment]
@CV01HatsuneASD try it any way:
`dos2unix cross_compile_ffmpeg.sh`

**Comment by rdp** [comment]
closing no response, feel free to reopen is problem is still present.
