### ISSUE TITLE
Decklink SDK Update

### ISSUE THREAD

**Issue by smoothstreams** [rdp/ffmpeg-windows-build-helpers#325]
Hi,

Could I bother you to update the Decklink files in patches from latest SDK ?
They are on there if you complete the form (I filled out bunch of fake info and was able to download from link)
https://www.blackmagicdesign.com/support/family/capture-and-playback

Thanks again for all your hard work and continuing to keep this project updated.

**Comment by rdp** [comment]
does it not work with the current?

**Comment by rdp** [comment]
pull requests welcome :)

**Comment by rdp** [comment]
OK I may have found an easy place to get the headers, I still don't know
how/where to download

DeckLinkAPI.idl LOL. See also
https://superuser.com/questions/1259866/ffmpeg-decklink-windows/1260130#1260130
 https://notabug.org/RiCON/decklink-headers
