### ISSUE TITLE
ERROR: aom >= 1.0.0 not found using pkg-config

### ISSUE THREAD

**Issue by amol996** [rdp/ffmpeg-windows-build-helpers#331]
Hi All
Im trying to compile FFmpeg for ubuntu 14.x using https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu this link but i am getting following error 

*******************************************************************************************************************
ffmpeg/libpostproc/Makefile
ffmpeg/libpostproc/libpostproc.v
ffmpeg/libpostproc/postprocess_altivec_template.c
ffmpeg/libpostproc/postprocess_internal.h
ffmpeg/libpostproc/postprocess.c
ffmpeg/libpostproc/postprocess_template.c
ffmpeg/libpostproc/postprocess.h
ffmpeg/libpostproc/postprocres.rc
ffmpeg/libpostproc/version.h
ERROR: aom >= 1.0.0 not found using pkg-config                  

*************************ERROR*********************

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

**Comment by rdp** [comment]
this repo is for "windows builds" did you build libaom?

**Comment by AndCycle** [comment]
@rdp this fixed by https://github.com/rdp/ffmpeg-windows-build-helpers/pull/330

**Comment by rdp** [comment]
OK assuming fixed for now, please reopen if required.

**Comment by amol996** [comment]
Hi this is on Ubuntu linux 14.
Config.log logs are attached here..


[config.log](https://github.com/rdp/ffmpeg-windows-build-helpers/files/2200857/config.log)

**Comment by rdp** [comment]
did you try with git master?
