### ISSUE TITLE
Frequent build fails with "Reversed (or previously applied) patch detected!  Assume -R?"

### ISSUE THREAD

**Issue by nschlia** [rdp/ffmpeg-windows-build-helpers#336]
Build fails now every few days after asking to apply a patch anyway, then auto-answering "no".

> 09:12:27 applying patch vpx_160_semaphore.patch
> 09:12:27 patching file vp8/common/threading.h
> 09:12:27 Reversed (or previously applied) patch detected!  Assume -R? [n] 
> 09:12:27 Apply anyway? [n] 
> 09:12:27 Skipping patch.
> 09:12:27 1 out of 1 hunk ignored -- saving rejects to file vp8/common/threading.h.rej
> 09:12:27 Build step 'Shell ausführen' marked build as failure
> 09:12:27 Sending e-mails to: nschlia@oblivion-software.de
> 09:12:27 Finished: FAILURE

When run manually and answering "y" the build runs through:

> applying patch frei0r_load-shared-libraries-dynamically.diff
> patching file libavfilter/vf_frei0r.c
> Reversed (or previously applied) patch detected!  Assume -R? [n] y

Wouldn't it be possible two answer "y" in such cases to avoid automatic build fails?

**Comment by AndCycle** [comment]
that usually means some ambiguity during the source patch phase,
force a clean git checkout should do the job rather than blindly double click "Y",

you can identify that line of code by yourself and provide a PR to fix it.

**Comment by rdp** [comment]
it prompts for that every time?

**Comment by AndCycle** [comment]
@rdp I just tested head version, it prompt with second rebuild, need to sanitize the git checkout/patch procedure.

**Comment by rdp** [comment]
OK I think I know what it is, could you try nuking or renaming sandbox first?

**Comment by rdp** [comment]
OK I...think...I may have fixed it though it wasn't clear how or when it got broken either.  Though I did mess with patch logic last week.  Anyway give it a gander.  Cheers!

**Comment by nschlia** [comment]
7 hours after you've submitted the fix my daily builds went through without issues. Seems to be fixed. I close this. Hope the problem does not turn up again :).
