### ISSUE TITLE
I've been trying to build this for a week but...

### ISSUE THREAD

**Issue by bucker00** [rdp/ffmpeg-windows-build-helpers#337]
I get the following message:

Found no assembler
Minimum version is nasm-2.13
 If you really want to compile without asm, configure with --disable-asm.

I've tried everything I know how to do, got nasm-2.13.1 and put it where the rest of the files go.  Dunno.

**Comment by rdp** [comment]
you need a newer version of "nasm" on your system, recommend building one from source...

**Comment by rdp** [comment]
comment here if still problem, cheers!
