### ISSUE TITLE
libx264 license was changed?

### ISSUE THREAD

**Issue by kgp700** [rdp/ffmpeg-windows-build-helpers#338]
some license changed for libx264?
I can't understand why recently change commit for libx264 

https://github.com/rdp/ffmpeg-windows-build-helpers/commit/e4f68bd77cfa220f06f30e476803cca3120477c1

local licensed_gpl=n # lgpl build with libx264 included for those with "commercial" license :)
    if [[ $licensed_gpl == 'y' ]]; then
      apply_patch file://$patch_dir/x264_non_gpl.diff -p1
      config_options+=" --enable-libx264"
    fi 

It means for commercial use, build with LGPL. for personal use, build with GPL?
sorry. my english not good. so, I'm little bit confusing...

**Comment by rdp** [comment]
it's the same.  If you "buy" a special libx264 license then you can use it
in distributable software without having to open source your project.
Cheers!

**Comment by kgp700** [comment]
OK. thanks :)
