### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by Socke81** [rdp/ffmpeg-windows-build-helpers#345]
Hello, I just downloaded this tool. I started build_locally_with_various_option_prompts.bat. Win64 only selected. Unfortunately, something seems to be going wrong. On Windows 10 64. AMD Ryzen. 

https://pastebin.com/WULCtYyn

**Comment by rdp** [comment]
OK appears to be a "cygwin libtool" weirdness, reported here: https://github.com/rdp/ffmpeg-windows-build-helpers/issues/292 and not yet fixed
