### ISSUE TITLE
Build of libavcodec fails

### ISSUE THREAD

**Issue by nschlia** [rdp/ffmpeg-windows-build-helpers#346]
The build fails for five days now, there is a syntax error in libavcodec/libfdk-aacenc.c. I tried everything, including deleting the whole sandbox, but no dice...

Build command:

./cross_compile_ffmpeg.sh --high-bitdepth=y --gcc-cpu-count=4 --disable-nonfree=n --sandbox-ok=y --compiler-flavors=multi --build-ffmpeg-static=n --build-ffmpeg-shared=y --build-amd-amf=y 

and with --high-bitdepth=n. Also removed --build-amd-amf=y (don't know anymore why I put that here) and --build-gpl=n. Same result.

```
CC        libavcodec/lclenc.o
CC        libavcodec/libaomdec.o
CC        libavcodec/libaomenc.o
CC        libavcodec/libfdk-aacdec.o
CC        libavcodec/libfdk-aacenc.o
CC        libavcodec/libgsmdec.o
libavcodec/libfdk-aacenc.c: In function 'aac_encode_init':
libavcodec/libfdk-aacenc.c:293:35: error: 'AACENC_InfoStruct {aka struct <anonymous>}' has no member named 'encoderDelay'; did you mean 'nDelay'?
     avctx->initial_padding = info.encoderDelay;
                                   ^~~~~~~~~~~~
                                   nDelay
ffbuild/common.mak:60: die Regel für Ziel „libavcodec/libfdk-aacenc.o“ scheiterte
make: *** [libavcodec/libfdk-aacenc.o] Fehler 1
```

**Comment by Reino17** [comment]
See [this FFmpeg mailinglist message](https://ffmpeg.org/pipermail/ffmpeg-user/2018-September/041129.html).

**Comment by nschlia** [comment]
Thanks for the info. Did not find that one.

**Comment by hydra3333** [comment]
Or, do your own patches and a sed like over in here
https://github.com/jb-alvarado/media-autobuild_suite/issues/911
and 
https://github.com/jb-alvarado/media-autobuild_suite/blob/master/build/media-suite_compile.sh (search for lensfun to see the patches)

**Comment by hydra3333** [comment]
This patch to ffmpeg seems to make the build error go away
```
--- a/libavcodec/libfdk-aacenc.c	2018-09-05 22:28:50.071703112 +0930
+++ b/libavcodec/libfdk-aacenc.c	2018-09-05 22:30:05.183907088 +0930
@@ -290,7 +290,11 @@
     }
 
     avctx->frame_size = info.frameLength;
+#if AACENCODER_LIB_VL0 < 4
     avctx->initial_padding = info.encoderDelay;
+#else
+    avctx->initial_padding = info.nDelay;
+#endif
     ff_af_queue_init(avctx, &s->afq);
 
     if (avctx->flags & AV_CODEC_FLAG_GLOBAL_HEADER) {
```

Although I'm not sure if the ffmpwg.exe produces valid aac output ...

**Comment by schmidthubert** [comment]
I don't see any (other than what you read too) complaints about crackling. Otherwise I would have not [posted that](https://github.com/jb-alvarado/media-autobuild_suite/issues/907#issuecomment-418697221). They should go to the fdk-aac authors and complain there. I don't see any tickets [over there](https://github.com/mstorsjo/fdk-aac/issues) either regarding crackling? I use fdk on a regularly basis to convert some doku stuff, with params like this:

`ffmpeg .... -c:a libfdk_aac -b:a 128k -profile:a aac_he_v2 -ac 2 ...`

And there isn't any crackling as someone said somewhere, I've just checked again. Anyway, "full patch" (if you want to call it like that) is also available if needed:
https://github.com/mstorsjo/fdk-aac/issues/93 :+1:

**Comment by hydra3333** [comment]
OK, nice, thank you @schmidthubert  I'll try that full patch instead of the one you had originally posted and see what happens.

**Comment by nschlia** [comment]
I've applied the patch [https://github.com/mstorsjo/fdk-aac/issues/93](url) as suggested by schmidthubert, now my builds work again. I also tested an aac file using

`ffmpeg .... -c:a libfdk_aac -b:a 128k -profile:a aac_he_v2 -ac 2 ...`

and it was fine (no clicks or whatever). The patch seems to work for me.

**Comment by schmidthubert** [comment]
There are more fdk changes but there's nothing on the ffmpeg devel list and nothing in patchwork, nothing recent from Martin Storsjö at all there. Maybe he just wants to have something more stable/bug free first, after all this is version 2.0.0 so wait a bit and it will come. Until then do manual edits ... https://git.libav.org/?p=libav.git;a=shortlog;h=HEAD

**Comment by nschlia** [comment]
Thanks! For now I can live with the patch.

**Comment by nschlia** [comment]
Thanks all for your efforts!

**Comment by rdp** [comment]
As a note one shouldn't  even really "need" fdk aac anymore, with the
native AAC encoder being pretty good these days...

**Comment by hydra3333** [comment]
Thank you for that information.

**Comment by rdp** [comment]
OK if you feel the built in is "lacking" then feel free to adjust this web page: https://trac.ffmpeg.org/wiki/Encode/HighQualityAudio OK was finally able to repro the failure, working around it for now...

**Comment by schmidthubert** [comment]
It's all [fixed now](https://git.ffmpeg.org/gitweb/ffmpeg.git?a=search&h=HEAD&st=commit&s=fdk), so you can revert that ... :+1:
