### ISSUE TITLE
 libmfx not found after 2c23180

### ISSUE THREAD

**Issue by AndCycle** [rdp/ffmpeg-windows-build-helpers#347]
simple report, haven't dive into the issue

```
$ uname -a
Linux bacztwo 4.14.40-gentoo 
$ ./cross_compile_ffmpeg.sh --disable-nonfree=n --compiler-flavors=win64
```

```
applying patch frei0r_load-shared-libraries-dynamically.diff
patching file libavfilter/vf_frei0r.c
Hunk #2 succeeded at 244 (offset 5 lines).
configuring ffmpeg_git_with_fdk_aac [too long, cutoff]
ERROR: libmfx not found
```

remove the
```
unset PKG_CONFIG_LIBDIR
```
then rebuild libmfx will make configure happy

**Comment by rdp** [comment]
Ffbuild/config.log file please?

On Monday, September 17, 2018, AndCycle <notifications@github.com> wrote:
> simple report, haven't dive into the issue
>
> $ uname -a
> Linux bacztwo 4.14.40-gentoo
> $ ./cross_compile_ffmpeg.sh --disable-nonfree=n --compiler-flavors=win64
>
> applying patch frei0r_load-shared-libraries-dynamically.diff
> patching file libavfilter/vf_frei0r.c
> Hunk #2 succeeded at 244 (offset 5 lines).
> configuring ffmpeg_git_with_fdk_aac [too long, cutoff]
> ERROR: libmfx not found
>
> remove the
>
> unset PKG_CONFIG_LIBDIR
>
> and
>
> export PKG_CONFIG_LIBDIR=
>
> will make configure happy
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/NSBQt4msCzQchzmadm-DW7w_nbzn00sYHl-AJ3Wq1giYY3knm_mEi6YAguXWIURxUKdtekZjSX7jO3W-GnyGVPfnqgf-Zx_IZ0Vm9YGJW-pQqBVw72yA6UdNgk1ZvH95bVKU_pp2G9aE3wKN0IjjkIc5TbqbBg=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0EbHvrnlr2mAqYYe6xfgt6jUnhqXks5ub5ULgaJpZM4Wrzwp.gif>

**Comment by AndCycle** [comment]
oops, missed that

https://pastebin.com/g4NAt9Jj

**Comment by AndCycle** [comment]
it do exist,
```
$ file  ./sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libmfx.a
./sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libmfx.a: current ar archive`
```

here is the pkgconfig
```
$ cat ./sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig/libmfx.pc
prefix=/home/andcycle/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libmfx
Description: Intel Media SDK Dispatched static library
Version: 1.23
Libs: -L${libdir} -lmfx -lstdc++  -lva-drm -lva -lva-x11 -lva
Libs.private:
Cflags: -I${includedir}

```

**Comment by rdp** [comment]
Maybe is corrupted try nuking sandbox and try again

On Wednesday, September 19, 2018, AndCycle <notifications@github.com> wrote:
> it do exist,
>
> $ file
./sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libmfx.a
>
./sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libmfx.a:
current ar archive`
>
> here is the pkgconfig
>
> $ cat
./sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig/libmfx.pc
>
prefix=/home/andcycle/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
> exec_prefix=${prefix}
> libdir=${exec_prefix}/lib
> includedir=${prefix}/include
>
> Name: libmfx
> Description: Intel Media SDK Dispatched static library
> Version: 1.23
> Libs: -L${libdir} -lmfx -lstdc++ -lva-drm -lva -lva-x11 -lva
> Libs.private:
> Cflags: -I${includedir}
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/LjPLG8m-pw3a5i0wo40lDakuRrgkZbd39q9c7Rm5IDemZ7d4FYXJYhAf_H4DDH7_fBKhYcTkEbJ_B8pxdLYk2Z5nAeoF9C2H2BkOg16A5n1I1xp9IwNehS7GzjtZC6gElpg3EN4IMqoA4YRyEgKjbSEIXuW9KA=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0PHBT9aa4mAAzcbFRY-YIfgHdxK0ks5ucx_JgaJpZM4Wrzwp.gif>

**Comment by AndCycle** [comment]
I tried that three times, very reproducible, 

the pkgconfig says libmfx depend on libva which is very suspicious.

**Comment by rdp** [comment]
This is a bit confusing here...
I don't see this line:

unset PKG_CONFIG_LIBDIR

but the whole purpose of it was to protect you from this exact problem
(local libs leaking in...hmm..._

somebody send me a patch of what fixed it for them maybe?

**Comment by AndCycle** [comment]
it's here

https://github.com/rdp/ffmpeg-windows-build-helpers/blob/ac65c9cc9cc12b9322b26dff1ea366f78044ad97/cross_compile_ffmpeg.sh#L662

**Comment by rdp** [comment]
OK I think I see where I headed south there, thanks for the report
