### ISSUE TITLE
Execution Failure on Windows Due to Missing libwinpthread-1.dll

### ISSUE THREAD

**Issue by barndawgie** [rdp/ffmpeg-windows-build-helpers#348]
I built ffmpeg on a Macbook running High Sierra using the stock quick_cross_compile_ffmpeg_fdk_aac_and_x264_using_packaged_mingw64.sh. I installed mingw and other dependencies using brew.

Build succeeds, generating ffmpeg and ffprobe binaries, but ffmpeg fails to execute on Windows saying "The code execution cannot proceed because libwinpthread-1.dll was not found."

![Failure Message](https://user-images.githubusercontent.com/11252867/45921686-eefc6b00-be6e-11e8-8fd0-954cd13a0268.PNG)

**Comment by rdp** [comment]
That's probably an artifact of using the homebrew mingw gcc version. You'll
have to do it the "non quick" way to avoid that...or tell homebrew to tweak
their mingw gcc build :)

**Comment by barndawgie** [comment]
That was a big help, thanks! I was able to solve it by re-brewing mingw with the "--without-posix" flag.
