### ISSUE TITLE
Unable to build natively under windows 10 due to libbs2b-3.0.1 issues

### ISSUE THREAD

**Issue by thyAnger** [rdp/ffmpeg-windows-build-helpers#351]
Hi,

I am trying to build ffmpeg for windows with "build_locally_with_various_option_prompts.bat". At some point I get

> ../libtool: line 975: X--tag=CC: command not found
../libtool: line 975: X--tag=CXX: command not found
../libtool: line 1008: libtool: ignoring unknown tag : command not found
../libtool: line 975: X--mode=compile: command not found
../libtool: line 1008: libtool: ignoring unknown tag : command not found
../libtool: line 975: X--mode=compile: command not found
../libtool: line 1142: *** Warning: inferring the mode of operation is deprecated.: command not found
../libtool: line 1143: *** Future versions of Libtool will require --mode=MODE be specified.: command not found
../libtool: line 1142: *** Warning: inferring the mode of operation is deprecated.: command not found
../libtool: line 1286: Xi686-w64-mingw32-gcc: command not found
../libtool: line 1143: *** Future versions of Libtool will require --mode=MODE be specified.: command not found
../libtool: line 1286: Xi686-w64-mingw32-g++: command not found
../libtool: line 1286: X-DPACKAGE_NAME="libbs2b": command not found
../libtool: line 1286: X-DPACKAGE_NAME="libbs2b": command not found
../libtool: line 1286: X-DPACKAGE_TARNAME="libbs2b": command not found
../libtool: line 1286: X-DPACKAGE_TARNAME="libbs2b": command not found
../libtool: line 1286: X-DPACKAGE_VERSION="3.1.0": command not found
../libtool: line 1286: X-DPACKAGE_VERSION="3.1.0": command not found
../libtool: line 1286: X-DPACKAGE_STRING="libbs2b 3.1.0": command not found
../libtool: line 1286: X-DPACKAGE_STRING="libbs2b 3.1.0": command not found
../libtool: line 1286: X-DPACKAGE_BUGREPORT="boris_mikhaylov@users.sourceforge.net": command not found
../libtool: line 1286: X-DPACKAGE_BUGREPORT="boris_mikhaylov@users.sourceforge.net": command not found
../libtool: line 1286: X-DPACKAGE_URL="": command not found
../libtool: line 1286: X-DPACKAGE_URL="": command not found
../libtool: line 1286: X-DPACKAGE="libbs2b": command not found
../libtool: line 1286: X-DPACKAGE="libbs2b": command not found
../libtool: line 1286: X-DVERSION="3.1.0": command not found
../libtool: line 1286: X-DVERSION="3.1.0": command not found
../libtool: line 1286: X-DSTDC_HEADERS=1: command not found
../libtool: line 1286: X-DSTDC_HEADERS=1: command not found
../libtool: line 1286: X-DHAVE_SYS_TYPES_H=1: command not found
../libtool: line 1286: X-DHAVE_SYS_TYPES_H=1: command not found
../libtool: line 1286: X-DHAVE_SYS_STAT_H=1: command not found
../libtool: line 1286: X-DHAVE_SYS_STAT_H=1: command not found
../libtool: line 1286: X-DHAVE_STDLIB_H=1: command not found
../libtool: line 1286: X-DHAVE_STDLIB_H=1: command not found
../libtool: line 1286: X-DHAVE_STRING_H=1: command not found
../libtool: line 1286: X-DHAVE_STRING_H=1: command not found
../libtool: line 1286: X-DHAVE_MEMORY_H=1: command not found
../libtool: line 1286: X-DHAVE_MEMORY_H=1: command not found
../libtool: line 1286: X-DHAVE_STRINGS_H=1: command not found
../libtool: line 1286: X-DHAVE_STRINGS_H=1: command not found
../libtool: line 1286: X-DHAVE_INTTYPES_H=1: command not found
../libtool: line 1286: X-DHAVE_INTTYPES_H=1: command not found
../libtool: line 1286: X-DHAVE_STDINT_H=1: command not found
../libtool: line 1286: X-DHAVE_STDINT_H=1: command not found
../libtool: line 1286: X-DHAVE_UNISTD_H=1: command not found
../libtool: line 1286: X-DHAVE_UNISTD_H=1: command not found
../libtool: line 1286: X-DHAVE_DLFCN_H=1: command not found
../libtool: line 1286: X-DHAVE_DLFCN_H=1: command not found
../libtool: line 1286: X-DLT_OBJDIR=".libs/": No such file or directory
../libtool: line 1286: X-DLT_OBJDIR=".libs/": No such file or directory
../libtool: line 1286: X-DHAVE_FCNTL_H=1: command not found
../libtool: line 1286: X-DHAVE_MALLOC_H=1: command not found
../libtool: line 1286: X-DHAVE_FCNTL_H=1: command not found
../libtool: line 1286: X-DHAVE_MALLOC_H=1: command not found
../libtool: line 1286: X-DHAVE_STRING_H=1: command not found
../libtool: line 1286: X-DHAVE_STRING_H=1: command not found
../libtool: line 1286: X-DHAVE__BOOL=1: command not found
../libtool: line 1286: X-DHAVE__BOOL=1: command not found
../libtool: line 1286: X-DHAVE_STDBOOL_H=1: command not found
../libtool: line 1286: X-DHAVE_STDBOOL_H=1: command not found
../libtool: line 1286: X-DHAVE_STRRCHR=1: command not found
../libtool: line 1286: X-DHAVE_STRRCHR=1: command not found
../libtool: line 1286: X-I.: command not found
../libtool: line 1286: X-I.: command not found
../libtool: line 1286: X-g: command not found
../libtool: line 1286: X-mtune=generic: command not found
../libtool: line 1286: X-O2: command not found
../libtool: line 1286: X-O3: command not found
../libtool: line 1286: X-MT: command not found
../libtool: line 1286: X-MT: command not found
../libtool: line 1286: Xbs2bclass.lo: command not found
../libtool: line 1286: Xbs2b.lo: command not found
../libtool: line 1286: X-MD: command not found
../libtool: line 1286: X-MD: command not found
../libtool: line 1286: X-MP: command not found
../libtool: line 1286: X-MP: command not found
../libtool: line 1286: X-MF: command not found
../libtool: line 1286: X-MF: command not found
../libtool: line 1286: X.deps/bs2bclass.Tpo: No such file or directory
../libtool: line 1286: X.deps/bs2b.Tpo: No such file or directory
../libtool: line 1286: X-c: command not found
../libtool: line 1286: X-c: command not found
../libtool: line 1339: Xbs2bclass.lo: command not found
../libtool: line 1339: Xbs2b.lo: command not found
../libtool: line 1344: libtool: compile: cannot determine name of library object from `': command not found
make[1]: *** [Makefile:410: bs2bclass.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
../libtool: line 1344: libtool: compile: cannot determine name of library object from `': command not found
make[1]: *** [Makefile:386: bs2b.lo] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/xxx/Desktop/ffmpeg-windows-build-helpers-master/native_build/windows/
ffmpeg_local_builds/sandbox/win32/libbs2b-3.1.0/src'
make: *** [Makefile:287: all-recursive] Error 1

which is similar to what reported in [https://github.com/rdp/ffmpeg-windows-build-helpers/issues/292](url). Actually, the workaround for me does not work. I changed "--enable-libbs2b" to "--disable-libbs2b" in "cross_compile_ffmpeg.sh" but I can't find "build_ffmpeg_dependencies" in order to remove "build_libbs2b" nor I can find that string by searching within the "ffmpeg-windows-build-helpers-master" tree. Additionally, deleting "libbs2b-3.1.0" folder from the "sandbox" directly does not work because it is downloaded and built again.

Is there another workaround, or meybe something I missed?

Thank you.

**Comment by rdp** [comment]
remvoed lensfun for now, nuke your sandbox/winx/libbsb folder or sandbox
and try again there, or report the error here and we can look at it.

**Comment by thyAnger** [comment]
Still getting

> ../libtool: line 975: X--tag=CC: command not found
../libtool: line 975: X--tag=CXX: command not found
../libtool: line 1008: libtool: ignoring unknown tag : command not found
../libtool: line 1008: libtool: ignoring unknown tag : command not found
../libtool: line 975: X--mode=compile: command not found
../libtool: line 975: X--mode=compile: command not found
../libtool: line 1142: *** Warning: inferring the mode of operation is deprecated.: command not found
../libtool: line 1142: *** Warning: inferring the mode of operation is deprecated.: command not found
../libtool: line 1143: *** Future versions of Libtool will require --mode=MODE be specified.: command not found
../libtool: line 1143: *** Future versions of Libtool will require --mode=MODE be specified.: command not found
../libtool: line 1286: Xi686-w64-mingw32-gcc: command not found
../libtool: line 1286: Xi686-w64-mingw32-g++: command not found
../libtool: line 1286: X-DPACKAGE_NAME="libbs2b": command not found
../libtool: line 1286: X-DPACKAGE_NAME="libbs2b": command not found
../libtool: line 1286: X-DPACKAGE_TARNAME="libbs2b": command not found
../libtool: line 1286: X-DPACKAGE_TARNAME="libbs2b": command not found
../libtool: line 1286: X-DPACKAGE_VERSION="3.1.0": command not found
../libtool: line 1286: X-DPACKAGE_VERSION="3.1.0": command not found
../libtool: line 1286: X-DPACKAGE_STRING="libbs2b 3.1.0": command not found
../libtool: line 1286: X-DPACKAGE_STRING="libbs2b 3.1.0": command not found
../libtool: line 1286: X-DPACKAGE_BUGREPORT="boris_mikhaylov@users.sourceforge.net": command not found
../libtool: line 1286: X-DPACKAGE_BUGREPORT="boris_mikhaylov@users.sourceforge.net": command not found
../libtool: line 1286: X-DPACKAGE_URL="": command not found
../libtool: line 1286: X-DPACKAGE_URL="": command not found
../libtool: line 1286: X-DPACKAGE="libbs2b": command not found
../libtool: line 1286: X-DPACKAGE="libbs2b": command not found
../libtool: line 1286: X-DVERSION="3.1.0": command not found
../libtool: line 1286: X-DVERSION="3.1.0": command not found
../libtool: line 1286: X-DSTDC_HEADERS=1: command not found
../libtool: line 1286: X-DSTDC_HEADERS=1: command not found
../libtool: line 1286: X-DHAVE_SYS_TYPES_H=1: command not found
../libtool: line 1286: X-DHAVE_SYS_TYPES_H=1: command not found
../libtool: line 1286: X-DHAVE_SYS_STAT_H=1: command not found
../libtool: line 1286: X-DHAVE_SYS_STAT_H=1: command not found
../libtool: line 1286: X-DHAVE_STDLIB_H=1: command not found
../libtool: line 1286: X-DHAVE_STDLIB_H=1: command not found
../libtool: line 1286: X-DHAVE_STRING_H=1: command not found
../libtool: line 1286: X-DHAVE_STRING_H=1: command not found
../libtool: line 1286: X-DHAVE_MEMORY_H=1: command not found
../libtool: line 1286: X-DHAVE_MEMORY_H=1: command not found
../libtool: line 1286: X-DHAVE_STRINGS_H=1: command not found
../libtool: line 1286: X-DHAVE_STRINGS_H=1: command not found
../libtool: line 1286: X-DHAVE_INTTYPES_H=1: command not found
../libtool: line 1286: X-DHAVE_INTTYPES_H=1: command not found
../libtool: line 1286: X-DHAVE_STDINT_H=1: command not found
../libtool: line 1286: X-DHAVE_STDINT_H=1: command not found
../libtool: line 1286: X-DHAVE_UNISTD_H=1: command not found
../libtool: line 1286: X-DHAVE_UNISTD_H=1: command not found
../libtool: line 1286: X-DHAVE_DLFCN_H=1: command not found
../libtool: line 1286: X-DHAVE_DLFCN_H=1: command not found
../libtool: line 1286: X-DLT_OBJDIR=".libs/": No such file or directory
../libtool: line 1286: X-DLT_OBJDIR=".libs/": No such file or directory
../libtool: line 1286: X-DHAVE_FCNTL_H=1: command not found
../libtool: line 1286: X-DHAVE_FCNTL_H=1: command not found
../libtool: line 1286: X-DHAVE_MALLOC_H=1: command not found
../libtool: line 1286: X-DHAVE_MALLOC_H=1: command not found
../libtool: line 1286: X-DHAVE_STRING_H=1: command not found
../libtool: line 1286: X-DHAVE_STRING_H=1: command not found
../libtool: line 1286: X-DHAVE__BOOL=1: command not found
../libtool: line 1286: X-DHAVE__BOOL=1: command not found
../libtool: line 1286: X-DHAVE_STDBOOL_H=1: command not found
../libtool: line 1286: X-DHAVE_STDBOOL_H=1: command not found
../libtool: line 1286: X-DHAVE_STRRCHR=1: command not found
../libtool: line 1286: X-DHAVE_STRRCHR=1: command not found
../libtool: line 1286: X-I.: command not found
../libtool: line 1286: X-I.: command not found
../libtool: line 1286: X-mtune=generic: command not found
../libtool: line 1286: X-g: command not found
../libtool: line 1286: X-O3: command not found
../libtool: line 1286: X-O2: command not found
../libtool: line 1286: X-MT: command not found
../libtool: line 1286: X-MT: command not found
../libtool: line 1286: Xbs2b.lo: command not found
../libtool: line 1286: Xbs2bclass.lo: command not found
../libtool: line 1286: X-MD: command not found
../libtool: line 1286: X-MD: command not found
../libtool: line 1286: X-MP: command not found
../libtool: line 1286: X-MP: command not found
../libtool: line 1286: X-MF: command not found
../libtool: line 1286: X-MF: command not found
../libtool: line 1286: X.deps/bs2b.Tpo: No such file or directory
../libtool: line 1286: X.deps/bs2bclass.Tpo: No such file or directory
../libtool: line 1286: X-c: command not found
../libtool: line 1286: X-c: command not found
../libtool: line 1339: Xbs2b.lo: command not found
../libtool: line 1339: Xbs2bclass.lo: command not found
../libtool: line 1344: libtool: compile: cannot determine name of library object from `': command not found
make[1]: *** [Makefile:386: bs2b.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
../libtool: line 1344: libtool: compile: cannot determine name of library object from `': command not found
make[1]: *** [Makefile:410: bs2bclass.lo] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/xyz/Desktop/ffmpeg-windows-build-helpers-master/native_build/windows/ffmpeg_local_builds/sandbox/win32/libbs2b-3.1.0/src'
make: *** [Makefile:287: all-recursive] Error 1

With  

> nuke your sandbox/winx/libbsb folder

do you mean to delete the folder (sorry, english is not my native language :)) and relaunch "build_locally_with_various_option_prompts.bat"?

I did not try to remove the entire sandbox folder because now I can't wait the download and build process, also because during my first try I had to rename manually some xxxx.tmp folder after being downloaded from git due to some permissions issues with mv (by the way this is another issue I had not the time to investigate further and report about). In case it is necessary I will try tomorrow.

Thank you.

**Comment by thyAnger** [comment]
By also commenting out

> build_libbs2b() {
  download_and_unpack_file https://downloads.sourceforge.net/project/bs2b/libbs2b/3.1.0/libbs2b-3.1.0.tar.gz
  cd libbs2b-3.1.0
    sed -i.bak "s/AC_FUNC_MALLOC//" configure.ac # #270
    export LIBS=-lm # avoid pow failure linux native
    generic_configure_make_install 
    unset LIBS
  cd ..
}

in "cross_compile_ffmpeg.sh" I have been able to go further with the compilation process. Unfortunately now I get

> checking how to get verbose linking output from ifc... configure: WARNING: compilation failed
checking for Fortran 77 libraries of ifc...
checking for dummy main to link with Fortran 77 libraries... none
checking for Fortran 77 name-mangling scheme... configure: error: in `/cygdrive/c/Users/xyz/Desktop/ffmpeg-windows-build-helpers-master/native_build/windows/ffmpeg_local_builds/sandbox/win32/fftw-3.3.6-pl2':
configure: error: cannot compile a simple Fortran program
See `config.log' for more details

By giving a look at config.log (in attachment) it seems there is an unrecognized command. [config.log](https://github.com/rdp/ffmpeg-windows-build-helpers/files/2437093/config.log).

Any suggestion? Thank you and regards.

**Comment by rdp** [comment]
Still a problem?  I think...maybe...I did something that might affect it since then...

**Comment by thyAnger** [comment]
Hi, I am not working on it anymore.

**Comment by rdp** [comment]
For followers this was a failure on cygwin:

configure:21068: checking for Fortran 77 name-mangling scheme
configure:21081: ifc -c  conftest.f >&5
usage: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\ifc.exe [subcommand] [options...]

  subcommands:

    OBJ            Convert an interface file into a dummy object file which can be archived into a static lib.
    EMBED          Embed an interface file into an existing static lib, producing a new lib.
    EXTRACT        Extract an embedded interface file from an existing static lib, producing the ifc.
    LOCATE         Find all embedded interface files and print their offset + size to stdout.
configure:21081: $? = 1
configure: failed program was:
|       subroutine foobar()
|       return
|       end
|       subroutine foo_bar()
|       return
|       end
configure:21214: error: in `/cygdrive/c/Users/vmariani/Desktop/ffmpeg-windows-build-helpers-master/native_build/windows/ffmpeg_local_builds/sandbox/win32/fftw-3.3.6-pl2':
configure:21216: error: cannot compile a simple Fortran program
See `config.log' for more details


I'm going to guess you should remove ifc.exe from the PATH and try again... :)
