### ISSUE TITLE
configuring x264_normal_bitdepth -> Found no assembler

### ISSUE THREAD

**Issue by Nomadluap** [rdp/ffmpeg-windows-build-helpers#352]
When I try to run the build script on Ubuntu 16.04, I get the following error:

```
$ ./cross_compile_ffmpeg.sh --build-ffmpeg-shared=y --build-ffmpeg-static=n --gcc-cpu-count=8 --disable-nonfree=n --enable-gpl=n --compiler-flavors=win64    
   <snip>    
    doing git checkout origin/stable
    M       configure
    HEAD is now at 0a84d98... x86inc: Fix VEX -> EVEX instruction conversion
    Already up-to-date.
    fetched no code changes, not forcing reconfigure for that...
    configuring x264_normal_bitdepth (/home/pbelanger/source/ffmpeg-windows-build-helpers/sandbox/win64/x264_normal_bitdepth) as $ PKG_CONFIG_PATH=/home/pbelanger/source/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/home/pbelanger/source/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --host=x86_64-w64-mingw32 --enable-static --cross-prefix=/home/pbelanger/source/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --prefix=/home/pbelanger/source/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-strip --disable-lavf --extra-cflags=-mtune=generic --extra-cflags=-O3
    Found no assembler
    Minimum version is nasm-2.13
    If you really want to compile without asm, configure with --disable-asm.
```

I have added the following ffmpeg config flags  in the build_ffmpeg function: 

    dconfig_options+=" --enable-d3d11va --enable-dxva2"

Since I don't plan on using this build for encoding, I am OK with disabling asm for the encoder here. Where in the build script should I add the `--disable-asm` flag?

**Comment by rdp** [comment]
in the heart of build_libx264 or you could install a newer nasm from source.  I think d3d11va dxva2 are auto detect so already on?

**Comment by Nomadluap** [comment]
Thanks for the advice. I had installed nasm 2.11.08 from my distribution repo, but was able to continue the build after installing 2.13.03  (building from source) from the release page [here](https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/)

**Comment by rdp** [comment]
Nice work

On Monday, October 15, 2018, Paul Belanger <notifications@github.com> wrote:
> Thanks for the advice. I had installed nasm 2.11.08 from my distribution
repo, but was able to continue the build after installing 2.13.03 (building
from source) from the release page here
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/EeI47cBlruCT2ygYwrC6ZQgeMo1QAoqNUedb5FW8TnLA1DO3zNix_bUQYMKGo3ZNGUUiSPgVeGi_quoRZxDAEDKXFKTY3xlLurM_rtfI21EQFL1fS1sW_1Z4qjfTMbp3iE_9zNXSYRRn4eWAKDTbIAz8qsLQmQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0AreErrdkIXjxsp_rXAy5hdrF19Wks5ulIpzgaJpZM4XZrMK.gif>
