### ISSUE TITLE
Makefile:61: recipe for target 'release' failed; make: *** [release] Error 2

### ISSUE THREAD

**Issue by mouset447** [rdp/ffmpeg-windows-build-helpers#353]
Hello,

I have a problem to build ffmpeg.

System: ubuntu 18.04 x64 minimal command line
./cross_compile_ffmpeg.sh

after some time:

compiling sources/Base/SocketAddress.cpp
compiling sources/Base/Signal.cpp
compiling sources/Base/Timezone.cpp
compiling sources/Base/Mona.cpp
compiling sources/Base/Packet.cpp
compiling sources/Base/Buffer.cpp
compiling sources/Base/Util.cpp
In file included from ./include/Base/Util.h:20:0,
                 from sources/Base/Util.cpp:17:
./include/Base/Parameters.h: In static member function 'static const Base::Parameters& Base::Util::Environment()':
./include/Base/Parameters.h:83:172: warning: argument 1 null where non-null expected [-Wnonnull]
  const std::string& setString(const std::string& key, const char* value, std::size_t size = std::string::npos) { return setParameter(key, value, size == std::string::npos ? strlen(value) : size); }
                                                                                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ffmpeg/Desktop/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/c++/7.1.0/cstring:42:0,
                 from ./include/Base/Mona.h:24,
                 from ./include/Base/Util.h:19,
                 from sources/Base/Util.cpp:17:
/home/ffmpeg/Desktop/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/string.h:64:18: note: in a call to function 'size_t strlen(const char*)' declared here
   size_t __cdecl strlen(const char *_Str);
                  ^~~~~~
make[1]: Verzeichnis „/home/ffmpeg/Desktop/ffmpeg-windows-build-helpers/sandbox/win64/librtmfp_git“ wird verlassen
Makefile:61: recipe for target 'release' failed
make: *** [release] Error 2
root@ffmpeg-vm:/home/ffmpeg/Desktop/ffmpeg-windows-build-helpers#

Does anyone have an idea?

**Comment by rdp** [comment]
you can comment out build_librtmfp for now...

**Comment by FrejAndersson** [comment]
Re;
> checking for LIBFFI... no
> configure: error: Package requirements (libffi >= 3.0.0) were not met:
> 
> No package 'libffi' found
>

@rdp The libffi problem seems to be a build-order issue.

@mouset447: I had the same problem (also running Ubuntu WSL).
You can probably work around the problem by editing the build_lensfun() part of cross_compile_ffmpeg.sh. move build_glib from the top down to so it is built after gettext and libffi right before download_and_unpack_file...

Like So:
`build_lensfun() {`
`  export CPPFLAGS='-DLIBXML_STATIC' # gettext build...`
`  generic_download_and_make_and_install  https://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.8.1.tar.xz`
`  unset CPPFLAGS`
`  generic_download_and_make_and_install  http://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz # also dep`
`  build_glib`
`  download_and_unpack_file https://sourceforge.net/projects/lensfun/files/0.3.95/lensfun-0.3.95.tar.gz`
`  ...`

(I also have the same librtmfp-problem btw..)

**Comment by rdp** [comment]
build order hopefully better now...

**Comment by crazybytes** [comment]
I'll try to.
Just fixed the tesseract issue, by using the 
apt-get install autoconf-archive
see https://github.com/rdp/ffmpeg-windows-build-helpers/issues/315

It's not fixed in the helper script right now....
They should put the dots on the i to make it as perfect as possible.
It should run like:
-Enable linux shell for powershell (powershell command + enable linux install)
-Install ubuntu, make root command
-Run script
-Ready.
But that is only my point of view.
Then create READ.ME file with these few simple steps.
Then it should be maintained as soon as the chain gives error because of updates.
Run whole script every day several days from scratch automatically, and start panicking  when chain is broken.
:)
Thanks for all the work!

**Comment by rdp** [comment]
I...can't remember but think fixed now, thank you for the report
