### ISSUE TITLE
Failed to configure libaac

### ISSUE THREAD

**Issue by luntino** [rdp/ffmpeg-windows-build-helpers#356]
I'm trying to run the script on Centos 7 targeting Windows x64 with the non free options enabled as I require the libfdk codec.

The error occurs when trying to configure the libaac module and I can replicate by just running the bootstrap from the libacc_git folder as per below.

./bootstrap
+ test yes = yes
+ libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `.auto'.
libtoolize: copying file `.auto/ltmain.sh'
libtoolize: You should add the contents of the following files to `aclocal.m4':
libtoolize:   `/usr/share/aclocal/libtool.m4'
libtoolize:   `/usr/share/aclocal/ltoptions.m4'
libtoolize:   `/usr/share/aclocal/ltversion.m4'
libtoolize:   `/usr/share/aclocal/ltsugar.m4'
libtoolize:   `/usr/share/aclocal/lt~obsolete.m4'
libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
+ test -n .auto -a '!' .auto = . -a -f ltmain.sh
+ aclocal -I .auto -I .
configure.ac:32: warning: macro 'AM_PROG_LIBTOOL' not found in library
+ autoconf
configure.ac:31: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:32: error: possibly undefined macro: AM_PROG_LIBTOOL
configure.ac:33: error: possibly undefined macro: AC_LIBTOOL_CXX

I can confirm I have the latest versions of libtool/autoconf/automake

Any suggestions on how I can go about fixing it so the rest of the script can complete?

**Comment by rdp** [comment]
hmm...

**Comment by rdp** [comment]
I assume you mean libfdk-aac here in this case?

**Comment by rdp** [comment]
closing for no feedback
