### ISSUE TITLE
error while loading shared libraries: ?: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by RekiDunois** [rdp/ffmpeg-windows-build-helpers#358]
C:/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin/x86_arm/lib.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
make[3]: *** [Makefile:882：fontconfig.lib] 错误 127
make[3]: 离开目录“/cygdrive/d/code/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/win32/fontconfig-2.12.4/src”
make[2]: *** [Makefile:503：all] 错误 2
make[2]: 离开目录“/cygdrive/d/code/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/win32/fontconfig-2.12.4/src”
make[1]: *** [Makefile:581：all-recursive] 错误 1
make[1]: 离开目录“/cygdrive/d/code/ffmpeg-windows-build-helpers/native_build/windows/ffmpeg_local_builds/sandbox/win32/fontconfig-2.12.4”
make: *** [Makefile:465：all] 错误 2

I met this issue several times，seems something wrong with vc compiler？And I google it ，only find the issue that happened in Linux. Can I get some help from here, please?

**Comment by rdp** [comment]
Are you using visual studio to build ffmpeg?  My scripts only support gcc
ATM I think...

**Comment by rdp** [comment]
reopen if still trouble
