### ISSUE TITLE
libfdk_aac

### ISSUE THREAD

**Issue by AmandaMQ** [rdp/ffmpeg-windows-build-helpers#359]
I've been trying for the last couple days to compile a build of ffmpeg with libfdk_aac. I tried several combinations of parameters but none of them produces a build with the codec. Am I missing something? Is this by design or am I doing something wrong? Thanks.

**Comment by rdp** [comment]
How are you checking for the codec?

**Comment by AmandaMQ** [comment]
If you mean after built, by checking the header and also by ffmpeg -encoders, ffmpeg -codecs... the usual ways. Only AAC related codecs showing up in those lists are built-in aac and aac_latm - which is a just a decoder.

**Comment by rdp** [comment]
reopen if still a problem, thanks
