### ISSUE TITLE
Question, regarding gnutls git

### ISSUE THREAD

**Issue by ArcAngelRyse** [rdp/ffmpeg-windows-build-helpers#360]
So I'm in the middle of compiling and building the libraries but I'm curious its been at Running bootstrap for about 20mins how long should that typically take? It shows no errors, at least no obvious ones.
![annotation 2018-12-19 212743](https://user-images.githubusercontent.com/34932364/50260134-1236a800-03d5-11e9-9a38-af69fcb646da.jpg)

**Comment by rdp** [comment]
I don't actually maintain the media-autobuild-suite under msys that you
seem to be running there...gl!

**Comment by ArcAngelRyse** [comment]
Thanks!

**Comment by rdp** [comment]
In response to your question, I doubt it's expectd, I think I've had
something like that occur once, it was weird, try interrupting and doing it
again and cross your fingers! :)

**Comment by ArcAngelRyse** [comment]
Yea, it was just taking really long because of some odd issue with using 98%+ on CPU and RAM tasks. I guess 16GB's isn't enough for compiling. I got past all that after awhile but now I'm stuck with attempting to get realtime motion interpolation working. Because anytime I attempt to enable the filter it fails and I have mvtools but I don't know where or how to actually install it.

Honestly this whole thing is new to me.

**Comment by rdp** [comment]
yeah ask the media-autobuild-suite guys or try mine in an ubuntu instead :)
