### ISSUE TITLE
Harfbuzz

### ISSUE THREAD

**Issue by crazybytes** [rdp/ffmpeg-windows-build-helpers#362]
Trying to compile on arch linux...
fontconfig is missing harfbuzz  ( -lharfbuzz )

How to compile harfbuzz? Or what should i do.
Trying to compile old ffmpeg-2.8 with help of cross compiling, with subtitles, needs libass, needs fontconfig, who needs harfbuzz.
Don't know how the script managed on ubuntu, which gave no errors on this.

Inserted routine in helper script like:

build_libharfbuzz() {
  do_git_checkout https://github.com/harfbuzz/harfbuzz.git
  cd harfbuzz_git
    if [[ ! -f ./configure ]]; then
      ./autogen.sh
    fi
    generic_configure
    do_make_and_make_install
  cd ..
}
And many many other settings/tries, but nothing works.
I give it another shot then i try ubuntu or debian.

compiling the ffmpeg static 64 bits gives errors on linking when i combine it with cmake-gui and the sfemovie libs.
Only managed to compile ffmpeg-2.8 with bash script 32 bits shared.... :P 
Well, just keep on going.

**Comment by rdp** [comment]
fontconfig requires harfbuzz?

**Comment by rdp** [comment]
OK looks like freetype can use it.  Hopefully added it, thanks for the report, in 1b817bb

**Comment by rdp** [comment]
actually appears there is a circular dependency in there "on purpose" ... whoa...not out of the woods yet

**Comment by rdp** [comment]
it's theoretically in there now...

**Comment by rdp** [comment]
That was whacky, it's like a circular dependency, yikes...
