### ISSUE TITLE
Nuts

### ISSUE THREAD

**Issue by crazybytes** [rdp/ffmpeg-windows-build-helpers#363]
If i cross compile ffmpeg with the helper script, static, 64 bits, 

what compiler i should use outside ubuntu to compile  with the sfemovie lib for sfml?
How should i  compile the sfml, normally i use cmake-gui under windows, with the path set to my mingw32 compiler from the codeblocks dir. When using shared 32 bit libs from ffmpeg-2.8 it works ok.
But i want static ffmpeg libs 64 bits.
Now how and with what compile the sfml source, the sfemovie source, so i end up using it in my codeblocks program using the standard mingw32 dir from codeblocks.
Do i need to compile sfml under ubuntu with cross compiler?
Or just with standard mingw32? With cmake under windows? With cmake under ubuntu?
Also i want to use the libass option, for sub-titles, but even for shared dll's for ffmpeg 32 bits i can not archive that, als nothing on the internet about it.
Best results end up when compiling sfemovie demo's, using the ffmpeg libs compiled with the cross compiler. Giving errors on linking. Linking with .dll libs goes ok. But not with static.
Also lots of problems with harfbuzz, freetype, fontconfig, libass ...
Also any guide on the net does not work like expected. You always end up in a jungle.....

**Comment by rdp** [comment]
This system is "cross compiling" so it uses gcc like mingw-w64-gcc etc.
fwiw :|

**Comment by rdp** [comment]
assuming you're adding smfl to the cross compile build script...if it's a C library then I think any compiler.  If not best to stick with mingw-w64
