### ISSUE TITLE
x265 error compiling helper script.

### ISSUE THREAD

**Issue by crazybytes** [rdp/ffmpeg-windows-build-helpers#364]
Ubuntu shell under windows 10.

[ 98%] Building CXX object CMakeFiles/cli.dir/x265.cpp.obj
/opt/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-windres: /opt/sandbox/win64/x265/source/x265.rc:4: syntax error
CMakeFiles/cli.dir/build.make:262: recipe for target 'CMakeFiles/cli.dir/x265.rc.res' failed
make[2]: *** [CMakeFiles/cli.dir/x265.rc.res] Error 1

x265.rc:

#include <winresrc.h>

VS_VERSION_INFO VERSIONINFO
  FILEVERSION    3,0_RC,0,2                                                     <<< line 4... ?
  PRODUCTVERSION 3,0_RC,0,2
  FILEFLAGSMASK  VS_FFI_FILEFLAGSMASK
  FILEOS         VOS_NT_WINDOWS32
#ifdef OPENOBEX_EXPORTS
  FILETYPE       VFT_DLL
#else
  FILETYPE       VFT_STATIC_LIB
#endif
  FILESUBTYPE    VFT2_UNKNOWN
  BEGIN
    BLOCK "StringFileInfo"
    BEGIN
      BLOCK "04090000"
      BEGIN
        VALUE "FileDescription",  "HEVC video encoder"
        VALUE "FileVersion",      "3.0_RC+2-5251075203e1"
        VALUE "InternalName",     "x265"
        VALUE "LegalCopyright",   "Multicoreware: GPLv2 or commercial"
        VALUE "OriginalFilename", "libx265.dll"
        VALUE "ProductName",      "x265"
        VALUE "ProductVersion",   "3.0_RC+2-5251075203e1"
      END
    END
    BLOCK "VarFileInfo"
    BEGIN
      VALUE "Translation", 0x409, 1200
    END
END

**Comment by bschantz** [comment]
FILEVERSION and PRODUCTVERSION only accept a set of 4 integers: https://docs.microsoft.com/en-us/windows/desktop/menurc/versioninfo-resource

The cmake file pulls the version info from the latest tag, which is currently 3.0_RC.

I've created an issue over at the x265 repo: https://bitbucket.org/multicoreware/x265/issues/461/tag-with-non-integer-content-breaks-rc

**Comment by rdp** [comment]
looks like resolved upstream, if so, phew and thanks for reporting it to them
