### ISSUE TITLE
Error on tesseract

### ISSUE THREAD

**Issue by crazybytes** [rdp/ffmpeg-windows-build-helpers#365]
configuring tesseract_git (/opt/sandbox/win64/tesseract_git) as $ PKG_CONFIG_PATH=/opt/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/opt/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --host=x86_64-w64-mingw32 --prefix=/opt/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --disable-shared --enable-static
checking for x86_64-w64-mingw32-g++... x86_64-w64-mingw32-g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-w64-mingw32-g++ accepts -g... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-w64-mingw32-strip... x86_64-w64-mingw32-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of x86_64-w64-mingw32-g++... gcc3
./configure: line 3971: AX_SPLIT_VERSION: command not found
./configure: line 3972: s/^[^0-9]*//: No such file or directory
./configure: line 3974: s/^\([0-9][0-9]*\).*/\1/: No such file or directory
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-w64-mingw32
./configure: line 4220: syntax error near unexpected token `-mavx,'
./configure: line 4220: `AX_CHECK_COMPILE_FLAG(-mavx, avx=true, avx=false)'
root@DESKTOP-NJ5FGA2:/opt#

**Comment by eclyptox** [comment]
I have same error as you @crazybytes . Did you fixed in #369 ? After installing autoconf-archive, did you ran any command?

Thanks

**Comment by rdp** [comment]
https://github.com/rdp/ffmpeg-windows-build-helpers/issues/354 help?

**Comment by rdp** [comment]
closing no feedback...
