### ISSUE TITLE
More issues.

### ISSUE THREAD

**Issue by crazybytes** [rdp/ffmpeg-windows-build-helpers#366]
First time building went very ok. But i am getting more and more errors on compiling now. Also started complete new building, it should be same, but it has changed now. Dit i forget something to install?
How to update?
[ 87%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/modifier.cpp.obj
[ 93%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/auxfun.cpp.obj
In file included from /opt/sandbox/win64/lensfun-0.3.95/libs/lensfun/modifier.cpp:7:
/opt/sandbox/win64/lensfun-0.3.95/lensfun.h: In constructor 'lfModifier::lfModifier(float, int, int, lfPixelFormat, bool)':
/opt/sandbox/win64/lensfun-0.3.95/lensfun.h:3058:19: warning: 'lfModifier::PixelFormat' will be initialized after [-Wreorder]
     lfPixelFormat PixelFormat;
                   ^~~~~~~~~~~
/opt/sandbox/win64/lensfun-0.3.95/lensfun.h:3048:12: warning:   'double lfModifier::Crop' [-Wreorder]
     double Crop;
            ^~~~
/opt/sandbox/win64/lensfun-0.3.95/libs/lensfun/modifier.cpp:132:1: warning:   when initialized here [-Wreorder]
 lfModifier::lfModifier (float imgcrop, int imgwidth, int imgheight,
 ^~~~~~~~~~
[100%] Linking CXX static library liblensfun.a
Traceback (most recent call last):
  File "/opt/sandbox/win64/lensfun-0.3.95/apps/setup.py", line 6, in <module>
    from distutils.core import setup
ModuleNotFoundError: No module named 'distutils.core'
apps/CMakeFiles/python-package.dir/build.make:60: recipe for target 'apps/build/timestamp' failed
make[2]: *** [apps/build/timestamp] Error 1
CMakeFiles/Makefile2:158: recipe for target 'apps/CMakeFiles/python-package.dir/all' failed
make[1]: *** [apps/CMakeFiles/python-package.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target lensfun
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
root@DESKTOP-NJ5FGA2:/opt#

**Comment by crazybytes** [comment]
I will download the script again and try if its getting better.
Maybe make update on the script itself inside the script... :P

**Comment by rdp** [comment]
lensfun built the first time then rebuilt?

**Comment by rdp** [comment]
sudo apt-get install python3-distutils apparently FWIW
