### ISSUE TITLE
Jungle

### ISSUE THREAD

**Issue by crazybytes** [rdp/ffmpeg-windows-build-helpers#367]
Compiling packages with all kinds of different settings is very confusing.
There is no standard, like addons like this helper script.
Like a collection of tools, patches, etc. etc.
There are already lots of tools, like make, config, pkg-config, cmake, etc. etc. etc.
There is no standard.

Also, i compile with the 7.3.0 gcc seh posix lib my programs.
How about the compiler downloaded and compiled to do the cross compiling?
What code does it generate? How is it compiled? 
Can i use it with the gcc seh posix gcc? Or should the compiler being compiled to match the gcc seh posix 7.3.0? Because they say use same system for all used code.
I use codeblocks now, with the gcc seh posix 7.3.0, because adviced by sfml page.
So i compile my program, the sfml lib, the sfemoviefix lib, and the ffmpeg-2.8 with this compiler.

How can i match the cross compiler used in this script, or is it ok? Does the generated code match the other compiler.

Just asking some indian in the jungle who knows how to survive.

The overhead of programming this way is like 90%. 
I spend most time on it, against my own program.
Its such a waste of time.

Btw, great achievement this script.
Maybe the whole open source needs a little management, because of infiltration and trolls.
Like the new ffmpeg is not compatible with the sfemovie or sfemoviefix fro sfml, they changed it that way, and the sfemovie is not getting along with it.

Maybe you could take a look on the sfemovie and / or sfemoviefix code for sfml using ffmpeg-2.8 right now, so the code for sfemovie can be changed to follow the new ffmpeg.
They changed things like variables, so the sfemovie don't match the new ffmpeg 3 and 4.

Maybe you can help them out adapting the sfemovie code. So we can use all new codecs etc.
Like xlib264 xlib265, etc. 
Als problems with the libass library. Do i need old libass, freetype, fontconfig etc. to compile with the ffmpeg-2.8.
Also the script has option for older/other version of ffmpeg. How does it work against the newer other libs with pkg-config.
Etc.

Just asking my way in the jungle.... 
Watch out, the magic coconut has to placed in the monkeys ass for an hour before using is.
Or, get that from the other side of the cliff, but the bridge is broken, etc.
Its like some sort of quest, and the rabit holes never end, and go in circles.
Also all guides on the internet don't work. Seems like they manipulate EVERYTHING.
(The big commercial companies using the open source, then manipulate it so others can not keep up).

(conspiracy shit :P )
Anyway, go on like this. 
Need money? Just give me a call.

**Comment by crazybytes** [comment]
Or are you one of the trolls keeping us busy? Because you never know peoples intentions. Saying all this makes me target of naïef people who think it doesn't exists.
So, everybody in the open source should give their credentials somehow. 
Because the money is everywhere. If you know what i am saying.

**Comment by crazybytes** [comment]
![image](https://user-images.githubusercontent.com/26222708/50725612-45c94000-1100-11e9-95bb-d64f784ea52c.png)

What about this. The ubuntu directory is from windows not available. I can not delete it.
But i am the owner.
I start ubunto in root mode and administrator mode.
So i have to change it from inside ubuntu itself.
Strange, i even don't own my own computer anymore.

**Comment by crazybytes** [comment]
Same error on tessaract with new script. Also deleted old tesseract dir.
checking whether make supports nested variables... yes
checking dependency style of x86_64-w64-mingw32-g++... gcc3
./configure: line 3971: AX_SPLIT_VERSION: command not found
./configure: line 3972: s/^[^0-9]*//: No such file or directory
./configure: line 3974: s/^\([0-9][0-9]*\).*/\1/: No such file or directory
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-w64-mingw32
./configure: line 4220: syntax error near unexpected token `-mavx,'
./configure: line 4220: `AX_CHECK_COMPILE_FLAG(-mavx, avx=true, avx=false)'
root@DESKTOP-NJ5FGA2:/opt#

**Comment by crazybytes** [comment]
Whoops, did something wrong with the downloaded script.
Fix some things, then i report again... 

📦

**Comment by crazybytes** [comment]
And the next one:

Just reporting.

/opt/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/c++/8.2.0/exception:144:10: fatal error: bits/nested_exception.h: No such file or directory
 #include <bits/nested_exception.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/c++/8.2.0/new:40,
                 from /opt/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/c++/8.2.0/ext/new_allocator.h:33,
                 from /opt/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/c++/8.2.0/x86_64-w64-mingw32/bits/c++allocator.h:33,
                 from /opt/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/c++/8.2.0/bits/allocator.h:46,
                 from /opt/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/c++/8.2.0/string:41,
                 from /opt/sandbox/win64/lensfun-0.3.95/lensfun.h:39,
                 from /opt/sandbox/win64/lensfun-0.3.95/libs/lensfun/camera.cpp:7:
/opt/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/c++/8.2.0/exception:144:10: fatal error: bits/nested_exception.h: No such file or directory
 #include <bits/nested_exception.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
libs/lensfun/CMakeFiles/lensfun.dir/build.make:63: recipe for target 'libs/lensfun/CMakeFiles/lensfun.dir/camera.cpp.obj' failed
make[2]: *** [libs/lensfun/CMakeFiles/lensfun.dir/camera.cpp.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
libs/lensfun/CMakeFiles/lensfun.dir/build.make:88: recipe for target 'libs/lensfun/CMakeFiles/lensfun.dir/database.cpp.obj' failed
make[2]: *** [libs/lensfun/CMakeFiles/lensfun.dir/database.cpp.obj] Error 1
Traceback (most recent call last):
  File "/opt/sandbox/win64/lensfun-0.3.95/apps/setup.py", line 6, in <module>
    from distutils.core import setup
ModuleNotFoundError: No module named 'distutils.core'
apps/CMakeFiles/python-package.dir/build.make:60: recipe for target 'apps/build/timestamp' failed
make[2]: *** [apps/build/timestamp] Error 1
CMakeFiles/Makefile2:158: recipe for target 'apps/CMakeFiles/python-package.dir/all' failed
make[1]: *** [apps/CMakeFiles/python-package.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:103: recipe for target 'libs/lensfun/CMakeFiles/lensfun.dir/all' failed
make[1]: *** [libs/lensfun/CMakeFiles/lensfun.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
root@DESKTOP-NJ5FGA2:/opt#

For your convenience.

**Comment by crazybytes** [comment]
Strange, first time everything works ok.
Now i am using it, and things stop working.
Like the manipulate real time....

**Comment by crazybytes** [comment]
Greatest trick of the devil is denying its existence btw.....

**Comment by rdp** [comment]
That's weird I'll try a full rebuild sometime to make sure it works...

On Saturday, January 5, 2019, Gerard Wensink <notifications@github.com>
wrote:
> Greatest trick of the devil is denying its existence btw.....
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/7NckxmJX3ihUcwVHe1TUBLEnYcnUJsp0udYgq1C20BxQBByV4Y7h_GRmM-AwDg18bnyShuiNITd6dX2wADl7-QZ5u730Hsxn7bla3cF5w_SiWcst6P0hhqyTD_rZiz2Zvx-QyroT4tNYZg9O2WannYXrFQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0NGWsmW2CZR5jDHuwvWI0TfTt5i1ks5vAM0sgaJpZM4ZxMEz.gif>

**Comment by crazybytes** [comment]
Sorry, i got little frustrated. Now everything is ok.
What about compiling with tesseract and lensfun?
Should i delete whole win64 dir and compile over again?

**Comment by rdp** [comment]
Yes please.  I believe we're addressing those two issues as separate github issues to this one is that right?
