### ISSUE TITLE
Windows 10->Powershell->Ubuntu->Helperscript-> error on  tesseract and lensfun fixed

### ISSUE THREAD

**Issue by crazybytes** [rdp/ffmpeg-windows-build-helpers#369]
compiling ffmpeg with helpers script:

error on tesseract:
	'apt-get install autoconf-archive'
	(sudo apt-get install autoconf-archive)
	https://github.com/rdp/ffmpeg-windows-build-helpers/issues/315

error on lensfun:
	https://github.com/kyuupichan/electrumx/issues/464
	'As a workaround I had to use ppa:deadsnakes/ppa or install python3-distutils.'
	(sudo apt-get install python3-distutils)

**Comment by crazybytes** [comment]
Running like a train now. (10 januari 2019)

**Comment by rdp** [comment]
Yeah I don't know how to test for those easily so...kind of rely on people to not have other packages and for them to blindly install using the list it spits out...
