### ISSUE TITLE
This error is happening again in the latest release.

### ISSUE THREAD

**Issue by miguelapg** [rdp/ffmpeg-windows-build-helpers#370]
This error is happening again in the latest release.

Please, can you fix it?

Thank you very much

Mapg

_Originally posted by @miguelapg in https://github.com/rdp/ffmpeg-windows-build-helpers/issues/235#issuecomment-456460736_

**Comment by rdp** [comment]
Try now...though I have no idea how it ever worked now to be honest, unless ffmpeg itself changed somehow revealing that we never did get it quite right originally...hmm...

**Comment by rdp** [comment]
This time I think I got it...hopefully
