### ISSUE TITLE
enhancement: add libsrt

### ISSUE THREAD

**Issue by vidanio** [rdp/ffmpeg-windows-build-helpers#373]
Would u enable libsrt from https://github.com/Haivision/srt on ffmeg build ?
Regards

**Comment by rdp** [comment]
Hmm glanced at it, doesn't look immediately trivial...

**Comment by vidanio** [comment]
Yes, you are right. I tried a "generic_download_and_make_and_install" but it doesn't find libsrt.a with pkg-config.

**Comment by rdp** [comment]
hopefully fixed, thanks to sponsorship from vidanio :)
