### ISSUE TITLE
Compile fails on 'Linkink CXX executable srt-file-transmit.exe'

### ISSUE THREAD

**Issue by Mr-Antivirus** [rdp/ffmpeg-windows-build-helpers#377]
Hello.

I downloaded Ubuntu from the Windows store and I'm running the cross compile script from that terminal. When I get to this line, it fails when it tries to link the two executables.

`Making /home/linux/ffmpeg-windows-build-helpers/sandbox/win64/srt_git as $ PATH=/home/linux/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH make  -j 8`

This is the entire log.

linux@PC:~$ cd ffmpeg-windows-build-helpers/
linux@PC:~/ffmpeg-windows-build-helpers$ ./cross_compile_ffmpeg.sh
cmake binary for this build will be cmake
Wed Feb 20 08:51:40 DST 2019
     ##################### Welcome ######################
  Welcome to the ffmpeg cross-compile builder-helper script.
  Downloads and builds will be installed to directories within /home/linux/ffmpeg-windows-build-helpers/sandbox
  If this is not ok, then exit now, and cd to the directory where you'd
  like them installed, then run this script again from there.
  NB that once you build your compilers, you can no longer rename/move
  the sandbox directory, since it will have some hard coded paths in there.
  You can, of course, rebuild ffmpeg from within it, etc.
sit back, this may take awhile...
What version of MinGW-w64 would you like to build or update?
  1. Both Win32 and Win64
  2. Win32 (32-bit only)
  3. Win64 (64-bit only)
  4. Local native
  5. Exit
Input your choice [1-5]: 3
Starting to download and build cross compile version of gcc [requires working internet access] with thread count 8...

Done building (or already built) MinGW-w64 cross-compiler(s) successfully...
Wed Feb 20 08:52:07 DST 2019

**************Starting 64-bit builds...
Building ffmpeg dependency libraries...
doing git checkout origin/master
M       Makefile
HEAD is now at 278c782 Merge pull request #44 from pali/master
fetched no code changes, not forcing reconfigure for that...
Already made dlfcn-win32_git ...
not svn Updating xavs_svn since usually svn repo's aren't updated frequently enough...
Already made xavs_svn ...
doing git checkout origin/master
HEAD is now at 2d0b10a Merge pull request #50 from nmcclatchey/winver_check
fetched no code changes, not forcing reconfigure for that...
Already made zlib-1.2.11 ...
doing git checkout f1267fbd3cd3635a
M       caca/caca.h
M       caca/caca0.h
M       caca/figfont.c
M       caca/string.c
HEAD is now at f1267fb Fix copyright headers so that the testsuite passes again.
fetched no code changes, not forcing reconfigure for that...
Already made libcaca_git ...
already made bzip2-1.0.6
Already made xz-5.2.3 ...
Already made libiconv-1.15 ...
Already made SDL2-2.0.5 ...
doing git checkout origin/master
HEAD is now at d9928b3 Delete already_installed
fetched no code changes, not forcing reconfigure for that...
doing git checkout origin/master
HEAD is now at a7d95e5 API update to 1.27
fetched no code changes, not forcing reconfigure for that...
Already made mfx_dispatch_git ...
doing git checkout origin/master
HEAD is now at cd967ef Update README for SDK 9.0.18
fetched no code changes, not forcing reconfigure for that...
doing git checkout 8e87f5a4b88e16ccafb2e7ade8ef45
HEAD is now at 8e87f5a colorspace: fix assertion failure
fetched no code changes, not forcing reconfigure for that...
Already made zimg_git ...
doing git checkout origin/master
HEAD is now at 51f097e6 Merge pull request #1172 from hlef/master
fetched no code changes, not forcing reconfigure for that...
Already made openjpeg_git ...
doing git checkout origin/master
HEAD is now at 8439534da Fix a memory leak in pngtest.c
fetched no code changes, not forcing reconfigure for that...
Already made libpng_git ...
doing git checkout origin/master
HEAD is now at d9a662e1 WebPRescalerGetScaledDimensions: round scaled dimension up
fetched no code changes, not forcing reconfigure for that...
Already made libwebp_git ...
done harfbuzz
Already made libxml2-2.9.4 ...
doing git checkout origin/master
M       feature/src/adm_options.h
M       libsvm/Makefile
M       ptools/Makefile.VMAF
M       ptools/fdtools.h
M       ptools/opencontainers_1_8_4/include/ocsynchronizer.h
M       wrapper/Makefile
HEAD is now at a0e7289 Update BuildForWindows.md
fetched no code changes, not forcing reconfigure for that...
Already made vmaf_git ...
Already made fontconfig-2.12.4 ...
Already made gmp-6.1.2 ...
Already made nettle-3.4 ...
Already made libidn-1.35 ...
Already made gnutls-3.5.19 ...
doing git checkout origin/master
HEAD is now at 0acd32d Remove trailing whitespace from the api documentation.
fetched no code changes, not forcing reconfigure for that...
Already made ogg_git ...
doing git checkout origin/master
HEAD is now at 9eadecc Don't leak memory in test_sharedbook to please asan.
fetched no code changes, not forcing reconfigure for that...
Already made vorbis_git ...
doing git checkout origin/master
HEAD is now at 9f2a0c70 Properly handle a bad stream_id in OPUS_MULTISTREAM_GET_*_STATE_REQUEST
fetched no code changes, not forcing reconfigure for that...
Already made opus_git ...
doing git checkout origin/master
HEAD is now at 74db0e5 Ignore the m4 folder created by autogen.sh
fetched no code changes, not forcing reconfigure for that...
Already made speexdsp_git ...
doing git checkout origin/master
HEAD is now at 6e04bfa generate-samples: change output directory
fetched no code changes, not forcing reconfigure for that...
Already made speex_git ...
doing git checkout origin/master
HEAD is now at e5d205b Clean up old automake options.
fetched no code changes, not forcing reconfigure for that...
Already made theora_git ...
doing git checkout origin/master
HEAD is now at 1a87c443 Avoid two static analysis warnings
fetched no code changes, not forcing reconfigure for that...
Already made libsndfile_git ...
already installed GSM 6.10 ...
doing git checkout origin/master
M       configure
HEAD is now at ab5a540f - calculate input transform matrix once on initialization - calculate clip detect even when scaling was set; else one doesn't notice that clipping still might happen.
fetched no code changes, not forcing reconfigure for that...
Already made lame_git ...
doing git checkout origin/master
M       Makefile.am
HEAD is now at 3fc06cf Upgraded to Doxygen 1.8.14
fetched no code changes, not forcing reconfigure for that...
Already made twolame_git ...
Already made opencore-amr-0.1.5 ...
Already made vo-amrwbenc-0.1.3 ...
doing git checkout origin/master
M       m4/ltsugar.m4
HEAD is now at 4d0c2edf1 add platform definitions for PPC and Sparc (#23)
fetched no code changes, not forcing reconfigure for that...
Already made libilbc_git ...
doing git checkout origin/master
M       INSTALL
HEAD is now at af00e21 Merge pull request #36 from sagamusix/master
fetched no code changes, not forcing reconfigure for that...
Already made libmodplug_git ...
Already made game-music-emu-0.6.2 ...
doing git checkout origin/master
M       .gitmodules
M       contrib/libudfread
M       jni/win32/jni_md.h
HEAD is now at 2d18c709 Split FileInputStream to SE/ME versions
fetched no code changes, not forcing reconfigure for that...
Already made libbluray_git ...
Already made libbs2b-3.1.0 ...
doing git checkout origin/master
HEAD is now at 945b592 update NEWS, versions
fetched no code changes, not forcing reconfigure for that...
Already made soxr_git ...
Already made flite-2.0.0-release ...
doing git checkout origin/master
HEAD is now at d4be414 Remove MSBuild section from AppVeyor configuration.
fetched no code changes, not forcing reconfigure for that...
Already made snappy_git ...
Already made vamp-plugin-sdk-vamp-plugin-sdk-v2.7.1 ...
Already made fftw-3.3.6-pl2 ...
doing git checkout origin/master
HEAD is now at a2eb281 fix macos compile errors - modernize audio api
fetched no code changes, not forcing reconfigure for that...
Already made libsamplerate_git ...
doing git checkout origin/master
M       Makefile.in
M       rubberband.pc.in
HEAD is now at 8efc278 Add reference to the .NET interface and its licence
fetched no code changes, not forcing reconfigure for that...
Already made rubberband_git ...
doing git checkout origin/master
HEAD is now at 004e8c0 Merge pull request #71 from rrrapha/opencv-include-dirs
fetched no code changes, not forcing reconfigure for that...
Already made frei0r_git ...
doing git checkout origin/master
M       CMakeLists.txt
HEAD is now at aeabc8d Merge pull request #72 from candrews/patch-3
fetched no code changes, not forcing reconfigure for that...
Already made vid.stab_git ...
doing git checkout origin/master
HEAD is now at 50ee637 Merge pull request #59 from richardpl/master
fetched no code changes, not forcing reconfigure for that...
Already made libmysofa_git ...
Already made zvbi-0.2.35 ...
doing git checkout origin/master
HEAD is now at 58c6cb3 meson: Pass visibility args to test executable
fetched no code changes, not forcing reconfigure for that...
Already made fribidi_git ...
doing git checkout origin/master
HEAD is now at fa49852 stroker: correctly handle case of many small segments
fetched no code changes, not forcing reconfigure for that...
Already made libass_git ...
Already made generic ...
doing git checkout origin/master
M       apps/srt-file-transmit.cpp
HEAD is now at 446fc1d Putting global objects with short names under a namespace (#576)
fetched no code changes, not forcing reconfigure for that...

Making /home/linux/ffmpeg-windows-build-helpers/sandbox/win64/srt_git as $ PATH=/home/linux/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH make  -j 8

[ 20%] Built target srtsupport_virtual
[ 55%] Built target srt_virtual
[ 85%] Built target haicrypt_virtual
[ 90%] Built target srt_static
[ 92%] Linking CXX executable srt-file-transmit.exe
[ 95%] Linking CXX executable srt-live-transmit.exe
/home/linux/ffmpeg-windows-build-helpers/sandbox//homecross_compilers//linuxmingw/-ffmpegw64--windowsx86_64-/buildlib-/helpersgcc//sandboxx86_64/-cross_compilersw64/-mingwmingw32-/w648.2.0-/x86_64./.lib//.gcc.//x86_64.-.w64/-.mingw32.//8.2.0x86_64/-.w64.-/mingw32./.bin//.ld.:/ ./.home//x86_64linux-/w64ffmpeg--mingw32windows/-binbuild/-ldhelpers:/ sandbox//homecross_compilers//linuxmingw/-ffmpegw64--windowsx86_64-/buildlib-/helpersgcc//sandboxx86_64/-cross_compilersw64/-mingwmingw32-/w648.2.0-/x86_64./.lib//.gcc.//x86_64.-.w64/-.mingw32.//8.2.0x86_64/-.w64.-/mingw32./.lib//....//.lib.//libgnutls.ax86_64(-strw64--idna.omingw32)/:libstr/-.idna.c.:/(lib./textlibgnutls.a+(0x60str)-:idna.o )undefined: strreference- idna.cto: (`.idna_to_ascii_8ztext'+
0x60/)home:/ linuxundefined/ ffmpegreference- windowsto- build`-idna_to_ascii_8zhelpers'/
sandbox//homecross_compilers//linuxmingw/-ffmpegw64--windowsx86_64-/buildlib-/helpersgcc//sandboxx86_64/-cross_compilersw64/-mingwmingw32-/w648.2.0-/x86_64./.lib//.gcc.//x86_64.-.w64/-.mingw32.//8.2.0x86_64/-.w64.-/mingw32./.bin//.ld.:/ ./.home//x86_64linux-/w64ffmpeg--mingw32windows/-binbuild/-ldhelpers:/ sandbox//homecross_compilers//linuxmingw/-ffmpegw64--windowsx86_64-/buildlib-/helpersgcc//sandboxx86_64/-cross_compilersw64/-mingwmingw32-/w648.2.0-/x86_64./.lib//.gcc.//x86_64.-.w64/-.mingw32.//8.2.0x86_64/-.w64.-/mingw32./.lib//....//.lib.//libgnutls.ax86_64(-strw64--idna.omingw32)/:libstr/-.idna.c.:/(lib./textlibgnutls.a+(0x7dstr)-:idna.o )undefined: strreference- idna.cto: (`.idn_freetext'+
0x7d/)home:/ linuxundefined/ ffmpegreference- windowsto- build`-idn_freehelpers'/
sandbox//homecross_compilers//linuxmingw/-ffmpegw64--windowsx86_64-/buildlib-/helpersgcc//sandboxx86_64/-cross_compilersw64/-mingwmingw32-/w648.2.0-/x86_64/lib./.gcc//.x86_64.-/w64.-.mingw32//.8.2.0.//.x86_64.-/w64.-.mingw32//.bin.//ld.:. //x86_64home-/w64linux-/mingw32ffmpeg/-binwindows/-ldbuild:- helpers//homesandbox//linuxcross_compilers//ffmpegmingw--windowsw64--buildx86_64-/helperslib//sandboxgcc//cross_compilersx86_64/-mingww64--w64mingw32-/x86_648.2.0//lib./.gcc//.x86_64.-/w64.-.mingw32//.8.2.0.//.x86_64.-/w64.-.mingw32//.lib.//....//libx86_64/-libgnutls.aw64(-strmingw32-/idna.olib)/:.str.-/idna.clib:/(libgnutls.a.(textstr+-0xa8idna.o)):: strundefined- idna.creference: (to. text`+idn_free0xa8')
:/ homeundefined/ linuxreference/ ffmpegto- windows`-idn_freebuild'-
helpers//homesandbox//linuxcross_compilers//ffmpegmingw--windowsw64--buildx86_64-/helperslib//sandboxgcc//cross_compilersx86_64/-mingww64--w64mingw32-/x86_648.2.0//lib./.gcc//.x86_64.-/w64.-.mingw32//.8.2.0.//.x86_64.-/w64.-.mingw32//.bin.//ld.:. //x86_64home-/w64linux-/mingw32ffmpeg/-binwindows/-ldbuild:- helpers//homesandbox//linuxcross_compilers//ffmpegmingw--windowsw64--buildx86_64-/helperslib//sandboxgcc//cross_compilersx86_64/-mingww64--w64mingw32-/x86_648.2.0//lib./.gcc//.x86_64.-/w64.-.mingw32//.8.2.0.//.x86_64.-w64/-.mingw32.//lib./../../.lib//x86_64libgnutls.a-(w64str--mingw32idna.o/)lib:/str.-.idna.c/:lib(/.libgnutls.atext(+str0x1f3-)idna.o:) :undefinedstr -referenceidna.c :to( .`textidna_strerror+'0x1f3
)/:home /undefinedlinux /referenceffmpeg -towindows -`buildidna_strerror-'helpers
//sandboxhome//cross_compilerslinux//mingwffmpeg--w64windows--x86_64build/-libhelpers//gccsandbox//x86_64cross_compilers-/w64mingw--mingw32w64/-8.2.0x86_64//.lib.//gcc./.x86_64/-.w64.-/mingw32./.8.2.0//x86_64.-.w64/-.mingw32.//bin./.ld/:. .//homex86_64/-linuxw64/-ffmpegmingw32-/windowsbin-/buildld-:helpers //sandboxhome//cross_compilerslinux//mingwffmpeg--w64windows--x86_64build/-libhelpers//gccsandbox//x86_64cross_compilers-/w64mingw--mingw32w64/-8.2.0x86_64//.lib.//gcc./.x86_64/-.w64.-/mingw32./.8.2.0//x86_64.-.w64/-.mingw32.//lib./../../.lib//x86_64libgnutls.a-(w64str--mingw32idna.o/)lib:/str.-.idna.c/:lib(/.libgnutls.atext(+str0x2ea-)idna.o:) :undefinedstr -referenceidna.c :to( .`textidna_to_unicode_8z8z+'0x2ea
)/:home /undefinedlinux /referenceffmpeg -towindows -`buildidna_to_unicode_8z8z-'helpers
//sandboxhome//cross_compilerslinux//mingwffmpeg--w64windows--x86_64build/-libhelpers//gccsandbox//x86_64cross_compilers-/w64mingw--mingw32w64/-8.2.0x86_64//.lib.//gcc./.x86_64/-.w64.-/mingw32./.8.2.0//x86_64.-.w64/-.mingw32.//bin./.ld/:. .//homex86_64/-linuxw64/-ffmpegmingw32-/windowsbin-/buildld-:helpers //sandboxhome//cross_compilerslinux//mingwffmpeg--w64windows--x86_64build/-libhelpers//gccsandbox//x86_64cross_compilers-/w64mingw--mingw32w64/-8.2.0x86_64//.lib.//gcc./.x86_64/-.w64.-/mingw32./.8.2.0//x86_64.-.w64/-.mingw32.//lib./../../.lib//x86_64libgnutls.a-(w64str--mingw32idna.o/)lib:/str.-.idna.c/:lib(/.libgnutls.atext(+str0x332-)idna.o:) :undefinedstr -referenceidna.c :to( .`textidn_free+'0x332
)/:home /undefinedlinux /referenceffmpeg -towindows -`buildidn_free-'helpers
//sandboxhome//cross_compilerslinux//mingwffmpeg--w64windows--x86_64build/-libhelpers//gccsandbox//x86_64cross_compilers-/w64mingw--mingw32w64/-8.2.0x86_64//.lib.//gcc./.x86_64/-.w64.-/mingw32./.8.2.0//x86_64.-.w64/-.mingw32.//bin./.ld/:. .//homex86_64/-linuxw64/-ffmpegmingw32-/windowsbin-/buildld-:helpers //sandboxhome//cross_compilerslinux//mingwffmpeg--w64windows--x86_64build/-libhelpers//gccsandbox//x86_64cross_compilers-/w64mingw--mingw32w64/-8.2.0x86_64//.lib.//gcc./.x86_64/-.w64.-/mingw32./.8.2.0//x86_64.-.w64/-.mingw32.//lib./../../.lib//x86_64libgnutls.a-(w64str--mingw32idna.o/)lib:/str.-.idna.c/:lib(/.libgnutls.atext(+str0x3d3-)idna.o:) :undefinedstr -referenceidna.c :to( .`textidna_strerror+'0x3d3
)/:home /undefinedlinux /referenceffmpeg -towindows -`buildidna_strerror-'helpers
//sandboxhome//cross_compilerslinux//mingwffmpeg--w64windows--x86_64build/-libhelpers//gccsandbox//x86_64cross_compilers-/w64mingw--mingw32w64/-8.2.0x86_64//.lib.//gcc./.x86_64/-.w64.-/mingw32./.8.2.0//x86_64.-.w64/-.mingw32.//bin./.ld/:. .//homex86_64/-linuxw64/-ffmpegmingw32-/windowsbin-/buildld-:helpers //sandboxhome//cross_compilerslinux//mingwffmpeg--w64windows--x86_64build/-libhelpers//gccsandbox//x86_64cross_compilers-/w64mingw--mingw32w64/-8.2.0x86_64//.lib.//gcc./.x86_64/-.w64.-/mingw32./.8.2.0//x86_64.-.w64/-.mingw32.//lib./../../.lib//x86_64libgnutls.a-(w64str--mingw32idna.o/)lib:/str.-.idna.c/:lib(/.libgnutls.ardata$.refptr.idn_free([str.-refptr.idn_freeidna.o])+:0x0str)-:idna.c :undefined( .referencerdata$.refptr.idn_free [to. refptr.idn_free`]idn_free+'0x0
):collect2: error: ld returned 1 exit status
 undefined reference to `idn_free'
collect2: error: ld returned 1 exit status
CMakeFiles/srt-file-transmit.dir/build.make:108: recipe for target 'srt-file-transmit.exe' failed
make[2]: *** [srt-file-transmit.exe] Error 1
CMakeFiles/Makefile2:255: recipe for target 'CMakeFiles/srt-file-transmit.dir/all' failed
make[1]: *** [CMakeFiles/srt-file-transmit.dir/all] Error 2
CMakeFiles/srt-live-transmit.dir/build.make:108: recipe for target 'srt-live-transmit.exe' failed
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [srt-live-transmit.exe] Error 1
CMakeFiles/Makefile2:180: recipe for target 'CMakeFiles/srt-live-transmit.dir/all' failed
make[1]: *** [CMakeFiles/srt-live-transmit.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cdgriffith** [comment]
Pulled to latest commit `653e362bdff1ef36927c71536d02a981b7610968` and also having that issue. (Also on WSL Ubuntu 18.04) 

<details><summary>Error details</summary>
<p>

```
HEAD is now at 446fc1d Putting global objects with short names under a namespace (#576)
fetched no code changes, not forcing reconfigure for that...

Making /home/james/ffmpeg-windows-build-helpers/sandbox/win64/srt_git as $ PATH=/home/james/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH make  -j 16

[ 20%] Built target srtsupport_virtual
[ 55%] Built target srt_virtual
[ 85%] Built target haicrypt_virtual
[ 90%] Built target srt_static
[ 95%] Linking CXX executable srt-live-transmit.exe
[ 95%] Linking CXX executable srt-file-transmit.exe
/home/james/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64bin//libld/:gcc //x86_64home-/w64james-/mingw32ffmpeg/-8.2.0windows/-.build.-/helpers./.sandbox//.cross_compilers.//mingw.-.w64/-x86_64x86_64-/w64lib-/mingw32gcc//binx86_64/-ldw64:- mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64lib//lib./.gcc//libx86_64/-libgnutls.aw64(-strmingw32-/idna.o8.2.0)/:.str.-/idna.c.:.(/..text.+/0x60.).:/ x86_64undefined- w64reference- mingw32to/ lib`/idna_to_ascii_8z.'.
//libhome//libgnutls.ajames(/strffmpeg--idna.owindows)-:buildstr--helpersidna.c/:sandbox(/.cross_compilerstext/+mingw0x60-)w64:- x86_64undefined/ libreference/ gccto/ x86_64`-idna_to_ascii_8zw64'-
mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64bin//libld/:gcc //x86_64home-/w64james-/mingw32ffmpeg/-8.2.0windows/-.build.-/helpers./.sandbox//.cross_compilers.//mingw.-.w64/-x86_64x86_64-/w64lib-/mingw32gcc//binx86_64/-ldw64:- mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64lib//lib./.gcc//libx86_64/-libgnutls.aw64(-strmingw32-/idna.o8.2.0)/:.str.-/idna.c.:.(/..text.+/0x7d.).:/ x86_64undefined- w64reference- mingw32to/ lib`/idn_free.'.
//libhome//libgnutls.ajames(/strffmpeg--idna.owindows)-:buildstr--helpersidna.c/:sandbox(/.cross_compilerstext/+mingw0x7d-)w64:- x86_64undefined/ libreference/ gccto/ x86_64`-idn_freew64'-
mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64bin//libld/:gcc //x86_64home-/w64james-/mingw32ffmpeg/-8.2.0windows/-.build.-/helpers./.sandbox//.cross_compilers.//mingw.-.w64/-x86_64x86_64-/w64lib-/mingw32gcc//binx86_64/-ldw64:- mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64lib//lib./.gcc//libx86_64/-libgnutls.aw64(-strmingw32-/idna.o8.2.0)/:.str.-/idna.c.:.(/..text.+/0xa8.).:/ x86_64undefined- w64reference- mingw32to/ lib`/idn_free.'.
//libhome//libgnutls.ajames(/strffmpeg--idna.owindows)-:buildstr--helpersidna.c/:sandbox(/.cross_compilerstext/+mingw0xa8-)w64:- x86_64undefined/ libreference/ gccto/ x86_64`-idn_freew64'-
mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64bin//libld/:gcc //x86_64home-/w64james-/mingw32ffmpeg/-8.2.0windows/-.build.-/helpers./.sandbox//.cross_compilers.//mingw.-.w64/-x86_64x86_64-/w64lib-/mingw32gcc//binx86_64/-ldw64:- mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64lib//lib./.gcc//libx86_64/-libgnutls.aw64(-strmingw32-/idna.o8.2.0)/:.str.-/idna.c.:.(/..text.+/0x1f3.).:/ x86_64undefined- w64reference- mingw32to/ lib`/idna_strerror.'.
//libhome//libgnutls.ajames(/strffmpeg--idna.owindows)-:buildstr--helpersidna.c/:sandbox(/.cross_compilerstext/+mingw0x1f3-)w64:- x86_64undefined/ libreference/ gccto/ x86_64`-idna_strerrorw64'-
mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64bin//libld/:gcc //x86_64home-/w64james-/mingw32ffmpeg/-8.2.0windows/-.build.-/helpers./.sandbox//.cross_compilers.//mingw.-.w64/-x86_64x86_64-/w64lib-/mingw32gcc//binx86_64/-ldw64:- mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64lib//lib./.gcc//libx86_64/-libgnutls.aw64(-strmingw32-/idna.o8.2.0)/:.str.-/idna.c.:.(/..text.+/0x2ea.).:/ x86_64undefined- w64reference- mingw32to/ lib`/idna_to_unicode_8z8z.'.
//libhome//libgnutls.ajames(/strffmpeg--idna.owindows)-:buildstr--helpersidna.c/:sandbox(/.cross_compilerstext/+mingw0x2ea-)w64:- x86_64undefined/ libreference/ gccto/ x86_64`-idna_to_unicode_8z8zw64'-
mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64bin//libld/:gcc //x86_64home-/w64james-/mingw32ffmpeg/-8.2.0windows/-.build.-/helpers./.sandbox//.cross_compilers.//mingw.-.w64/-x86_64x86_64-/w64lib-/mingw32gcc//binx86_64/-ldw64:- mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64lib//lib./.gcc//libx86_64/-libgnutls.aw64(-strmingw32-/idna.o8.2.0)/:.str.-/idna.c.:.(/..text.+/0x332.).:/ x86_64undefined- w64reference- mingw32to/ lib`/idn_free.'.
//libhome//libgnutls.ajames(/strffmpeg--idna.owindows)-:buildstr--helpersidna.c/:sandbox(/.cross_compilerstext/+mingw0x332-)w64:- x86_64undefined/ libreference/ gccto/ x86_64`-idn_freew64'-
mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64bin//libld/:gcc //x86_64home-/w64james-/mingw32ffmpeg/-8.2.0windows/-.build.-/helpers./.sandbox//.cross_compilers.//mingw.-.w64/-x86_64x86_64-/w64lib-/mingw32gcc//binx86_64/-ldw64:- mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64lib//lib./.gcc//libx86_64/-libgnutls.aw64(-strmingw32-/idna.o8.2.0)/:.str.-/idna.c.:.(/..text.+/0x3d3.).:/ x86_64undefined- w64reference- mingw32to/ lib`/idna_strerror.'.
//libhome//libgnutls.ajames(/strffmpeg--idna.owindows)-:buildstr--helpersidna.c/:sandbox(/.cross_compilerstext/+mingw0x3d3-)w64:- x86_64undefined/ libreference/ gccto/ x86_64`-idna_strerrorw64'-
mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64bin//libld/:gcc //x86_64home-/w64james-/mingw32ffmpeg/-8.2.0windows/-.build.-/helpers./.sandbox//.cross_compilers.//mingw.-.w64/-x86_64x86_64-/w64lib-/mingw32gcc//binx86_64/-ldw64:- mingw32//home8.2.0//james./.ffmpeg/-.windows.-/build.-.helpers//.sandbox.//cross_compilersx86_64/-mingww64--w64mingw32-/x86_64lib//lib./.gcc//libx86_64/-libgnutls.aw64(-strmingw32-/idna.o8.2.0)/:.str.-/idna.c.:.(/..rdata$.refptr.idn_free.[/..refptr.idn_free.]/+x86_640x0-)w64:- mingw32undefined/ libreference/ .to. /`libidn_free/'libgnutls.a
(collect2: error: ld returned 1 exit status
str-idna.o):str-idna.c:(.rdata$.refptr.idn_free[.refptr.idn_free]+0x0): undefined reference to `idn_free'
collect2: error: ld returned 1 exit status
CMakeFiles/srt-live-transmit.dir/build.make:108: recipe for target 'srt-live-transmit.exe' failed
make[2]: *** [srt-live-transmit.exe] Error 1
CMakeFiles/Makefile2:180: recipe for target 'CMakeFiles/srt-live-transmit.dir/all' failed
make[1]: *** [CMakeFiles/srt-live-transmit.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/srt-file-transmit.dir/build.make:108: recipe for target 'srt-file-transmit.exe' failed
make[2]: *** [srt-file-transmit.exe] Error 1
CMakeFiles/Makefile2:255: recipe for target 'CMakeFiles/srt-file-transmit.dir/all' failed
make[1]: *** [CMakeFiles/srt-file-transmit.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
</p>
</details>

**Comment by rdp** [comment]
Nuke that

srt_git folder first, it will have some outdated configure options... :)

**Comment by cdgriffith** [comment]
That did it, pulled to latest and removed the `srt_git` folder let it continue 👍

**Comment by Mr-Antivirus** [comment]
Yep, confirmed fixed. Thanks!
