### ISSUE TITLE
openh264 not found using pkg-config

### ISSUE THREAD

**Issue by Phane7** [rdp/ffmpeg-windows-build-helpers#380]
After working through some distro and configure issues on my own, the script was working on 2/25/19.  Between now and then, something broke it, though.  Now it bombs out when trying to configure ffmpeg with "ERROR: openh264 not found using pkg-config"  full configure output as follows:

`config options --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libaom --enable-libopenjpeg --enable-libopenh264 --enable-liblensfun --enable-libvmaf --enable-libsrt --enable-demuxer=dash --enable-libxml2 --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-avisynth --enable-frei0r --enable-filter=frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxavs --enable-avresample --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-nonfree --enable-decklink --enable-libfdk-aac ./configure
ERROR: openh264 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
`

**Comment by rdp** [comment]
bottom (poignant) part of ffmpeg_git/ffbuild/config.log please?

**Comment by Phane7** [comment]
I think this is the relevant portion.

'/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc -Wl,--nxcompat,--dynamicbase -Wl,--high-entropy-va -Wl,--as-needed -Wl,--pic-executable,-e,mainCRTStartup -Wl,--image-base,0x140000000 -I/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include -L/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib -o /tmp/ffconf.5aczVQ7X/test.exe /tmp/ffconf.5aczVQ7X/test.o -lopenh264 -lstdc++ -lpthread -lm -lharfbuzz
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x3a9): undefined reference to `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x3a9): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x3de): undefined reference to `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x3de): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x4a3): undefined reference to `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x4a3): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x592): undefined reference to `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x592): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x610): undefined reference to `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x610): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x692): more undefined references to `__stack_chk_fail' follow
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x692): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x76c): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x962): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0x9ee): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0xa61): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.text+0xd25): additional relocation overflows omitted from the output
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsEncoderExt.o):welsEncoderExt.cpp:(.rdata$.refptr.__stack_chk_guard[.refptr.__stack_chk_guard]+0x0): undefined reference to `__stack_chk_guard'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(utils.o):utils.cpp:(.text+0x13a): undefined reference to `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(utils.o):utils.cpp:(.text+0x7ff): undefined reference to `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsCodecTrace.o):welsCodecTrace.cpp:(.text+0x71): undefined reference to `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsCodecTrace.o):welsCodecTrace.cpp:(.text+0xc4): undefined reference to `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsCodecTrace.o):welsCodecTrace.cpp:(.text+0x114): undefined reference to `__stack_chk_fail'
/home/phane/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenh264.a(welsCodecTrace.o):welsCodecTrace.cpp:(.text+0x175): more undefined references to `__stack_chk_fail' follow
collect2: error: ld returned 1 exit status
ERROR: openh264 not found using pkg-config'

**Comment by rdp** [comment]
OK try again, made a blind attempt at it...

**Comment by Phane7** [comment]
Still not working, sorry.

**Comment by darth2499** [comment]
Your newest commits have fixed this issue for me.

**Comment by Phane7** [comment]
Confirmed.  It's working now.  Thanks a lot for the help!

**Comment by AndCycle** [comment]
openh264 have moved global compile flag to platform specific
https://github.com/cisco/openh264/commit/963f51e2fa17c8af5de425f01747bece2037c967

it's no longer necessary to pin the git version.

**Comment by rdp** [comment]
unpinned it, thanks for the note.

**Comment by donradzsk** [comment]
Got this error just now. I'm building it on Windows 10 using the Ubuntu app. Is there a fix?

End of config.log:
`/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-gcc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U__STRICT_ANSI__ -D__USE_MINGW_ANSI_STDIO=1 -D__printf__=__gnu_printf__ -D_WIN32_WINNT=0x0600 -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -mtune=generic -O3 -DLIBTWOLAME_STATIC -DMODPLUG_STATIC -DCACA_STATIC -mtune=generic -O3 -std=c11 -fomit-frame-pointer -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -pthread -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libpng16 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -DLIBXML_STATIC -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libxml2 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/fribidi -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/freetype2 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libpng16 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/harfbuzz -DLIBXML_STATIC -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libxml2 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/freetype2 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libpng16 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/harfbuzz -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/bs2b -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -DLIBXML_STATIC -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libxml2 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/freetype2 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libpng16 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/harfbuzz -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/freetype2 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libpng16 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/harfbuzz -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/fribidi -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -pthread -mms-bitfields -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/lensfun -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/glib-2.0 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/glib-2.0/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -c -o /tmp/ffconf.4hck4W8F/test.o /tmp/ffconf.4hck4W8F/test.c
/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-gcc -Wl,--large-address-aware -Wl,--nxcompat,--dynamicbase -Wl,--as-needed -Wl,--pic-executable,-e,_mainCRTStartup -o /tmp/ffconf.4hck4W8F/test.exe /tmp/ffconf.4hck4W8F/test.o -lopencore-amrwb -lpthread -lmpg123 -lshlwapi -lm -lharfbuzz
require_pkg_config libopenh264 openh264 wels/codec_api.h WelsGetCodecVersion
check_pkg_config libopenh264 openh264 wels/codec_api.h WelsGetCodecVersion
test_pkg_config libopenh264 openh264 wels/codec_api.h WelsGetCodecVersion
pkg-config --exists --print-errors openh264
check_func_headers wels/codec_api.h WelsGetCodecVersion -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/openh264 -L/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib -lopenh264 -lstdc++
test_ld cc -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/openh264 -L/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib -lopenh264 -lstdc++
test_cc -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/openh264 -L/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib
BEGIN /tmp/ffconf.4hck4W8F/test.c
    1	#include <wels/codec_api.h>
    2	#include <stdint.h>
    3	long check_WelsGetCodecVersion(void) { return (long) WelsGetCodecVersion; }
    4	int main(void) { int ret = 0;
    5	 ret |= ((intptr_t)check_WelsGetCodecVersion) & 0xFFFF;
    6	return ret; }
END /tmp/ffconf.4hck4W8F/test.c
/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-gcc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U__STRICT_ANSI__ -D__USE_MINGW_ANSI_STDIO=1 -D__printf__=__gnu_printf__ -D_WIN32_WINNT=0x0600 -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -mtune=generic -O3 -DLIBTWOLAME_STATIC -DMODPLUG_STATIC -DCACA_STATIC -mtune=generic -O3 -std=c11 -fomit-frame-pointer -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -pthread -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libpng16 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -DLIBXML_STATIC -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libxml2 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/fribidi -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/freetype2 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libpng16 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/harfbuzz -DLIBXML_STATIC -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libxml2 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/freetype2 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libpng16 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/harfbuzz -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/bs2b -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -DLIBXML_STATIC -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libxml2 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/freetype2 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libpng16 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/harfbuzz -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/freetype2 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/libpng16 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/harfbuzz -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/fribidi -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -pthread -mms-bitfields -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/lensfun -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/glib-2.0 -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/glib-2.0/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include -I/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/include/openh264 -L/home/joe/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib -c -o /tmp/ffconf.4hck4W8F/test.o /tmp/ffconf.4hck4W8F/test.c
/tmp/ffconf.4hck4W8F/test.c:1:10: fatal error: wels/codec_api.h: No such file or directory
    1 | #include <wels/codec_api.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
ERROR: openh264 not found using pkg-config`

**Comment by rdp** [comment]
Do you have the file codec_api.h anywhere?
