### ISSUE TITLE
FontConfig download fails because freedesktop.org is no longer online

### ISSUE THREAD

**Issue by rboy1** [rdp/ffmpeg-windows-build-helpers#381]
Looks like the website has been offline for 4 days and may not come back any time soon so the build is failing.

Instead of downloading from freedesktop.org you can have the script download fontconfig from
`https://github.com/freedesktop/fontconfig/archive/2.12.4.tar.gz`

**Comment by rboy1** [comment]
You would also need to pass the directory name as `fontconfig-2.12.4` to the download and unpack method since the filename in the url above doesn't match the directory name when it's extracted

**Comment by rboy1** [comment]
And you also need to add `python-lxml` as the list of package dependencies required to build ffmpeg/fontconfig

**Comment by rdp** [comment]
Which package needs it/fails without it? which os?

**Comment by rboy1** [comment]
Trying to build ffmpeg for Windows using Ubuntu 16.04

**Comment by rdp** [comment]
OK seems it's back.  What exact error message?

**Comment by rboy1** [comment]
Yup, I'm going to close this
