### ISSUE TITLE
"Could not find the following execs" during compile commands

### ISSUE THREAD

**Issue by Sunboyz21** [rdp/ffmpeg-windows-build-helpers#382]
Clean install on unbuntu 18.0.4, used exact same commands and everything, but whenever i try to compile - it just says this:

`Could not find the following execs (svn is actually package subversion, makeinfo is actually package texinfo, hg is actually package mercurial if you're missing them): libtoolize cmake autogen gperf nasm unzip pax hg g++ makeinfo bison flex cvs yasm automake autoconf gcc svn make pkg-config ragel
Install the missing packages before running this script.
for ubuntu: $ sudo apt-get install subversion ragel curl texinfo g++ bison flex cvs yasm automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev mercurial unzip pax nasm gperf autogen bzip2 autoconf-archive p7zip-full python3-distutils -y`

There were more before this but i had already "sudo-apt" them and they vanished. These never go away and will aways pop up. When I try to sudo-apt the above error, (using provided command), this pops up:

`Reading package lists... Done
Building dependency tree
Reading state information... Done
Package autoconf-archive is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package mercurial is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package p7zip-full is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package subversion is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'subversion' has no installation candidate
E: Unable to locate package ragel
E: Unable to locate package textinfo
E: Unable to locate package cvs
E: Unable to locate package yasm
E: Package 'mercurial' has no installation candidate
E: Unable to locate package nasm
E: Unable to locate package gperf
E: Unable to locate package autogen
E: Package 'autoconf-archive' has no installation candidate
E: Package 'p7zip-full' has no installation candidate
E: Unable to locate package phython3-distutils`

It says to install the missing packages but how  would i do that?

**Comment by rdp** [comment]
OK attempted to add better instructions, give it a shot

**Comment by rdp** [comment]
the trick was `apt update` seems...
