### ISSUE TITLE
ginstall: cannot create regular file '/bin/cacademo': Operation not permitted

### ISSUE THREAD

**Issue by fmaxx** [rdp/ffmpeg-windows-build-helpers#383]
macos mojave: 10.14.3
xcode: 10.1 (10B61).

run: ./cross_compile_ffmpeg.sh --enable-gpl=n 
// tried [sudo ./cross_compile_ffmpeg.sh --enable-gpl=n], same error

error:
libtool: install: /usr/local/bin/ginstall -c cacademo /bin/cacademo
ginstall: cannot create regular file '/bin/cacademo': Operation not permitted
make[2]: *** [install-binPROGRAMS] Error 1
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1

----------------------------------
full output:
cmake binary for this build will be cmake
warning: you may need to install zlib development headers first if you want to build mp4-box [on ubuntu: $ apt-get install zlib1g-dev] [on redhat/fedora distros: $ yum install zlib-devel]
Tue Mar 26 12:22:51 +05 2019
     ##################### Welcome ######################
  Welcome to the ffmpeg cross-compile builder-helper script.
  Downloads and builds will be installed to directories within /Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox
  If this is not ok, then exit now, and cd to the directory where you'd
  like them installed, then run this script again from there.
  NB that once you build your compilers, you can no longer rename/move
  the sandbox directory, since it will have some hard coded paths in there.
  You can, of course, rebuild ffmpeg from within it, etc.
sit back, this may take awhile...
What version of MinGW-w64 would you like to build or update?
  1. Both Win32 and Win64
  2. Win32 (32-bit only)
  3. Win64 (64-bit only)
  4. Local native
  5. Exit
Input your choice [1-5]: 4
native build, not building any cross compilers...
starting native build...
realpath: /Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native: No such file or directory
realpath: /Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/bin: No such file or directory
Building ffmpeg dependency libraries...
doing git checkout origin/master
HEAD is now at 4e22f33... Merge pull request #51 from nmcclatchey/bugfix-2019-02-22
fetched no code changes, not forcing reconfigure for that...
Already made zlib-1.2.11 ...
doing git checkout f1267fbd3cd3635a
M	caca/caca.h
M	caca/caca0.h
M	caca/figfont.c
M	caca/string.c
HEAD is now at f1267fb... Fix copyright headers so that the testsuite passes again.
fetched no code changes, not forcing reconfigure for that...
Already made libcaca_git ...
make installing /Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/native/libcaca_git as $ PATH=:$PATH make install 
Making install in kernel
make[2]: Nothing to be done for `install-data-am'.
Making install in caca
Making install in .
  CC       libcaca_la-caca.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-caca_conio.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-caca0.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-canvas.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-dirty.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-string.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-transform.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-charset.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-attr.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-line.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-box.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-conic.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-triangle.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-frame.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-dither.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
dither.c:1117:24: warning: taking the absolute value of unsigned type 'unsigned int' has no effect [-Wabsolute-value]
                dist = abs(rgba[0] * (2*dchmax-1) - newr)
                       ^
dither.c:1117:24: note: remove the call to 'abs' since unsigned values cannot be negative
                dist = abs(rgba[0] * (2*dchmax-1) - newr)
                       ^~~
dither.c:1118:24: warning: taking the absolute value of unsigned type 'unsigned int' has no effect [-Wabsolute-value]
                     + abs(rgba[1] * (2*dchmax-1) - newg)
                       ^
dither.c:1118:24: note: remove the call to 'abs' since unsigned values cannot be negative
                     + abs(rgba[1] * (2*dchmax-1) - newg)
                       ^~~
dither.c:1119:24: warning: taking the absolute value of unsigned type 'unsigned int' has no effect [-Wabsolute-value]
                     + abs(rgba[2] * (2*dchmax-1) - newb);
                       ^
dither.c:1119:24: note: remove the call to 'abs' since unsigned values cannot be negative
                     + abs(rgba[2] * (2*dchmax-1) - newb);
                       ^~~
dither.c:1322:21: warning: cast from 'const uint8_t *' (aka 'const unsigned char *') to 'const uint32_t *' (aka 'const unsigned int *') increases required
      alignment from 1 to 4 [-Wcast-align]
            bits = *(uint32_t const *)pixels;
                    ^~~~~~~~~~~~~~~~~~~~~~~~
dither.c:1343:21: warning: cast from 'const uint8_t *' (aka 'const unsigned char *') to 'const uint16_t *' (aka 'const unsigned short *') increases required
      alignment from 1 to 2 [-Wcast-align]
            bits = *(uint16_t const *)pixels;
                    ^~~~~~~~~~~~~~~~~~~~~~~~
dither.c:207:20: warning: unused function 'rgb2hsv_default' [-Wunused-function]
static inline void rgb2hsv_default(int r, int g, int b,
                   ^
6 warnings generated.
  CC       libcaca_la-font.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-file.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-figfont.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-graphics.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-event.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-time.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-prof.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       libcaca_la-getopt.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       codec/libcaca_la-import.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       codec/libcaca_la-export.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       codec/libcaca_la-text.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       driver/libcaca_la-null.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       driver/libcaca_la-raw.lo
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  OBJCLD   libcaca.la
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-prof.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-conio.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-ncurses.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-slang.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-vga.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-win32.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-x11.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-gl.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-prof.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-conio.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-ncurses.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-slang.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-vga.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-win32.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-x11.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcaca.a(libcaca_la-gl.o) has no symbols
 /usr/local/bin/gmkdir -p '/lib'
 /bin/sh ../libtool   --mode=install /usr/local/bin/ginstall -c   libcaca.la '/lib'
libtool: install: /usr/local/bin/ginstall -c .libs/libcaca.lai /lib/libcaca.la
libtool: install: /usr/local/bin/ginstall -c .libs/libcaca.a /lib/libcaca.a
libtool: install: chmod 644 /lib/libcaca.a
libtool: install: ranlib /lib/libcaca.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /lib/libcaca.a(libcaca_la-prof.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /lib/libcaca.a(libcaca_la-conio.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /lib/libcaca.a(libcaca_la-ncurses.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /lib/libcaca.a(libcaca_la-slang.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /lib/libcaca.a(libcaca_la-vga.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /lib/libcaca.a(libcaca_la-win32.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /lib/libcaca.a(libcaca_la-x11.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /lib/libcaca.a(libcaca_la-gl.o) has no symbols
 /usr/local/bin/gmkdir -p '/include'
 /usr/local/bin/ginstall -c -m 644 caca.h caca_types.h caca_conio.h caca0.h '/include'
 /usr/local/bin/gmkdir -p '/lib/pkgconfig'
 /usr/local/bin/ginstall -c -m 644 caca.pc '/lib/pkgconfig'
Making install in t
  CC       simple.o
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CCLD     simple
ld: warning: directory not found for option '-L/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/lib'
  CC       bench.o
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CCLD     bench
ld: warning: directory not found for option '-L/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/lib'
  CC       bug-setlocale.o
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CCLD     bug-setlocale
ld: warning: directory not found for option '-L/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/lib'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in src
  CC       cacademo.o
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CCLD     cacademo
ld: warning: directory not found for option '-L/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/lib'
  CC       aafire.o
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CCLD     cacafire
ld: warning: directory not found for option '-L/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/lib'
  CC       cacaplay.o
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CCLD     cacaplay
ld: warning: directory not found for option '-L/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/lib'
  CC       cacaview-cacaview.o
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       cacaview-common-image.o
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CCLD     cacaview
ld: warning: directory not found for option '-L/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/lib'
  CC       img2txt-img2txt.o
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CC       img2txt-common-image.o
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CCLD     img2txt
ld: warning: directory not found for option '-L/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/lib'
  CC       cacaclock.o
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CCLD     cacaclock
ld: warning: directory not found for option '-L/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/lib'
  CC       cacaserver.o
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CCLD     cacaserver
ld: warning: directory not found for option '-L/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/lib'
  CC       cacadraw.o
clang: warning: optimization flag '-fno-strength-reduce' is not supported [-Wignored-optimization-argument]
  CCLD     cacadraw
ld: warning: directory not found for option '-L/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/lib'
 /usr/local/bin/gmkdir -p '/bin'
  /bin/sh ../libtool   --mode=install /usr/local/bin/ginstall -c cacademo cacafire cacaplay cacaview img2txt cacaclock cacaserver '/bin'
libtool: install: /usr/local/bin/ginstall -c cacademo /bin/cacademo
ginstall: cannot create regular file '/bin/cacademo': Operation not permitted
make[2]: *** [install-binPROGRAMS] Error 1
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1

**Comment by rdp** [comment]
OK hopefully fixed, thanks for the report!

**Comment by fmaxx** [comment]
I've tried the latest code...

error:
**configure: error: darwin18.2.0 not supported.**

partial output (too long):
....
configuring mfx_dispatch_git (/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/native/mfx_dispatch_git) as $ PKG_CONFIG_PATH=/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/lib/pkgconfig PATH=/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/bin:$PATH ./configure --host= --prefix=/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native --disable-shared --enable-static 
all touch files already_configured* touchname= already_configured_0918eab0e841f99f5f275b1af08d28b7
config options --host= --prefix=/Volumes/SD/111/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native --disable-shared --enable-static ./configure
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-apple-darwin18.2.0
checking host system type... x86_64-apple-darwin18.2.0
configure: error: darwin18.2.0 not supported.

**Comment by rdp** [comment]
try with --compiler-flavors=native

**Comment by fmaxx** [comment]
ok, next one:
**ERROR: gnutls not found using pkg-config**

I've tried [pkg-config --list-all | grep gnutls]:
_gnutls-dane           GnuTLS-DANE - DANE security library for the GNU system
gnutls                GnuTLS - Transport Security Layer implementation for the GNU system_

partial output:
_doing git checkout origin/master
M	libavfilter/vf_frei0r.c
HEAD is now at b131a07... fate: unbreak fate with custom binary names
fetched no code changes, not forcing reconfigure for that...
configuring ffmpeg_git_xp_compat_lgpl (/Volumes/SD/1/ffmpeg-windows-build-helpers/sandbox/native/ffmpeg_git_xp_compat_lgpl) as $ PKG_CONFIG_PATH=/Volumes/SD/1/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/lib/pkgconfig PATH=/Volumes/SD/1/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native/bin:$PATH ./configure --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libaom --enable-libopenjpeg  --enable-libopenh264 --enable-liblensfun  --enable-libvmaf --enable-libsrt --enable-demuxer=dash --enable-libxml2 --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --disable-libmfx --enable-avresample --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static --disable-shared --prefix=/Volumes/SD/1/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native 
all touch files already_configured* touchname= already_configured_2ed33ca0c4888e98f8f49250359e697d
config options --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libaom --enable-libopenjpeg --enable-libopenh264 --enable-liblensfun --enable-libvmaf --enable-libsrt --enable-demuxer=dash --enable-libxml2 --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --disable-libmfx --enable-avresample --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static --disable-shared --prefix=/Volumes/SD/1/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native ./configure_

**Comment by rdp** [comment]
OK I just tried it locally and it configured OK.  Check the bottom of your sandbox/native/ffmpeg

It uses a local copy of gnutls so you'd have to run it like `PKG_CONFIG_PATH=xxx pkg-config ...` to see the local packages, or search for a file "gnutls.pc" in your sandbox, FWIW...

**Comment by rdp** [comment]
please reopen if still a problem, thanks!
