### ISSUE TITLE
Compile fail ffmpeg

### ISSUE THREAD

**Issue by rhadamants** [rdp/ffmpeg-windows-build-helpers#385]
If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

/build/fail_comp: line 1: declare: `'': not a valid identifier
/build/fail_comp: line 1: declare: `'': not a valid identifier
/build/fail_comp: line 1: declare: `'': not a valid identifier
/build/fail_comp: line 1: declare: `'': not a valid identifier
This is required for other packages, so this script will exit.

All relevant logs have been anonymously uploaded to https://0x0.st/zNYM.zip
Copy and paste [logs.zip](https://0x0.st/zNYM.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by rdp** [comment]
full console output please?

**Comment by rhadamants** [comment]
Only this log https://0x0.st/zNYM.zip

**Comment by rdp** [comment]
Hmm is this from media-autobuild ? (which is not this project fwiw...)
