### ISSUE TITLE
Compile with latest libaom

### ISSUE THREAD

**Issue by cdgriffith** [rdp/ffmpeg-windows-build-helpers#386]
Hello, I see that 7 months ago libaom was set at a fixed commit https://github.com/rdp/ffmpeg-windows-build-helpers/commit/5965cba4685a4275ab27bdbf012259b984a6f40a , I was wondering if there was an easy way to test to see if that issue is still happening with their master branch. (like does it fail to compile, or something harder to detect.) 

Just as libaom is a new thing it has lots of updates since then and wanted to get as latest as possible while still having VP9 support. 

Thanks!

**Comment by rdp** [comment]
appears to be working, thanks!
