### ISSUE TITLE
default 8, 10, 12 bit support for libx265

### ISSUE THREAD

**Issue by Yrosma** [rdp/ffmpeg-windows-build-helpers#387]
apparently since some time in ffmpeg it is now possible to have 8, 10 and even 12 bit support for libx265 in one build.

8 and 10 bit are also possible for lib264. With the latest build I made a month ago I saw 8 and 10 bit for libx264 is already possible with the "normal" ffmpeg build so the highbitdepth build is not needed for libx264 to do 10 bit encodes.

But for libx265 the "normal" build only can encode 8 bits and the highbithdepth build is still needed to be able to encode 10 bit while this shouldn't be needed anymore for libx265

**Comment by rdp** [comment]
Hmm it's a bit confusing what's going on there, the x265 CMakeLists.txt:


    # You will need to disable assembly manually.
    option(HIGH_BIT_DEPTH "Store pixel samples as 16bit values (Main10/Main12)" OFF)
endif(X64)
if(HIGH_BIT_DEPTH)
    option(MAIN12 "Support Main12 instead of Main10" OFF)
    if(MAIN12)
        add_definitions(-DHIGH_BIT_DEPTH=1 -DX265_DEPTH=12)
    else()
        add_definitions(-DHIGH_BIT_DEPTH=1 -DX265_DEPTH=10)
    endif()
else(HIGH_BIT_DEPTH)
    add_definitions(-DHIGH_BIT_DEPTH=0 -DX265_DEPTH=8)
endif(HIGH_BIT_DEPTH)


it's not clear which parameters to support "more than one" at the same time...

**Comment by rdp** [comment]
anyway there's already an option for "high bit depth" or not, which I think varies it from 8 to 10, let me know if you need more somehow...

-high-bitdepth=n
