### ISSUE TITLE
srt was recently updated and build failed.

### ISSUE THREAD

**Issue by ntropy25** [rdp/ffmpeg-windows-build-helpers#390]
As noted at the title, srt was updated and the recent version can't be built.
srt-v1.3.2 worked and I modified build_libsrt() as follows:

build_libsrt() {
    **download_and_unpack_file https://codeload.github.com/Haivision/srt/tar.gz/v1.3.2 srt-1.3.2
    cd srt-1.3.2**
    if [[ $compiler_flavors != "native" ]]; then
      do_cmake "-DUSE_GNUTLS=ON -DENABLE_SHARED=OFF"
      apply_patch file://$patch_dir/srt.app.patch -p1
    else
      do_cmake "-DUSE_GNUTLS=ON -DENABLE_SHARED=OFF -DENABLE_CXX11=OFF"
    fi
    do_make_and_make_install
  cd ..
}

**Comment by rdp** [comment]
good find, thanks!
