### ISSUE TITLE
Use of https may result in error

### ISSUE THREAD

**Issue by cdlvcdlv** [rdp/ffmpeg-windows-build-helpers#395]
Depending on your local configuration, you can get a secure channel error when trying to download x64 setup for cygwin:
`The request was aborted: Could not create SSL/TLS secure channel.`

The x86 download is http, while the x64 one is https.

This can be avoid either adding a Tls12 request or simply using the http download available from cygwin:
`powershell -command "$clnt = new-object System.Net.WebClient; [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; $clnt.DownloadFile(\"https://www.cygwin.com/setup-x86.exe\", \"setup-x86.exe\")"`

Or...
`powershell -command "$clnt = new-object System.Net.WebClient; $clnt.DownloadFile(\"http://www.cygwin.com/setup-x86.exe\", \"setup-x86.exe\")"`

**Comment by rdp** [comment]
We don't actually have cygwin in there anymore do we? Is it around
somewhere?

**Comment by cdlvcdlv** [comment]
This line is inside `native_build\windows\build_locally_with_various_option_prompts.bat`.

**Comment by rdp** [comment]
see discussion in #396
