### ISSUE TITLE
Missing ragel package in native build

### ISSUE THREAD

**Issue by cdlvcdlv** [rdp/ffmpeg-windows-build-helpers#396]
Batch file `build_locally_with_various_option_prompts.bat` needs `,ragel` at the end of both x86 and x64 package lists.
```
--packages ^
ed,curl,libcurl4,wget,subversion,texinfo,gcc-g++,bison,flex,cvs,yasm,automake,libtool,autoconf,gcc-core,cmake,git,make,pkg-config,zlib1g-dev,mercurial,unzip,pax,ncurses,patch,gettext-devel,nasm,p7zip,gperf,autogen,ragel
```

**Comment by rdp** [comment]
OK yeah the cygwin stuff is supposed to be deprecated pretend it doesn't exist for now, carry on :)

**Comment by cdlvcdlv** [comment]
README.md says
> On Windows 10, you can use the bash shell (provided that you've installed the Windows Subsystem for Linux

You cannot natively compile anymore in previous versions of Windows? I mean, if cygwin is deprecated.

**Comment by rdp** [comment]
virtualbox?

**Comment by cdlvcdlv** [comment]
I wouldn't call 'natively' installing a complete OS in a virtual machine. 

But, anyway, it is a much heavier download, much longer to implement (you must download the installer and install the OS just to get started), you need administrator rights, installing drivers in the system, a CPU with virtualization, additional memory...

On the other hand, the old way works in any borrowed machine: you launch it, save the builds once finished, erase the folder and you're done. Significant less time, bandwidth, CPU, memory and disk storage needed, no system mess at all and almost automated. That's what I love of your helpers. It's not just a matter of taste -- there are objective measures. (Deprecated why?)

Just saying...

**Comment by rdp** [comment]
Yeah it was deprecated in favor of wsl...to reduce maintenance overhead (for instance, I couldn't use cygwin x86_64 to build it, it caused some package or other to not work, I had to use 32-bit, that kind of stuff scared me).  Not to mention the builds IIRC took practically forever in cygwin :)

**Comment by rdp** [comment]
removed cygwin for now, thank you for the report! (though ragel was added I think, before it was removed, if you want that, go back to the last commit that has cygwin, 0c123bc7e64eae57eea750f9c362c7d705f75059
