### ISSUE TITLE
Ubuntu 18.04.2 freetype fails due to missing libbz2

### ISSUE THREAD

**Issue by kode54** [rdp/ffmpeg-windows-build-helpers#397]
I installed the kit on a freshly created Ubuntu 18.04.2 Server virtual machine, freshly upgraded to today's available packages, and installed the required packages mentioned by the script.

I altered the script in the following way:

https://gist.github.com/kode54/f48abb70cad69be3264101a5debba7cc

And ran it:

```
$ ./cross_compile_ffmpeg.sh --build-ffmpeg-shared=y --build-ffmpeg-static=n --gcc-cpu-count=16 --build-intel-qsv=n --compiler-flavors=multi
```

And it fails with the following config.log from freetype:

https://gist.github.com/kode54/a8d630fbc3a54c1dbb6293da825c7f54

It appears to be failing to find libbz2, somehow.

**Comment by rdp** [comment]
try it with the latest

**Comment by kode54** [comment]
Yes, that fixed it, thanks.
