### ISSUE TITLE
Can´t compile win64 or multi target

### ISSUE THREAD

**Issue by Classsic** [rdp/ffmpeg-windows-build-helpers#398]
I try to compile in latest ubuntu version. I get the right .exe when use : 
`./cross_compile_ffmpeg.sh --disable-nonfree=n  --compiler-flavors=win32`
but when try with:
 `./cross_compile_ffmpeg.sh --disable-nonfree=n  --compiler-flavors=win64 ` 
or
 `./cross_compile_ffmpeg.sh --disable-nonfree=n  --compiler-flavors=multi`
I get this error:
`**************Starting 64-bit builds...
Building ffmpeg dependency libraries...
doing git checkout origin/master
M       Makefile
HEAD is now at e476c01 Merge pull request #58 from pali/master
fetched no code changes, not forcing reconfigure for that...
configuring dlfcn-win32_git (/root/ffmpeg-windows-build-helpers/sandbox/win64/dlfcn-win32_git) as $ PKG_CONFIG_PATH=/root/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/root/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --prefix=/root/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --cross-prefix=/root/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-
all touch files already_configured* touchname= already_configured_c527796e6c268b7b5cf7fb170e772dbb-
config options --prefix=/root/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --cross-prefix=/root/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- ./configure
testing compiler: /root/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc -shared -o tmptest.dll tmptest.c
/root/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgcc
/root/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status
/root/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc could not create shared file with Windows API functions.
Make sure your MinGW system is working properly.`
Any clue about this?
thanks.

**Comment by rdp** [comment]
Hmm first example works OK here...nuke sandbox and it fails again?
Does this file exist?
sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.2.0/libgcc.a
(it should...)

**Comment by rdp** [comment]
closing no feedback, please reopen if desired
