### ISSUE TITLE
Wrong link to xvidcore

### ISSUE THREAD

**Issue by z1trus** [rdp/ffmpeg-windows-build-helpers#399]
Site moved from .org to .com so manual change in script solve building failure.  Perhaps will be better to change it in your project too.

**Comment by rdp** [comment]
Hmm just worked here... hmm...

**Comment by z1trus** [comment]
In my brower I've got blank page, when I try to visit xvid.org, but
xvid.com works normally. I've got an error when I try crosscompile, until I change address in .sh file. Even Wikipedia says "Website	www.xvid.com"

I just decide to tell you about that.

**Comment by rdp** [comment]
Yes thanks for the note.
http://downloads.xvid.org/downloads/xvidcore-1.3.4.tar.gz works OK in my
browser? Hmm

**Comment by taroxd** [comment]
The official website <https://labs.xvid.com/source/> links to <https://downloads.xvid.com/downloads/xvidcore-1.3.5.tar.gz> .
By the way, version 1.3.5 compiles in my environment (without changing the patch file), so maybe it is a good idea to update to version 1.3.5.

**Comment by rdp** [comment]
OK bumped the version, thanks for your help.
