### ISSUE TITLE
Error cross compiling win64 binary on Ubuntu 18.04 w/ Non-Free Enabled

### ISSUE THREAD

**Issue by ufgkirk** [rdp/ffmpeg-windows-build-helpers#400]
I am attempting to compile a win64 binary with non-free components enabled on Ubuntu 18.04, but ran into an error during compilation, related to things which I had no part in specifying, so it must be a bug.

`# ./cross_compile_ffmpeg.sh --disable-nonfree=y`

> libavcodec/amfenc.c: In function 'amf_init_context':
> libavcodec/amfenc.c:216:5: error: unknown type name 'AMFContext1'; did you mean 'AMFContext'?
>      AMFContext1 *context1 = NULL;
>      ^~~~~~~~~~~
>      AMFContext
> libavcodec/amfenc.c:315:32: error: implicit declaration of function 'IID_AMFContext1'; did you mean 'IID_AMFContext'? [-Werror=implicit-function-declaration]
>                  AMFGuid guid = IID_AMFContext1();
>                                 ^~~~~~~~~~~~~~~
>                                 IID_AMFContext
> libavcodec/amfenc.c:315:32: error: invalid initializer
> libavcodec/amfenc.c:319:31: error: request for member 'pVtbl' in something not a structure or union
>                  res = context1->pVtbl->InitVulkan(context1, NULL);
>                                ^~
> libavcodec/amfenc.c:320:25: error: request for member 'pVtbl' in something not a structure or union
>                  context1->pVtbl->Release(context1);
>                          ^~
> CC	libavcodec/dct32_float.o
> cc1: some warnings being treated as errors
> ffbuild/common.mak:59: recipe for target 'libavcodec/amfenc.o' failed
> make: *** [libavcodec/amfenc.o] Error 1
> make: *** Waiting for unfinished jobs....

**Comment by ufgkirk** [comment]
It appears I get the same error with the opposite switch, FYI.
`# ./cross_compile_ffmpeg.sh --disable-nonfree=n`

**Comment by rdp** [comment]
OK worked around it for now, disabled amf.

**Comment by rdp** [comment]
hopefully fixed in fd89a42ae4ef24f221819d4e6d9e300db8f70567 response was "

Recently we added vulkan support to ffmpeg, and this change increased required version of amf.

Script cross_compile_ffmpeg.sh downloads amf from https://github.com/rdp/amf_headers.
AMF version in this repo is outdated, minimum required version for latest ffmpeg is 1.4.9(1.4.7 presents)
Latest version of amf (1.4.14) can be downloaded from https://github.com/GPUOpen-LibrariesAndSDKs/AMF"

**Comment by ufgkirk** [comment]
Issue appears fixed, I was able to compile on a vanilla Ubuntu 18 installation after installing the dependencies specified by the script's output without any problems this time. :) Thank you!
