### ISSUE TITLE
Feature request: libdav1d

### ISSUE THREAD

**Issue by krakow10** [rdp/ffmpeg-windows-build-helpers#401]
I would love to see the fast AV1 decoder dav1d added to this.  The build process described in the readme of dav1d involves meson and ninja, which doesn't match anything already in the script, which is why I don't think I could put it together myself.

**Comment by rdp** [comment]
hmm how to cross compile with meson... hmm

**Comment by hydra3333** [comment]
Apparently done over here https://github.com/DeadSix27/python_cross_compile_script

build and install the latest meson (some things require a greater version than ubuntu 18.04 has):
```
cd ~/Desktop
#git clone https://github.com/mesonbuild/meson.git
git clone --depth 1 --branch "0.51.2" https://github.com/mesonbuild/meson.git "meson_git"
cd meson_git
sudo python3 setup.py clean 
sudo python3 setup.py build
sudo python3 setup.py install 
sudo python3 setup.py check
#sudo python3 setup.py test
cd ~/Desktop
```

**Comment by Warblefly** [comment]
On Fri, Sep 20, 2019 at 12:09 AM Roger Pack <notifications@github.com>
wrote:

> hmm how to cross compile with meson... hmm
>
> On Thu, Sep 19, 2019 at 9:00 AM krakow10 <notifications@github.com> wrote:
>
> > I would love to see the fast AV1 decoder dav1d added to this. The build
> > process described in the readme of dav1d involves meson and ninja, which
>

If it's of any help, all I did, Roger, was take your generic scripts for
gnu tools, copy appropriate functions, and replace the autoconf, etc., bits
with meson and replace make with ninja.

https://raw.githubusercontent.com/Warblefly/MultimediaTools-mingw-w64/master/cross_compile_ffmpeg_shared.sh

And it works. For example, the compile for ATK is as follows:

build_atk() {
download_and_unpack_file
http://ftp.gnome.org/pub/GNOME/sources/atk/2.29/atk-2.29.1.tar.xz atk-2.29.1
  cd atk-2.29.1
    generic_meson_ninja_install
  cd ..
}

with best wishes,
JW

**Comment by rdp** [comment]
interesting very nice...

**Comment by krakow10** [comment]
I tried to compile in libdav1d by copying some functions from https://raw.githubusercontent.com/Warblefly/MultimediaTools-mingw-w64/master/cross_compile_ffmpeg_shared.sh
namely:
do_meson, generic_meson, generic_meson_ninja_install, do_ninja_and_ninja_install, build_meson_cross
And adding a top_dir variable.

I added this build function:
```
build_dav1d() {
  do_git_checkout https://code.videolan.org/videolan/dav1d.git libdav1d
  cd libdav1d
    generic_meson_ninja_install
  cd ..
}
```
and everything compiled successfully.  However, when I went to use it, ffmpeg went looking for libdav1d.dll.  I don't know enough about cross compiling to know how to "make it static"

**Comment by DeadSix27** [comment]
<https://github.com/DeadSix27/python_cross_compile_script/blob/master/packages/dependencies/libdav1d.py#L11>

Make sure this line is set, check the generic_meson.. function it prob has that default to shared.

**Comment by krakow10** [comment]
I did actually notice that the title of the script I was copying from was cross_compile_ffmpeg_shared.sh, and found that config option.  The final ffmpeg build it produces still asks for libdav1d.dll.  Does it matter whether it's --default-library static or --default-library=static with an equals sign?

**Comment by rdp** [comment]
You may have built it "shared" once or twice so it's still linking against
the .dll .a file so clear everything out and start over maybe?
By default it "prefers" linking against the .dll even if both it and the
static are present :|

**Comment by Warblefly** [comment]
On Mon, Sep 23, 2019 at 3:06 PM Roger Pack <notifications@github.com> wrote:

> You may have built it "shared" once or twice so it's still linking against
> the .dll .a file so clear everything out and start over maybe?
> By default it "prefers" linking against the .dll even if both it and the
> static are present :|
>
> On Mon, Sep 23, 2019 at 7:53 AM krakow10 <notifications@github.com> wrote:
>
> > I did actually notice that the title of the script I was copying from was
> > cross_compile_ffmpeg_shared.sh, and found that config option. The final
> > ffmpeg build it produces still asks for libdav1d.dll. Does it matter
> > whether it's --default-library static or --default-library=static with an
> > equals sign?

My script is a very scrappily modified version of Roger's, from some time
ago. But if you look through my patches, there are several examples of how
to compile a shared library where the autoconf or CMake files are written
to create only a static library.

I'm probably doing it wrongly, but it seemed scarily easy to do.

JW

**Comment by krakow10** [comment]
Once I cleared out the libdav1d.dll.a file, the build started working.  Now I have my very own cross compiled ffmpeg with dav1d decoder, very cool!

**Comment by rdp** [comment]
diffs welcome :)
