### ISSUE TITLE
gmp-6.1.2 needs a patch to cross compile

### ISSUE THREAD

**Issue by kode54** [rdp/ffmpeg-windows-build-helpers#402]
This patch comes from the Arch User Repository:

https://aur.archlinux.org/cgit/aur.git/tree/exeext.patch?h=mingw-w64-gmp

The compile time helpers that generate some of the tables will not run without it. Of course, it also won't be able to execute them without wine.

**Comment by rdp** [comment]
What failure (environment, message) does this address?

**Comment by kode54** [comment]
This addresses two failures in building the gmp package on Linux when cross compiling with mingw:

1) it can’t detect the build executable extension, because when it tests the conftest binary, it doesn’t include the extension when executing it, and Linux doesn’t auto append any extensions when searching for binaries.
2) it can’t run the generated .exe binaries used for generating tables and headers for the build process, because it again doesn’t append the extension to the name when executing them. Also, if the user does not have wine installed, and configured for binfmt execution, it can’t run them anyway.

**Comment by Reino17** [comment]
So this patch isn't necessary when you use rdp's script on Windows?
I've never had any problems with gmp on Windows anyway.

**Comment by kode54** [comment]
No, it's not necessary to build on Windows, but I wasn't even aware this repository supported building on Windows.

**Comment by Reino17** [comment]
Literally the first line of the [README](https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/README.md):
> This helper script lets you cross compile a **windows-based** 32 or 64-bit version of ffmpeg

The reason why Roger started his script, I think.

**Comment by kode54** [comment]
And right in the second paragraph:

> The script allows the user to either build on a Linux host (which uses cross compiles to build windows binaries). Windows users can use windows bash or virtualbox.

**Comment by rdp** [comment]
OK hopefully "a" gmp failure with this: https://github.com/rdp/ffmpeg-windows-build-helpers/commit/6914112b907e13fa5a9da99c13a8ec7ed6a79608 is the patch still useful/necessary? Thanks!

**Comment by rdp** [comment]
assuming fixed, thanks!
