### ISSUE TITLE
Feature request: Add support for filters availed by the ffnvcodec package.

### ISSUE THREAD

**Issue by Brainiarc7** [rdp/ffmpeg-windows-build-helpers#403]
Hello there,

Please enable support for the filters availed by the [ffnvcodec headers package](https://github.com/FFmpeg/nv-codec-headers), ie scale_cuda and [yadif_cuda](https://ffmpeg.org/ffmpeg-filters.html#yadif_005fcuda) respectively.

Similar to the current NVENC implementation, this does not require the CUDA SDK to be installed.
At the moment, the only filter that explicitly requires CUDA SDK is [scale_npp](https://ffmpeg.org/ffmpeg-filters.html#scale_005fnpp).

**Comment by hydra3333** [comment]
I'd be interested to see how you do this, as well :)

**Comment by rdp** [comment]
Appears it's possible now #430
