### ISSUE TITLE
SVT-AV1 and SVT-VP9

### ISSUE THREAD

**Issue by krakow10** [rdp/ffmpeg-windows-build-helpers#407]
In #406, I submit changes that should result in a working build that includes SVT-HEVC (Tested on ubuntu 19.04 compiling for win64).  I also include my attempt to add SVT-AV1 and SVT-VP9 in commented out bits.
ffmpeg.exe compiled with SVT-AV1 prints info but does not seem to produce video output.
SVT-AV1 conflicts with libaom-av1.

ffmpeg compiled with SVT-VP9 has some warnings when making ffmpeg_g.exe, and does not seem to produce output either, but for a different reason.  It spams the console with
[AVBSFContext @ 000001b9a8ccef40] Failed to receive packet from filter vp9_superframe for stream 0
[AVBSFContext @ 000001b9a8ccef40] Too many invisible frames
SVT-VP9 conflicts with libvpx and libxvid.

**Comment by rdp** [comment]
I think you fixed this?

**Comment by krakow10** [comment]
By swapping in some commented lines in the build_ffmpeg function, an executable can be compiled that includes either svt-av1 or avt-vp9, but neither of them produce any video output when you try to use the codec.

**Comment by krakow10** [comment]
Looks like the ffmpeg plugin for SVT-VP9 is labeled as an "upcoming feature" on their trello board.
