### ISSUE TITLE
hg clone on build_libx265 not effective

### ISSUE THREAD

**Issue by 1337umbra** [rdp/ffmpeg-windows-build-helpers#408]
Looks like something is changed, Perhaps better take a look.

I personally now am using an old fashioned way, which is downloading latest app, setting the most prefered being, which is 12-bit to suit my needs.

**Comment by rdp** [comment]
What does it say?

**Comment by 1337umbra** [comment]
nay, just holding too long.

When copying the hg clone https://(x265 thing), it shows wrong command.

Roger Pack <notifications@github.com> 於 2019年10月1日 週二 下午12:18寫道：

**Comment by rdp** [comment]
working OK here, full output please?

**Comment by rdp** [comment]
assuming fixed
