### ISSUE TITLE
libvmaf.various.patch fails to apply as vmaf repo recently re-organised

### ISSUE THREAD

**Issue by JGRennison** [rdp/ffmpeg-windows-build-helpers#411]
Various directories in the vmaf repository have been moved around as of this commit: https://github.com/Netflix/vmaf/commit/4905c3a027051753ffffe27c12951430f6b4a8e6
libvmaf.various.patch subsequently fails to apply and the build fails.

**Comment by rdp** [comment]
try it now

**Comment by JGRennison** [comment]
Thanks, that fixes building vmaf here.
