### ISSUE TITLE
Failed on Windows 10 1903 WSL

### ISSUE THREAD

**Issue by LeeThompson** [rdp/ffmpeg-windows-build-helpers#415]
The script fails on Windows 10 (1903) WSL (Debian):

```
lib -name:libfontconfig-1.dll -def:fontconfig.def -out:fontconfig.lib
/bin/bash: lib: command not found
```

**Comment by LeeThompson** [comment]
Worked around it by copying Microsoft's lib to /bin/lib which is probably a really bad thing to do but it got past that step

**Comment by LeeThompson** [comment]
And a new error:

```
checking for x86_64-w64-mingw32-gcc option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... x86_64-w64-mingw32-gcc -E
checking build system compiler x86_64-w64-mingw32-gcc... yes
checking for build system preprocessor... x86_64-w64-mingw32-gcc -E
checking for build system executable suffix... configure: error: Cannot determine executable suffix
```

**Comment by rdp** [comment]
What version of debian does it install?

**Comment by LeeThompson** [comment]
That's a really good question.   The string returned by uname doesn't seem very Debian like.

`Linux (MACHINENAME) 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 GNU/Linux`

The Microsoft Store entry:
https://www.microsoft.com/en-us/p/debian/9msvkqc78pk6?rtc=1&activetab=pivot:overviewtab

Source Tree:
https://salsa.debian.org/rhaist-guest/WSL

**Comment by rdp** [comment]
what about ubuntu wsl?

**Comment by rdp** [comment]
I don't get the lib error (ubuntu),
here's my uname -a:

Linux roger-win10 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

appears that "disabling binfmt" helps with the "unable to determine executable prefix" (gmp) ref: https://aur.archlinux.org/packages/mingw-w64-gmp/ https://docs.microsoft.com/en-us/windows/wsl/interop

**Comment by rdp** [comment]
assuming fixed, thank you.
