### ISSUE TITLE
VP9 Codec make ffmpeg crash

### ISSUE THREAD

**Issue by AeonDave** [rdp/ffmpeg-windows-build-helpers#416]
Hello, 
after **successful** compiling on Ubuntu 19.10
with
` ./cross_compile_ffmpeg.sh --compiler-flavors=win64 --gcc-cpu-count=4 --disable-nonfree=n`
Any vp9 encoding make ffmpeg "stop responding" instantly.
You can try even with example commands found here "trac.ffmpeg.org/wiki/Encode/VP9"

I've tried on 2 different computers with different Ubuntu version.
Thank you

**Comment by rdp** [comment]
You're running it on straight windows I presume?

**Comment by AeonDave** [comment]
yes i'm running the compiled ffmpeg.exe on win10

**Comment by rdp** [comment]
what does gdb say? zeranoe builds work?

**Comment by AeonDave** [comment]
Yes, zeranoe are ok. so i suppose vp9 sources are ok

**Comment by rdp** [comment]
OK try the latest, though if it works, I have no idea why...

**Comment by rdp** [comment]
latest work?

**Comment by rdp** [comment]
Assuming it does, cheers!
