### ISSUE TITLE
savannah.gnu.org

### ISSUE THREAD

**Issue by AmandaMQ** [rdp/ffmpeg-windows-build-helpers#417]
hi,

Something in the script keeps trying to access savannah.gnu.org. I've been trying to build ffmpeg for a couple days now but the script just keeps throwing a _"savannah.gnu.org seems to be offline right now and is needed to download the file "config.guess", please try again later."_

any workarounds? thanks.

**Comment by rdp** [comment]
git.savannah.gnu.org seems down hmm
<http://git.savannah.gnu.org>
I'm not as familiar with that part of the build script so don't know an
immediate work around, trying the stalling technique to see if it comes
back up... :)
try it again?

**Comment by rdp** [comment]
seems back up again.  response would be nice here...
