### ISSUE TITLE
x86_64-w64-mingw32-gcc is unable to create an executable file

### ISSUE THREAD

**Issue by Bilb** [rdp/ffmpeg-windows-build-helpers#418]
Hi,
thanks for this script which is really heplful!
I have a small issue with the build:

```
/home/audric/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc is unable to create an executable file.
C compiler test failed.
```

I cannot get the script to compile ffmpeg on win64. I think it compiled every dependencies (I removed lots of them) so far but I am currently stuck 

I join the full builds logs (of cross-compiler and FFmpeg). It looks like I have an error at the end of the cross-compiler build, but if I just restart the script it starts to build the dependency

Here are the logs with a fresh start (rm -rf sandbox/)
[build-sandbox.log](https://github.com/rdp/ffmpeg-windows-build-helpers/files/3935820/build-sandbox.log)
[ffmpeg-build.log](https://github.com/rdp/ffmpeg-windows-build-helpers/files/3935816/ffmpeg-build.log)

**Comment by Bilb** [comment]
Found out I had removed to much dependencies build without removing them from the config-options. So ld was not linking. So everything is alright!

**Comment by rdp** [comment]
Good, that one was looking a bit weird :)
