### ISSUE TITLE
meson.build:25:0: ERROR: Unknown compiler(s): [['/Users/XXX/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc']]

### ISSUE THREAD

**Issue by zelik888** [rdp/ffmpeg-windows-build-helpers#419]
When compiling on OSX 10.14, I get this error:
meson.build:25:0: ERROR: Unknown compiler(s): [['/Users/XXX/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc']]

file exists, here is a copy of the log:

Build started at 2019-12-12T09:30:24.915346
Main binary: /usr/local/opt/python/bin/python3.7
Build Options: -Dprefix=/Users/XXX/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 -Dlibdir=/Users/XXX/ffmpeg-windows-build-helpers/sandbox/cross_comp$
Python system: Darwin
The Meson build system
Version: 0.52.0
Source dir: /Users/XXX/ffmpeg-windows-build-helpers/sandbox/win64/libdav1d
Build dir: /Users/XXX/ffmpeg-windows-build-helpers/sandbox/win64/libdav1d/build
Build type: cross build
Project name: dav1d
Project version: 0.5.2
Appending CFLAGS from environment: '-mtune=generic -O3'
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /Users/XXX/ffmpeg-windows-build-helpers/sandbox/win64/libdav1d/build/meson-private/sanitycheckc.c -o /Users/XXX/ffmpeg-windows-build-helpers/sandbox/win$
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /Users/XXX/ffmpeg-windows-build-helpers/sandbox/win64/libdav1d/build/meson-private/sanitycheckc.exe
C compiler for the build machine: cc (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
C linker for the build machine: APPLE ld 450.3

meson.build:25:0: ERROR: Unknown compiler(s): [['/Users/XXX/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc']]

I tried compiling with 
./cross_compile_ffmpeg.sh  --disable-nonfree=n 

Any ideas what is wrong? I can run x86_64-w64-mingw32-gcc

**Comment by rdp** [comment]
still occurring after getting latest, nuking sandbox?

**Comment by rdp** [comment]
closing no feedback
