### ISSUE TITLE
Gettext does not compile on Gentoo x64

### ISSUE THREAD

**Issue by Neo2003** [rdp/ffmpeg-windows-build-helpers#420]
Hi,

Since few months, I cannot make it work.
Then I tried again today with latest version and same: Gettext does not compile

Making all in misc
make[4] : on entre dans le répertoire « /root/ffmpegwin/ffmpeg-windows-build-helpers/sandbox/win64/gettext-0.19.8.1/gettext-tools/misc »
if test "xemacs" != "no"; then \
  am__dir=. am__subdir_includes=''; \
  case start-po.elc in */*) \
    am__dir=`echo 'start-po.elc' | sed 's,/[^/]*$,,'`; \
    am__subdir_includes="-L $am__dir -L ./$am__dir"; \
  esac; \
  test -d "$am__dir" || /bin/mkdir -p "$am__dir" || exit 1; \
  xemacs --batch \
      \
    $am__subdir_includes -L . -L . \
    --eval "(defun byte-compile-dest-file (f) \"start-po.elc\")" \
    --eval "(unless (byte-compile-file \"start-po.el\") (kill-emacs 1))"; \
else :; fi
if test "xemacs" != "no"; then \
  am__dir=. am__subdir_includes=''; \
  case po-mode.elc in */*) \
    am__dir=`echo 'po-mode.elc' | sed 's,/[^/]*$,,'`; \
    am__subdir_includes="-L $am__dir -L ./$am__dir"; \
  esac; \
  test -d "$am__dir" || /bin/mkdir -p "$am__dir" || exit 1; \
  xemacs --batch \
      \
    $am__subdir_includes -L . -L . \
    --eval "(defun byte-compile-dest-file (f) \"po-mode.elc\")" \
    --eval "(unless (byte-compile-file \"po-mode.el\") (kill-emacs 1))"; \
else :; fi
if test "xemacs" != "no"; then \
  am__dir=. am__subdir_includes=''; \
  case po-compat.elc in */*) \
    am__dir=`echo 'po-compat.elc' | sed 's,/[^/]*$,,'`; \
    am__subdir_includes="-L $am__dir -L ./$am__dir"; \
  esac; \
  test -d "$am__dir" || /bin/mkdir -p "$am__dir" || exit 1; \
  xemacs --batch \
      \
    $am__subdir_includes -L . -L . \
    --eval "(defun byte-compile-dest-file (f) \"po-compat.elc\")" \
    --eval "(unless (byte-compile-file \"po-compat.el\") (kill-emacs 1))"; \
else :; fi
if test -f archive.dir.tar; then \
  inputfile=archive.dir.tar; \
else \
  inputfile='.'/archive.dir.tar; \
fi; \
xz -c -5 < "$inputfile" > archive.dir.tar.xz-t && mv archive.dir.tar.xz-t archive.dir.tar.xz
/root/ffmpegwin/ffmpeg-windows-build-helpers/sandbox/win64/gettext-0.19.8.1/gettext-tools/misc is a directory
xemacs exiting
.
make[4]: *** [Makefile:1907: start-po.elc] Error 255
make[4]: *** Attente des tâches non terminées....

I don't know how to fix this and why I get this error while no one reported it yet.

Thanks

**Comment by rdp** [comment]
nuke gettext directory and try again?

**Comment by Neo2003** [comment]
Already tried several times without luck, but it's going on now that I:
- commented: build_lensfun
- removed: --enable-liblensfun

**Comment by Neo2003** [comment]
Now it fails later in libav:

libavformat/libsrt.c: In function 'libsrt_set_options_pre':
libavformat/libsrt.c:330:66: error: 'SRTO_ENFORCEDENCRYPTION' undeclared (first use in this function); did you mean 'FS_FILE_ENCRYPTION'?
         (s->enforced_encryption >= 0 && libsrt_setsockopt(h, fd, SRTO_ENFORCEDENCRYPTION, "SRTO_ENFORCEDENCRYPTION", &s->enforced_encryption, sizeof(s->enforced_encryption)) < 0) ||
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~
                                                                  FS_FILE_ENCRYPTION
libavformat/libsrt.c:330:66: note: each undeclared identifier is reported only once for each function it appears in
make: *** [ffbuild/common.mak:59: libavformat/libsrt.o] Error 1

I don't know why it does not work on gentoo. And yes I did nuke sandbox to check.

**Comment by Neo2003** [comment]
Now livavformat does not compile:

CC      libavformat/mkvtimestamp_v2.o
CC      libavformat/mlpdec.o
CC      libavformat/mlvdec.o
CC      libavformat/mm.o
CC      libavformat/mmf.o
libavformat/libsrt.c: In function 'libsrt_set_options_pre':
libavformat/libsrt.c:330:66: error: 'SRTO_ENFORCEDENCRYPTION' undeclared (first use in this function); did you mean 'FS_FILE_ENCRYPTION'?
         (s->enforced_encryption >= 0 && libsrt_setsockopt(h, fd, SRTO_ENFORCEDENCRYPTION, "SRTO_ENFORCEDENCRYPTION", &s->enforced_encryption, sizeof(s->enforced_encryption)) < 0) ||
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~
                                                                  FS_FILE_ENCRYPTION
libavformat/libsrt.c:330:66: note: each undeclared identifier is reported only once for each function it appears in
make: *** [ffbuild/common.mak:59: libavformat/libsrt.o] Error 1
make: *** Attente des tâches non terminées....
CC      libavformat/mms.o

I use this command line:
./cross_compile_ffmpeg.sh --gcc-cpu-count=12
and I do select 3. Win64 only.

Gentoo is maybe no more compatible with this tool, it used to work last year.

Linux version 4.19.86-gentoo (root@Vangogh) (gcc version 9.2.0 (Gentoo 9.2.0-r2 p3)) #1 SMP Wed Nov 27 15:55:51 CET 2019

**Comment by rdp** [comment]
for second issue see #419 for the first issue, it's working OK on ubuntu?  Maybe either use the docker or a VM?  I don't quite have time to support all distros, PR also welcome!

**Comment by AndCycle** [comment]
I did a build on Gentoo without any problem, 
most of the time clear sandbox resolve 99% of the problem.

**Comment by rdp** [comment]
nice!
