### ISSUE TITLE
Any way to set vbv_delay?

### ISSUE THREAD

**Issue by ufgkirk** [rdp/ffmpeg-windows-build-helpers#423]
I am working with someone on some complex ffmpeg needs, and I supplied a build I made using this tool recently.

The build I made does what is needed, from an audio codec standpoint, but it apparently has a memory leak that manifests after a few hours of use.  Our hunch is it's related to the following:

It was reported to me that my build and several other builds that were tried, the log reflects a vbv_delay value of n/a.  Another build, which works for the suited purpose except it lacks a needed codec, sets a vbv_delay value of -1.  Is there a way to compile a build using this tool which will have that effect?

I'm not sure if this is really a bug\issue but last time I spoke with a developer on this project in another issue ticket, it seems like you guys know your stuff, so maybe you will have some suggestion.

Thanks!

**Comment by rdp** [comment]
like hard code one?  Is there no parameter for it?  If there's a memory
leak you might be able to find it using valgrind on linux (or dr. memory on
windows, gulp).  Anyway if you can talk to maybe the ffmpeg-user mailing
list or superuser.com and figure out a "patch" for ffmpeg I maybe could
apply it.  But don't know more than build parameters besides that.
Sometimes growing memory is expected if you're writing out to .mp4 (but not
growing like...crazy so dunno).  GL!

**Comment by rdp** [comment]
closing for no response, feel free to re open
