### ISSUE TITLE
Your meson version is too old 0.45.1 wanted 0.47

### ISSUE THREAD

**Issue by donradzsk** [rdp/ffmpeg-windows-build-helpers#429]
Hey, guys. I would like to get this started on a Windows 10 machine using the Ubuntu app and apparently there's an updated 0.47 version of meson but the system says the 0.45 version I have is the newest.
```
$ cd ffmpeg-windows-build-helpers
/ffmpeg-windows-build-helpers$ ./cross_compile_ffmpeg.sh
your meson version is too old 0.45.1 wanted 0.47
/ffmpeg-windows-build-helpers$ sudo apt-get install meson
[sudo] password for :
Reading package lists... Done
Building dependency tree
Reading state information... Done
meson is already the newest version (0.45.1-2ubuntu0.18.04.1).
The following package was automatically installed and is no longer required:
  libdumbnet1
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by hydra3333** [comment]
perhaps try something along these lines in a back script ?

```
cd ~/Desktop
set -x
if [[ ! -d "meson_git" ]]; then
   #git clone https://github.com/mesonbuild/meson.git
   #git clone --depth 1 https://github.com/mesonbuild/meson.git "meson_git"
   #git clone --depth 1 --branch "0.51.2" https://github.com/mesonbuild/meson.git "meson_git"
   git clone --depth 1 --branch "0.52.1" https://github.com/mesonbuild/meson.git "meson_git"
   cd meson_git
   sudo python3 setup.py clean 
   sudo python3 setup.py build
   sudo python3 setup.py install 
   sudo python3 setup.py check
   #sudo python3 setup.py test
fi
cd ~/Desktop
```

**Comment by yanM95** [comment]
Had the same issue yesterday.
I am using Ubuntu, but it may lead youto a solution
I downloaded the meson-0.47.0.tar.gz on [here](https://github.com/mesonbuild/meson/releases/tag/0.47.0)
Using the comand lines,
I uninstalled properly my mension version (sudo apt remove meson --autoremove --purge)
I unzipped it (tar xzvf ./meson-0.47.0.tar.gz)
And installed it (sudo python3 setup.py install)
Then, after checking the version, everything worked properly :)
Good luck

**Comment by rdp** [comment]
Nice!  Yeah you have to manually install newer meson, sadly

**Comment by donradzsk** [comment]
OK guys, thanks.
@hydra3333 that worked.

**Comment by rdp** [comment]
For followers, I usually end up doing something like this:

```
cd ~
git clone https://github.com/mesonbuild/meson.git
cd meson
cp meson.py meson
# add ~/meson to the PATH environment variable, ex add this line to ~/.bashrc
# export PATH=$HOME/mason:$PATH
```
sorry it's a pain.  @hydra3333 's method would work too.

**Comment by AnimMouse** [comment]
Just install meson via pip
```
sudo pip3 install meson ninja
```
No need to use git.

**Comment by reginalluna** [comment]
> Had the same issue yesterday.
> I am using Ubuntu, but it may lead youto a solution
> I downloaded the meson-0.47.0.tar.gz on [here](https://github.com/mesonbuild/meson/releases/tag/0.47.0)
> Using the comand lines,
> I uninstalled properly my mension version (sudo apt remove meson --autoremove --purge)
> I unzipped it (tar xzvf ./meson-0.47.0.tar.gz)
> And installed it (sudo python3 setup.py install)
> Then, after checking the version, everything worked properly :)
> Good luck

It works! Thank you.
