### ISSUE TITLE
Error compiling leptonica on Debian vanilla

### ISSUE THREAD

**Issue by ccyrano** [rdp/ffmpeg-windows-build-helpers#433]
Hi,
I apologize for format: this is my first post and I welcome constructive criticism.

So, I created a docker with vanilla Debian within my Linux server with the sole purpose to compile ffmpeg.
Installed and run as root, that is Debian:Latest, vanilla latest "buster" image build (I have done this many times for many compile projects).
After installing dependencies (all ok), I run the script for w64 only.
Everything goes great until it hits leptonica_git: it make most of the modules, at which point breaks on "CCLD colorinfo_reg.exe" as its looking for missing/undefined references. (please see attached log snap)
I took a peek at the colorinfo_reg.c code, I can't see anything emergent.
Am I the only one having this issue? Is this another missing TAB in the code?
What can I do? 
PS: if this is a Debian issue, which OS should I use to get this done?

![leptonica_git_break](https://user-images.githubusercontent.com/61009657/74429392-dce6e800-4e28-11ea-896a-fd190cc0a484.png)

**Comment by Warblefly** [comment]
On Thu, 13 Feb 2020, 11:28 ccyrano, <notifications@github.com> wrote:

> Everything goes great until it hits leptonica_git: it make most of the
> modules, at which point breaks on "CCLD colorinfo_reg.exe" as its looking
> for missing/undefined references. (please see attached log snap)
>
The git code changed just a couple of days ago and some symbols don't seem
to get linked, or might even be absent. I'm currently using the previous
git tree for this.
JW

**Comment by rdp** [comment]
OK I was able to repro it in OS X, so it isn't an OS thing :|

```
/Users/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: colorinfo_reg.o:colorinfo_reg.c:(.text.startup+0x184): undefined reference to `l_colorinfoCreate'
/Users/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: colorinfo_reg.o:colorinfo_reg.c:(.text.startup+0x1c1): undefined reference to `pixColorContentByLocation'
/Users/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: colorinfo_reg.o:colorinfo_reg.c:(.text.startup+0x25b): undefined reference to `l_colorinfoDestroy'
/Users/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: colorinfo_reg.o:colorinfo_reg.c:(.text.startup+0x276): undefined reference to `makeColorinfoTestData'
/Users/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: colorinfo_reg.o:colorinfo_reg.c:(.text.startup+0x2fb): undefined reference to `l_colorinfoCreate'
/Users/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: colorinfo_reg.o:colorinfo_reg.c:(.text.startup+0x338): undefined reference to `pixColorContentByLocation'
/Users/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: colorinfo_reg.o:colorinfo_reg.c:(.text.startup+0x3ec): undefined reference to `l_colorinfoDestroy'
/Users/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: colorinfo_reg.o:colorinfo_reg.c:(.text.startup+0x401): undefined reference to `l_colorinfoCreate'
/Users/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: colorinfo_reg.o:colorinfo_reg.c:(.text.startup+0x43e): undefined reference to `pixColorContentByLocation'
/Users/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: colorinfo_reg.o:colorinfo_reg.c:(.text.startup+0x51e): undefined reference to `l_colorinfoDestroy'
```
attempted to work around it.
If you still run into
```
make[2]: *** No rule to make target `colorinfo_reg.c', needed by `colorinfo_reg.o'.  Stop.
make[2]: *** Waiting for unfinished jobs....
  CC       colorcontent_reg.o
```
then nuke the leptonica_git folder [or whole sandbox] and try again.  I usually test it on ubuntu FWIW.  GL!
