### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by Roki100** [rdp/ffmpeg-windows-build-helpers#437]
hi, my build always failing, first try ended with `no source provided or makefile does not exist` or something like that
and now ```../../source/gcc-8.3.0/gcc/machmode.h:94:28: fatal error: mode-classes.def: No such file or directory
compilation terminated.
Makefile:1110: recipe for target 'double-int.o' failed
make[1]: *** [double-int.o] Error 1
make[1]: *** Waiting for unfinished jobs....
rm gcc.pod
make[1]: Leaving directory '/mnt/h/ffmpegBuilding/ffmpeg-windows-build-helpers-master/ffmpeg-windows-build-helpers-master/sandbox/cross_compilers/pkgs/gcc/build/gcc'
Makefile:4266: recipe for target 'all-gcc' failed
make: *** [all-gcc] Error 2
error```
im literally giving up because it always fails for me no matter what i do
(spent like 3-4 hours on it)
any ideas how can i build ffmpeg successfully?
one thing i need i standard ffmpeg + librubberband 
command i used: ` sudo ./cross_compile_ffmpeg.sh --enable-gpl=y --build-dependencies=y`
never had that much issues with building anything

**Comment by rdp** [comment]
tha'ts weird.  Yeah I don't think you can do it in /mnt/h land (which is
actually backed by a windows formatted drive), it'll have to be a normal
linux drive methinks... :)

**Comment by Roki100** [comment]
well i also tried building for windows via "normal" method (./configure --[args], make etc) but i got `ERROR: gnutls not found using pkg-config` and `ERROR: gmp not found` on `./configure`
args i used `sudo ./configure --arch=x86 --target-os=mingw32 --cross-prefix=i686-w64-mingw32- --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf --enable-librubberband`
maybe you know how to fix this error(s)?
i mean i would like to build it on linux subsystem on windows in any method because i need librubberband in ffmpeg

**Comment by rdp** [comment]
Did you try a different directory?

**Comment by Roki100** [comment]
i didnt but i will try but i think `gmp not found` is something related to packages or something?

**Comment by rdp** [comment]
Might mean it didn't build right...try from ~

**Comment by Roki100** [comment]
i mean im getting it before any building starts

**Comment by rdp** [comment]
nuke sandbox and build from somewhere within ~ ?

**Comment by rdp** [comment]
Feel free to continue conversation if still failing.
