### ISSUE TITLE
Cannot find -lpthread

### ISSUE THREAD

**Issue by Nathan-Powell** [rdp/ffmpeg-windows-build-helpers#438]
I'm getting this error when compiling:

`zmbv_encoder='yes'
zmbv_encoder_deps='zlib'
zmq_filter='yes'
zmq_filter_deps='libzmq'
zoompan_filter='yes'
zoompan_filter_deps='swscale'
zscale_filter='yes'
zscale_filter_deps='libzimg const_nan'
mktemp -u XXXXXX
k587Fu
test_ld cc
test_cc
BEGIN /tmp/ffconf.uE0mvNK6/test.c
    1   int main(void){ return 0; }
END /tmp/ffconf.uE0mvNK6/test.c
/home/user/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc -mtune=generic -O3 -DLIBTWOLAME_STATIC -DMODPLUG_STATIC -DCACA_STATIC -mtune=generic -O3 -c -o /tmp/ffconf.uE0mvNK6/test.o /tmp/ffconf.uE0mvNK6/test.c
/home/user/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc -o /tmp/ffconf.uE0mvNK6/test.exe /tmp/ffconf.uE0mvNK6/test.o -lpthread -lm -lharfbuzz
/home/user/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lpthread
collect2: error: ld returned 1 exit status
C compiler test failed.`

Seems like part of MinGW is missing. Any ideas?

**Comment by rdp** [comment]
Full output possible?

**Comment by rdp** [comment]
Things have changed around threading, leave more feedback if still broken, thanks.
