### ISSUE TITLE
build fails due to missing videolan repositories

### ISSUE THREAD

**Issue by primitiveType** [rdp/ffmpeg-windows-build-helpers#439]
It looks like Videolan has relocated many of their repositories to code.videolan.org. This causes ffmpeg-builder to fail on:
`fatal: repository 'https://git.videolan.org/videolan/libbluray.git/' not found`

**Comment by rdp** [comment]
same with the latest git master?

**Comment by primitiveType** [comment]
I was pretty sure I was up-to-date when I discovered this issue, but looking at cross_compile_ffmpeg, it looks like the paths are updated. I'll test it and close the ticket if it is working.
