### ISSUE TITLE
svt-av1

### ISSUE THREAD

**Issue by buhlaze** [rdp/ffmpeg-windows-build-helpers#440]
is there any way to get a working svt-av1 implemented in ffmpeg yet for Windows?

**Comment by rdp** [comment]
I don't see an official way.
There's some manual lines in the build you can enable to "see" if you can
get it in there, search for svt:

```
$ grep svt.*av1 *
cross_compile_ffmpeg.sh:build_svt-av1() {
cross_compile_ffmpeg.sh:    #git apply
"../SVT-AV1_git/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch"
```
Good luck!
