### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by byancode** [rdp/ffmpeg-windows-build-helpers#447]
[logs.zip](https://0x0.st/ijaz.zip)

**Comment by rdp** [comment]
I think you intended that for the media autobuild suite project?
https://github.com/m-ab-s/media-autobuild_suite/issues
FWIW `psl.c:(.text+0x976): undefined reference to
`__imp_psl_is_cookie_domain_acceptable'` can sometimes mean it anticipates
a "dynamic library" dll but it "got" a static one :)

**Comment by rdp** [comment]
Maybe https://github.com/m-ab-s/media-autobuild_suite/issues/1622 ?
