### ISSUE TITLE
problem building OpenCL ICD Loader

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#448]
Hello.  Related to this project and building OpenCL functionality (I guess) ...

I see the OpenCL ICD Loader used to bake OpenCL into ffmpeg, now fails to build as of this commit
https://github.com/KhronosGroup/OpenCL-ICD-Loader/commit/47f05fad43621aa1637427d857d639d0ecfbb7cd
due to a new dependency not found in mingw64 cross compilation

```
fatal error: windows.management.deployment.h: No such file or directory
   27 | #include <windows.management.deployment.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

```
No help so far on the issue at https://github.com/KhronosGroup/OpenCL-ICD-Loader

Does anyone else encounter this ?
Information and suggestions would be greatly appreciated.

**Comment by rdp** [comment]
Is this failing a build somewhere? thanks!

**Comment by hydra3333** [comment]
Yes it's been fixed upstream.
Use -DOPENCL_ICD_LOADER_DISABLE_OPENCLON12=ON to build an OpenCL import lib only and it avoids that and related errors, and will load OpenCL.dll at runtime on Win10.

**Comment by hydra3333** [comment]
reference: https://github.com/KhronosGroup/OpenCL-ICD-Loader/issues/107#issuecomment-621639994 and below.

i.e commits
https://github.com/KhronosGroup/OpenCL-ICD-Loader/commit/bb98ad9a9c264d63ad2204c1eeee0a3a1e724e20
https://github.com/KhronosGroup/OpenCL-ICD-Loader/commit/c276388b15472f0da260d0eef49482ec1979d038
https://github.com/KhronosGroup/OpenCL-ICD-Loader/commit/bbdf079426d859fb8a68c332b41b714f9c87d6ad
on 9 May
https://github.com/KhronosGroup/OpenCL-ICD-Loader/commits/master
