### ISSUE TITLE
Failure building mingwex on Travis CI

### ISSUE THREAD

**Issue by lnihlen** [rdp/ffmpeg-windows-build-helpers#451]
Hey,

Thanks so much for maintaining this super-helpful build script.

I've been stymied by a toolchain compilation error when trying to get a windows shared library build of ffmpeg cross-compiling on the Travis continuous integration build system.

My command line is:

```
./cross_compile_ffmpeg.sh --build-ffmpeg-shared=y --compiler-flavors=win64 --enable-gpl=y --sandbox-ok=y --ffmpeg-git-checkout-version=${FFMPEG_GIT_TAG} --ffmpeg-git-checkout=${FFMPEG_GIT_REPO} --gcc-cpu-count=2 --debug
```
with `FFMPEG_GIT_REPO=https://git.ffmpeg.org/ffmpeg.git` and `FFMPEG_GIT_TAG=release/4.2`.

Extract from the end of the build output is here:

```
checking for _mingw_mac.h... no
configure: error: Please check if the mingw-w64 header set and the build/host option are set properly.
error

See build.log for more details.
+[[ ! -f ../cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc ]]
+[[ ! -f ../cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libmingwex.a ]]
+echo 'failure building mingwex? 64 bit'
failure building mingwex? 64 bit
```

Full build log is available at [this gist](https://gist.github.com/lnihlen/2b1d09a38dd06c70576322e27efd0bb8).

The build system is Ubuntu Bionic 18.04.04 LTS.

I'm happy to provide any additional info, and would really appreciate any insight you could offer!

Thanks much!

**Comment by lnihlen** [comment]
I've also tried removing the --gcc-cpu-count option, to see if it was some kind of parallelism issue with make, but no luck.

**Comment by rdp** [comment]
Does

libmingwex.a exist anywhere?

Thanks!

**Comment by lnihlen** [comment]
I've made a lot more progress using the pre-built toolchain and modifying the quick build script to suit. Closing this issue as a fix is not needed anymore. Thanks a lot for your quick response!
