### ISSUE TITLE
windows.h: No such file or directory

### ISSUE THREAD

**Issue by jftuga** [rdp/ffmpeg-windows-build-helpers#453]
I am trying to build `ffmpeg` with Ubuntu 18.04.4 LTS

I get this error message when running `./cross_compile_ffmpeg.sh`:

```
libtool: compile:  gcc -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.31\" "-DPACKAGE_STRING=\"libmfx 1.31\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libmfx\" -DVERSION=\"1.31\" -DMFX_HAVE_LINUX=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I. -I./include -DMINGW_HAS_SECURE_API=1 -mtune=generic -O3 -MT src/libmfx_la-mfx_va_glue.lo -MD -MP -MF src/.deps/libmfx_la-mfx_va_glue.Tpo -c src/mfx_va_glue.c -o src/libmfx_la-mfx_va_glue.o
src/main.cpp:21:10: fatal error: windows.h: No such file or directory
 #include <windows.h>
          ^~~~~~~~~~~
compilation terminated.
Makefile:702: recipe for target 'src/libmfx_la-main.lo' failed
make: *** [src/libmfx_la-main.lo] Error 1
```

I selected `Win64 (64-bit only)` from the menu.  How can I fix this?

I also ran `find / 2>&1 | grep windows.h`, but this file is not on my system.

Please let me know if there is a better OS to build from.  I am using AWS and they have plenty to choose from.

**Comment by rdp** [comment]
do you have windows.h anywhere?
Anyway nuke sandbox and try again?

**Comment by jftuga** [comment]
I did not find `windows.h` on my system.  I created a new AWS EC2 instance running Ubuntu and tried again with the same result.

**Comment by rdp** [comment]
That's odd you should have something like
./ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/windows.h
after building the cross compilers...

**Comment by rdp** [comment]
Does it work now?

**Comment by jftuga** [comment]
I don't know.  I closed because I am going to try to build `ffmpeg` with your script on `AppVeyor` instead of on `AWS` with `Ubuntu`.
