### ISSUE TITLE
build hangs in WSL2 during Make

### ISSUE THREAD

**Issue by asheimo** [rdp/ffmpeg-windows-build-helpers#454]
Need some help figuring out what is happening please. Seems to go along ok but then it just hangs at this point:

Install the project...
-- Install configuration: ""
-- Up-to-date: /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/openjpeg-2.3/OpenJPEGTargets.cmake
-- Installing: /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/openjpeg-2.3/OpenJPEGTargets-noconfig.cmake
-- Up-to-date: /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/openjpeg-2.3/OpenJPEGConfig.cmake
-- Up-to-date: /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig/libopenjp2.pc
-- Up-to-date: /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/openjpeg-2.3/opj_config.h
-- Installing: /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libopenjp2.a
-- Installing: /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/openjpeg-2.3/openjpeg.h
-- Up-to-date: /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/openjpeg-2.3/opj_stdint.h
Already made build ...
Already made glfw-3.3 ...
doing git checkout origin/master
HEAD is now at 3676fd324 ci: Add a new top-level directory, dedicated for CI verification
fetched no code changes, not forcing reconfigure for that...
Already made libpng_git ...
doing git checkout origin/master
HEAD is now at e3c259a2 Fix integer overflow in EmitFancyRGB.
fetched no code changes, not forcing reconfigure for that...
Already made libwebp_git ...

Making /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8 as $ PATH=/mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH make  -j 4

/mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/objs/apinames.exe         -o/mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/objs/ftexport.sym  /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/tttables.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftcid.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftstroke.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/t1tables.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/fterrors.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftpcfdrv.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftglyph.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftbitmap.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftmodapi.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftsystem.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftfntfmt.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftsynth.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftlcdfil.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftpfr.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftsizes.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftrender.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftlzw.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftoutln.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftbzip2.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftlist.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftincrem.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftchapters.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftbdf.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftcache.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftgxval.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftgzip.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftwinfnt.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/freetype.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/fttypes.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftttdrv.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftotval.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftautoh.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftmm.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftadvanc.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftbbox.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftcffdrv.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftmoderr.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftgasp.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftsnames.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/tttags.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ttunpat.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/fterrdef.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/fttrigon.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ftimage.h /mnt/c/Users/HomeWin10/ffmpeg-windows-build-helpers/sandbox/win64/freetype-2.8/include/freetype/ttnameid.h

**Comment by rdp** [comment]
Hmm just tried it here and worked OK.  That WSL is unstable...maybe try
building within the linux structure and not /mnt/c ?

**Comment by asheimo** [comment]
OK I tried that and got a different error:

```
unzipping gmp-6.1.2.tar.xz ...
configuring gmp-6.1.2 (/home/asheimo/ffmpeg-windows-build-helpers/sandbox/win64/gmp-6.1.2) as $ PKG_CONFIG_PATH=/home/asheimo/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/home/asheimo/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --host=x86_64-w64-mingw32 --prefix=/home/asheimo/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --disable-shared --enable-static ABI=64
all touch files already_configured* touchname= already_configured_10b4b0b100b2404de42cf816a81c7a28-
config options --host=x86_64-w64-mingw32 --prefix=/home/asheimo/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --disable-shared --enable-static ABI=64 ./configure
checking build system type... skylake-pc-linux-gnu
checking host system type... x86_64-w64-mingw32
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-w64-mingw32-strip... x86_64-w64-mingw32-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking ABI=64
checking compiler x86_64-w64-mingw32-gcc -mtune=generic -O3 ... yes
checking compiler x86_64-w64-mingw32-gcc -mtune=generic -O3  has long long... yes
checking for x86_64-w64-mingw32-gcc... x86_64-w64-mingw32-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-w64-mingw32-gcc accepts -g... yes
checking for x86_64-w64-mingw32-gcc option to accept ISO C89... none needed
checking whether x86_64-w64-mingw32-gcc understands -c and -o together... yes
checking for x86_64-w64-mingw32-gcc option to accept ISO C99... none needed
checking for x86_64-w64-mingw32-gcc option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... x86_64-w64-mingw32-gcc -E
checking build system compiler x86_64-w64-mingw32-gcc... yes
checking for build system preprocessor... x86_64-w64-mingw32-gcc -E
checking for build system executable suffix... configure: error: Cannot determine executable suffix
```

I did also nuke the sandbox before trying again to be sure there were no leftovers.

**Comment by rdp** [comment]
Seems similar to
https://github.com/rdp/ffmpeg-windows-build-helpers/issues/415 wonder if my
check isn't working right with WSL2...try with binfmts disabled?

**Comment by asheimo** [comment]
Not to be obtuse but what do you mean "try with binfmts disabled"?

**Comment by asheimo** [comment]
After looking through the links in #415 I found how to disable binfmts and that did indeed allow the compile to complete. For sake of documenting the answer:

You need to make the change from root in WSL2 so to get there you have to type `sudo su`. Then enter your password from there enter `echo 0 > /proc/sys/fs/binfmt_misc/WSLInterop` after this the compile works. 

to reverse this the command is `echo 1 > /proc/sys/fs/binfmt_misc/WSLInterop`

https://docs.microsoft.com/en-us/windows/wsl/interop

**Comment by rdp** [comment]
Nice.  It's "supposed" to warn you when that's off, wonder why it failed in your case:

```
$ ./cross_compile_ffmpeg.sh  -a
windows WSL detected: you must first disable 'binfmt' by running this
      sudo bash -c 'echo 0 > /proc/sys/fs/binfmt_misc/WSLInterop'
```

**Comment by jaromanda** [comment]
> 
> 
> Nice. It's "supposed" to warn you when that's off, wonder why it failed in your case:
> 
> ```
> $ ./cross_compile_ffmpeg.sh  -a
> windows WSL detected: you must first disable 'binfmt' by running this
>       sudo bash -c 'echo 0 > /proc/sys/fs/binfmt_misc/WSLInterop'
> ```

because the code is incorrect - it's testing for `"-Microsoft "` in uname output

But, the output is - in my case - `... 4.19.128-microsoft-standard ...`
