### ISSUE TITLE
Building a new version

### ISSUE THREAD

**Issue by asheimo** [rdp/ffmpeg-windows-build-helpers#455]
In order to build a new version do you have to remove the sandbox and start over or can you run the command again and have it pull the latest versions?

**Comment by rdp** [comment]
There is a parameter --git-get-latest the default is "yes" :)

**Comment by asheimo** [comment]
Thanks, that's what I needed.

**Comment by asheimo** [comment]
Sorry, when using that option I've run into this error: ERROR: failed checking for nvcc. Any ideas?

**Comment by rdp** [comment]
Was there a fix?

**Comment by asheimo** [comment]
The parameter you gave me worked. I then got an error that was due to trying to build with the cuda sdk and I need to download and install it first.
