### ISSUE TITLE
'./cross_compile_ffmpeg.sh' fails ... libtoolize

### ISSUE THREAD

**Issue by markfilipak** [rdp/ffmpeg-windows-build-helpers#456]
Regarding 'https://github.com/rdp/ffmpeg-windows-build-helpers#ffmpeg-windows-build-helpers'

'./cross_compile_ffmpeg.sh' fails with "Could not find the following execs...: libtoolize".

I could not find 'libtoolize' anywhere. Can you help? Or is there an alternative that will allow cross_compile_ffmpeg?

Thanks, and Regards,
Mark.

**Comment by rdp** [comment]
Is this OS X?

**Comment by markfilipak** [comment]
Oh, sorry. I meant to include the environment but then I had a brain fart.
It's Linux Mint 18.3 running in a VirtualBox running in Win10-1803.

**Comment by markfilipak** [comment]
The problem appears to be that 'libtoolize' is not a package. On the off chance that I could fix this myself by installing the 'libtool' package, I launched 'Synaptic Package Manager' and submitted 'libtool'. No Joy. It appears that there are conflicts, to wit:

'Synaptic Package Manager'>'Package: libtool 2.4.6.0.1'>'Dependencies'>
'Conflicts: autoconf (<=2.12)' -- installed is 2.69-9
'Conflicts: automake (<=1.3)' -- installed is 1:1.15-4ubuntu1
'Conflicts: libtool1.4' -- I have no idea what this means

**Comment by rdp** [comment]
Yeah I'm not sure on mint.  Recommend using the docker script or using an
ubuntu VM, or WSL.

**Comment by markfilipak** [comment]
> Yeah I'm not sure on mint. Recommend using the docker script or using an ubuntu VM, or WSL.

Mint is Ubuntu. I doubt that pure Ubuntu would opt for older versions of 'autoconf' & 'automake', so I trust that 'ffmpeg-windows-build-helpers' will fail on that, too. As for WSL, I think that's Microsoft's version of Linux. If so, it's a non-starter because I don't allow Windows to access the Internet.

**Comment by rdp** [comment]
For ubuntu the list is this:
$ sudo apt-get install subversion ragel curl texinfo g++ bison flex cvs
yasm automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev
mercurial unzip pax nasm gperf autogen bzip2 autoconf-archive p7zip-full
meson clang
Are you able to install those?

**Comment by markfilipak** [comment]
I've given up. Why? ...This is a trip down the rabbit hole...

I tried installing your utility a few months ago and Linux immediately got so f'd up I had to restore the VM from backup. Then I forgot that experience. Well, I experienced it again the other day.

Symptom: After installing to the point where the install fails, when I reboot the VM, I get this notification: "VBoxClient: The parent session seems to be non-X11. Exiting...". The VM window is 640x480 -- my screen is 3840x2160 -- and the window displays just the upper-left corner of Linux applications, and there's no recovery. So it appears that something about the installation is trashing X11.

If you like, I will put some time into this problem because my VM set-up is probably not too unusual and so, might help you and other users. Please advise.

Regards,
Mark.

**Comment by rdp** [comment]
That's weird, never experienced anything like that!

**Comment by markfilipak** [comment]
Sorry for the bother. VirtualBox update from 6.1.6 to 6.1.8 apparently has a Guest Additions bug, so I regressed the Guest Additions back to 6.1.6.

The problem cited previously (https://github.com/rdp/ffmpeg-windows-build-helpers/issues/456#issuecomment-634915629) will nonetheless prevent me from running './cross_compile_ffmpeg.sh'. I read about the "docker script" and am unsure how to proceed with it.

Since I had to restore the VM from a saved copy, all the prior dependency installs demanded by './cross_compile_ffmpeg.sh' have been lost and my Linux VM is back to a pristine state. Thus, I could repeat the entire operation while taking notes and/or try something different at your option. Please advise.

**Comment by rdp** [comment]
Try this: https://github.com/rdp/ffmpeg-windows-build-helpers/issues/456#issuecomment-635092594

**Comment by rdp** [comment]
May need a sudo apt-get update first?

**Comment by markfilipak** [comment]
Giving up. Linux is just too primative. I'm giving up on ffmpeg too. It's too poorly documented to be truly useful.

**Comment by cslycord** [comment]
> The problem appears to be that 'libtoolize' is not a package. On the off chance that I could fix this myself by installing the 'libtool' package, I launched 'Synaptic Package Manager' and submitted 'libtool'. No Joy. It appears that there are conflicts, to wit:
> 
> 'Synaptic Package Manager'>'Package: libtool 2.4.6.0.1'>'Dependencies'>
> 'Conflicts: autoconf (<=2.12)' -- installed is 2.69-9
> 'Conflicts: automake (<=1.3)' -- installed is 1:1.15-4ubuntu1
> 'Conflicts: libtool1.4' -- I have no idea what this means

What this seems to mean is that the packages/repos your installation of Synaptic uses conflict with the installed ones that you already have. It's like you're mixing and matching stuff from likely older mint repos with stuff from fairly new ubuntu ones. And in the end you get conflicts of packages that can't be installed together.

**Comment by markfilipak-windows** [comment]
> What this seems to mean is that the packages/repos your installation of Synaptic uses conflict with the installed ones that you already have...

Yes, I think you understand the problem. Do you compile ffmpeg from source using a cross-compiler? Do you know where/how I can find all the tools in the dependency chain that are mutually compatible?

**Comment by cslycord** [comment]
If you don't care about which distro you use, I think using one that (unlike mint) includes libtool would be easiest. If you're used to mint-like distros, debian and ubuntu would seem to fit the bill.

But if you want to use mint, you could always build libtool from source. It's also possible to create a virtual machine of a different distro or have a directory where some distro is put in as a chroot.

**Comment by rdp** [comment]
Not sure where to go here, thanks for the initial report!
