### ISSUE TITLE
[Question]FFMPEG Version

### ISSUE THREAD

**Issue by villiersnorton** [rdp/ffmpeg-windows-build-helpers#464]
How can I specify a specific ffmpeg tag or head for example 4.2.3? I checked the scripts but cannot see any options to add this

**Comment by PeacefullyDisturbed** [comment]
You can specify a specific tag or git commit hash with the _**--ffmpeg-git-checkout-version**_ option, for example:
`--ffmpeg-git-checkout-version=n4.3`

Another option is to download the source release and extract it; then use the _**--ffmpeg-source-dir**_ option like this:
`--ffmpeg-source-dir=/path/to/source/ffmpeg-4.3`

**Comment by rdp** [comment]
Yep, thanks!
