### ISSUE TITLE
Build fails with libvmaf 1.5.1

### ISSUE THREAD

**Issue by HugoStrasser** [rdp/ffmpeg-windows-build-helpers#465]
./cross_compile_ffmpeg.sh

Build fails at: 

error: libvmaf >= 1.5.2 not found using pkg-config....

on Ubuntu 20 Virtual Machine, building for windows 64

is there any fix for this, or a patch for libvmaf 1.5.2?

**Comment by rdp** [comment]
hopefully fixed with #466

**Comment by AnimMouse** [comment]
@rdp Fixed already. Thanks!
