### ISSUE TITLE
./cross_compile_ffmpeg.sh: line 954: ./autogen.sh: No such file or directory

### ISSUE THREAD

**Issue by marierose147** [rdp/ffmpeg-windows-build-helpers#479]
run:
```
bash ./cross_compile_ffmpeg.sh --ffmpeg-git-checkout-version=n4.3.1 --disable-nonfree=n --compiler-flavors=win64 --build-ffmpeg-static=y --build-ffmpeg-shared=n
```
log:
```
./cross_compile_ffmpeg.sh: line 954: ./autogen.sh: No such file or directory
configuring harfbuzz_git (/home/runner/ffmpeg-windows-build-helpers/sandbox/win64/harfbuzz_git) as $ PKG_CONFIG_PATH=/home/runner/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/home/runner/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --host=x86_64-w64-mingw32 --prefix=/home/runner/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --disable-shared --enable-static --with-freetype=yes --with-fontconfig=no --with-icu=no
all touch files already_configured* touchname= already_configured_93f6a4693fbf2c4e7d3da13d831a9e32-
config options --host=x86_64-w64-mingw32 --prefix=/home/runner/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --disable-shared --enable-static --with-freetype=yes --with-fontconfig=no --with-icu=no ./configure
autoreconf: 'configure.ac' or 'configure.in' is required
nice: ‘./configure’: No such file or directory
##[error]Process completed with exit code 1.
```

**Comment by johnyhost** [comment]
There was a code change in harfbuzz a week ago, as a workaround you can checkout one of the previous commits. Go to cross_compile_ffmpeg.sh and add lines:
`cd harfbuzz_git
git checkout 3d164d5883ceb5698a98ca025b5f75ce465e1f51`

so it looks like:
`939 build_harfbuzz() {
 940   local new_build=false
 941   do_git_checkout https://github.com/harfbuzz/harfbuzz.git harfbuzz_git
 942   cd harfbuzz_git
 943   git checkout 3d164d5883ceb5698a98ca025b5f75ce465e1f51
 944   cd ..
 945   if [ ! -f harfbuzz_git/already_done_harf ]; then # Not done or new master, so build
 946     new_build=true
 947   fi
 948
`

**Comment by PeacefullyDisturbed** [comment]
It looks like HarfBuzz has removed autotools support and will only build with Meson now.

So I have changed it to build with Meson and created a pull request (#480).

If you want to get around this before it is merged you can do similar to what @johnyhost said and simply add the commit tag 3d164d5883ceb5698a98ca025b5f75ce465e1f51 to the _**do_git_checkout**_ line in the _**build_harfbuzz**_ function, so line 941 would change to
```
do_git_checkout https://github.com/harfbuzz/harfbuzz.git harfbuzz_git 3d164d5883ceb5698a98ca025b5f75ce465e1f51
```

Or you can apply the patch file of the pull request:  https://github.com/rdp/ffmpeg-windows-build-helpers/pull/480.patch
