### ISSUE TITLE
cannot find input file src/sndfile.h.in

### ISSUE THREAD

**Issue by xatabhk** [rdp/ffmpeg-windows-build-helpers#489]
cannot find input file src/sndfile.h.in

**Comment by xatabhk** [comment]
fix:re-cloning

**Comment by rdp** [comment]
Glad you found it

On Friday, September 4, 2020, xatabhk <notifications@github.com> wrote:
> fix:re-cloning
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/rtn_02aiHH8hO7VaZqXWgpHBE0b9UHcRlmHIVhiY7SFt5--4skQgh6LzufbCJJsGeOhjY8ukvt6fydKE0eQXDv93XE-b8_jEQseZD-j6M7p941xZBk-66LZQDRk1Wqzn-SGLEiV5R4emOWcvBZ3masPmxZ0MbOkW0aFmLgvaRrA5CQuVhzALbjYgO5CZUxf3_uP0p-AjfgTm02nOu_q5_xJUbG01vqx79W0cJaQWrg=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUDZKLSM5NXRSHX4BY3SEF76DA5CNFSM4QZCBCZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFD5DVRA.gif>
