### ISSUE TITLE
trying to build with libnpp having errors

### ISSUE THREAD

**Issue by asheimo** [rdp/ffmpeg-windows-build-helpers#490]
I'm trying to get libnpp included in my build. I run the script as `./cross_compile_ffmpeg.sh --disable-nonfree=n` I have also added `--enable-cuda-sdk --enable-libnpp --extra-cflags=-I/usr/local/cuda/include  --extra-ldflags=-L/usr/local/cuda/lib64` to line 2323 config_options=

It fails with `ERROR: failed checking for nvcc`. I have installed the cuda toolkit in both windows and wsl. so I'm stuck with what I have wrong. attached is the log from the build

[buildlog.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/5189776/buildlog.txt)

**Comment by rdp** [comment]
Check the ffbuild/config.log fort within ffmpeg for...?

On Tuesday, September 8, 2020, asheimo <notifications@github.com> wrote:
> I'm trying to get libnpp included in my build. I run the script as
./cross_compile_ffmpeg.sh --disable-nonfree=n I have also added
--enable-cuda-sdk --enable-libnpp --extra-cflags=-I/usr/local/cuda/include
--extra-ldflags=-L/usr/local/cuda/lib64 to line 2323 config_options=
>
> It fails with ERROR: failed checking for nvcc. I have installed the cuda
toolkit in both windows and wsl. so I'm stuck with what I have wrong.
attached is the log from the build
>
> buildlog.txt
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/8IiGnklvuYvpMeDQ68DV75QoRvSyNsOloxO_uuPh4ssntyk8p0RwWmFgpdGWMdRm97OKz0DS_HZrDMyDtrd_VaoXZ3kxEG1uJ7XQmhStfk-x2MM-lxA9C8HchJtRMepsQ_hAKmV7k7yYGkMDW0c_uB5D9n5Ubb70o1b4s7lfV8RswYM5KhPqQCHhtdFVtLrq8dYBaQeMoSPqCCOqWMe4h-tCIg0=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUANAGT7K7GS3FYYLCDSEZPVLA5CNFSM4RAIBK52YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4KL4VLGQ.gif>

**Comment by asheimo** [comment]
I figure that I might be using a wrong parameter which is why I opened the issue.

**Comment by rdp** [comment]
did the ffbuild/config.log file reveal anything useful?

**Comment by asheimo** [comment]
Not to me maybe you can understand it, I tried again today to make sure there was no change. Still wondering if I added the right things to the build script and called the script correctly.
[config.log](https://github.com/rdp/ffmpeg-windows-build-helpers/files/5251812/config.log)

**Comment by asheimo** [comment]
closing unsolved
