### ISSUE TITLE
Fatal error on Windows XP

### ISSUE THREAD

**Issue by nicolaasjan** [rdp/ffmpeg-windows-build-helpers#496]
Hi,
I had successfully built a 32bit XP-compatible version with the option `build_intel_qsv=n` (line 2675), but when calling ffmpeg in a Dutch XP SP3 it gave the error (translated):

`The NtCreateFile API failed. This error should never be returned to an application, it is a place holder for the Windows Lan Manager Redirector to use in its internal error mapping routines`

I did some searching and  found a [thread on Doom9's Forum](http://forum.doom9.net/showthread.php?p=1922562), where someone found out that the option `--disable-mediafoundation` had to be added. I inserted that in line 2323.

So I recompiled (with the `cross_compilers` folder still intact) , but the resulting binary gave exactly the same error...

What am I missing here?

**Comment by rdp** [comment]
I don't think ffmpeg itself has supported XP for awhile...you have to go
back to a specific version.
I put a few builds xp here:
https://sourceforge.net/projects/ffmpegwindowsbi/files/random_builds/ but
it isn't easy...I can't remember all the specifics, I've done a few with
funding.  Good luck!

**Comment by nicolaasjan** [comment]
> I don't think ffmpeg itself has supported XP for awhile...you have to go back to a specific version. I put a few builds xp here: https://sourceforge.net/projects/ffmpegwindowsbi/files/random_builds/ but it isn't easy...I can't remember all the specifics, I've done a few with funding. Good luck!
>

Oh...,
Well, I thought it would be somehow possible, because [Reino](https://rwijnsma.home.xs4all.nl/files/ffmpeg/?C=M;O=D) still builds them (on Windows) with a [fork](https://github.com/Reino17/ffmpeg-windows-build-helpers) of your script. I don't know if I can run that on Linux.

**Comment by rdp** [comment]
If you can figure out which library is using the "non xp" functions you
could exclude it...
