### ISSUE TITLE
Build to a specific commit

### ISSUE THREAD

**Issue by asheimo** [rdp/ffmpeg-windows-build-helpers#498]
How would I go about building ffmpeg to a specific commit version with your script?

**Comment by asheimo** [comment]
I think I have figured it out, can you tell me if I'm doing it correctly

./cross_compile_ffmpeg.sh --ffmpeg-git-checkout-version=<commit>

**Comment by rdp** [comment]
Looks right :)

On Thursday, October 29, 2020, asheimo <notifications@github.com> wrote:
> I think I have figured it out, can you tell me if I'm doing it correctly
>
> ./cross_compile_ffmpeg.sh --ffmpeg-git-checkout-version=
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/53K5HBwAkY_EBO83EZs-NtBY-VAODglYR2xeuzAL3ZK5NX4v3aqFGpuK67zmEzQlo3fDAzrxumoV6a4-DDgEh3h4nZXn_GkqT9uhesOpN12gbP2jhRw7OsfJQqXZ6yT88MQKLTl0Oib5CwpJLyGcGKVn1W_QWyzTHR-9nUtwO0uOwfoJJxBEV_M0NITT5iUN7Mokd4DOJcgyI4k7ALstAqGle5Og7UuDaDuqZSn9ng=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUBHE6QRFHAIBPSKCOTSNHWAJA5CNFSM4TEI7JCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFLOBJAA.gif>
