### ISSUE TITLE
Segmentation Fault CUDA

### ISSUE THREAD

**Issue by FC2469** [rdp/ffmpeg-windows-build-helpers#504]
Hi, I have this issue compiling on Debian 10 for Win64:
0.      Program arguments: /usr/lib/llvm-3.8/bin/clang -cc1 -triple nvptx64-nvidia-cuda -aux-triple x86_64-pc-linux-gnu -fcuda-target-overloads -fcuda-disable-target-call-checks -S -disable-free -disable-llvm-verifier -main-file-name vf_scale_cuda_bicubic.cu -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -no-integrated-as -mconstructor-aliases -fcuda-is-device -target-cpu sm_30 -dwarf-column-info -debugger-tuning=gdb -coverage-file /root/ffwin/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git_with_fdk_aac/libavfilter/vf_scale_cuda_bicubic.ptx -resource-dir /usr/lib/llvm-3.8/bin/../lib/clang/3.8.1 -include ./compat/cuda/cuda_runtime.h -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/backward -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-3.8/bin/../lib/clang/3.8.1/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/backward -O2 -fdeprecated-macro -fno-dwarf-directory-asm -fdebug-compilation-dir /root/ffwin/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git_with_fdk_aac -ferror-limit 19 -fmessage-length 237 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o libavfilter/vf_scale_cuda_bicubic.ptx -x cuda libavfilter/vf_scale_cuda_bicubic.cu
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'libavfilter/vf_scale_cuda_bicubic.cu'.
4.      Running pass 'NVPTX DAG->DAG Pattern Instruction Selection' on function '@_Z17Subsample_BicubicIhEvPF6float4ffEyPT_iiiiiif'
clang: error: unable to execute command: Segmentation fault
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.1-24 (tags/RELEASE_381/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/vf_scale_cuda_bicubic-0dbdf2.cu
clang: note: diagnostic msg: /tmp/vf_scale_cuda_bicubic-0dbdf2.sh
clang: note: diagnostic msg:

********************
ffbuild/common.mak:102: set di istruzioni per l'obiettivo "libavfilter/vf_scale_cuda_bicubic.ptx" non riuscito
make: *** [libavfilter/vf_scale_cuda_bicubic.ptx] Errore 254
make: *** Attesa per i processi non terminati....
+ exit 1

**Comment by rdp** [comment]
Llvm 3.8 isn't that a bit old?
Maybe try in an Ubuntu vm? Or docker?

On Friday, November 6, 2020, Software Magic <notifications@github.com>
wrote:
> Hi, I have this issue compiling on Debian 10 for Win64:
> 0. Program arguments: /usr/lib/llvm-3.8/bin/clang -cc1 -triple
nvptx64-nvidia-cuda -aux-triple x86_64-pc-linux-gnu -fcuda-target-overloads
-fcuda-disable-target-call-checks -S -disable-free -disable-llvm-verifier
-main-file-name vf_scale_cuda_bicubic.cu -mrelocation-model static
-mthread-model posix -mdisable-fp-elim -fmath-errno -no-integrated-as
-mconstructor-aliases -fcuda-is-device -target-cpu sm_30 -dwarf-column-info
-debugger-tuning=gdb -coverage-file
/root/ffwin/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git_with_fdk_aac/libavfilter/vf_scale_cuda_bicubic.ptx
-resource-dir /usr/lib/llvm-3.8/bin/../lib/clang/3.8.1 -include
./compat/cuda/cuda_runtime.h -internal-isystem
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0
-internal-isystem
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0
-internal-isystem
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0
-internal-isystem
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/backward
-internal-isystem /usr/local/include -internal-isystem
/usr/lib/llvm-3.8/bin/../lib/clang/3.8.1/include -internal-externc-isystem
/include -internal-externc-isystem /usr/include -internal-isystem
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0
-internal-isystem
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0
-internal-isystem
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0
-internal-isystem
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/backward
-O2 -fdeprecated-macro -fno-dwarf-directory-asm -fdebug-compilation-dir
/root/ffwin/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git_with_fdk_aac
-ferror-limit 19 -fmessage-length 237 -fobjc-runtime=gcc -fcxx-exceptions
-fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops
-vectorize-slp -o libavfilter/vf_scale_cuda_bicubic.ptx -x cuda libavfilter/
vf_scale_cuda_bicubic.cu
>
> <eof> parser at end of file
>
> Code generation
>
> Running pass 'Function Pass Manager' on module 'libavfilter/
vf_scale_cuda_bicubic.cu'.
>
> Running pass 'NVPTX DAG->DAG Pattern Instruction Selection' on function
'@_Z17Subsample_BicubicIhEvPF6float4ffEyPT_iiiiiif'
>
> clang: error: unable to execute command: Segmentation fault
> clang: error: clang frontend command failed due to signal (use -v to see
invocation)
> clang version 3.8.1-24 (tags/RELEASE_381/final)
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> clang: note: diagnostic msg: PLEASE submit a bug report to
http://llvm.org/bugs/ and include the crash backtrace, preprocessed source,
and associated run script.
> clang: note: diagnostic msg:
>
> ________________________________
>
> PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
> Preprocessed source(s) and associated run script(s) are located at:
> clang: note: diagnostic msg: /tmp/vf_scale_cuda_bicubic-0dbdf2.cu
> clang: note: diagnostic msg: /tmp/vf_scale_cuda_bicubic-0dbdf2.sh
> clang: note: diagnostic msg:
>
> ________________________________
>
> ffbuild/common.mak:102: set di istruzioni per l'obiettivo
"libavfilter/vf_scale_cuda_bicubic.ptx" non riuscito
> make: *** [libavfilter/vf_scale_cuda_bicubic.ptx] Errore 254
> make: *** Attesa per i processi non terminati....
>
> exit 1
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/Ek15sIOYYBiWS6FFIsfQ2fmgdxXdAYC-lJhEuPel3DRtAx2AEK1N4JOZyoHUyoVPnWPFGO8diIJRbXqW4lBUzuDEP_B1GwthtvsI8ZQfQPEq9FlEywXKbiKjgzC-UjVemOiPjiG3DaZtPZHnWMfWFzzZJEpoTlUINdOOvW6Lt-jhKx9jy-X11ZXLmIs5ZqOJzfDXgzwISI4P7EAO-IOBYM-exFM=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUGI2MOY5LN2UVG7GJ3SORFZVA5CNFSM4TNCAWQ2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4K745IHQ.gif>

**Comment by SoftwareMagicIT** [comment]
Debian Buster on my Linux i5 server (not virtual)

**Comment by rdp** [comment]
Buster should be llvm 7?

On Saturday, November 7, 2020, Software Magic <notifications@github.com>
wrote:
> Debian Buster on my Linux i5 server (not virtual)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/Hzx-zORE4iRFQ7E1fDYxfIyd1w5_QflrcyTJjWIqQ4tWIIWBuIAZVhfJZ3WZ4kZMcE3ysMYlDw_GzYi_8H_I-sofqIk-VOytlsNxk2soJBM8LYa59wxqC616Nup-Fp7IOMvItoKmw-KnHJZBtC9LOQuD_c3ThOjMxftcsaaXWNDF7EjDTnO0lWcHfU5PdVDN5GY3fQ43uO06ILPWyCRmfg5HDll0wuj7AKQnAeLImw=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUA6X2BJ4UZP7GNCVQTSOTXVJA5CNFSM4TNCAWQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFMPEXYY.gif>

**Comment by SoftwareMagicIT** [comment]
I'm sorry debian is stretch and llvm is 3.8. But with ubuntu 18.04 I have successfully compiled for gpl version. But libaribb24 require version 1.0.3 or higher for lgpl

**Comment by rdp** [comment]
I'm not sure I understand, PR welcome always :)

**Comment by rdp** [comment]
Not sure how to support it...
