### ISSUE TITLE
Outputs for *nix version

### ISSUE THREAD

**Issue by asheimo** [rdp/ffmpeg-windows-build-helpers#508]
This may already be answered in the readme and I'm just blind but can this script also create binaries that will run on *nix? If not any idea what it would take and if you be interested in adding support?

**Comment by garoto** [comment]
Taking a glance at the name of the repository, I'm inclined to say that no, this won't output a Linux binary out of the box.

But googling for "ffmpeg Linux compiling script" returned this: https://github.com/markus-perl/ffmpeg-build-script

**Comment by rdp** [comment]
there is an option "--compiler-flavors=native" but I haven't used it in
awhile...

**Comment by rdp** [comment]
It may or may not work...

**Comment by asheimo** [comment]
OK so here is what I found using the native option, there are 2 areas that fail during the build, GLEW and FFmpeg itself.

To get GLEW to compile I had to install these packages: libxmu-dev, libxi-dev, libgl-dev, libxrandr-dev, libxinerama-dev, libxcursor-dev
I hope to see if they can be built into the chain or if GLEW is even needed.

For FFmpeg to compile I had to install these packages: libv4l-dev, libxcb-shm0-dev, libxcb-shape0-dev, libxcb-xfixes0-dev
These are directly related to line 2326 where the line before the comment says "just use locally packages for all the xcb stuff for now, you need to install them locally first..." maybe a check could be added for these packages and a warning given if they are missing? could they be added to the chain?

I am going to attempt to tackle some of this myself but any pointers or help would be appreciated. It would be nice to have one script I could use to build both Win and *nix version and not have to worry that they are built with different options.

**Comment by rdp** [comment]
Sure, just target ubuntu I think... maybe 20.04?

**Comment by rdp** [comment]
You can at least add those packages to the "huge package list" that it
spits out initially... :)
