### ISSUE TITLE
avisynth support?

### ISSUE THREAD

**Issue by Mister-XY** [rdp/ffmpeg-windows-build-helpers#509]
Hello, is it possible to add the avisynth support for the ffmpeg script?

**Comment by rdp** [comment]
Shoot I kind of dropped the ball on this one.  Might take me a little
while, PR's welcome :)

**Comment by Mister-XY** [comment]
I found a solution for me. I add the line `--enable-avisynth` to the line with code  `config_options="$init_options` and copy my headless avisynth folder to `/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/avisynth`.
I think its also easy to implent this in the `cross_compile_ffmpeg.sh` file

**Comment by rdp** [comment]
I thought they dropped support for avisynth in favor of avisynth2 or
sunbathing like that.  Hmmm

On Wednesday, November 25, 2020, Mister-XY <notifications@github.com> wrote:
> I found a solution for me. I add the line --enable-avisynth to the line
with code config_options="$init_options and copy my headless avisynth
folder to
/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/avisynth.
> I think its also easy to implent this in the cross_compile_ffmpeg.sh file
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/QKAPJf_owD8GagM5DOk85KBxXqpljvILTBWitvwYurBJgliILP6eKMo5q2hcyteGEkKqdd2A0ZUIUNfzU_oJ70d9llCQ_ozWdoUJ0CFQ7BGC6Wk--wUdxXCdccIk5KciMxNGfyRm4abxYevzG8Sb4V-n6vwznvmylq99sd96yjKfjET_0vZ36be7eDP5Q2ARf243deQIR8qKi9rR9uDbyedHBLNYipcT_XW8qCi1HA=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUECKGLVYXO6TXA3TGTSRSXLJA5CNFSM4UA5SKJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFO4KYHQ.gif>

**Comment by Mister-XY** [comment]
You need the header from avisynth+
https://github.com/AviSynth/AviSynthPlus

**Comment by rdp** [comment]
does latest master work now?

**Comment by Mister-XY** [comment]
It's look like fine.
