### ISSUE TITLE
VP8 encoding is not working (libvpx)

### ISSUE THREAD

**Issue by AnimMouse** [rdp/ffmpeg-windows-build-helpers#513]
Running FFmpeg build created by this script and using libvpx
```
ffmpeg -hide_banner -h encoder=libvpx
ffmpeg -hide_banner -i input.mp4 -c:v libvpx -c:a copy output.mp4
```
Returns with
```
Codec 'libvpx' is not recognized by FFmpeg.
Unknown encoder 'libvpx'
```
Even through the build is built with --enable-libvpx
```
ffmpeg version n4.3.1-ffmpeg-windows-build-helpers Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.1.0 (GCC)
  configuration: --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/runner/work/ffmpeg-stable-autobuild/ffmpeg-stable-autobuild/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-liblensfun --enable-libvmaf --enable-libsrt --enable-libaribb24 --enable-demuxer=dash --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libaom --enable-libvpx --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-filter=frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --enable-avresample --extra-cflags='-mtune=generic' --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/runner/work/ffmpeg-stable-autobuild/ffmpeg-stable-autobuild/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-nonfree --enable-libfdk-aac --enable-decklink
```
But VP9 (libvpx-vp9) is working.

**Comment by rdp** [comment]
Do zeranoe builds work?

On Tuesday, December 1, 2020, Anim Mouse <notifications@github.com> wrote:
> Running FFmpeg build created by this script and using libvpx
>
> ffmpeg -hide_banner -h encoder=libvpx
> ffmpeg -hide_banner -i input.mp4 -c:v libvpx -c:a copy output.mp4
>
> Returns with
>
> Codec 'libvpx' is not recognized by FFmpeg.
> Unknown encoder 'libvpx'
>
> Even through the build is built with --enable-libvpx
>
> ffmpeg version n4.3.1-ffmpeg-windows-build-helpers Copyright (c)
2000-2020 the FFmpeg developers
> built with gcc 10.1.0 (GCC)
> configuration: --pkg-config=pkg-config --pkg-config-flags=--static
--extra-version=ffmpeg-windows-build-helpers --enable-version3
--disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32
--cross-prefix=/home/runner/work/ffmpeg-stable-autobuild/ffmpeg-stable-autobuild/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-
--enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig
--enable-gmp --enable-gnutls --enable-libass --enable-libbluray
--enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi
--enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug
--enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb
--enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex
--enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc
--enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi
--enable-libmysofa --enable-libopenjpeg --enable-libopenh264
--enable-liblensfun --enable-libvmaf --enable-libsrt --enable-libaribb24
--enable-demuxer=dash --enable-libxml2 --enable-opengl --enable-libdav1d
--enable-cuda-llvm --enable-libaom --enable-libvpx --enable-nvenc
--enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm
--extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC
--extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf
--enable-libmfx --enable-gpl --enable-frei0r --enable-filter=frei0r
--enable-librubberband --enable-libvidstab --enable-libx264
--enable-libx265 --enable-libxvid --enable-libdavs2 --enable-libxavs2
--enable-libxavs --enable-avresample --extra-cflags='-mtune=generic'
--extra-cflags=-O3 --enable-static --disable-shared
--prefix=/home/runner/work/ffmpeg-stable-autobuild/ffmpeg-stable-autobuild/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
--enable-nonfree --enable-libfdk-aac --enable-decklink
>
> But VP9 (libvpx-vp9) is working.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/6KsR-TnU79_ygLJXjCkKZJag8di3sdg9cTJ00jrM88jrbm7Wo4p8hefGwkFIAI3etVkB-Fr72YTjw_TWU_mTs30Avl91WUbxhs5W3YO6OvG4iqZrAXoQ2rVt2a1rKYPl9gqcXriga90-J87ysrid2th9_y_H9Wr0koJipeJPpmCY1ZKIOu9qemQYcbhTGD9hEdHASxmK7jegtZ7YsIWjSAlnYyY=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUEFX5LAXRZWFGUQU6LSSS5PFA5CNFSM4UIZNDMKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4LHU5T2A.gif>

**Comment by AnimMouse** [comment]
@rdp Yes, tried it on the latest Zeranoe builds (before it's shutdown), [gyan.dev](https://www.gyan.dev/ffmpeg/builds/) and [BtbN](https://github.com/BtbN/FFmpeg-Builds) builds.

**Comment by rdp** [comment]
Hmm wonder what the difference is...

**Comment by mbechard** [comment]
I'm running into the same issue. The configure tests for ffmpeg are failing when trying to enable vp8 with the linker error:
`undefined reference to 'vp8_full_search_sadx3'.`
The VP9 tests pass fine.

**Comment by mbechard** [comment]
Looks to be related to the --disable-sse3 option you are passing to configure libvpx. If I remove that then the ffmpeg configure picks up vp8 correctly. Not sure what the ramifications are of removing this option though

**Comment by AnimMouse** [comment]
Closed with https://github.com/rdp/ffmpeg-windows-build-helpers/pull/602

**Comment by FransW5** [comment]
Why doesn't libvpx OR libvpx-vp9 work?
```
Unknown encoder 'libvpx'
Unknown encoder 'libvpx-vp9'
```

**Comment by AnimMouse** [comment]
@FransW5 #679
