### ISSUE TITLE
LGPL build fails because of AviSynth

### ISSUE THREAD

**Issue by kusaanko** [rdp/ffmpeg-windows-build-helpers#516]
When I try to build the LGPL version, I get the following error

```
avisynth is gpl and --enable-gpl is not specified.
```

Isn't AviSynth GPL-only?

**Comment by rdp** [comment]
I guess so.  If you remove enable avisynth how far does it get?

On Friday, December 11, 2020, Kusaanko <notifications@github.com> wrote:
> When I try to build the LGPL version, I get the following error
>
> avisynth is gpl and --enable-gpl is not specified.
>
> Isn't AviSynth GPL-only?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/ESI3TXsE2WcwWE4QypYauFI4TRd8vDN74_OeKQVA_rHDnxrOwjUtJq1Wp3ueYaj_tNWpLuqLa5TtgYOOjhY3clbEGXPVuEjkCIL-XMvJgwmO3eEgLODdq-ePpqqdl54CuR0nSYTSwXMuZEkR9PDhri5X_b5T7aOoNaskDvDCufhkUoYRw5BYpNioXBTh0A2BkQXUACQbY2BakQHUZ8x84ap9-rg=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUHOATXEDVSZBXR7AXLSUIR5VA5CNFSM4UWV5FX2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4LLQ6GGQ.gif>

**Comment by kusaanko** [comment]
I have the same problem as #510, so I removed --enable-libaribb24.
I also removed --enable-avisynth from the script and it builds fine.
