### ISSUE TITLE
Fails because libilbc git has 'main' branch instead of 'master'

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [rdp/ffmpeg-windows-build-helpers#519]
The script attempts to checkout `origin/master` for https://github.com/TimothyGu/libilbc but the main branch is `origin/main`, which causes

```
error: pathspec 'origin/master' did not match any file(s) known to git
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
```

Main branch name was changed ~6 hours ago.

**Comment by brianjford** [comment]
Emmanuel, even with your change to the main branch, it still doesn't build for me.  
It looks to me like the script needs to be changed to use CMake instead of just calling ./configure; and also it needs to run "git submodule update --init".

**Comment by rdp** [comment]
Maybe we can switch to an older commit that still used configure or an
older release tarball?

On Friday, December 18, 2020, brianjford <notifications@github.com> wrote:
> Emmanuel, even with your change to the main branch, it still doesn't
build for me.
> It looks to me like the script needs to be changed to use CMake instead
of just calling ./configure; and also it needs to run "git submodule update
--init".
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/xi29Uk76aIThzJ6GEW1Jb1I-JSBZGd5Ozc9doiKEKoXGEokMQLcUwHrt3eycWUXjEaDGapIaG9JJhRG_EEuBEidYNTOvhqXmv4nOqQMFaZ2_vE6hqPXL-2PKBigp4prut06ZJMhtPrzQHosIovOdDLcIwdSgsZvkYUVa_jTosQxbRNkeIFC1h5ToDUsauJT0YhZLlwRiG1IlbkpuoOVpIXcWVlln78BMZCAV799YZg=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUDJ7VWUETD6UFPQW6DSVOVGNA5CNFSM4VA7EMWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFSM565Q.gif>

**Comment by AlyoshaVasilieva** [comment]
I changed the relevant call to `do_git_checkout https://github.com/TimothyGu/libilbc.git libilbc_git v2.0.2` and it appears to have fixed the libilbc build process, if anyone else needs a short-term workaround.

**Comment by rdp** [comment]
I think we worked around it, thanks for the report.
