### ISSUE TITLE
x265 now has an official git repo

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [rdp/ffmpeg-windows-build-helpers#520]
Currently the script tries to pull x265 from `http://hg.videolan.org/x265` which is failing as it appears to be down. Might be temporary. While investigating this I noticed that the hg repo https://bitbucket.org/multicoreware/x265 is now dead and has been recently replaced by the git repo https://bitbucket.org/multicoreware/x265_git. VideoLAN also maintain a GitHub mirror at https://github.com/videolan/x265.

The script notes that x265 is "the only one that uses mercurial" so it may be a good time to switch to a git repo.

**Comment by rdp** [comment]
Try the latest, though untested as of yet...

**Comment by AlyoshaVasilieva** [comment]
Appears to work, compiled successfully. Thanks.

**Comment by rdp** [comment]
Seems fixed, thanks for the report.
