### ISSUE TITLE
Script won't run

### ISSUE THREAD

**Issue by ReenigneArcher** [rdp/ffmpeg-windows-build-helpers#523]
I cannot get this script to run. Not sure if it matters, but OS is Ubuntu 20.10 running in as a VirtualBox guest.

The script is saying some packages are missing; however running the recommended commands doesn't install anything new and still can't run the script. Any ideas?
```
Could not find the following execs (svn is actually package subversion, makeinfo is actually package texinfo, hg is actually package  if you're missing them): hg
Install the missing packages before running this script.
for ubuntu:
$ sudo apt-get update
$ sudo apt-get install subversion ragel curl texinfo g++ bison flex cvs yasm automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev unzip pax nasm gperf autogen bzip2 autoconf-archive p7zip-full meson clang python3-distutils python-is-python3 -y
osboxes@osboxes:~/ffmpeg-windows-build-helpers$ sudo apt-get update
[sudo] password for osboxes: 
Get:1 http://security.ubuntu.com/ubuntu groovy-security InRelease [110 kB]
Hit:2 http://us.archive.ubuntu.com/ubuntu groovy InRelease
Get:3 http://us.archive.ubuntu.com/ubuntu groovy-updates InRelease [110 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu groovy-backports InRelease [101 kB]
Fetched 321 kB in 2s (173 kB/s)   
Reading package lists... Done
osboxes@osboxes:~/ffmpeg-windows-build-helpers$ sudo apt-get install subversion ragel curl texinfo g++ bison flex cvs yasm automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev unzip pax nasm gperf autogen bzip2 autoconf-archive p7zip-full meson clang python3-distutils python-is-python3 -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-11.1).
automake is already the newest version (1:1.16.2-4ubuntu1).
bison is already the newest version (2:3.7+dfsg-1).
bzip2 is already the newest version (1.0.8-4ubuntu2).
cmake is already the newest version (3.16.3-3ubuntu2).
flex is already the newest version (2.6.4-8).
g++ is already the newest version (4:10.2.0-1ubuntu1).
gcc is already the newest version (4:10.2.0-1ubuntu1).
git is already the newest version (1:2.27.0-1ubuntu1).
libtool is already the newest version (2.4.6-14).
make is already the newest version (4.3-4ubuntu1).
pax is already the newest version (1:20190825-1).
pkg-config is already the newest version (0.29.2-1ubuntu1).
python-is-python3 is already the newest version (3.8.2-4).
python3-distutils is already the newest version (3.8.6-1).
unzip is already the newest version (6.0-25ubuntu1).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu4).
autoconf-archive is already the newest version (20190106-2.1ubuntu1).
autogen is already the newest version (1:5.18.16-4).
clang is already the newest version (1:11.0-51~exp1).
cvs is already the newest version (2:1.12.13+real-27build1).
gperf is already the newest version (3.1-1build1).
meson is already the newest version (0.55.3-1).
nasm is already the newest version (2.15.04-1).
p7zip-full is already the newest version (16.02+dfsg-8).
ragel is already the newest version (6.10-1build1).
subversion is already the newest version (1.14.0-2).
texinfo is already the newest version (6.7.0.dfsg.2-5).
yasm is already the newest version (1.3.0-2ubuntu1).
curl is already the newest version (7.68.0-1ubuntu4.2).
The following package was automatically installed and is no longer required:
  virtualbox-guest-utils
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by rdp** [comment]
Oops try latest again?

On Monday, December 21, 2020, ReenigneArcher <notifications@github.com>
wrote:
> I cannot get this script to run. Not sure if it matters, but OS is Ubuntu
20.10 running in as a VirtualBox guest.
>
> The script is saying some packages are missing; however running the
recommended commands doesn't install anything new and still can't run the
script. Any ideas?
>
> Could not find the following execs (svn is actually package subversion,
makeinfo is actually package texinfo, hg is actually package if you're
missing them): hg Install the missing packages before running this script.
for ubuntu: $ sudo apt-get update $ sudo apt-get install subversion ragel
curl texinfo g++ bison flex cvs yasm automake libtool autoconf gcc cmake
git make pkg-config zlib1g-dev unzip pax nasm gperf autogen bzip2
autoconf-archive p7zip-full meson clang python3-distutils python-is-python3
-y osboxes@osboxes:~/ffmpeg-windows-build-helpers$ sudo apt-get update
[sudo] password for osboxes: Get:1 http://security.ubuntu.com/ubuntu
groovy-security InRelease [110 kB] Hit:2 http://us.archive.ubuntu.com/ubuntu
groovy InRelease Get:3 http://us.archive.ubuntu.com/ubuntu groovy-updates
InRelease [110 kB] Get:4 http://us.archive.ubuntu.com/ubuntu
groovy-backports InRelease [101 kB] Fetched 321 kB in 2s (173 kB/s) Reading
package lists... Done osboxes@osboxes:~/ffmpeg-windows-build-helpers$ sudo
apt-get install subversion ragel curl texinfo g++ bison flex cvs yasm
automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev unzip
pax nasm gperf autogen bzip2 autoconf-archive p7zip-full meson clang
python3-distutils python-is-python3 -y Reading package lists... Done
Building dependency tree Reading state information... Done autoconf is
already the newest version (2.69-11.1). automake is already the newest
version (1:1.16.2-4ubuntu1). bison is already the newest version
(2:3.7+dfsg-1). bzip2 is already the newest version (1.0.8-4ubuntu2). cmake
is already the newest version (3.16.3-3ubuntu2). flex is already the newest
version (2.6.4-8). g++ is already the newest version (4:10.2.0-1ubuntu1).
gcc is already the newest version (4:10.2.0-1ubuntu1). git is already the
newest version (1:2.27.0-1ubuntu1). libtool is already the newest version
(2.4.6-14). make is already the newest version (4.3-4ubuntu1). pax is
already the newest version (1:20190825-1). pkg-config is already the newest
version (0.29.2-1ubuntu1). python-is-python3 is already the newest version
(3.8.2-4). python3-distutils is already the newest version (3.8.6-1). unzip
is already the newest version (6.0-25ubuntu1). zlib1g-dev is already the
newest version (1:1.2.11.dfsg-2ubuntu4). autoconf-archive is already the
newest version (20190106-2.1ubuntu1). autogen is already the newest version
(1:5.18.16-4). clang is already the newest version (1:11.0-51~exp1). cvs is
already the newest version (2:1.12.13+real-27build1). gperf is already the
newest version (3.1-1build1). meson is already the newest version
(0.55.3-1). nasm is already the newest version (2.15.04-1). p7zip-full is
already the newest version (16.02+dfsg-8). ragel is already the newest
version (6.10-1build1). subversion is already the newest version
(1.14.0-2). texinfo is already the newest version (6.7.0.dfsg.2-5). yasm is
already the newest version (1.3.0-2ubuntu1). curl is already the newest
version (7.68.0-1ubuntu4.2). The following package was automatically
installed and is no longer required: virtualbox-guest-utils Use 'sudo apt
autoremove' to remove it. 0 upgraded, 0 newly installed, 0 to remove and 0
not upgraded.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/QIaBeMkV6BtKGQL3G-RtlpgvaCnKHy4NBtGlFSxVpjRKple7OyhUc241P_l-PeDQl9uWqsYWOq3U949P420j42DtbmGcQTJWE4qQr7-vAcO0Q-4uwTV6rhrvhYsj5X50Psgdgk18g2AgzWZ3IXTCkXjLPgifAerCxfxhDFKxyyTTGw8LYC0FIQul42ADAzatIu2tRNe8AX6H_2pUrkwcl-S17wU=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUCFQFLCSOYVLX74DLTSV6VXTA5CNFSM4VEWGFT2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4LQKQ7TQ.gif>

**Comment by ReenigneArcher** [comment]
It's working now. Thank you!
