### ISSUE TITLE
Compile failures using 

### ISSUE THREAD

**Issue by emveepee** [rdp/ffmpeg-windows-build-helpers#529]
First it is not clear which option I should use to compile ffmpeg for Windows, the MingGW builds or the native mode.  No matter since I have tried both and neither seem to work and hoping for some help to move forward.

In MinGW-w64 mode I can compile the cross compiler but then I get a C compiler not found message before the script finishes.  I tried updating the path as suggested but no change.

In native mode there are several libraries not built but even if I disable the failing ones I get failures.  The failing modules I disable are libtesseract, libflite, 

I believe things are ok in general because the quick option does build ffmpeg and ffprobe.   I am hoping to build ffplay version as well  

Thanks for this very helpful tool.

**Comment by rdp** [comment]
MingGW for windows.
I assume you'd is the other issue logged in the x compiler...

On Thursday, December 31, 2020, emveepee <notifications@github.com> wrote:
> First it is not clear which option I should use to compile ffmpeg for
Windows, the MingGW builds or the native mode. No matter since I have tried
both and neither seem to work and hoping for some help to move forward.
>
> In MinGW-w64 mode I can compile the cross compiler but then I get a C
compiler not found message before the script finishes. I tried updating the
path as suggested but no change.
>
> In native mode there are several libraries not built but even if I
disable the failing ones I get failures. The failing modules I disable are
libtesseract, libflite,
>
> I believe things are ok in general because the quick option does build
ffmpeg and ffprobe. I am hoping to build ffplay version as well
>
> Thanks for this very helpful tool.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/MSTTbHn_I3XJv1TngZiZD0_sh8kID7ICNWUw3jH4U1FugpMLBq7P9G1U5ychHheQry36dIN867m8LcOED8EAQF_oEdZYGVQI89Fppbx6bmH7G-TueRA_BiDH-fNQG6gxi-ZZOYmEHYQmRXzxsISU1Kx9TaTpfhq23LN9oiZYuVvEfewLYi-VunfBXKlQtoWXgd4q5CvjyV2FMHX30yBQPjcA6qA=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUHWGIS77BPQP47FPK3SXTIXLA5CNFSM4VPV5OK2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4LSR7CNA.gif>

**Comment by emveepee** [comment]
> 
> MingGW for windows. I assume you'd is the other issue logged in the x compiler...

This is my first post not clear what you mean.  I will try again tomorrow and leave native alone.

**Comment by rdp** [comment]
Oops "yours is the other issue"?

On Thursday, December 31, 2020, emveepee <notifications@github.com> wrote:
> MingGW for windows. I assume you'd is the other issue logged in the x
compiler...
>
> This is my first post not clear what you mean. I will try again tomorrow
and leave native alone.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/mlEHLBmceSWnWyk0OLzNVufhW1soyVcRFfq9dFrVhts_SEMdhhxDYHHZhTaQCMZSD3pf0SnjA7sf6nAEGWCxB2jGIQrmWt1CKL1JKeBr_32_VpXaxYyL6JO8rIz4FzWlcW4sfjKPoCYH3cD8c7limklWKBlbkzv_soYfVsWzZQssDWneQ4xXfjXC5Jz-BdQ0J1ljIFDQw_5OEQ36WoRuWusyz1Jk2HeVo59NFSXYSA=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUDFECM34THDHR7SF5TSXVM7LA5CNFSM4VPV5OK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFTS5SCY.gif>

**Comment by emveepee** [comment]
> Oops "yours is the other issue"?

I do see a similar thread but after using option 3 this is what I see

```
Done building (or already built) MinGW-w64 cross-compiler(s) successfully...
Fri 01 Jan 2021 12:07:45 PM EST

**************Starting 64-bit builds...
Building ffmpeg dependency libraries...
doing git checkout origin/master
M	Makefile
fetched no code changes, not forcing reconfigure for that...
Already made dlfcn-win32_git ...
not svn Updating xavs_svn since usually svn repo's aren't updated frequently enough...
configuring xavs_svn (/media/acer/ac4/ffmpeg-windows-build-helpers/sandbox/win64/xavs_svn) as $ PKG_CONFIG_PATH=/media/acer/ac4/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/media/acer/ac4/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --host=x86_64-w64-mingw32 --prefix=/media/acer/ac4/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --cross-prefix=/media/acer/ac4/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-
all touch files already_configured* touchname= already_configured_b7361917104b8f0b38cbdb21b20bb7be-
config options --host=x86_64-w64-mingw32 --prefix=/media/acer/ac4/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --cross-prefix=/media/acer/ac4/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- ./configure
No working C compiler found.
```

**Comment by emveepee** [comment]
When I change $DEVNULL to /dev/null in configure for xavs_svn my compile work fine.

**Comment by rdp** [comment]
what is DEVNULL by default?

**Comment by emveepee** [comment]
When I change $DEVNULL to /dev/null in configure for xavs_svn my compile work fine.

> what is DEVNULL by default?

Is is showing as NUL set in line 208 I am running Ubuntu 20.04

**Comment by rdp** [comment]
Issue still present with latest?

**Comment by rdp** [comment]
Closing no feedback
