### ISSUE TITLE
FFMPEg compile error

### ISSUE THREAD

**Issue by pranjalisnow** [rdp/ffmpeg-windows-build-helpers#531]
FFMPEG compiler stops with this error....

`config.status: error: cannot find input file: `doc/libsndfile.css.in'`

**Comment by rdp** [comment]
Still failing?

On Sunday, January 3, 2021, pranjalisnow <notifications@github.com> wrote:
> FFMPEG compiler stops with this error....
>
> config.status: error: cannot find input file: doc/libsndfile.css.in'`
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/DKWSwDvU8i0G-SuD6gyJiIwVeBhfDDxTAS_bUDWX5dyUtXjMBgmQFV8f5bbCheE7p94TcBklYjItmgDGfAWaKpzGROM2S5eCYuhaHA2yeTgHnEhXJylV3fOYXNLzh7BfcDPcdk1bWFypiGwOpGv9oDcRwHYqyh2XTx9bZOOS8TZrY8y1aX_SGoLDs5leXGMgnk1fNR_nhwHffGF-bBKvmknu9yQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUCL4NTFSK4W6HSZK7TSYAQRDA5CNFSM4VRVXIQ2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4LSZEKGA.gif>

**Comment by pranjalisnow** [comment]
Thank your for your reply.

Just started a re-compile..... will update here.

Regards.

**Comment by pranjalisnow** [comment]
Still the same error.
part of the last bit of the compile process is below....

`doing git checkout origin/master
Previous HEAD position was d03045b0 Fix GitHub actions CI macOS job
HEAD is now at 91131124 Improve handling of SMPL chunks in WAV files. fixes #675
got upstream changes, forcing re-configure. Doing git clean -f
HEAD is now at 91131124 Improve handling of SMPL chunks in WAV files. fixes #675
Removing include/sndfile.h
configuring libsndfile_git (/home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/win32/libsndfile_git) as $ PKG_CONFIG_PATH=/home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/pkgconfig PATH=/home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin:$PATH ./configure --host=i686-w64-mingw32 --prefix=/home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --disable-shared --enable-static --disable-sqlite --disable-external-libs --disable-full-suite
all touch files already_configured* touchname= already_configured_11bbb464d271c4b48f134c1afecd9245-
config options --host=i686-w64-mingw32 --prefix=/home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --disable-shared --enable-static --disable-sqlite --disable-external-libs --disable-full-suite ./configure
checking whether configure should try to set CFLAGS/CXXFLAGS/CPPFLAGS/LDFLAGS... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... i686-w64-mingw32
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for i686-w64-mingw32-strip... i686-w64-mingw32-strip
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for i686-w64-mingw32-gcc... i686-w64-mingw32-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether i686-w64-mingw32-gcc accepts -g... yes
checking for i686-w64-mingw32-gcc option to accept ISO C89... none needed
checking whether i686-w64-mingw32-gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of i686-w64-mingw32-gcc... gcc3
checking for i686-w64-mingw32-gcc option to accept ISO C99... none needed
checking how to run the C preprocessor... i686-w64-mingw32-gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for i686-w64-mingw32-g++... i686-w64-mingw32-g++
checking whether we are using the GNU C++ compiler... yes
checking whether i686-w64-mingw32-g++ accepts -g... yes
checking dependency style of i686-w64-mingw32-g++... gcc3
checking for C compiler vendor... gnu
checking for a sed that does not truncate output... /usr/bin/sed
checking for C compiler version... 10.1.0
checking for C++ compiler vendor... gnu
checking for C++ compiler version... 10.1.0
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for i686-w64-mingw32-ar... i686-w64-mingw32-ar
checking the archiver (i686-w64-mingw32-ar) interface... ar
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by i686-w64-mingw32-gcc... /home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld
checking if the linker (/home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-nm -B
checking the name lister (/home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to i686-w64-mingw32 format... func_convert_file_nix_to_w32
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld option to reload object files... -r
checking for i686-w64-mingw32-objdump... i686-w64-mingw32-objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for i686-w64-mingw32-dlltool... i686-w64-mingw32-dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for i686-w64-mingw32-ar... (cached) i686-w64-mingw32-ar
checking for archiver @FILE support... @
checking for i686-w64-mingw32-strip... (cached) i686-w64-mingw32-strip
checking for i686-w64-mingw32-ranlib... i686-w64-mingw32-ranlib
checking command to parse /home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-nm -B output from i686-w64-mingw32-gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for i686-w64-mingw32-mt... no
checking for mt... mt
configure: WARNING: using cross tools not prefixed with host triplet
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for i686-w64-mingw32-as... i686-w64-mingw32-as
checking for i686-w64-mingw32-dlltool... (cached) i686-w64-mingw32-dlltool
checking for i686-w64-mingw32-objdump... (cached) i686-w64-mingw32-objdump
checking for objdir... .libs
checking if i686-w64-mingw32-gcc supports -fno-rtti -fno-exceptions... no
checking for i686-w64-mingw32-gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if i686-w64-mingw32-gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if i686-w64-mingw32-gcc static flag -static works... yes
checking if i686-w64-mingw32-gcc supports -c -o file.o... yes
checking if i686-w64-mingw32-gcc supports -c -o file.o... (cached) yes
checking whether the i686-w64-mingw32-gcc linker (/home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... i686-w64-mingw32-g++ -E
checking for ld used by i686-w64-mingw32-g++... /home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld
checking if the linker (/home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld) is GNU ld... yes
checking whether the i686-w64-mingw32-g++ linker (/home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld) supports shared libraries... yes
checking for i686-w64-mingw32-g++ option to produce PIC... -DDLL_EXPORT -DPIC
checking if i686-w64-mingw32-g++ PIC flag -DDLL_EXPORT -DPIC works... yes
checking if i686-w64-mingw32-g++ static flag -static works... yes
checking if i686-w64-mingw32-g++ supports -c -o file.o... yes
checking if i686-w64-mingw32-g++ supports -c -o file.o... (cached) yes
checking whether the i686-w64-mingw32-g++ linker (/home/pk/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking for i686-w64-mingw32-windres... i686-w64-mingw32-windres
checking whether ln -s works... yes
checking for python... /usr/bin/python
checking for python version... 3.8
checking for python platform... linux
checking for python script directory... ${prefix}/lib/python3.8/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python3.8/site-packages
checking for autogen... yes
checking for wine... no
checking for xcode-select... no
checking for ANSI C header files... (cached) yes
checking endian.h usability... no
checking endian.h presence... no
checking for endian.h... no
checking byteswap.h usability... no
checking byteswap.h presence... no
checking for byteswap.h... no
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for sys/wait.h that is POSIX.1 compatible... no
checking whether S_IRGRP is declared... yes
checking size of wchar_t... 2
checking size of short... 2
checking size of int... 4
checking size of long... 4
checking size of float... 4
checking size of double... 8
checking size of void*... 4
checking size of size_t... 4
checking size of int64_t... 8
checking size of long long... 8
checking size of off_t... 4
checking for ssize_t... yes
checking whether byte ordering is bigendian... no
checking for malloc... yes
checking for calloc... yes
checking for realloc... yes
checking for free... yes
checking for open... yes
checking for read... yes
checking for write... yes
checking for lseek... yes
checking for lseek64... yes
checking for fstat... yes
checking for fstat64... no
checking for ftruncate... yes
checking for fsync... no
checking for snprintf... yes
checking for vsnprintf... yes
checking for gmtime... yes
checking for gmtime_r... no
checking for localtime... yes
checking for localtime_r... no
checking for gettimeofday... yes
checking for mmap... no
checking for getpagesize... yes
checking for setlocale... yes
checking for pipe... no
checking for waitpid... no
checking for library containing floor... none required
checking for floor... yes
checking for ceil... yes
checking for fmod... yes
checking for lrint... yes
checking for lrintf... yes
checking for i686-w64-mingw32-pkg-config... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
configure: WARNING: *** External libs (FLAC, Ogg, Vorbis) disabled. ***

configure: WARNING: *** One or more of the external libraries (ie libflac, libogg and
configure: WARNING: *** libvorbis) is either missing (possibly only the development
configure: WARNING: *** headers) or is of an unsupported version.
configure: WARNING: ***
configure: WARNING: *** Unfortunately, for ease of maintenance, the external libs
configure: WARNING: *** are an all or nothing affair.

checking processor clipping capabilities... none
checking for ALSA... no
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Wextra... yes
checking whether C compiler accepts -Wpointer-arith... yes
checking whether C compiler accepts -Wcast-align... yes
checking whether C compiler accepts -Wcast-qual... yes
checking whether C compiler accepts -Wshadow... yes
checking whether C compiler accepts -Wwrite-strings... yes
checking whether C compiler accepts -Wundef... yes
checking whether C compiler accepts -Wuninitialized... yes
checking whether C compiler accepts -Winit-self... yes
checking whether C compiler accepts -Wno-format-truncation... yes
checking whether C compiler accepts -Wvla... yes
checking whether C compiler accepts -Wbad-function-cast... yes
checking whether C compiler accepts -Wnested-externs... yes
checking whether C compiler accepts -Wstrict-prototypes... yes
checking whether C compiler accepts -Wmissing-prototypes... yes
checking whether C compiler accepts -Wmissing-declarations... yes
checking whether C compiler accepts -Waggregate-return... yes
checking whether C++ compiler accepts -Wall... yes
checking whether C++ compiler accepts -Wextra... yes
checking whether C++ compiler accepts -Wpointer-arith... yes
checking whether C++ compiler accepts -Wcast-align... yes
checking whether C++ compiler accepts -Wcast-qual... yes
checking whether C++ compiler accepts -Wshadow... yes
checking whether C++ compiler accepts -Wwrite-strings... yes
checking whether C++ compiler accepts -Wundef... yes
checking whether C++ compiler accepts -Wuninitialized... yes
checking whether C++ compiler accepts -Winit-self... yes
checking whether C++ compiler accepts -Wno-format-truncation... yes
checking whether C++ compiler accepts -Wctor-dtor-privacy... yes
checking whether C++ compiler accepts -Wnon-virtual-dtor... yes
checking whether C++ compiler accepts -Woverloaded-virtual... yes
checking whether C++ compiler accepts -Wreorder... yes
checking whether C++ compiler accepts -Wsign-promo... yes
checking whether to add -D_FORTIFY_SOURCE=2 to CPPFLAGS... no
checking whether C compiler accepts -mstackrealign... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating Octave/Makefile
config.status: creating src/version-metadata.rc
config.status: creating include/sndfile.h
config.status: creating tests/test_wrapper.sh
config.status: creating tests/pedantic-header-test.sh
config.status: error: cannot find input file: `doc/libsndfile.css.in'`

**Comment by rdp** [comment]
Issue still present?

**Comment by rdp** [comment]
Closing no feedback
