### ISSUE TITLE
ffmpeg compile error in rubberband_git ladspa.h

### ISSUE THREAD

**Issue by smoothstreams** [rdp/ffmpeg-windows-build-helpers#534]
Using OS Ubuntu 20 LTS.

Getting an error on rubberband_git

Cannot seem to find some LADSPA header ladspa.h.

Here is the tail end of the ffmpeg compile script.

Already made vamp-plugin-sdk-vamp-plugin-sdk-v2.10 ...
Already made fftw-3.3.8 ...
doing git checkout origin/master
HEAD is now at 27efea7 Restore accidentally deleted Jekyll files
fetched no code changes, not forcing reconfigure for that...
Already made libsamplerate_git ...
doing git checkout origin/master
M	Makefile.in
M	rubberband.pc.in
HEAD is now at 955a32f Copyright dates
fetched no code changes, not forcing reconfigure for that...
configuring rubberband_git (/home/ffmpeg/utils/ffmpeg/ffmpeg-windows-build-helpers/sandbox/win64/rubberband_git) as $ PKG_CONFIG_PATH=/home/ffmpeg/utils/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/home/ffmpeg/utils/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --host=x86_64-w64-mingw32 --prefix=/home/ffmpeg/utils/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
all touch files already_configured* touchname= already_configured_03b5f3cde612a4ea32e300b0cbd6aa58-
config options --host=x86_64-w64-mingw32 --prefix=/home/ffmpeg/utils/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 ./configure
checking for x86_64-w64-mingw32-g++... x86_64-w64-mingw32-g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether x86_64-w64-mingw32-g++ accepts -g... yes
checking for x86_64-w64-mingw32-g++ option to enable C++11 features... none needed
checking for x86_64-w64-mingw32-gcc... x86_64-w64-mingw32-gcc
checking whether the compiler supports GNU C... yes
checking whether x86_64-w64-mingw32-gcc accepts -g... yes
checking for x86_64-w64-mingw32-gcc option to enable C11 features... none needed
checking for x86_64-w64-mingw32-pkg-config... no
checking for pkg-config... /usr/bin/pkg-config
configure: WARNING: using cross tools not prefixed with host triplet
checking pkg-config is at least version 0.9.0... yes
checking for SRC... yes
checking for SNDFILE... yes
checking for FFTW... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for ladspa.h... no
configure: error: LADSPA header not found

Consider installing the LADSPA SDK or configuring with --disable-ladspa

Thanks.

**Comment by smoothstreams** [comment]
Since we probably do not need ladspa thing, I followed the text and added --disable-ladspa to configure line on librubberband.
Until someone gives a better answer or fix.

On a side note, rdp, thanks for all you do.

build_librubberband() {
  do_git_checkout https://github.com/breakfastquay/rubberband.git
  cd rubberband_git
    apply_patch file://$patch_dir/rubberband_git_static-lib.diff # create install-static target
    do_configure "--host=$host_target --prefix=$mingw_w64_x86_64_prefix **--disable-ladspa**"

And the compile has finished ok without the ladspa thing.

**Comment by naabtog** [comment]
I am getting the same error. I installed ladspa-sdk but the script still can't find ladspa.h. Maybe fault is on rubberband's side. Either way @smoothstreams fix is a temporary solution.

**Comment by Mister-XY** [comment]
same error here. I use debian.

**Comment by rdp** [comment]
I think the pr fixed it, please confirm
