### ISSUE TITLE
not support vmware? build failures 

### ISSUE THREAD

**Issue by qythker** [rdp/ffmpeg-windows-build-helpers#536]
.vmware16 ubuntu 20.04lts

when i execute ./cross_compile_ffmpeg.sh 

unzipping fontconfig-2.13.92.tar.xz ...
configuring fontconfig-2.13.92 (/home/ubuntu/桌面/ffmpeg-windows-build-helpers/sandbox/win32/fontconfig-2.13.92) as $ PKG_CONFIG_PATH=/home/ubuntu/桌面/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/pkgconfig PATH=/home/ubuntu/桌面/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin:$PATH ./configure --host=i686-w64-mingw32 --prefix=/home/ubuntu/桌面/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --disable-shared --enable-static --enable-iconv --enable-libxml2 --disable-docs --with-libiconv
all touch files already_configured* touchname= already_configured_bfea33178b68d079b757278eb09c7f8c-
config options --host=i686-w64-mingw32 --prefix=/home/ubuntu/桌面/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32 --disable-shared --enable-static --enable-iconv --enable-libxml2 --disable-docs --with-libiconv ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking ....
checking ....
checking ....
*** SAX1 support in libxml2 is required. enable it or use expat instead

How to solve it,Thanks for you help.

**Comment by rdp** [comment]
Nuke sandbox and try again same result?

On Tuesday, January 19, 2021, qyt <notifications@github.com> wrote:
> .vmware16 ubuntu 20.04lts
>
> when i execute ./cross_compile_ffmpeg.sh
>
> unzipping fontconfig-2.13.92.tar.xz ...
> configuring fontconfig-2.13.92
(/home/ubuntu/桌面/ffmpeg-windows-build-helpers/sandbox/win32/fontconfig-2.13.92)
as $
PKG_CONFIG_PATH=/home/ubuntu/桌面/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/pkgconfig
PATH=/home/ubuntu/桌面/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin:$PATH
./configure --host=i686-w64-mingw32
--prefix=/home/ubuntu/桌面/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32
--disable-shared --enable-static --enable-iconv --enable-libxml2
--disable-docs --with-libiconv
> all touch files already_configured* touchname=
already_configured_bfea33178b68d079b757278eb09c7f8c-
> config options --host=i686-w64-mingw32
--prefix=/home/ubuntu/桌面/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32
--disable-shared --enable-static --enable-iconv --enable-libxml2
--disable-docs --with-libiconv ./configure
> checking for a BSD-compatible install... /usr/bin/install -c
> checking ....
> checking ....
> checking ....
> *** SAX1 support in libxml2 is required. enable it or use expat instead
>
> How to solve it,Thanks for you help.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/M58wh06W6px6eE-C446xMMts2jLE5kOgxN3Zxjrdg11aiYEuuzjcUsjXeIHLwU2oamkmGsk8INK9Q3JkIXm9ucDMN_Prl9hPn6gudeQxrHSeEQwYsvZTw-7iHCX82_iNy2EHfSTBcTNuUIOgST8KDPwbgYw-7AVkJLddLdo00Kimt2t0JQXs7aHubkCLAiPCTRf1P9L8GMynXiZy06WG6jKaM-I=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUESBWGXA63NFZYZQQLS2Y6G5A5CNFSM4WJ7CXVKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4LYP5ICA.gif>

**Comment by qythker** [comment]
yes.tried many time is same error

**Comment by hglee** [comment]
Would you try to avoid chinese text in directory name?

I got same error if I use korean text in directory name.

@rdp I attached error log for that (include path error).

[config.log](https://github.com/rdp/ffmpeg-windows-build-helpers/files/5854388/config.log)

**Comment by rdp** [comment]
So works ok with latin char path?

On Friday, January 22, 2021, Hyogeol Lee <notifications@github.com> wrote:
> Would you try to avoid chinese text in directory name?
>
> I got same error if I use korean text in directory name.
>
> @rdp I attached error log for that (include path error).
>
> config.log
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/NLvflWgPLbaQDIdYZHhwJVgvnLhxZaZXM-q9pGk7_rloMF4DDeYOlgPnwF4u837jVTTiKKLLH7orgG295Xm5bFVXtV34X_qyLCHXTb7ZTg1-fnh0debzgAQ7EuiHNSs-8HpgDERtRxoLAjKawc6O9npjdrjWvlnc5ErVgnwphCbVz02GCt8fFJYZkONs1bL_KlWadAPC-b6bdl4PMU4kTAWTUC5JYoj0Qzypjrd74Q=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUF7BRIDWO4K62F75GDS3EYJBA5CNFSM4WJ7CXVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFWOG3OY.gif>

**Comment by hglee** [comment]
> 
> So works ok with latin char path?
> On Friday, January 22, 2021, Hyogeol Lee ***@***.***> wrote: Would you try to avoid chinese text in directory name? I got same error if I use korean text in directory name. @rdp I attached error log for that (include path error). config.log — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.<
> https://ci6.googleusercontent.com/proxy/NLvflWgPLbaQDIdYZHhwJVgvnLhxZaZXM-q9pGk7_rloMF4DDeYOlgPnwF4u837jVTTiKKLLH7orgG295Xm5bFVXtV34X_qyLCHXTb7ZTg1-fnh0debzgAQ7EuiHNSs-8HpgDERtRxoLAjKawc6O9npjdrjWvlnc5ErVgnwphCbVz02GCt8fFJYZkONs1bL_KlWadAPC-b6bdl4PMU4kTAWTUC5JYoj0Qzypjrd74Q=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUF7BRIDWO4K62F75GDS3EYJBA5CNFSM4WJ7CXVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFWOG3OY.gif>

That's OK.

**Comment by qythker** [comment]
yes.it's ok now ,thanks
