### ISSUE TITLE
Errors with --git-get-latest=y setting

### ISSUE THREAD

**Issue by cooperdk** [rdp/ffmpeg-windows-build-helpers#537]
Debian 10.7 (WSL)

./cross_compile_ffmpeg.sh --build-ffmpeg-static=y --git-get-latest=y --gcc-cpu-count=4 --compiler-flavors=win64

Building for a good while, but it fails here:

MAN     doc/libavformat.3
pod2man: unable to format doc/libswresample.pod
make: *** [doc/Makefile:96: doc/libswresample.3] Error 1
make: *** Waiting for unfinished jobs....
pod2man: unable to format doc/libavcodec.pod
make: *** [doc/Makefile:96: doc/libavcodec.3] Error 1
pod2man: unable to format doc/libavformat.pod
make: *** [doc/Makefile:96: doc/libavformat.3] Error 1

**Comment by Mister-XY** [comment]
i use also debian 10 and have no problem here. I clean my win64 folder and compile with your commandline.

**Comment by rdp** [comment]
Maybe there was some temporary error they already fixed...try it again?

**Comment by rdp** [comment]
or maybe have to blow away in certain cases and start fresh?  Let me know if issue is still present, thanks.

**Comment by cooperdk** [comment]
I ended up compiling successfully. Don't actually remember what I did to make it work.
