### ISSUE TITLE
Error - Unable to download from festvox

### ISSUE THREAD

**Issue by bala-smart** [rdp/ffmpeg-windows-build-helpers#540]
Compilation exited with above error

Not able to download from browser itself,(Not found)

![failure](https://user-images.githubusercontent.com/68465441/106985345-4c1ec000-678f-11eb-922e-54223a5b45ad.png)

**Comment by nanake** [comment]
it's intermittent failure i can say.

**Comment by bala-smart** [comment]
> it's intermittent failure i can say.

So what's the solution?

**Comment by nanake** [comment]
just re-run job. i can access to that site.

**Comment by rdp** [comment]
Seems OK now, alternative mirror welcome
