### ISSUE TITLE
libvpx git error

### ISSUE THREAD

**Issue by mtujikawa** [rdp/ffmpeg-windows-build-helpers#546]
Hello Friends.

I am building n4.3.2.
I get an error with git check out in libvpx.

> doing git checkout origin/stable
> error: pathspec 'origin/stable' did not match any file(s) known to git

It seems that the cause is that 'origin/stable' does not exist in libvpx.
How can I avoid it?

Thank you.

WSL2, Ubuntu 20.04.2 LTS on Windows10

**Comment by Biswa96** [comment]
Please share your solution with others.
