### ISSUE TITLE
Compile Error libaom and av1

### ISSUE THREAD

**Issue by smoothstreams** [rdp/ffmpeg-windows-build-helpers#547]
Build OS: Ubuntu 20 LTS

Going along and then...

MAN     doc/libavformat.3
MAN     doc/libavdevice.3
MAN     doc/libavfilter.3
AR      libswscale/libswscale.a
AR      libavutil/libavutil.a
STRIP   libavcodec/x86/vp9itxfm.o
AR      libavcodec/libavcodec.a
LD      ffplay_g.exe
LD      ffmpeg_g.exe
LD      ffprobe_g.exe
/home/ffmpeg/utils/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /home/ffmpeg/utils/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libaom.a(av1_cx_iface.c.obj):av1_cx_iface.c:(.text+0x4570): undefined reference to `warn'
/home/ffmpeg/utils/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libaom.a(av1_cx_iface.c.obj):av1_cx_iface.c:(.text+0x4570): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `warn'
/home/ffmpeg/utils/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /home/ffmpeg/utils/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libaom.a(av1_cx_iface.c.obj):av1_cx_iface.c:(.text+0x4570): undefined reference to `warn'
/home/ffmpeg/utils/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libaom.a(av1_cx_iface.c.obj):av1_cx_iface.c:(.text+0x4570): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `warn'
/home/ffmpeg/utils/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /home/ffmpeg/utils/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libaom.a(av1_cx_iface.c.obj):av1_cx_iface.c:(.text+0x4570): undefined reference to `warn'
/home/ffmpeg/utils/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libaom.a(av1_cx_iface.c.obj):av1_cx_iface.c:(.text+0x4570): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `warn'
collect2: error: ld returned 1 exit status
make: *** [Makefile:124: ffprobe_g.exe] Error 1
make: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make: *** [Makefile:124: ffplay_g.exe] Error 1
collect2: error: ld returned 1 exit status
make: *** [Makefile:124: ffmpeg_g.exe] Error 1

Thanks in advance.

**Comment by rdp** [comment]
Still there?

**Comment by rdp** [comment]
Closing no comment
