### ISSUE TITLE
rubberband fails to apply patch for static build

### ISSUE THREAD

**Issue by Smalls1652** [rdp/ffmpeg-windows-build-helpers#551]
Looks like rubberband has changed how it's building (Done in this commit breakfastquay/rubberband@093e7cc5d871d1c119db1c7cacaf8b70f82e1ca5), so the patch file will fail to apply because those build files don't exist anymore.

This is the error I get:
```
doing git checkout default
M	rubberband.pc.in
Already on 'default'
Your branch is up to date with 'origin/default'.
Already up to date.
fetched no code changes, not forcing reconfigure for that...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1081  100  1081    0     0  1055k      0 --:--:-- --:--:-- --:--:-- 1055k
applying patch rubberband_git_static-lib.diff
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff -ur Makefile.in.bak Makefile.in
|--- Makefile.in.bak	2017-04-27 15:44:27.859375000 +0200
|+++ Makefile.in	2017-05-23 23:10:31.531250000 +0200
--------------------------
```

I'm currently testing this right now, but I think the quickest solution is to change the build function from:

```bash
build_librubberband() {
  do_git_checkout https://github.com/breakfastquay/rubberband.git rubberband_git default
  cd rubberband_git
    apply_patch file://$patch_dir/rubberband_git_static-lib.diff # create install-static target
    do_configure "--host=$host_target --prefix=$mingw_w64_x86_64_prefix --disable-ladspa"
    do_make "install-static AR=${cross_prefix}ar" # No need for 'do_make_install', because 'install-static' already has install-instructions.
    sed -i.bak 's/-lrubberband.*$/-lrubberband -lfftw3 -lsamplerate -lstdc++/' $PKG_CONFIG_PATH/rubberband.pc
  cd ..
}
```

To:

```bash
build_librubberband() {
  do_git_checkout https://github.com/breakfastquay/rubberband.git rubberband_git eb612718de62519cfdfdd17ef6b7f1eb48f6d6d1
  cd rubberband_git
    apply_patch file://$patch_dir/rubberband_git_static-lib.diff # create install-static target
    do_configure "--host=$host_target --prefix=$mingw_w64_x86_64_prefix --disable-ladspa"
    do_make "install-static AR=${cross_prefix}ar" # No need for 'do_make_install', because 'install-static' already has install-instructions.
    sed -i.bak 's/-lrubberband.*$/-lrubberband -lfftw3 -lsamplerate -lstdc++/' $PKG_CONFIG_PATH/rubberband.pc
  cd ..
}
```

Doing this goes back to a commit (breakfastquay/rubberband@eb612718de62519cfdfdd17ef6b7f1eb48f6d6d1) before changes were made to how building was done.

I think the two short/long-term solutions to fix this would be to either:

- Target a release before the build system changed (Basically breakfastquay/rubberband@6659d61f010e19080d62aa2fd2eae88f16e5d9c9 for the v1.9 release).
- Change to the `meson` build system, since that seems to be where rubberband is going.

**Comment by naabtog** [comment]
I can confirm this quick fix works. Also I don't think it's time to change build system only because rubberband dev decided to do so.

**Comment by hydra3333** [comment]
well, rubberband has removed the configure file now.

**Comment by rdp** [comment]
eb612718 is the last good commit?

**Comment by hydra3333** [comment]
57d680a8e3a6523a4151315f99dfa7fa60260c7e

**Comment by Smalls1652** [comment]
@rdp Actually looking further into the repo's commit history, it looks like the old build files actually got moved to the [/otherbuilds](https://github.com/breakfastquay/rubberband/tree/default/otherbuilds) directory. This is the specific commit where they were moved: breakfastquay/rubberband@093e7cc5d871d1c119db1c7cacaf8b70f82e1ca5.

Might be able to just work around with just that?

**Comment by hydra3333** [comment]
ooh, thank you.

**Comment by Smalls1652** [comment]
Yeah it seems that they removed it in the `meson` branch and that change got merged into `default`. breakfastquay/rubberband@6ae0bd26a5f8fa75deeedd2b4b4559de5a6e2b09

Wonder if that was intentional. 🤔

**Comment by rdp** [comment]
try it now, reverted to older version

**Comment by rdp** [comment]
Let me know if not working.
