### ISSUE TITLE
windres error with binutils 2.36.1

### ISSUE THREAD

**Issue by hglee** [rdp/ffmpeg-windows-build-helpers#554]
Build error on windres with binutils 2.36.1

> CC	libavdevice/sdl2.o
> CC	libavdevice/utils.o
> CC	libavdevice/vfwcap.o
> WINDRES	libavdevice/avdeviceres.o
> sh: 1: /home/hglee/Workspace/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-gcc -E -xc-header -DRC_INVOKED -MMD -MF libavdevice/avdeviceres.d -MT libavdevice/avdeviceres.o: not found
> /home/hglee/Workspace/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-windres: preprocessing failed.

Same issue:  https://github.com/m-ab-s/media-autobuild_suite/issues/1909

binutils 2.36.1 build error
binutils 2.35.1 build OK

**Comment by rdp** [comment]
What os?

On Monday, March 29, 2021, Hyogeol Lee ***@***.***> wrote:
> Build error on windres with binutils 2.36.1
>
> CC libavdevice/sdl2.o
> CC libavdevice/utils.o
> CC libavdevice/vfwcap.o
> WINDRES libavdevice/avdeviceres.o
> sh: 1:
/home/hglee/Workspace/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-gcc
-E -xc-header -DRC_INVOKED -MMD -MF libavdevice/avdeviceres.d -MT
libavdevice/avdeviceres.o: not found
>
/home/hglee/Workspace/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-windres:
preprocessing failed.
>
> Same issue: m-ab-s/media-autobuild_suite#1909
>
> binutils 2.36.1 build error
> binutils 2.35.1 build OK
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/I4FCwUsJf2w5K4g46jx327qaMMD2qwUFzc4_9lTM8jfjMfvZBsq9XBEvBMOPzLFeyRAQW8RmIWGo2OC0kg3H0_B8l09HO4RwVDsAhLrK6QwEVf2v6TR7agYtUyfvebfZjWrMT0P847DnNkSulaYEMGdIpXBQ597IogMSJFJA7jJqSNh5L4WJbZureri9VpJObOKVuE3t9lF4J0EvZmymoWInnrE=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUBLWVHKI3NXXUIXEMTTGBC47A5CNFSM4Z7HE54KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4MSB6TZQ.gif>

**Comment by hglee** [comment]
OS
 - Ubuntu 20.04.2.0 LTS

ffmpeg-windows-build-helpers    
 - bfd2c8c2d415d34538be980be8a3a613b7c66133
 - ./cross_compile_ffmpeg.sh --build-ffmpeg-static=n --build-ffmpeg-shared=y 
 - Both (x86, x64) build option

**Comment by Warblefly** [comment]
On Mon, Mar 29, 2021 at 10:37 AM Hyogeol Lee ***@***.***>
wrote:
Build error on windres with binutils 2.36.1

CC libavdevice/sdl2.o
CC libavdevice/utils.o
CC libavdevice/vfwcap.o
WINDRES libavdevice/avdeviceres.o
sh: 1:
/home/hglee/Workspace/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-gcc
-E -xc-header -DRC_INVOKED -MMD -MF libavdevice/avdeviceres.d -MT
libavdevice/avdeviceres.o: not found
/home/hglee/Workspace/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-windres:
preprocessing failed.

Same issue: m-ab-s/media-autobuild_suite#1909

binutils 2.36.1 build error
binutils 2.35.1 build OK



When linking, there seems to be a change in the way the preprocessor is
passed arguments in binutils 2.36.1 compared to the 2.35 (and earlier)
branches.

Got this when compiling 2.36.1 from source.

Tried a quick fix to the FFmpeg makefiles but am not doing it correctly.

**Comment by emailtoan** [comment]
Have this been resolved?  I'm stuck here too and spent days trying do a shared build.  I've switched Ubuntu versions, tried Linux Mint, nothing is working.  :(

**Comment by hglee** [comment]
> Have this been resolved? I'm stuck here too and spent days trying do a shared build. I've switched Ubuntu versions, tried Linux Mint, nothing is working. :(

If you want to build for now, set this to 2.35.1

https://github.com/rdp/ffmpeg-windows-build-helpers/blob/bfd2c8c2d415d34538be980be8a3a613b7c66133/patches/mingw-w64-build-r22.local#L83

**Comment by emailtoan** [comment]
Thank you hglee and jojje.  Your suggestions worked :). 👍

**Comment by rdp** [comment]
Not sure why it exists with only newer binutils.  I also get 

```
                                                                                    WINDRES libavdevice/avdeviceres.o                                                                                            GEN     libavdevice/libavdevice.ver                                                                                          sh: 1: /root/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc -E -xc-header -DRC_INVOKED -MMD -MF libavdevice/avdeviceres.d -MT libavdevice/avdeviceres.o: not found                                      
CC      libavfilter/aeval.o                                                                                                  /root/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-windres: preprocessing failed.                                                                                                                         make: *** [ffbuild/common.mak:93: libavdevice/avdeviceres.o] Error 1         
```
applying patch by jojje for now.
