### ISSUE TITLE
Doesn't build with libavresample

### ISSUE THREAD

**Issue by naabtog** [rdp/ffmpeg-windows-build-helpers#565]
Build `failed to configure` because of `Unknown option --enable-libavresample`. I commented out line 2388, and it worked.
After that I found out ffmpeg [doesn't support](https://github.com/FFmpeg/FFmpeg/commit/420cedd49745b284c35d97b936b71ff79b43bdf7) it any longer.
`libavresample: Remove deprecated library` `420cedd`
I suppose everything related to it should be removed.

**Comment by rdp** [comment]
OK thanks for the report

**Comment by nschlia** [comment]
> Build `failed to configure` because of `Unknown option --enable-libavresample`. I commented out line 2388, and it worked.
> After that I found out ffmpeg [doesn't support](https://github.com/FFmpeg/FFmpeg/commit/420cedd49745b284c35d97b936b71ff79b43bdf7) it any longer.
> `libavresample: Remove deprecated library` `420cedd`
> I suppose everything related to it should be removed.

Support has definetely been  removed from FFmpeg. This has been discussed for 9 years now, see this post of Michael Niedermayer, the project leader until 2015:

https://vlc-devel.videolan.narkive.com/XTPI3IKq/libswresample-vs-libavresample

Any references should be removed. Use swresample instead.

**Comment by rdp** [comment]
Theroetically fixed with f38feb0387b3ae2a6a0c2e7b4fe00de542b7bc40
thanks for the report.
