### ISSUE TITLE
gnutls can't find autoopts/options.h with autogen installed

### ISSUE THREAD

**Issue by wraithdu** [rdp/ffmpeg-windows-build-helpers#57]
At first I thought it might be my Ubuntu install, so I spun up a brand new VM (Ubuntu 14.04 LTS, 64-bit), updated it and installed the script's dependencies. I get these errors from gnutls if autogen is installed. If I remove the autogen package, compilation completes.
```
In file included from srptool-args.c:43:0:
srptool-args.h:49:30: fatal error: autoopts/options.h: No such file or directory
 #include <autoopts/options.h>
                              ^
compilation terminated.
make[4]: *** [libcmd_srp_la-srptool-args.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
In file included from ocsptool-args.c:43:0:
ocsptool-args.h:49:30: fatal error: autoopts/options.h: No such file or directory
 #include <autoopts/options.h>
                              ^
compilation terminated.
In file included from psk-args.c:43:0:
psk-args.h:49:30: fatal error: autoopts/options.h: No such file or directory
 #include <autoopts/options.h>
                              ^
compilation terminated.
make[4]: *** [libcmd_ocsp_la-ocsptool-args.lo] Error 1
make[4]: *** [libcmd_psk_la-psk-args.lo] Error 1
In file included from serv-args.c:43:0:
serv-args.h:49:30: fatal error: autoopts/options.h: No such file or directory
 #include <autoopts/options.h>
                              ^
```

**Comment by rdp** [comment]
Interesting.

On OS X I get something different

  CCLD     srptool.exe

  CCLD     ocsptool.exe

  CCLD     gnutls-cli-debug.exe

copying selected object files to avoid basename conflicts...

copying selected object files to avoid basename conflicts...

/usr/local/Cellar/autogen/5.18.4/lib/libopts.a: error adding symbols: File
format not recognized

collect2: error: ld returned 1 exit status

make[4]: *** [psktool.exe] Error 1

make[4]: *** Waiting for unfinished jobs....

/usr/local/Cellar/autogen/5.18.4/lib/libopts.a: error adding symbols: File
format not recognized

collect2: error: ld returned 1 exit status

make[4]: *** [srptool.exe] Error 1

/usr/local/Cellar/autogen/5.18.4/lib/libopts.a: error adding symbols: File
format not recognized

collect2: error: ld returned 1 exit status

make[4]: *** [ocsptool.exe] Error 1

/usr/local/Cellar/autogen/5.18.4/lib/libopts.a: error adding symbols: File
format not recognized

collect2: error: ld returned 1 exit status

make[4]: *** [gnutls-cli-debug.exe] Error 1

make[3]: *** [all-recursive] Error 1

make[2]: *** [all] Error 2

make[1]: *** [all-recursive] Error 1

make: *** [all] Error 2



shoot it seems that if you have an autogen installed for the host then it
hoses the cross compile.   hmm...

same with newer versions of gnutls.

I'm at a loss here...hmm...maybe I should just add a warning and say
"uninstall that package!"?

**Comment by abarbieri** [comment]
same for me on Ubuntu 14.04.1 LTS with gnutls-3.3.9. removing the autogen package successfully builds the win32 gnutls dependency.

**Comment by AndCycle** [comment]
according to this,

[gnutls/f19] do not link with autogen, nor expect tpmtool.
https://lists.fedoraproject.org/pipermail/scm-commits/Week-of-Mon-20131125/1149971.html


add
```
--enable-local-libopts
```
to configure will make gnutls happy, I have tested this today and it work as expected.

**Comment by rdp** [comment]
That worked, thanks!

**Comment by rdp** [comment]
hopefully fixed, report back if not
