### ISSUE TITLE
Error building libsndfile

### ISSUE THREAD

**Issue by naabtog** [rdp/ffmpeg-windows-build-helpers#574]
I had errors building libsndfile. It turned out its repo owner has changed, so did git link and something else.
Reverting to previous commit works, but maybe someone will do better than that.
So, in my case [line 1323](https://github.com/rdp/ffmpeg-windows-build-helpers/blob/1c63fa54889b2357dd1ce86cfcb0aa5025adc9f3/cross_compile_ffmpeg.sh#L1323) looks like:
`  do_git_checkout https://github.com/libsndfile/libsndfile.git libsndfile_git 62b7fb3b35ef8a0519af6af90d38981366d4665c`

**Comment by rdp** [comment]
Thanks for the tip I attempted to implement it...

**Comment by naabtog** [comment]
They have changed version number to an unsupported value so it broke configuring. In order to have future updates one must change it manually.

**Comment by naabtog** [comment]
@rdp they have [fixed](https://github.com/libsndfile/libsndfile/issues/758#event-4907879626) it, so commit is longer needed.
```
do_git_checkout https://github.com/libsndfile/libsndfile.git
```
