### ISSUE TITLE
libsoxr has died?

### ISSUE THREAD

**Issue by kusaanko** [rdp/ffmpeg-windows-build-helpers#582]
I got an error
```
fatal: unable to access 'https://git.code.sf.net/p/soxr/code/': Empty reply from server
```
I tried accessing to "https://git.code.sf.net/p/soxr/code/" and Chrome replied "git.code.sf.net was not found".

I think this error is occured by https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/cross_compile_ffmpeg.sh#L1489
I searched "libsoxr" on Google and I found https://github.com/chirlu/soxr
Is it libsoxr? And can I fix this error?

**Comment by Biswa96** [comment]
Link ok here https://sourceforge.net/p/soxr/code/ci/master/tree/

**Comment by kusaanko** [comment]
I run "git clone https://git.code.sf.net/p/soxr/code/" and it was ok.
I will retry to build.

**Comment by kusaanko** [comment]
The build was ok, but sometimes failture.
It may be server side problem.
