### ISSUE TITLE
Apply patch files

### ISSUE THREAD

**Issue by dude2k5** [rdp/ffmpeg-windows-build-helpers#583]
Im trying to compile this patch with this script. There is a section in cross_compile_ffmpeg.sh that says "PUT PATCHES FOR OTHER VERSIONS HERE". Would this be the correct location? I've placed the patch in the same folder as the others. 

![image](https://user-images.githubusercontent.com/24706365/129060871-888058a1-29e1-4979-85b9-2d3e618de0d0.png)

Im trying to get this working, but it seems when I try to recompile it, it doesn't seem to do anything. Do I need to add anything to specifically say, apply this patch?

https://trac.ffmpeg.org/ticket/8211

**Comment by rdp** [comment]
I'd just put it outside that if statement if it's for one off use :)

On Wednesday, August 11, 2021, dude2k5 ***@***.***> wrote:
> Im trying to compile this patch with this script. There is a section in
cross_compile_ffmpeg.sh that says "PUT PATCHES FOR OTHER VERSIONS HERE".
Would this be the correct location? I've placed the patch in the same
folder as the others.
>
> <
https://ci4.googleusercontent.com/proxy/nbes1H1IjIL_o6AsN733ROeeHY_bIY45r_bqSE-X9Gd_6MFJailp068dB14JEUWXEeF2hjtSh7aL8_6eTPrQwe7zDzyEyiXAK0CWTDOU1WimtBYCVNre4q_k59fCN22-7jft1kRMpRhaYlzY4vGQv_HL7vyEjwS9=s0-d-e1-ft#https://user-images.githubusercontent.com/24706365/129060871-888058a1-29e1-4979-85b9-2d3e618de0d0.png
>
>
> Im trying to get this working, but it seems when I try to recompile it,
it doesn't seem to do anything. Do I need to add anything to specifically
say, apply this patch?
>
> https://trac.ffmpeg.org/ticket/8211
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.<
https://ci6.googleusercontent.com/proxy/5QY0cktV7eUgMOm6XsXKGjKS0DV0pggDmmjOn_c6MFtIlLMgT1hJIxvbRoRCFvOHBuKdtZ-CaFaWc7VVA2od36ncA7-kf4NqlmFxXhD5_3SIcowepsGNKEPhyOp0NUa_rMxQ-or1NpeQihu_QHdhJ1R0s8Ltts6uhjaGxZoA0UYPXkpTINuqVT4PuLtXTYIscPHrAfB9K2g5okPcJO-V3RBP8i4=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUHYTBH24ZZ7GDIPGL3T4KLPPA5CNFSM5B62YS2KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4ONCXG6A.gif>

**Comment by AnimMouse** [comment]
@dude2k5 That "PUT PATCHES FOR OTHER VERSIONS HERE" is for the SVT-HEVC patch, don't use it for applying patch files.

For applying FFmpeg patch files, I recommend you to just use an external FFmpeg source dir `--ffmpeg-source-dir=` and manually apply patches there.

Example:
```
git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg-source
cd ffmpeg-source
git apply webcam.patch
cd ..
./cross_compile_ffmpeg.sh --ffmpeg-source-dir=ffmpeg-source
```

**Comment by rdp** [comment]
Yeah.  It just seemed so convenient... :)

On Tuesday, October 19, 2021, Anim Mouse ***@***.***> wrote:
> @dude2k5 That "PUT PATCHES FOR OTHER VERSIONS HERE" is for the SVT-HEVC
patch, don't use it for applying patch files.
>
> For applying FFmpeg patch files, I recommend you to just use an external
FFmpeg source dir --ffmpeg-source-dir= and manually apply patches there.
>
> Example:
>
> git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg-source
> cd ffmpeg-source
> git apply webcam.patch
> cd ..
> ./cross_compile_ffmpeg.sh --ffmpeg-source-dir=ffmpeg-source
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. <
https://ci4.googleusercontent.com/proxy/eOVgxk1sxJIRF30HDjxEe6kfwU0htPAi4d-d3jbyJsarp8hk5Bv66HPp7YFPI5VckdDF-ncc-K_VNoDnMtoJY7Qd3_HiCeGLG1Vcb2ASsVbg_93Pj4i0buoqmFA-rjtKllTgwZjuqIfQ2dqrQLs0NwWY8mbyZF82rXoJ23dnuv-GHcw6wqeI-J1oMhsQgBS8R8IBmM4LRLFRmaY28OKx0UZBj70PNbZT5QQtUDcAlw=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUHKTAFU7AGCJHD434DUHZFJ5A5CNFSM5B62YS2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOHB3SRCQ.gif>

**Comment by rdp** [comment]
hope you got this figured out, if not reopen, thanks
