### ISSUE TITLE
cant compile since beginning of August

### ISSUE THREAD

**Issue by Krautmaster** [rdp/ffmpeg-windows-build-helpers#585]
i always get a ffmpeg collect2 error ld returned 1. Any ideas on that screenshot? Anything i shall provide?

![image](https://user-images.githubusercontent.com/1076514/131265257-016250be-9405-42c5-8d29-e3394ca0b493.png)

Commandline:
./cross_compile_ffmpeg.sh --git-get-latest=y --disable-nonfree=n --compiler-flavors=win64 --sandbox-ok=y --gcc-cpu-count=4 --prefer-stable=n

but it seem to always stuck there even if i do a fresh checkout
Linux buildserver 5.11.0-31-generic #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

https://githubmemory.com/repo/rdp/ffmpeg-windows-build-helpers/issues/547

@rdp 
seems to be still there

**Comment by Krautmaster** [comment]
is it that one 
https://aomedia.googlesource.com/aom/+/79f3606b62b9c881a64a81e74b9b4e72115eda18%5E%21/#F0 ?

**Comment by Krautmaster** [comment]
idea?

**Comment by rdp** [comment]
Worked OK for me with 21.04, maybe fixed upstream?  Still present?

**Comment by Krautmaster** [comment]
ill check thx a lot, hope u hade a nice holiday ;)

**Comment by rdp** [comment]
Closing no feedback, feel free to reopen :)
