### ISSUE TITLE
liblzma url path

### ISSUE THREAD

**Issue by yanhua1012** [rdp/ffmpeg-windows-build-helpers#587]
when build liblzma
the download url is https://nchc.dl.sourceforge.net/project/lzmautils/xz-5.2.5.tar.xz,
it has been invalid.
I use browser to download , then was redirect to https://nchc.dl.sourceforge.net/project/lzmautils/xz-5.2.5.tar.xz.

**Comment by rdp** [comment]
I think it's working now?
