### ISSUE TITLE
Error building ffmpeg n4.4

### ISSUE THREAD

**Issue by MomidiMomidi** [rdp/ffmpeg-windows-build-helpers#591]
I'm using Google Translate

I want to use a stable version and specified n4.4, but I get an error.
I was able to build by deleting the version specification.
Is there a way to solve it?
Is there no choice but to delete the version specification?

Command line
./cross_compile_ffmpeg.sh --build-ffmpeg-static=y --ffmpeg-git-checkout-version=n4.4 --disable-nonfree=y --build-intel-qsv=y --build-libmxf=n --build-mp4box=n --build-mplayer=n --build-vlc=n --build-lsw=n --build-ismindex=n --build-dvbtee=n --enable-gpl=y --build-dependencies=y

```
    [INSTALL] /home/momidi/Downloads/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig/vpx.pc
doing git checkout origin/stable
HEAD is now at ce882936d Update x265Version.txt
fetched no code changes, not forcing reconfigure for that...
Already made 12bit ...
Already made 10bit ...
Already made 8bit ...
doing git checkout origin/master
M	codec/encoder/core/inc/param_svc.h
HEAD is now at 9d615325 Merge pull request #3407 from mstorsjo/fix-test-refs
fetched no code changes, not forcing reconfigure for that...
Already made openh264_git ...
remote: Finding sources: 100% (11/11)
remote: Total 11 (delta 6), reused 10 (delta 6)
Unpacking objects: 100% (11/11), 7.17 KiB | 193.00 KiB/s, done.
From https://aomedia.googlesource.com/aom
   72cc691fe..ece54a153  master     -> origin/master
doing git checkout origin/master
Previous HEAD position was 72cc691fe AV1 RT: Introducing CDEF search level 5
HEAD is now at ece54a153 Allintra: Remove unused params
got upstream changes, forcing re-configure. Doing git clean -f
HEAD is now at ece54a153 Allintra: Remove unused params
Already made aom_build ...
doing git checkout origin/master
M	meson_options.txt
HEAD is now at d174e6f Avoid leaking a dependency on stdatomic.h outside of the main library
fetched no code changes, not forcing reconfigure for that...
Already used meson libdav1d
already did ninja libdav1d
doing git checkout origin/master
HEAD is now at 47b6141a Fix: Unprocessed Overlay blend+opacity 10+bits rightmost mod8 pixels
fetched no code changes, not forcing reconfigure for that...
doing git checkout origin/stable
M	configure
HEAD is now at 5db6aa6c lavf: Fix compilation with new versions of ffmpeg
fetched no code changes, not forcing reconfigure for that...
Already made x264_all_bitdepth ...
remote: Enumerating objects: 77, done.
remote: Counting objects: 100% (77/77), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 77 (delta 61), reused 75 (delta 59), pack-reused 0
Unpacking objects: 100% (77/77), 66.69 KiB | 298.00 KiB/s, done.
From https://github.com/FFmpeg/FFmpeg
   6e26015a6b..a46e78d5b7  master     -> origin/master
doing git checkout n4.4
M	configure
M	doc/general_contents.texi
M	libavcodec/Makefile
M	libavcodec/allcodecs.c
M	libavfilter/vf_frei0r.c
HEAD is now at dc91b913b6 RELEASE_NOTES: Based on the version from 4.3
fetched no code changes, not forcing reconfigure for that...
error: patch failed: configure:288
error: configure: patch does not apply
error: patch failed: libavcodec/Makefile:1061
error: libavcodec/Makefile: patch does not apply
error: patch failed: libavcodec/allcodecs.c:757
error: libavcodec/allcodecs.c: patch does not apply
error: libavcodec/libsvt_hevc.c: already exists in working directory
error: patch failed: doc/general_contents.texi:259
error: doc/general_contents.texi: patch does not apply
doing ffmpeg make /home/momidi/Downloads/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git_n4.4

Making /home/momidi/Downloads/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git_n4.4 as $ PATH=/home/momidi/Downloads/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH make  -j 4

AR	libavdevice/libavdevice.a
AR	libavformat/libavformat.a
CC	libavcodec/libdav1d.o
CC	libavcodec/libgsmdec.o
CC	libavcodec/libgsmenc.o
libavcodec/libdav1d.c: In function 'libdav1d_init':
CC	libavcodec/libilbc.o
libavcodec/libdav1d.c:148:7: error: 'Dav1dSettings' has no member named 'n_tile_threads'; did you mean 'n_threads'?
  148 |     s.n_tile_threads = dav1d->tile_threads
      |       ^~~~~~~~~~~~~~
      |       n_threads
CC	libavcodec/libmp3lame.o
In file included from ./libavutil/avutil.h:296,
                 from ./libavutil/avassert.h:31,
                 from libavcodec/libdav1d.c:24:
libavcodec/libdav1d.c:150:52: error: 'DAV1D_MAX_TILE_THREADS' undeclared (first use in this function); did you mean 'DAV1D_MAX_THREADS'?
  150 |                      : FFMIN(floor(sqrt(threads)), DAV1D_MAX_TILE_THREADS);
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~
./libavutil/common.h:105:28: note: in definition of macro 'FFMIN'
  105 | #define FFMIN(a,b) ((a) > (b) ? (b) : (a))
      |                            ^
libavcodec/libdav1d.c:150:52: note: each undeclared identifier is reported only once for each function it appears in
  150 |                      : FFMIN(floor(sqrt(threads)), DAV1D_MAX_TILE_THREADS);
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~
./libavutil/common.h:105:28: note: in definition of macro 'FFMIN'
  105 | #define FFMIN(a,b) ((a) > (b) ? (b) : (a))
      |                            ^
libavcodec/libdav1d.c:151:6: error: 'Dav1dSettings' has no member named 'n_frame_threads'
  151 |     s.n_frame_threads = dav1d->frame_threads
      |      ^
In file included from ./libavutil/avutil.h:296,
                 from ./libavutil/avassert.h:31,
                 from libavcodec/libdav1d.c:24:
libavcodec/libdav1d.c:153:48: error: 'Dav1dSettings' has no member named 'n_tile_threads'; did you mean 'n_threads'?
  153 |                       : FFMIN(ceil(threads / s.n_tile_threads), DAV1D_MAX_FRAME_THREADS);
      |                                                ^~~~~~~~~~~~~~
./libavutil/common.h:105:22: note: in definition of macro 'FFMIN'
  105 | #define FFMIN(a,b) ((a) > (b) ? (b) : (a))
      |                      ^
libavcodec/libdav1d.c:153:65: error: 'DAV1D_MAX_FRAME_THREADS' undeclared (first use in this function); did you mean 'DAV1D_MAX_THREADS'?
  153 |                       : FFMIN(ceil(threads / s.n_tile_threads), DAV1D_MAX_FRAME_THREADS);
      |                                                                 ^~~~~~~~~~~~~~~~~~~~~~~
./libavutil/common.h:105:28: note: in definition of macro 'FFMIN'
  105 | #define FFMIN(a,b) ((a) > (b) ? (b) : (a))
      |                            ^
libavcodec/libdav1d.c:153:48: error: 'Dav1dSettings' has no member named 'n_tile_threads'; did you mean 'n_threads'?
  153 |                       : FFMIN(ceil(threads / s.n_tile_threads), DAV1D_MAX_FRAME_THREADS);
      |                                                ^~~~~~~~~~~~~~
./libavutil/common.h:105:40: note: in definition of macro 'FFMIN'
  105 | #define FFMIN(a,b) ((a) > (b) ? (b) : (a))
      |                                        ^
libavcodec/libdav1d.c:155:13: error: 'Dav1dSettings' has no member named 'n_frame_threads'
  155 |            s.n_frame_threads, s.n_tile_threads);
      |             ^
libavcodec/libdav1d.c:155:33: error: 'Dav1dSettings' has no member named 'n_tile_threads'; did you mean 'n_threads'?
  155 |            s.n_frame_threads, s.n_tile_threads);
      |                                 ^~~~~~~~~~~~~~
      |                                 n_threads
libavcodec/libdav1d.c: At top level:
libavcodec/libdav1d.c:462:94: error: 'DAV1D_MAX_TILE_THREADS' undeclared here (not in a function); did you mean 'DAV1D_MAX_THREADS'?
  462 |     { "tilethreads", "Tile threads", OFFSET(tile_threads), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, DAV1D_MAX_TILE_THREADS, VD },
      |                                                                                              ^~~~~~~~~~~~~~~~~~~~~~
      |                                                                                              DAV1D_MAX_THREADS
libavcodec/libdav1d.c:463:97: error: 'DAV1D_MAX_FRAME_THREADS' undeclared here (not in a function); did you mean 'DAV1D_MAX_THREADS'?
  463 |     { "framethreads", "Frame threads", OFFSET(frame_threads), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, DAV1D_MAX_FRAME_THREADS, VD },
      |                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                 DAV1D_MAX_THREADS
make: *** [ffbuild/common.mak:67: libavcodec/libdav1d.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by rdp** [comment]
Shoot looks like it needs a different version of libdav1d...try latest,
pull!

On Thursday, September 23, 2021, MomidiMomidi ***@***.***>
wrote:
> I'm using Google Translate
>
> I want to use a stable version and specified n4.4, but I get an error.
> I was able to build by deleting the version specification.
> Is there a way to solve it?
> Is there no choice but to delete the version specification?
>
> Command line
> ./cross_compile_ffmpeg.sh --build-ffmpeg-static=y
--ffmpeg-git-checkout-version=n4.4 --disable-nonfree=y --build-intel-qsv=y
--build-libmxf=n --build-mp4box=n --build-mplayer=n --build-vlc=n
--build-lsw=n --build-ismindex=n --build-dvbtee=n --enable-gpl=y
--build-dependencies=y
>
> ` [INSTALL]
/home/momidi/Downloads/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig/vpx.pc
> doing git checkout origin/stable
> HEAD is now at ce882936d Update x265Version.txt
> fetched no code changes, not forcing reconfigure for that...
> Already made 12bit ...
> Already made 10bit ...
> Already made 8bit ...
> doing git checkout origin/master
> M codec/encoder/core/inc/param_svc.h
> HEAD is now at 9d615325 Merge pull request #3407 from
mstorsjo/fix-test-refs
> fetched no code changes, not forcing reconfigure for that...
> Already made openh264_git ...
> remote: Finding sources: 100% (11/11)
> remote: Total 11 (delta 6), reused 10 (delta 6)
> Unpacking objects: 100% (11/11), 7.17 KiB | 193.00 KiB/s, done.
> From https://aomedia.googlesource.com/aom
> 72cc691fe..ece54a153 master -> origin/master
> doing git checkout origin/master
> Previous HEAD position was 72cc691fe AV1 RT: Introducing CDEF search
level 5
> HEAD is now at ece54a153 Allintra: Remove unused params
> got upstream changes, forcing re-configure. Doing git clean -f
> HEAD is now at ece54a153 Allintra: Remove unused params
> Already made aom_build ...
> doing git checkout origin/master
> M meson_options.txt
> HEAD is now at d174e6f Avoid leaking a dependency on stdatomic.h outside
of the main library
> fetched no code changes, not forcing reconfigure for that...
> Already used meson libdav1d
> already did ninja libdav1d
> doing git checkout origin/master
> HEAD is now at 47b6141a Fix: Unprocessed Overlay blend+opacity 10+bits
rightmost mod8 pixels
> fetched no code changes, not forcing reconfigure for that...
> doing git checkout origin/stable
> M configure
> HEAD is now at 5db6aa6c lavf: Fix compilation with new versions of ffmpeg
> fetched no code changes, not forcing reconfigure for that...
> Already made x264_all_bitdepth ...
> remote: Enumerating objects: 77, done.
> remote: Counting objects: 100% (77/77), done.
> remote: Compressing objects: 100% (18/18), done.
> remote: Total 77 (delta 61), reused 75 (delta 59), pack-reused 0
> Unpacking objects: 100% (77/77), 66.69 KiB | 298.00 KiB/s, done.
> From https://github.com/FFmpeg/FFmpeg
> 6e26015a6b..a46e78d5b7 master -> origin/master
> doing git checkout n4.4
> M configure
> M doc/general_contents.texi
> M libavcodec/Makefile
> M libavcodec/allcodecs.c
> M libavfilter/vf_frei0r.c
> HEAD is now at dc91b913b6 RELEASE_NOTES: Based on the version from 4.3
> fetched no code changes, not forcing reconfigure for that...
> error: patch failed: configure:288
> error: configure: patch does not apply
> error: patch failed: libavcodec/Makefile:1061
> error: libavcodec/Makefile: patch does not apply
> error: patch failed: libavcodec/allcodecs.c:757
> error: libavcodec/allcodecs.c: patch does not apply
> error: libavcodec/libsvt_hevc.c: already exists in working directory
> error: patch failed: doc/general_contents.texi:259
> error: doc/general_contents.texi: patch does not apply
> doing ffmpeg make
/home/momidi/Downloads/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git_n4.4
>
> Making
/home/momidi/Downloads/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git_n4.4
as $
PATH=/home/momidi/Downloads/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH
make -j 4
>
> AR libavdevice/libavdevice.a
> AR libavformat/libavformat.a
> CC libavcodec/libdav1d.o
> CC libavcodec/libgsmdec.o
> CC libavcodec/libgsmenc.o
> libavcodec/libdav1d.c: In function 'libdav1d_init':
> CC libavcodec/libilbc.o
> libavcodec/libdav1d.c:148:7: error: 'Dav1dSettings' has no member named
'n_tile_threads'; did you mean 'n_threads'?
> 148 | s.n_tile_threads = dav1d->tile_threads
> | ^~~~~~~~~~~~~~
> | n_threads
> CC libavcodec/libmp3lame.o
> In file included from ./libavutil/avutil.h:296,
> from ./libavutil/avassert.h:31,
> from libavcodec/libdav1d.c:24:
> libavcodec/libdav1d.c:150:52: error: 'DAV1D_MAX_TILE_THREADS' undeclared
(first use in this function); did you mean 'DAV1D_MAX_THREADS'?
> 150 | : FFMIN(floor(sqrt(threads)), DAV1D_MAX_TILE_THREADS);
> | ^~~~~~~~~~~~~~~~~~~~~~
> ./libavutil/common.h:105:28: note: in definition of macro 'FFMIN'
> 105 | #define FFMIN(a,b) ((a) > (b) ? (b) : (a))
> | ^
> libavcodec/libdav1d.c:150:52: note: each undeclared identifier is
reported only once for each function it appears in
> 150 | : FFMIN(floor(sqrt(threads)), DAV1D_MAX_TILE_THREADS);
> | ^~~~~~~~~~~~~~~~~~~~~~
> ./libavutil/common.h:105:28: note: in definition of macro 'FFMIN'
> 105 | #define FFMIN(a,b) ((a) > (b) ? (b) : (a))
> | ^
> libavcodec/libdav1d.c:151:6: error: 'Dav1dSettings' has no member named
'n_frame_threads'
> 151 | s.n_frame_threads = dav1d->frame_threads
> | ^
> In file included from ./libavutil/avutil.h:296,
> from ./libavutil/avassert.h:31,
> from libavcodec/libdav1d.c:24:
> libavcodec/libdav1d.c:153:48: error: 'Dav1dSettings' has no member named
'n_tile_threads'; did you mean 'n_threads'?
> 153 | : FFMIN(ceil(threads / s.n_tile_threads), DAV1D_MAX_FRAME_THREADS);
> | ^~~~~~~~~~~~~~
> ./libavutil/common.h:105:22: note: in definition of macro 'FFMIN'
> 105 | #define FFMIN(a,b) ((a) > (b) ? (b) : (a))
> | ^
> libavcodec/libdav1d.c:153:65: error: 'DAV1D_MAX_FRAME_THREADS' undeclared
(first use in this function); did you mean 'DAV1D_MAX_THREADS'?
> 153 | : FFMIN(ceil(threads / s.n_tile_threads), DAV1D_MAX_FRAME_THREADS);
> | ^~~~~~~~~~~~~~~~~~~~~~~
> ./libavutil/common.h:105:28: note: in definition of macro 'FFMIN'
> 105 | #define FFMIN(a,b) ((a) > (b) ? (b) : (a))
> | ^
> libavcodec/libdav1d.c:153:48: error: 'Dav1dSettings' has no member named
'n_tile_threads'; did you mean 'n_threads'?
> 153 | : FFMIN(ceil(threads / s.n_tile_threads), DAV1D_MAX_FRAME_THREADS);
> | ^~~~~~~~~~~~~~
> ./libavutil/common.h:105:40: note: in definition of macro 'FFMIN'
> 105 | #define FFMIN(a,b) ((a) > (b) ? (b) : (a))
> | ^
> libavcodec/libdav1d.c:155:13: error: 'Dav1dSettings' has no member named
'n_frame_threads'
> 155 | s.n_frame_threads, s.n_tile_threads);
> | ^
> libavcodec/libdav1d.c:155:33: error: 'Dav1dSettings' has no member named
'n_tile_threads'; did you mean 'n_threads'?
> 155 | s.n_frame_threads, s.n_tile_threads);
> | ^~~~~~~~~~~~~~
> | n_threads
> libavcodec/libdav1d.c: At top level:
> libavcodec/libdav1d.c:462:94: error: 'DAV1D_MAX_TILE_THREADS' undeclared
here (not in a function); did you mean 'DAV1D_MAX_THREADS'?
> 462 | { "tilethreads", "Tile threads", OFFSET(tile_threads),
AV_OPT_TYPE_INT, { .i64 = 0 }, 0, DAV1D_MAX_TILE_THREADS, VD },
> | ^~~~~~~~~~~~~~~~~~~~~~
> | DAV1D_MAX_THREADS
> libavcodec/libdav1d.c:463:97: error: 'DAV1D_MAX_FRAME_THREADS' undeclared
here (not in a function); did you mean 'DAV1D_MAX_THREADS'?
> 463 | { "framethreads", "Frame threads", OFFSET(frame_threads),
AV_OPT_TYPE_INT, { .i64 = 0 }, 0, DAV1D_MAX_FRAME_THREADS, VD },
> | ^~~~~~~~~~~~~~~~~~~~~~~
> | DAV1D_MAX_THREADS
> make: *** [ffbuild/common.mak:67: libavcodec/libdav1d.o] Error 1
> make: *** Waiting for unfinished jobs....
> `
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. <
https://ci5.googleusercontent.com/proxy/VPtXtAPPMZahClo3hDwCEfN74_lKwIqZuct27ObgTHioSCa-fisRfZ_J-6twx_EpsDUo7A676ryvZY18qCoysBN6KnjYBsTLUBhnQsEWa5Odt6Y7G6y_XXHN8fzXXswUU3V9Zl3Wa5VY7J5qtdYD2F7sHA8pdsMhyClj7AxfB_aTkIff-fWaRZASEU1OpcOn0EMtr54I9vcO7xWNijbFnQVIbH0=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUF6TVCCXXYYDDVC2Z3UDPK4HA5CNFSM5EU5PB3KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4O7WKEVA.gif>

**Comment by MomidiMomidi** [comment]
I was able to build.
thank you!
