### ISSUE TITLE
ISL tarball download location

### ISSUE THREAD

**Issue by malcweir** [rdp/ffmpeg-windows-build-helpers#592]
The site used for ISL at http://isl.gforge.inria.fr has apparently been shut down.  This causes "Connection timed out" errors when building (as the site isn't there!).

To fix, I changed line 692 of `ffmpeg-windows-build-helpers-master/patchesmingw-w64-build-r22.local` from:

`std_compile 'isl' "$isl_ver" "http://isl.gforge.inria.fr/isl-$isl_ver.tar.xz" "../source/isl-$isl_ver/configure" --prefix="$isl_prefix" --build="$system_type" $gcc_host --enable-static --disable-shared --with-gmp-prefix="$gmp_prefix" --with-piplib=no --with-clang=no`

To:

`std_compile 'isl' "$isl_ver" "https://sourceforge.net/projects/libisl/files/isl-$isl_ver.tar.xz" "../source/isl-$isl_ver/configure" --prefix="$isl_prefix" --build="$system_type" $gcc_host --enable-static --disable-shared --with-gmp-prefix="$gmp_prefix" --with-piplib=no --with-clang=no`

**Comment by malcweir** [comment]
(See e.g. https://groups.google.com/g/isl-development/c/JGaMo2VUu_8?pli=1 for discussion)

**Comment by rdp** [comment]
try latest?

**Comment by rdp** [comment]
hopefully fixed
