### ISSUE TITLE
Possible to upgrade VMAF to 2.3.0 from 1.5.2

### ISSUE THREAD

**Issue by eugenesvk** [rdp/ffmpeg-windows-build-helpers#597]
Currently built ffmpeg doesn't work with the new `.json` Netflix models since VMAF introduced new APIs/format in version 2, while your scripts use version `1.5.2`

On the one hand, there is this [vmaf issue](https://github.com/Netflix/vmaf/issues/753) that implies that v2 is not supported in ffmpeg (and I assumed this was the reason for the old version of VMAF in your build scripts)

On the other hand, this [Gyan's ffmpeg build](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.7z) includes the updated v2.3.0 version of VMAF (as stated in the `.log` file `"version": "2.3.0",`, it also supports links to `.json` models).
So I'm a bit confused as to the state of vmaf support in ffmpeg at the moment

Would it be possible to bump VMAF version in your scripts to `2.3.0` like it seems to be done in Gyan's builds or would it break the build, and we have to wait until Netflix resolves the issue linked above?
Thank you!

**Comment by rdp** [comment]
Looks like homebrew does some kind of funky search and replace...I wonder
if this will be fixed upstream soon?

**Comment by eugenesvk** [comment]
> Looks like homebrew does some kind of funky search and replace...

So homebrew is blocking your upgrade, is that right?

> I wonder if this will be fixed upstream soon?

I also hoped so, but then again it's been a year... :(


By the way, on the API front — FFMPEG with the upgraded VMAF still uses the old APIs (they are deprecated, but not removed yet and still work, so you can't pass the newer options to VMAF via FFMPEG), so the only major benefit is the ability to use newer model `.json` files, which should be ×2  more efficient due to a `floating point`→`integer point` switch (per Netflix's blog post)

**Comment by naabtog** [comment]
Since [this](https://github.com/FFmpeg/FFmpeg/commit/3d29724c008d8f27fecf85757152789b074e8ef9) vmaf 2.0.0 is required. So it doesn't build right now.

**Comment by BlackScreen** [comment]
Can we update vmaf please? Compilation is broken right now. 🙂

**Comment by kgp700** [comment]
I'm success build with lastest master ffmpeg commit, libvmaf v2.1.0
for x86/x64 both build users need script edit like this

```
build_libvmaf() {
if [ "$bits_target" = "32" ]; then
 do_git_checkout https://github.com/Netflix/vmaf.git vmaf_git v2.0.0
else
 do_git_checkout https://github.com/Netflix/vmaf.git vmaf_git v2.0.0
fi
```

Steps : 
1. run build > success 32bit ffmpeg build configuration but you will get compile error
2. after compile error script edit like this 

```
build_libvmaf() {
if [ "$bits_target" = "32" ]; then
 do_git_checkout https://github.com/Netflix/vmaf.git vmaf_git v2.1.0
else
 do_git_checkout https://github.com/Netflix/vmaf.git vmaf_git v2.0.0
fi
```
3. run build -> Sucessful 32bit ffmpeg build.
4. next 64bit build ->  success 64bit ffmpeg build configuration but you will get compile error
5. after compile error script edit like this 
```
build_libvmaf() {
if [ "$bits_target" = "32" ]; then
 do_git_checkout https://github.com/Netflix/vmaf.git vmaf_git v2.1.0
else
 do_git_checkout https://github.com/Netflix/vmaf.git vmaf_git v2.1.0
fi
```
6. run build -> Sucessful 64bit ffmpeg build.

I hope fix this issue fastly.

**Comment by naabtog** [comment]
> It just temporary method... I hope fix this issue fastly.

Please note this might work only if you skip the patch for v1.5.2. Otherwise script will ask you for a file to patch that doesn't exist.

**Comment by kgp700** [comment]
> > It just temporary method... I hope fix this issue fastly.
> 
> Please note this might work only if you skip the patch for v1.5.2. Otherwise script will ask you for a file to patch that doesn't exist.

Oops... I forgot that.
I removed patch for v1.5.2 line.

**Comment by hiiro74** [comment]
> I'm success build with lastest master branch ffmpeg commit, libvmaf v2.1.0 (ffmpeg comit : [FFmpeg/FFmpeg@61cbfdc](https://github.com/FFmpeg/FFmpeg/commit/61cbfdc0a29e88483a6fa9645f64fec71983689a)) for x86/x64 both build users need script edit like this
> 
> ```
> build_libvmaf() {
> if [ "$bits_target" = "32" ]; then
>  do_git_checkout https://github.com/Netflix/vmaf.git vmaf_git v2.0.0
> else
>  do_git_checkout https://github.com/Netflix/vmaf.git vmaf_git v2.0.0
> fi
> ```
> 
> Steps :
> 
> 1. run build > success 32bit ffmpeg build configuration but you will get compile error
> 2. after compile error script edit like this
> 
> ```
> build_libvmaf() {
> if [ "$bits_target" = "32" ]; then
>  do_git_checkout https://github.com/Netflix/vmaf.git vmaf_git v2.1.0
> else
>  do_git_checkout https://github.com/Netflix/vmaf.git vmaf_git v2.0.0
> fi
> ```
> 
> 3. run build -> Sucessful 32bit ffmpeg build.
> 4. next 64bit build ->  success 64bit ffmpeg build configuration but you will get compile error
> 5. after compile error script edit like this
> 
> ```
> build_libvmaf() {
> if [ "$bits_target" = "32" ]; then
>  do_git_checkout https://github.com/Netflix/vmaf.git vmaf_git v2.1.0
> else
>  do_git_checkout https://github.com/Netflix/vmaf.git vmaf_git v2.1.0
> fi
> ```
> 
> 6. run build -> Sucessful 64bit ffmpeg build.
> 
> It just temporary method... I hope fix this issue fastly.

Used this to fix "ERROR: libvmaf >= 2.0.0 not found using pkg-config"
But instead of going from 2.0.0 to 2.1.0 I went from 2.0.0 to 2.3.0
And yes I also removed the patch for v1.5.2 line.

**Comment by BlackScreen** [comment]
Can we just fix this in the build script for all of us?

**Comment by rdp** [comment]
OK hopefully working now, give it a shot, sorry for the delay.

**Comment by eugenesvk** [comment]
Thank a bunch, seems to be working with a .json model now
