### ISSUE TITLE
Builds fails using ffmpeg n5.0 or greater

### ISSUE THREAD

**Issue by echoxxzz** [rdp/ffmpeg-windows-build-helpers#603]
If I call the build script with -ffmpeg-git-checkout-version=n5.0 or any greater ffmpeg version the build fails with the following error:

Unknown option: "--enable-libsvthevc".

According to the output from ./configure --help it doesn't even show this as a valid option in 5.0 or greater of ffmpeg.

**Comment by MI2-2** [comment]
Unknown option "--enable-libsvthevc" with building ffmpeg #564
https://github.com/rdp/ffmpeg-windows-build-helpers/issues/564

**Comment by MI2-2** [comment]
`      if [[ $ffmpeg_git_checkout_version == *"n5.0"* ]] || [[ $ffmpeg_git_checkout_version == *"master"* ]]; then
`

**Comment by echoxxzz** [comment]
It also fails using n5.1-dev so you probably need some kind of check to catch any version greater than 5.0. Also what happens if you try and set the ffmpeg_git_checkout_version using a git hash? Maybe the only way around this going forward is to make libsvthevc a option parameter to the script. I suspect not a lot of people are using svthevc.

**Comment by rdp** [comment]
Is this fixed?

**Comment by MI2-2** [comment]
Not yet...

I cannot build master and n5.0.1 in my environment.
WSL Ubuntu on Win11

**Comment by rdp** [comment]
What failure message?  I am able to build git master I believe, though
haven't tried it on WSL

**Comment by naabtog** [comment]
n5.0.1 successfully builds on Ubuntu, so I suppose this issue is WSL-related.

**Comment by MI2-2** [comment]
My environment is as follows.
Ubuntu 20.  WSL on Win11


When command option below.
./cross_compile_ffmpeg.sh --ffmpeg-git-checkout-version=n5.0.1 --disable-nonfree=n --build-intel-qsv=y --build-ffmpeg-static=y --compiler-flavors=win64

Error message:
When ./configure of ffmpeg

------
Unknown option "--enable-libsvthevc".


When command option below.
./cross_compile_ffmpeg.sh --disable-nonfree=n --build-intel-qsv=y --build-ffmpeg-static=y --compiler-flavors=win64

. /configure passes.
Error message:
libavcodec/libsvt_hevc.c:571:23: note: (near initialization for 'ff_libsvt_hevc_encoder.cb.decode')
CC      libavcodec/libvorbisdec.o
CC      libavcodec/libvorbisenc.o
make: *** [ffbuild/common.mak:78: libavcodec/libsvt_hevc.o] Error 1
make: *** Waiting for unfinished jobs....

Can someone please tell me how to solve this problem?

**Comment by jam365** [comment]
> My environment is as follows. Ubuntu 20. WSL on Win11
> 
> When command option below. ./cross_compile_ffmpeg.sh --ffmpeg-git-checkout-version=n5.0.1 --disable-nonfree=n --build-intel-qsv=y --build-ffmpeg-static=y --compiler-flavors=win64
> 
> Error message: When ./configure of ffmpeg
> 
> > Unknown option "--enable-libsvthevc".
> 
> When command option below. ./cross_compile_ffmpeg.sh --disable-nonfree=n --build-intel-qsv=y --build-ffmpeg-static=y --compiler-flavors=win64
> 
> . /configure passes. Error message:
> 
> ```
> libavcodec/libsvt_hevc.c:571:23: note: (near initialization for 'ff_libsvt_hevc_encoder.cb.decode')
> CC      libavcodec/libvorbisdec.o
> CC      libavcodec/libvorbisenc.o
> make: *** [ffbuild/common.mak:78: libavcodec/libsvt_hevc.o] Error 1
> make: *** Waiting for unfinished jobs....
> ```
> 
> Can someone please tell me how to solve this problem?

I was having the same issue and manage to solve it by disabling [SVT-HEVC](https://github.com/OpenVisualCloud/SVT-HEVC), I don't have a need for that in my build.

If that is your case too, you can build it by commenting out lines 2352 and 2378, like: 

`# git apply "$work_dir/SVT-HEVC_git/ffmpeg_plugin/master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch"`
`# config_options+=" --enable-libsvthevc"`

Seems like the patch for SVT-HEVC is not applying correctly,

**Comment by rdp** [comment]
Made it opt-in now, give it a shot :)

**Comment by MI2-2** [comment]
I have successfully built n5.0.1!!
Thanks alot!!

**Comment by shamelesscookie** [comment]
> Made it opt-in now, give it a shot :)

@rdp am I understanding the fix correctly that the workaround for this is to not build svt at all by passing `--build-svt=n`?

If so, I would like to be able to selectively exclude only `libsvthevc` and still enable `libsvtav1` and `libvpx`.

I can file a PR to add this, but I wanted to make sure I understand what the change was that made the svthevc optional

**Comment by rdp** [comment]
libvpx is included by default, I think.  Are you wanting ffmpeg 5.x with
libsvtav1 and libvpx?  The current patch doesn't seem to work with 5.x and
I think it gives libsvtav1?  libvpx is enabled by default I believe (auto
detect).  Thanks!

**Comment by rgomezc** [comment]
I don't think libvpx is included by default right now. In the script it is inside the section that only gets called if you enabled SVT. Right now it is around line 2385.

I had to move it outside that if (to line 2386) for it to be included on the ffmpeg build.
