### ISSUE TITLE
libmodplug fails to build

### ISSUE THREAD

**Issue by naabtog** [rdp/ffmpeg-windows-build-helpers#608]
libmodplug fails to build due to recent activity. One of some recent commits that works is 2018ad5dfe19413c3656f6d109cb614dec95e92b (latest in 28 Jan). Haven't tried other ones.

**Comment by naabtog** [comment]
Sorry for opening this, I can't reproduce it. This issue should be closed.

**Comment by rdp** [comment]
No worries
