### ISSUE TITLE
fatal: http://repo.or.cz/r/x264.git/info/refs not valid: is this a git repository?

### ISSUE THREAD

**Issue by abcfy2** [rdp/ffmpeg-windows-build-helpers#61]
Stopped at this line. Maybe change the x264 official git can solve this issue?

**Comment by rdp** [comment]
Seems to be working ok here, could you try again? Make sure your git is
relatively new so has http support?

**Comment by abcfy2** [comment]
http://repo.or.cz/r/x264.git is empty at that time. But now it works. At that time, I change the x264 git repo to ``git://git.videolan.org/x264.git`` to solve this problem. The official x264 git repo is very fast.

**Comment by rdp** [comment]
Yeah unfortunately I need "http" access for myself, does git.videolan.org
have any for that one?

**Comment by abcfy2** [comment]
I didn't see any x264 official http git repo.

**Comment by rdp** [comment]
hmm this is a tricky one.  If I replace it with 
do_git_checkout "http://git.videolan.org/git/x264.git" "x264" "origin/stable"

it takes like a minute [for me here, location: Utah, US] whereas 20 seconds with the current one, which seems to be working again.  Anyone averse to leaving it the way it is? If it fails again I might get more aggressive.  Pretty lame they don't have a github mirror...

**Comment by rdp** [comment]
OK closing as "would be slower" for now, feel free to reopen if desired.
