### ISSUE TITLE
Object does not exist: libavcodec/libsvt_hevc.o

### ISSUE THREAD

**Issue by xatabhk** [rdp/ffmpeg-windows-build-helpers#610]
bavcodec/zerocodec.o libavcodec/zmbv.o libavcodec/zmbvenc.o libavcodec/log2_tab.o libavcodec/reverse.o > libavcodec/avcodec-59.def
Object does not exist: libavcodec/libsvt_hevc.o
make: *** [ffbuild/library.mak:118: libavcodec/avcodec-59.dll] Error 1
make: *** Waiting for unfinished jobs....
/home/hgfk/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-dlltool -m i386:x86-64 -d libpostproc/postproc-56.def -l libpostproc/postproc.lib -D postproc-56.dll
/home/hgfk/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-dlltool -m i386:x86-64 -d libswscale/swscale-6.def -l libswscale/swscale.lib -D swscale-6.dll

**Comment by rdp** [comment]
This is with unmodified?

**Comment by xatabhk** [comment]
> This is with unmodified?
Yes. I used a modified ffmpeg. I did not notice the official ffmpeg had removed ‘--enable-libsvthevc’ option.

**Comment by rdp** [comment]
is it fixed?
