### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by ericsia** [rdp/ffmpeg-windows-build-helpers#611]
removed

**Comment by ericsia** [comment]
Btw, hope this helps, I found this from official ffmpeg:
```
http_protocol_select="tcp_protocol"
https_protocol_select="tls_protocol"
tcp_protocol_select="network"
tls_protocol_deps_any="gnutls openssl schannel securetransport libtls mbedtls"
tls_protocol_select="tcp_protocol"
```

**Comment by rdp** [comment]
Looks like you need to also add

tcp_protocol

 to configure probably something like --enable-protocol=xxx?
https://ffmpeg.org/ffmpeg-protocols.html
