### ISSUE TITLE
REQUEST: Add support for building external libmpg123 to support building LAME with external libmpg123 decoder.

### ISSUE THREAD

**Issue by timothymowens** [rdp/ffmpeg-windows-build-helpers#616]
Currently I'm modifying the cross_compile_ffmpeg.sh script to pull LAME at revision r6478 as it is the last revision that compiles with the internal libmpg library.

Starting with the following revision, they started to rip out libmpg and instead require external libmpg123 to allow building with the decoder.

Please add support for building libmpg123 and enabling the decoder in the trunk of the LAME svn utilizing the external libmpg123 library.

I haven't figured out yet how to do this myself, but perhaps this will help someone with this request:

- https://sourceforge.net/p/lame/mailman/lame-dev/thread/20180923002748.0935d049%40cindy/

**Comment by timothymowens** [comment]
Actually, I think I figured it out.  I added the following function to pull down the newest mpg123 and build it:

```
build_mpg123() {
  do_svn_checkout svn://scm.orgis.org/mpg123/trunk mpg123_svn
  cd mpg123_svn
    generic_configure
    do_make_and_make_install
  cd ..
}
```

Then added `build_mpg123` before `build_lame`:

```
  build_libsndfile "install-libgsm" # Needs libogg >= 1.1.3 and libvorbis >= 1.2.3 for external support [disabled]. Uses dlfcn. 'build_libsndfile "install-libgsm"' to install the included LibGSM 6.10.
  build_mpg123
  build_lame # Uses dlfcn.
```

And finally, I added ` --enable-libmpg123` configuration flag for LAME:

```
build_lame() {
  do_svn_checkout https://svn.code.sf.net/p/lame/svn/trunk/lame lame_svn
  cd lame_svn
    sed -i.bak '1s/^\xEF\xBB\xBF//' libmp3lame/i386/nasm.h # Remove a UTF-8 BOM that breaks nasm if it's still there; should be fixed in trunk eventually https://sourceforge.net/p/lame/patches/81/
    generic_configure "--enable-nasm --enable-libmpg123"
    do_make_and_make_install
  cd ..
}
```

**Comment by timothymowens** [comment]
So after all this, ffmpeg fails to build with the following error: `ERROR: libmp3lame >= 3.98.3 not found`

This makes no sense considering the version of LAME that's being built is 3.100.1.

I'm stuck at this point unless someone else has an answer.

**Comment by rdp** [comment]
Yeah lame doesn't have a .pc file of its own (apparently) so it was a bit
painful.  Should be going now though, thanks for the idea.

**Comment by Biswa96** [comment]
> Yeah lame doesn't have a .pc file of its own (apparently) so it was a bit painful

I have sent a patch to upstream to add pkgconfig file support here https://sourceforge.net/p/lame/mailman/message/37616009/. Feel free to copy, modify or use it.

**Comment by rdp** [comment]
nice, thanks!

**Comment by timothymowens** [comment]
Sorry for the delay in my reply.  I'm closing this issue.  I was able to successfully build with the LAME decoder thanks to your updates to the cross compile script.  Thank you so much!  I appreciate your work.
