### ISSUE TITLE
capture sound has problem on windows x86

### ISSUE THREAD

**Issue by xengine-qyt** [rdp/ffmpeg-windows-build-helpers#617]
Unable to capture sound on x86 with ffmpeg n4.4.1

ffmpeg -list_devices true -f dshow -i dummy
...
[dshow @ 00981e00]  "virtual-audio-capturer"
[dshow @ 00981e00]     Alternative name "@device_sw_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\{8E14549B-DB61-4309-AFA1-3578E927E935}"
...

ffmpeg -f dshow -i audio="virtual-audio-capturer" a-out.aac

The program stop after enter the command...

but x64 it is ok...why....i don't know...

**Comment by xengine-qyt** [comment]
Does anyone have it working fine on version 4.4.1

**Comment by rdp** [comment]
does it work with latest ffmpeg?

**Comment by xengine-qyt** [comment]
v5.0 it is work....

**Comment by rdp** [comment]
git master fails?

**Comment by xengine-qyt** [comment]
> 

not work on 4.4.* version
