### ISSUE TITLE
n4.3.3 build failure.

### ISSUE THREAD

**Issue by xengine-qyt** [rdp/ffmpeg-windows-build-helpers#618]
./cross_compile_ffmpeg.sh --build-ffmpeg-shared=y --build-ffmpeg-static=n --ffmpeg-git-checkout-version=n4.3.3

CC	libavdevice/dshow_common.o
CC	libavdevice/dshow_crossbar.o
CC	libavdevice/dshow_enummediatypes.o
CC	libavdevice/dshow_enumpins.o
CC	libavdevice/dshow_filter.o
CC	libavdevice/dshow_pin.o
CC	libavdevice/gdigrab.o
CC	libavdevice/lavfi.o
CC	libavdevice/opengl_enc.o
CC	libavdevice/reverse.o
CC	libavdevice/sdl2.o
CC	libavdevice/utils.o
CC	libavdevice/vfwcap.o
WINDRES	libavdevice/avdeviceres.o
sh: 1: /home/ubuntu/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-gcc -E -xc-header -DRC_INVOKED -MMD -MF libavdevice/avdeviceres.d -MT libavdevice/avdeviceres.o: not found
/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-windres: preprocessing failed.
make: *** [ffbuild/common.mak:85：libavdevice/avdeviceres.o] errno 1

**Comment by rdp** [comment]
https://github.com/rdp/ffmpeg-windows-build-helpers/issues/578 helpful?

**Comment by xengine-qyt** [comment]
no,but i am delete winder compile in makefile that's work...
now a new error build on x64...

fetched no code changes, not forcing reconfigure for that...
error: patching failed: configure:288
error: configure: patch not applied
error: patching failed: libavcodec/Makefile:1061
error: libavcodec/Makefile: patch not applied
error: patching failed: libavcodec/allcodecs.c:757
error: libavcodec/allcodecs.c: patch not applied
error: libavcodec/libsvt_hevc.c: already exists in workspace
error: doc/general_contents.texi: no such file or directory
configuring ffmpeg_git_n4.3.3_shared (/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git_n4.3.3_shared) as $ PKG_CONFIG_PATH=/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw -w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --pkg- config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 - -target-os=mingw32 --cross-prefix=/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca -- enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype -- enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-am rnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-liblensfun --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libaom --enable-libvpx --enable-nvenc --enable-nvdec --extra -libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-shared --disable- static --prefix=/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git_n4.3.3_shared --disable-libdav1d
all touch files already_configured* touchname= already_configured_c5f5aa848464508de2a379612d61ee53-
config options --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- -- -enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite - -enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb -- enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-liblensfun --enable-libvmaf --enable-libsrt --e enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libaom --enable-libvpx --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC -- enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 -- enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-shared --disable-static --prefix= /home/ubuntu/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git_n4.3.3_shared --disable-libdav1d ./configure
Unknown option "--enable-libsvtav1".
See ./configure --help for available options.
failed configure ffmpeg_git_n4.3.3_shared
