### ISSUE TITLE
error in libavcodec

### ISSUE THREAD

**Issue by wfcook** [rdp/ffmpeg-windows-build-helpers#630]
This looks like its upstream I think, but in libavcodec, libsvt_hevc.c, line 571

    .encode2        = eb_encode_frame,

doesn;t work because theyve changed FFCodec so tat it no longer has an encode2 member. I *think* the fix is

    .cb.encode      = eb_encode_frame,

**Comment by rdp** [comment]
failure message please?

**Comment by rdp** [comment]
I think I might make svt opt in...

**Comment by wfcook** [comment]
ubuntu 20.04 under windows 11 wsl2. I'm trying with --ffmpeg-git-checkout-version=release/5.0 but as soon as that's through I'll post re-run with the other command line and duplicate the error to get you the full message and command line text

**Comment by wfcook** [comment]
This command line:
$ ./cross_compile_ffmpeg.sh --disable-nonfree=n --compiler-flavors=win64 --enable-gpl=n

Produces this output:
libavcodec/libsvt_hevc.c:571:6: **error**: 'FFCodec' has no member named 'encode2'
  571 |     .encode2        = eb_encode_frame,
      |      ^~~~~~~

**Comment by wfcook** [comment]
Also, This command line:

$ ./cross_compile_ffmpeg.sh --disable-nonfree=n --compiler-flavors=win64 --enable-gpl=n --ffmpeg-git-checkout-version=release/5.0

Produces this error:

Downloading (via git clone) ffmpeg_git_with_fdk_aac_lgpl_release_5.0 from https://github.com/FFmpeg/FFmpeg.git
Cloning into 'ffmpeg_git_with_fdk_aac_lgpl_release_5.0.tmp'...
remote: Enumerating objects: 661625, done.
remote: Total 661625 (delta 0), reused 0 (delta 0), pack-reused 661625
Receiving objects: 100% (661625/661625), 293.56 MiB | 24.79 MiB/s, done.
Resolving deltas: 100% (522184/522184), done.
done git cloning to ffmpeg_git_with_fdk_aac_lgpl_release_5.0
doing git checkout release/5.0
Branch 'release/5.0' set up to track remote branch 'release/5.0' from 'origin'.
Switched to a new branch 'release/5.0'
Already up to date.
got upstream changes, forcing re-configure. Doing git clean
HEAD is now at b655beb025 fate: update reference files after the recent dash manifest muxer changes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1430  100  1430    0     0  1396k      0 --:--:-- --:--:-- --:--:-- 1396k
applying patch frei0r_load-shared-libraries-dynamically.diff
patching file libavfilter/vf_frei0r.c
Hunk #2 succeeded at 244 (offset 5 lines).
error: patch failed: libavcodec/allcodecs.c:788
error: libavcodec/allcodecs.c: patch does not apply
configuring ffmpeg_git_with_fdk_aac_lgpl_release_5.0 (/home/wfcook/ffmpeg4/sandbox/win64/ffmpeg_git_with_fdk_aac_lgpl_release_5.0) as $ PKG_CONFIG_PATH=/home/wfcook/ffmpeg4/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/home/wfcook/ffmpeg4/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/wfcook/ffmpeg4/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg  --enable-libopenh264 --enable-liblensfun  --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libaom --enable-libvpx --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/wfcook/ffmpeg4/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-nonfree --enable-libfdk-aac --enable-decklink
all touch files already_configured* touchname= already_configured_bf199e0dd38e4ed696d100ff397d3043-
config options --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/wfcook/ffmpeg4/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-liblensfun --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libaom --enable-libvpx --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/wfcook/ffmpeg4/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-nonfree --enable-libfdk-aac --enable-decklink ./configure
**Unknown option "--enable-libsvthevc".**
See ./configure --help for available options.
failed configure ffmpeg_git_with_fdk_aac_lgpl_release_5.0

**Comment by nschlia** [comment]
> I think I might make svt opt in...

I commented out this part of the script (starting at line 2377):
```
    if [ "$bits_target" != "32" ]; then
      config_options+=" --enable-libsvthevc"
      config_options+=" --enable-libsvtav1"
      # config_options+=" --enable-libsvtvp9"
    fi
```
That fixed the problem. Making it optional would help, I think.

**Comment by wfcook** [comment]
It does appear that others are running into this:

[https://githubhot.com/repo/OpenVisualCloud/SVT-HEVC/issues/616](url)

**Comment by rdp** [comment]
OK made it "opt in" give it a shot, thanks for the report!
