### ISSUE TITLE
Build error in fontconfig-2.13.92

### ISSUE THREAD

**Issue by ngeojiajun** [rdp/ffmpeg-windows-build-helpers#631]
Building using the scripts on commit `ff31946970db9d8dc6166db1badec90d7ebe40df` for the win64  platform at Ubuntu 21.10 and always failed with this error when building the fontconfig
```
checking for a usable iconv... libiconv
checking for FREETYPE... yes
checking for FT_Get_BDF_Property... yes
checking for FT_Get_PS_Font_Info... yes
checking for FT_Has_PS_Glyph_Names... yes
checking for FT_Get_X11_Font_Format... yes
checking for FT_Done_MM_Var... yes
checking for LIBXML2... yes
checking SAX1 support in libxml2... configure: error: 
*** SAX1 support in libxml2 is required. enable it or use expat instead.
failed configure fontconfig-2.13.92
```

Additional notes:
An attempt is tried by manually adding the `--with-sax1` in the script and rebuild the libxml but it doesnt work also.

**Comment by rdp** [comment]
works on 20.04 hmm...

**Comment by ngeojiajun** [comment]
update: i have found an even weird situation which happened in linux mint cinnamon 20.3. which one build succeeded and another one failed. the only difference between those machine are linux kernel version.

**Comment by ngeojiajun** [comment]
fixed it by moving the folder to somewhere that only contain ascii characters in path
