### ISSUE TITLE
as it stands right now this script cannot complete a win32 and win64

### ISSUE THREAD

**Issue by james28909** [rdp/ffmpeg-windows-build-helpers#638]
i had problems all along the way. zimg_git will compile just fine if you do it manually (downloading 3.0.4 and specifying the cross compiler path and pkg config etc, then you have to edit that like out of the ffmpeg compiler script. then i also had issues with a few others which i compiled fine manually specifying necessary PATH AND PKGCONG and correct host etc. 

once you do all of this, then you can compile. one other thing is i noticed is that zimg (and others) gets built no matter what. there should be checks somehow that will just use existing configured libs and not make clean and nuke those config libs, or maybe there should be a flag to skip any already configured libs... even if there are new versions up stream. i get it though, you want to make sure that whoever builds gets the up to date versions of these libs, but somehow the script is broken because there is a handful of libs i can download and configure and make manually while specifying the correct prefix/pkgconfig/path etc, but the script itself wont do that

but with that said, i would not have been able to do this without this script. so thanks for sharing this lovely script

**Comment by james28909** [comment]
i shouldnt haver to edit out libs in the scripts and manually compile. if there is any way that i can help please let me know.

**Comment by rdp** [comment]
hopefully fixed, let me know if not still...thanks

**Comment by james28909** [comment]
i will try this in a few days and let you know for sure. thanks
