### ISSUE TITLE
How to get .pdb files?

### ISSUE THREAD

**Issue by alexgeek** [rdp/ffmpeg-windows-build-helpers#644]
Hey just did a build and changed `do_debug_build` to `y` but I don't get any pdbs.

Checked with find and only got a zlib one:
```
find . -name *.pdb
./sandbox/win64/libmysofa_git/windows/third-party/zlib-1.2.11/lib/zlib.pdb
```

Any idea?

Thanks

**Comment by rdp** [comment]
https://stackoverflow.com/questions/19269350/how-to-generate-pdb-files-while-building-library-using-mingw
may be useful.
