### ISSUE TITLE
Stops at dlfcn-win32

### ISSUE THREAD

**Issue by pyahmed** [rdp/ffmpeg-windows-build-helpers#65]
I'm trying to run the script on Ubuntu 14.10/64bit but at some point I get the following error:

Ok, done building MinGW-w64 cross-compiler(s)...
Building 32-bit ffmpeg...
PKG_CONFIG_PATH=/home/dataman/sandbox/mingw-w64-i686/i686-w64-mingw32/lib/pkgconfig
Downloading (via git clone) dlfcn-win32 from https://github.com/dlfcn-win32/dlfcn-win32.git
Cloning into 'dlfcn-win32.tmp'...
remote: Counting objects: 156, done.
remote: Total 156 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (156/156), 48.53 KiB | 0 bytes/s, done.
Resolving deltas: 100% (92/92), done.
Checking connectivity... done.
done downloading dlfcn-win32
./configure: 157: ./configure: cannot create /tmp/test.c: Permission denied
testing compiler: /home/dataman/sandbox/mingw-w64-i686/bin/i686-w64-mingw32-gcc -shared -o /tmp/test.dll /tmp/test.c
./configure: 163: ./configure: /home/dataman/sandbox/mingw-w64-i686/bin/i686-w64-mingw32-gcc: not found
/home/dataman/sandbox/mingw-w64-i686/bin/i686-w64-mingw32-gcc could not create shared file with Windows API functions.
Make sure your MinGW system is working properly.

making /home/dataman/sandbox/win32/dlfcn-win32 as $ PATH=/home/dataman/sandbox/mingw-w64-i686/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games make  -j 1

Makefile:4: config.mak: No such file or directory
make: *** No rule to make target 'config.mak'.  Stop.

**Comment by rdp** [comment]
./configure: 157: ./configure: cannot create /tmp/test.c: Permission denied

maybe you can it as root once but are not now?

**Comment by pyahmed** [comment]
This is a digital ocean instance. I get this when I run this as root:

Ok, done building MinGW-w64 cross-compiler(s)...
Building 32-bit ffmpeg...
PKG_CONFIG_PATH=/root/sandbox/mingw-w64-i686/i686-w64-mingw32/lib/pkgconfig
Downloading (via git clone) dlfcn-win32 from https://github.com/dlfcn-win32/dlfcn-win32.git
Cloning into 'dlfcn-win32.tmp'...
remote: Counting objects: 156, done.
remote: Total 156 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (156/156), 48.53 KiB | 0 bytes/s, done.
Resolving deltas: 100% (92/92), done.
Checking connectivity... done.
done downloading dlfcn-win32
testing compiler: /root/sandbox/mingw-w64-i686/bin/i686-w64-mingw32-gcc -shared -o /tmp/test.dll /tmp/test.c
./configure: 163: ./configure: /root/sandbox/mingw-w64-i686/bin/i686-w64-mingw32-gcc: not found
/root/sandbox/mingw-w64-i686/bin/i686-w64-mingw32-gcc could not create shared file with Windows API functions.
Make sure your MinGW system is working properly.

making /root/sandbox/win32/dlfcn-win32 as $ PATH=/root/sandbox/mingw-w64-i686/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games make  -j 1

Makefile:4: config.mak: No such file or directory
make: *** No rule to make target 'config.mak'.  Stop.

**Comment by rdp** [comment]
clear your sandbox first?

**Comment by pyahmed** [comment]
Yes - was done from absolutely clean state:
- new instance -> apt-get the deps as suggested by the script -> run the script.

**Comment by rdp** [comment]
OK I just built it on a DO "clean slate" as well and it worked OK.
I was root the whole time though it shouldn't matter.

testing compiler: /root/sandbox/mingw-w64-i686/bin/i686-w64-mingw32-gcc
-shared -o /tmp/test.dll /tmp/test.c
Does /tmp/test.dll exist? Can you delete it?
does  /root/sandbox/mingw-w64-i686/bin/i686-w64-mingw32-gcc exist? can you
run it?
can you delete /tmp/test.c?
GL!
-roger-

**Comment by pyahmed** [comment]
>Does /tmp/test.dll exist? Can you delete it?

Does not exist.

>does /root/sandbox/mingw-w64-i686/bin/i686-w64-mingw32-gcc exist?

Does not exist.

>can you delete /tmp/test.c?

Yes.
So I tried it again. Using the smallest digitalocean config (1CPU/512MB RAM) the script fails with the above error. When I do it with the slightly beefier config (2CPU/1GB RAM) it works perfectly. So seems to be a problem with number of cores or available RAM?

**Comment by rdp** [comment]
ahh interesting. Yeah with a small DO box you'd need to add some "virtual"
swap RAM
https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
I'll add that as a note.

**Comment by rdp** [comment]
OK note added

**Comment by rdp** [comment]
leaving open since I could warn even more...

**Comment by rdp** [comment]
added note, I believe.

**Comment by rdp** [comment]
ran into this again:

./configure: line 157: /tmp/test.c: Permission denied
testing compiler: /Users/rdp2/dev/ffmpeg-windows-build-helpers/sandbox/mingw-w64-i686/bin/i686-w64-mingw32-gcc -shared -o /tmp/test.dll /tmp/test.c
/Users/rdp2/dev/ffmpeg-windows-build-helpers/sandbox/mingw-w64-i686/lib/gcc/i686-w64-mingw32/4.9.3/../../../../i686-w64-mingw32/bin/ld: cannot open output file /tmp/test.dll: Permission denied
collect2: error: ld returned 1 exit status

it was a permissions issue at least this time (I did add a "you don't have enough RAM" notice as well)
