### ISSUE TITLE
Unknown option "--enable-libsvthevc" Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by duyanhstar** [rdp/ffmpeg-windows-build-helpers#655]
Here is the log.
`Install the project...
-- Install configuration: "Release"
-- Installing: /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libx265.a
-- Up-to-date: /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/x265.h
-- Up-to-date: /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/x265_config.h
-- Up-to-date: /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig/x265.pc
-- Installing: /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin/x265.exe
doing git checkout 75b9fcd2669c75a99791
M       codec/encoder/core/inc/param_svc.h
HEAD is now at 75b9fcd2 meson: fix broken shared library with no contents (#3477)
fetched no code changes, not forcing reconfigure for that...
Already made /home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64 openh264_git ...
doing git checkout origin/master
HEAD is now at 402e264b9 hadamard: Add 4x4 test.
fetched no code changes, not forcing reconfigure for that...
Already made /home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64/aom_git aom_build ...
doing git checkout origin/master
M       meson_options.txt
HEAD is now at 8f16314 threading: Add a pending list for async task insertion
fetched no code changes, not forcing reconfigure for that...
Already used meson libdav1d
already did ninja libdav1d
doing git checkout origin/master
HEAD is now at e0a3fd0f gitattributes: fix languages reporting
fetched no code changes, not forcing reconfigure for that...
Already made /home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64/avisynth_git avisynth-build ...
doing git checkout origin/stable
M       configure
HEAD is now at baee400f CI: Fix vlc-contrib processing on macos
fetched no code changes, not forcing reconfigure for that...
Already made /home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64 x264_all_bitdepth ...
install -d /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin
install x264.exe /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin
install -d /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include
install -d /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig
install -m 644 ./x264.h x264_config.h /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include
install -m 644 x264.pc /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig
install -d /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib
install -m 644 libx264.a /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc-ranlib /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libx264.a
doing git checkout master
M       libavfilter/vf_frei0r.c
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
fetched no code changes, not forcing reconfigure for that...
error: patch failed: configure:6686
error: configure: patch does not apply
configuring ffmpeg_git (/home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git) as $ PKG_CONFIG_PATH=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg  --enable-libopenh264  --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libvpx --enable-libaom --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
all touch files already_configured* touchname= already_configured_ec89ce325082052dd66c75141e938fa9-
config options --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libvpx --enable-libaom --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 ./configure
Unknown option "--enable-libsvthevc".
See ./configure --help for available options.
failed configure ffmpeg_git`

I try a lot solutions, anyone can help?

**Comment by rdp** [comment]
What script parameters of any?

On Thursday, November 3, 2022, duyanhstar ***@***.***> wrote:
> Here is the log.
> Install the project... -- Install configuration: "Release" -- Installing:
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libx265.a
-- Up-to-date:
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/x265.h
-- Up-to-date:
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/x265_config.h
-- Up-to-date:
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig/x265.pc
-- Installing:
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin/x265.exe
doing git checkout 75b9fcd2669c75a99791 M
codec/encoder/core/inc/param_svc.h HEAD is now at 75b9fcd2 meson: fix
broken shared library with no contents (#3477) fetched no code changes, not
forcing reconfigure for that... Already made
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64 openh264_git ...
doing git checkout origin/master HEAD is now at 402e264b9 hadamard: Add 4x4
test. fetched no code changes, not forcing reconfigure for that... Already
made /home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64/aom_git
aom_build ... doing git checkout origin/master M meson_options.txt HEAD is
now at 8f16314 threading: Add a pending list for async task insertion
fetched no code changes, not forcing reconfigure for that... Already used
meson libdav1d already did ninja libdav1d doing git checkout origin/master
HEAD is now at e0a3fd0f gitattributes: fix languages reporting fetched no
code changes, not forcing reconfigure for that... Already made
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64/avisynth_git
avisynth-build ... doing git checkout origin/stable M configure HEAD is now
at baee400f CI: Fix vlc-contrib processing on macos fetched no code
changes, not forcing reconfigure for that... Already made
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64 x264_all_bitdepth
... install -d
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin
install x264.exe
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin
install -d
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include
install -d
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig
install -m 644 ./x264.h x264_config.h
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include
install -m 644 x264.pc
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig
install -d
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib
install -m 644 libx264.a
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc-ranlib
/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libx264.a
doing git checkout master M libavfilter/vf_frei0r.c Already on 'master'
Your branch is up to date with 'origin/master'. Already up to date. fetched
no code changes, not forcing reconfigure for that... error: patch failed:
configure:6686 error: configure: patch does not apply configuring
ffmpeg_git
(/home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git) as $
PKG_CONFIG_PATH=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig
PATH=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH
./configure --pkg-config=pkg-config --pkg-config-flags=--static
--extra-version=ffmpeg-windows-build-helpers --enable-version3
--disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32
--cross-prefix=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-
--enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig
--enable-gmp --enable-gnutls --enable-libass --enable-libbluray
--enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi
--enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug
--enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb
--enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex
--enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc
--enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi
--enable-libmysofa --enable-libopenjpeg --enable-libopenh264
--enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl
--enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1
--enable-libvpx --enable-libaom --enable-nvenc --enable-nvdec
--extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi
--extra-libs=-lmpg123 --extra-libs=-lpthread
--extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC
--extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl
--enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264
--enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid
--enable-libdavs2 --enable-libxavs2 --enable-libxavs
--extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static
--disable-shared
--prefix=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
all touch files already_configured* touchname=
already_configured_ec89ce325082052dd66c75141e938fa9- config options
--pkg-config=pkg-config --pkg-config-flags=--static
--extra-version=ffmpeg-windows-build-helpers --enable-version3
--disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32
--cross-prefix=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-
--enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig
--enable-gmp --enable-gnutls --enable-libass --enable-libbluray
--enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi
--enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug
--enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb
--enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex
--enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc
--enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi
--enable-libmysofa --enable-libopenjpeg --enable-libopenh264
--enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl
--enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1
--enable-libvpx --enable-libaom --enable-nvenc --enable-nvdec
--extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi
--extra-libs=-lmpg123 --extra-libs=-lpthread
--extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC
--extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl
--enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264
--enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid
--enable-libdavs2 --enable-libxavs2 --enable-libxavs
--extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static
--disable-shared
--prefix=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
./configure Unknown option "--enable-libsvthevc". See ./configure --help
for available options. failed configure ffmpeg_git
>
> I try a lot solutions, anyone can help?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.<
https://ci4.googleusercontent.com/proxy/5MhXkyPmA96qzu2KrprNkou_ADnwoVT13m-BZrN8YsCHsqHn6wqWTP_cjszR1yeoI7HhKE_24rlLhhGUAhxlquYeGOIfKne37rYaHS83b2lZINyIGPyuWjmyF-ig4--_EOvUbmPW9hdA1wx-i3sTmcynYJDT4hFOMhWGKOz99qMeQHxnUfKrcELC5TJmfglYS_qUZNgo8_j68s2Mot7aMCo5e-yimUnYQmw=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUGYISTYQNNSOGFKICDWGPKLHA5CNFSM6AAAAAARWIHBZ2WGG33NNVSW45C7OR4XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHFLBQUF4.gif>Message
ID: ***@***.***>

**Comment by duyanhstar** [comment]
> What script parameters of any?
> On Thursday, November 3, 2022, duyanhstar ***@***.***> wrote: Here is the log. Install the project... -- Install configuration: "Release" -- Installing:
> /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libx265.a -- Up-to-date: /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/x265.h -- Up-to-date: /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/x265_config.h -- Up-to-date: /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig/x265.pc -- Installing: /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin/x265.exe doing git checkout 75b9fcd2669c75a99791 M codec/encoder/core/inc/param_svc.h HEAD is now at 75b9fcd2 meson: fix broken shared library with no contents (#3477) fetched no code changes, not forcing reconfigure for that... Already made /home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64 openh264_git ... doing git checkout origin/master HEAD is now at 402e264b9 hadamard: Add 4x4 test. fetched no code changes, not forcing reconfigure for that... Already made /home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64/aom_git aom_build ... doing git checkout origin/master M meson_options.txt HEAD is now at 8f16314 threading: Add a pending list for async task insertion fetched no code changes, not forcing reconfigure for that... Already used meson libdav1d already did ninja libdav1d doing git checkout origin/master HEAD is now at e0a3fd0f gitattributes: fix languages reporting fetched no code changes, not forcing reconfigure for that... Already made /home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64/avisynth_git avisynth-build ... doing git checkout origin/stable M configure HEAD is now at baee400f CI: Fix vlc-contrib processing on macos fetched no code changes, not forcing reconfigure for that... Already made /home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64 x264_all_bitdepth ... install -d /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin install x264.exe /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin install -d /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include install -d /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig install -m 644 ./x264.h x264_config.h /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include install -m 644 x264.pc /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig install -d /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib install -m 644 libx264.a /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc-ranlib /home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libx264.a doing git checkout master M libavfilter/vf_frei0r.c Already on 'master' Your branch is up to date with 'origin/master'. Already up to date. fetched no code changes, not forcing reconfigure for that... error: patch failed: configure:6686 error: configure: patch does not apply configuring ffmpeg_git (/home/duyanh/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git) as $ PKG_CONFIG_PATH=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig PATH=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH ./configure --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libvpx --enable-libaom --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 all touch files already_configured* touchname= already_configured_ec89ce325082052dd66c75141e938fa9- config options --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libvpx --enable-libaom --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/duyanh/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 ./configure Unknown option "--enable-libsvthevc". See ./configure --help for available options. failed configure ffmpeg_git
> I try a lot solutions, anyone can help? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.<
> https://ci4.googleusercontent.com/proxy/5MhXkyPmA96qzu2KrprNkou_ADnwoVT13m-BZrN8YsCHsqHn6wqWTP_cjszR1yeoI7HhKE_24rlLhhGUAhxlquYeGOIfKne37rYaHS83b2lZINyIGPyuWjmyF-ig4--_EOvUbmPW9hdA1wx-i3sTmcynYJDT4hFOMhWGKOz99qMeQHxnUfKrcELC5TJmfglYS_qUZNgo8_j68s2Mot7aMCo5e-yimUnYQmw=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUGYISTYQNNSOGFKICDWGPKLHA5CNFSM6AAAAAARWIHBZ2WGG33NNVSW45C7OR4XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHFLBQUF4.gif>Message ID: ***@***.***>

i run this script:
`$ ./cross_compile_ffmpeg.sh`

**Comment by rdp** [comment]
OK I disabled svt by default for now...
