### ISSUE TITLE
Error build: libmysofa_git

### ISSUE THREAD

**Issue by duyanhstar** [rdp/ffmpeg-windows-build-helpers#656]
Today, i get this problem when try to buid:
`
-- Found ZLIB: /home/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libz.a (found version "1.2.11")
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ENABLE_STATIC_RUNTIME

Build files have been written to: /home/ffmpeg-windows-build-helpers/sandbox/win64/libmysofa_git
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   323  100   323    0     0   315k      0 --:--:-- --:--:-- --:--:--  315k
applying patch libmysofa.patch
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- ./src/hrtf/mysofa_export.h.meorig  2019-01-23 08:17:24.209371300 -0700
|+++ ./src/hrtf/mysofa_export.h 2019-01-23 08:17:44.000717000 -0700
--------------------------
File to patch: /home/ffmpeg-windows-build-helpers/sandbox/win64/libmysofa_git
File /home/ffmpeg-windows-build-helpers/sandbox/win64/libmysofa_git is not a regular file -- refusing to patch
1 out of 1 hunk ignored -- saving rejects to file /home/ffmpeg-windows-build-helpers/sandbox/win64/libmysofa_git.rej
`

**Comment by rdp** [comment]
Maybe fixed, pull :)
