### ISSUE TITLE
cross-compiler question about lsw 

### ISSUE THREAD

**Issue by Dev-seD** [rdp/ffmpeg-windows-build-helpers#657]
Hello

I'll start by thanking you for sharing your skills.
I started following you a long time ago to build nightly versions of ffmpeg two to three times a year.
I'm using a WMware with Ubuntu-20.04.4

Last weekend I tried to get the LSMASHSource.dll for AviSynth with the following options without success

_./cross_compile_ffmpeg.sh --build-lsw=y_

I got the following error

_~/opt/ffmpeg-cross-compile_2022/ffmpeg-windows-build-helpers/sandbox/win32/lsw/VapourSynth
CFLAGS/LDFLAGS checking...
checking for liblsmash...
checking for libavformat...
error: libavformat checking failed.
error: libavformat/avformat.h might not be installed or some libs missing.
failed configure VapourSynth_

I must have forgotten a path but I don't know where...

**Comment by rdp** [comment]
OK its config.log seemed to complain of missing dependency, hopefully fixed, if not I'm not sure...

**Comment by Dev-seD** [comment]
Hi,

I tried yesterday after your changes, the build progressed a bit more
Unfortunately, it ends with an error...

I have attached the logs

Thank you for trying

[Error_with_win64.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/9991108/Error_with_win64.txt)
[Error_with_win32.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/9991109/Error_with_win32.txt)

**Comment by rdp** [comment]
Hmm uknown type name 'AVBSFContext

Maybe it isn't compatible with recent ffmpeg?  Hmmm...

On Friday, November 11, 2022, Dev-seD ***@***.***> wrote:
> Hi,
>
> I tried yesterday after your changes, the build progressed a bit more
> Unfortunately, it ends with an error...
>
> I have attached the logs
>
> Thank you for trying
>
> Error_with_win64.txt
> Error_with_win32.txt
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.<
https://ci4.googleusercontent.com/proxy/NCZg6U78RpBFGKa_alz5qSU83f31JsD-94km1nUQ56SMuwmtmBFSdWBUrvBgfuOMfss6YH9nf-Muh8HQKafYHOMgJJmXA9CPnWBlf-9uwMkBuc2EcgXch9P96_0rvDfvboER_MXVrYLfT0TVoC_u1w7P8vV68jTH9Qkh8nPRPw5uQsUhw7atUctOJ3YusCB14U_enuNlOAAY59tQJfrGs02gDvkbZ4lmEVN0dXP4QjZGr2zElA=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUCOVTBCYEOFWW4WMXTWHZOHDA5CNFSM6AAAAAAR2WA43WWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSOGB5KE.gif>Message
ID: ***@***.***>

**Comment by Dev-seD** [comment]
Hi

As you say, there is surely an incompatibility

I don't know if the problem is recent

At the moment I have a workaround using an older version of ffmpeg and LSMASHSource.dll

Anyway, thanks for watching

**Comment by rdp** [comment]
thanks
