### ISSUE TITLE
Windows Error Ffmpeg GetSystemTimePreciseAsFileTime not in KERNEL32.dll  (Windows 7)

### ISSUE THREAD

**Issue by Dev-seD** [rdp/ffmpeg-windows-build-helpers#659]
Hi,

I have been encountering a windows error since early 2022 when I run on windows 7 versions of ffmpeg/probe/play built in 2022 with the script cross_compile_ffmpeg.sh

"The procedure entry point GetSystemTimePreciseAsFileTime could not be found in the dynamic link library KERNEL32.dll"

The same versions work correctly on windows 10

The 'not compatible Windows 7' versions were built in master branch and 5.x.x 

Have you also encountered this error?
![Entry_point_not_found](https://user-images.githubusercontent.com/117771161/202852760-7b92033c-b3bc-465c-a57f-ff50ac887785.JPG)

**Comment by AnimMouse** [comment]
Some dependencies in FFmpeg built by [ffmpeg-windows-build-helpers](https://github.com/rdp/ffmpeg-windows-build-helpers) stopped supporting Windows lower than Windows 8 that does not support [`GetSystemTimePreciseAsFileTime` function](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime) thus causing this error.

https://github.com/AnimMouse/ffmpeg-stable-autobuild/issues/91

**Comment by rdp** [comment]
hopefully fixed

**Comment by Dev-seD** [comment]
Thanks for the update
I'm going to try ;)
