### ISSUE TITLE
Incorrect CPU Count

### ISSUE THREAD

**Issue by rboy1** [rdp/ffmpeg-windows-build-helpers#66]
The code reads the number of CPU's using this

cpu_count="$(grep -c processor /proc/cpuinfo)" # linux

If you look at the output the processor count starts from 0 (not 1), the actual count should be + 1

**Comment by rboy1** [comment]
This is a more accurate way to do it

    cpu_count="$(lscpu | grep -c 'CPU(s)')" # linux

**Comment by rdp** [comment]
appears that the "processor" line from /proc/cpuinfo gives the right number
[2 on my system for dual core, that is...]
what does this give for you?
cpu_count="$(grep -c processor /proc/cpuinfo)"
echo $cpu_count

**Comment by rboy1** [comment]
wierdly I got 3 the first time, after a reboot I got 4
