### ISSUE TITLE
Trying to build a native "flavor" keep getting the same error

### ISSUE THREAD

**Issue by TransLucida** [rdp/ffmpeg-windows-build-helpers#660]
with this line:
`./cross_compile_ffmpeg.sh --build-ffmpeg-static=y --gcc-cpu-count=2 --disable-nonfree=n --build-libmxf=n --build-mp4box=n --build-mplayer=n --build-vlc=n --build-lsw=n --build-ismindex=n --build-dvbtee=n --compiler-flavors=native --build-x264-with-libav=y --prefer-stable=y --enable-gpl=n`

I always end at this
`all touch files already_configured* touchname= already_configured_1c13e0f1865197f74e4c743de3f14588-
config options --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --enable-libv4l2 --enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-libxcb-shape --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libaom --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --disable-libmfx --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/amanda/ffmpeg-windows-build-helpers/sandbox/cross_compilers/native --enable-nonfree --enable-libfdk-aac --disable-libx264 ./configure`
`gcc is unable to create an executable file.`
`If gcc is a cross-compiler, use the --enable-cross-compile option.`
`Only do this if you know what cross compiling means.`
`**C compiler test failed.**`

`If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
failed configure ffmpeg_git_pre_x264_with_fdk_aac_lgpl`

Any ideas?

On a side note `--disable-x264` caught my eye there. Why?

**Comment by rdp** [comment]
linux?
--disable-libx264 is so it can build an ffmpeg to "integrate" into
libx264.exe (equivalent), before building libx264.  At the end it should
use it :)

**Comment by TransLucida** [comment]
Oh, I had no idea. You reckon this is what is causing the entire thing to fail? If I choose "win64" as my choice of flavor it completes the process normally and the executables work just fine. Not "native", though.

**Comment by rdp** [comment]
Nah I just haven't kept native very well up to date...

**Comment by rdp** [comment]
Try now?
