### ISSUE TITLE
libwebp_git clone failure

### ISSUE THREAD

**Issue by kevev** [rdp/ffmpeg-windows-build-helpers#662]
Downloading (via git clone) libwebp_git from https://chromium.googlesource.com/webm/libwebp.git
Cloning into 'libwebp_git.tmp'...
remote: Total 26578 (delta 16812), reused 26578 (delta 16812)
Receiving objects: 100% (26578/26578), 17.79 MiB | 13.93 MiB/s, done.
Resolving deltas: 100% (16812/16812), done.
done git cloning to libwebp_git
doing git checkout origin/master
error: pathspec 'origin/master' did not match any file(s) known to git
HEAD is now at 607611cd Merge "webp-container-spec: normalize section title case" into main
error: pathspec 'origin/master' did not match any file(s) known to git
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Fix:
Code needs update as Google is now using "main" instead of "master":

build_libwebp() {
  local checkout_dir=libwebp_git
  do_git_checkout https://chromium.googlesource.com/webm/libwebp.git $checkout_dir "origin/main"
  cd libwebp_git
    export LIBPNG_CONFIG="$mingw_w64_x86_64_prefix/bin/libpng-config --static" # LibPNG somehow doesn't get autodetected.
    generic_configure "--disable-wic"
    do_make_and_make_install
    unset LIBPNG_CONFIG
  cd ..
}

**Comment by rdp** [comment]
all righty try latest #663
