### ISSUE TITLE
error when building curl

### ISSUE THREAD

**Issue by james28909** [rdp/ffmpeg-windows-build-helpers#664]
everything was going great until i got to building curl! not to sure what to do to mitigate this particular issue. please advise

[curl_log.txt](https://github.com/rdp/ffmpeg-windows-build-helpers/files/10176898/curl_log.txt)

p.s. am building with wsl2 20.04

edit: there is another error earlier in the build process that i also enountered from the last time i used this script. the error is in libtiff iirc, and the fix involves renaming a command in tiff's configure script. i think the command is _**mv**_ and it needs to be _**cp**_ as referenced here: [Github - libtiff](https://github.com/libffi/libffi/issues/552#issuecomment-766158672). but this looks like it could be a wsl error but i am not certain.

**Comment by rdp** [comment]
Do you have anything funky on your path like mingw or wine? ref: https://github.com/aseprite/aseprite/issues/2017

**Comment by james28909** [comment]
@rdp just to remind you i am building in wsl2 on latest 22h2 windows 11. i do have mingw on windows itself, but it doesnt have any environment variables set, the mingw compiler on my windows environment sets its own environment when i execute the batch file which sets any environment variables it needs per session. so there is no system or environment variables on my windows machine itself...

with that said, my wsl does not have mingw or wine installed as far as i can tell. doing a `sudo apt list --install | grep "^w"` or `sudo apt list --install "^w"` does not return any thing related to mingw or wine. 

the rest of it builds fine though, just when i get to curl it detonates lol

**Comment by rdp** [comment]
OK I bumped curl try it again?

**Comment by james28909** [comment]
failed configure:
```
...
...
checking dependency style of i686-w64-mingw32-gcc... gcc3
checking curl version... 7.86.0
configure: error: select TLS backend(s) or disable TLS with --without-ssl.

Select from these:

  --with-amissl
  --with-bearssl
  --with-gnutls
  --with-mbedtls
  --with-nss
  --with-openssl (also works for BoringSSL and libressl)
  --with-rustls
  --with-schannel
  --with-secure-transport
  --with-wolfssl

failed configure curl-7.86.0
```
should i try to build and install openssl from source using the paths for the cross compilers? or could i simply add `--with-openssl` to the script when it invokes curl configuration? please advise and thanks for taking the time to help!

**Comment by rdp** [comment]
that's odd thought I made it past that, pull and try again...

**Comment by james28909** [comment]
i am pretty sure it made it past that. will let you know

**Comment by rdp** [comment]
Seemed OK just now, feel free to reopen if not so, thank you for the report!
