### ISSUE TITLE
Latest version build breaks on nettle

### ISSUE THREAD

**Issue by rboy1** [rdp/ffmpeg-windows-build-helpers#67]
When trying to build ffmpeg using the latest script on ubuntu 14.01 it breaks with the following error while trying to build gnutls:

      *** Libnettle 2.7.1 was not found. Note that this version of gnutls doesn't support nettle 3.0.

**Comment by rdp** [comment]
hmm mine with 14.04 just built ok this morning, maybe nuke your
sandbox/win32/*nettle* folder and try again?

**Comment by rboy1** [comment]
That is wierd, I nuked the entire win32 folder and started from scratch. Nettle builds fine just that it stop on gnutls.

Any other ideas - I'm struck out :(

**Comment by rboy1** [comment]
Does it matter if I'm using a 3.5.8 mingw?

**Comment by rboy1** [comment]
Nope, I cleaned out sandbox totally and started out, still after rebuilding mingw it got stuck at the same place. urghhhh

**Comment by rboy1** [comment]
Not sure if this helps but this is the output

> configuring gnutls-3.3.9 (/home/mcebuddy/Software/ffmpeg/sandbox/win32/gnutls-3.3.9) as $ PATH=/home/mcebuddy/Software/ffmpeg/sandbox/mingw-w64-i686/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games ./configure --host=i686-w64-mingw32 --prefix=/home/mcebuddy/Software/ffmpeg/sandbox/mingw-w64-i686/i686-w64-mingw32 --disable-shared --enable-static --disable-cxx --disable-doc
checking build system type... x86_64-unknown-linux-gnu
checking host system type... i686-w64-mingw32
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for i686-w64-mingw32-strip... i686-w64-mingw32-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
***
*** Checking for compilation programs...
> 
checking for i686-w64-mingw32-pkg-config... /usr/bin/i686-w64-mingw32-pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for i686-w64-mingw32-gcc... i686-w64-mingw32-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether i686-w64-mingw32-gcc accepts -g... yes
checking for i686-w64-mingw32-gcc option to accept ISO C89... none needed
checking whether i686-w64-mingw32-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of i686-w64-mingw32-gcc... gcc3
checking how to run the C preprocessor... i686-w64-mingw32-gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for Minix Amsterdam compiler... no
checking for i686-w64-mingw32-ar... i686-w64-mingw32-ar
checking for i686-w64-mingw32-ranlib... i686-w64-mingw32-ranlib
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking for _LARGEFILE_SOURCE value needed for large files... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... 64
checking dependency style of i686-w64-mingw32-gcc... gcc3
checking for i686-w64-mingw32-ar... (cached) i686-w64-mingw32-ar
checking the archiver (i686-w64-mingw32-ar) interface... ar
checking for i686-w64-mingw32-g++... i686-w64-mingw32-g++
checking whether we are using the GNU C++ compiler... yes
checking whether i686-w64-mingw32-g++ accepts -g... yes
checking dependency style of i686-w64-mingw32-g++... gcc3
checking for bison... bison -y
checking for a sed that does not truncate output... /bin/sed
checking for autogen... /bin/true
configure: WARNING:
***
*** autogen not found. Will not link against libopts.
*** 
checking for inline... inline
checking for ANSI C header files... (cached) yes
checking cpuid.h usability... yes
checking cpuid.h presence... yes
checking for cpuid.h... yes
checking for NETTLE... no
configure: error: 
  ***
  *** Libnettle 2.7.1 was not found. Note that this version of gnutls doesn't support nettle 3.0.

**Comment by rboy1** [comment]
Not sure if this has any difference, I'm running x64 through VMWare Player, a fresh installation.

**Comment by rboy1** [comment]
Sorry i'm using 14.04

**Comment by rdp** [comment]
OK I just tried a fresh 14.10 and it worked OK
do you have a file
./sandbox/mingw-w64-i686/lib/libnettle.a

./sandbox/mingw-w64-i686/lib/pkgconfig/nettle.pc


what's your config.log of gnutls?

**Comment by rboy1** [comment]
I just cleaned out the OS with a fresh install of 14.04. Will only follow the script instructions. lets see

**Comment by rboy1** [comment]
well it worked now. linux is wierd
