### ISSUE TITLE
Install ffmpeg in WSL

### ISSUE THREAD

**Issue by arrmo** [rdp/ffmpeg-windows-build-helpers#670]
Hi,

Apologies if this is a dumb question 😞. Have checked the docs (and README), also -h, but ... not finding how to install ffmpeg after the build is complete => like `sudo make install` for "regular" ffmpeg.

Is there a way to do this, so the resulting binaries / libraries here become the default in WSL?

Thanks!

**Comment by FREEWING-JP** [comment]
Manually copy from sandbox directory .

**Comment by arrmo** [comment]
Yep, makes sense - or I may just add soft links (WSL). Thanks!
