### ISSUE TITLE
AMF Issues, Win64 vs. Native

### ISSUE THREAD

**Issue by arrmo** [rdp/ffmpeg-windows-build-helpers#671]
Hi,

Apologies up front, this may be me (not fully understanding) - sorry! But ... I am building with AMF included, both Win64 and Native - and building in WSL, make sure I mention that ... LOL. After making a minor AMF change (pull the latest official headers), the builds are both completing fine, but when I try to run them, both from WSL (ffmpeg for Native, ffmpeg.exe for Win64) ... Win64 works with AMF, but not Native. Rather, I get the error,
```
AMF failed to initialise on the given Vulkan device: 1.
```
Huh? 😜. Is it that even from WSL, the two builds pull different drivers? I have installed (within WSL) the amdgpu needed shared libraries, but this is the next roadblock. Again, wondering if it's a Native vs. Win64 issue, and how drivers are accessed.

Likely me just being dumb, but if this the issue (Native vs. Win64) - perhaps mention this in the README somewhere? Just a thought.

Thanks!

**Comment by FREEWING-JP** [comment]
In your question, you should write
* your execution environment
* execution procedure
* error output content
 so that others can understand.

**Comment by arrmo** [comment]
Sorry, my bad! This is all from WSL. If I build both Native and Win64 ... only Win64 (ffmpeg.exe) works, not Native (ffmpeg, no .exe) - and again, from WSL. If I try to run the Native version, I get errors related to Vulkan. Thinking that Win64 and Native use / call different drivers somehow? I admit, as I'm building and running (both) from WSL, I'm not quite sure how Win64 is different from Native 😞 

Make sense?

Thanks!

**Comment by arrmo** [comment]
Sorry, cycling back to this, as with recent WSL updates, it seems that I can't even run the output `ffmpeg.exe` - does that make sense? When I mount the output directory `ffmpeg-windows-build-helpers\sandbox\win64\ffmpeg_git_with_fdk_aac`), and then try to run `ffmpeg.exe` from WSL, I get,
```
-bash: ./ffmpeg.exe: cannot execute binary file: Exec format error
```
Does that make any sense?

The build I did is,
```
./cross_compile_ffmpeg.sh --gcc-cpu-count=16 --disable-nonfree=n --compiler-flavors=win64
```
And I did check (in WSL),
```
$ file ffmpeg.exe
ffmpeg.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```
Thanks!

**Comment by arrmo** [comment]
Never mind! Found it 😆. To help others, this is due to running `systemd` ... it breaks WSL Interop. The fix is [here](https://github.com/microsoft/WSL/issues/8952#issuecomment-1272176985).

Thanks!
