### ISSUE TITLE
Some kind of error... Need help...

### ISSUE THREAD

**Issue by newcapricasean** [rdp/ffmpeg-windows-build-helpers#674]
-DCMAKE_INSTALL_DATAROOTDIR=/home/newcapricasean/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/newcapricasean/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/newcapricasean/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for include file endian.h
-- Looking for include file endian.h - not found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Checking for one of the modules 'glib-2.0'
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.10.6", minimum required is "3")
Python 3.10.6
-- -------------------------------------------------------------------------------------
-- Building Lensfun 0.3.95.0
-- -------------------------------------------------------------------------------------
-- Build as static library
-- Build type: Debug
-- Build doc: OFF
-- Build test suite: OFF
-- Build lenstool: OFF
-- Build with support for SSE: OFF
-- Build with support for SSE2: OFF
-- Install helper scripts: ON
--
Install prefix: /home/newcapricasean/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
--
Using:
-- GLIB2 include dir: /home/newcapricasean/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/glib-2.0;/home/newcapricasean/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/glib-2.0/include
-- GLIB2 library: glib-2.0;intl;ws2_32;winmm;m;iconv;ole32
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ENABLE_STATIC_RUNTIME

-- Build files have been written to: /home/newcapricasean/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git

Making /home/newcapricasean/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git as $ PATH=/home/newcapricasean/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH make  -j 64

[  6%] Generating build/timestamp
[ 12%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/camera.cpp.obj
[ 18%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/database.cpp.obj
[ 25%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/lens.cpp.obj
[ 31%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-coord-sse.cpp.obj
[ 37%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-coord.cpp.obj
[ 56%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-pc.cpp.obj
[ 62%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-color-sse.cpp.obj
[ 62%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/cpuid.cpp.obj
[ 62%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mount.cpp.obj
[ 81%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-subpix.cpp.obj
[ 81%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/modifier.cpp.obj
[ 81%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/auxfun.cpp.obj
[ 87%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-color.cpp.obj
[ 93%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-color-sse2.cpp.obj
Traceback (most recent call last):
  File "/home/newcapricasean/ffmpeg-windows-build-helpers/sandbox/win64/lensfun_git/apps/setup.py", line 6, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'
make[2]: *** [apps/CMakeFiles/python-package.dir/build.make:74: apps/build/timestamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:157: apps/CMakeFiles/python-package.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX static library liblensfun.a
[100%] Built target lensfun
make: *** [Makefile:156: all] Error 2
newcapricasean@NEW_BEGINNINGS:~/ffmpeg-windows-build-helpers$

**Comment by stickman561** [comment]
Make sure you have setuptools installed with Python 3. I had to install pip and setuptools was installed alongside it.
`sudo apt install python3-pip` Solved it for me on Ubuntu 22.04.1 LTS.

**Comment by newcapricasean** [comment]
Okie dokie... I tried that, but now it's telling me the following...

>>>
Could not find the following execs (svn is actually package subversion, makeinfo is actually package texinfo if you're missing them): libtoolize cmake python clang meson autogen gperf nasm unzip pax makeinfo bison flex cvs yasm automake autoconf svn pkg-config ragel
Install the missing packages before running this script.
for ubuntu:
$ sudo apt-get update
$ sudo apt-get install subversion ragel curl texinfo g++ ed bison flex cvs yasm automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev unzip pax nasm gperf autogen bzip2 autoconf-archive p7zip-full meson clang python3-distutils python-is-python3 -y
NB if you use WSL Ubuntu 20.04 you need to do an extra step: https://github.com/rdp/ffmpeg-windows-build-helpers/issues/452
newcapricasean@NEW_BEGINNINGS:~/ffmpeg-windows-build-helpers$
<<<

Okay... I did what it told me, there, and it worked! Now, I get to test out the build!

**Comment by newcapricasean** [comment]
Well, there is one major problem, for me, and that is that the build doesn't include the non-free libfdk... Fraunhofer AAC audio encoder... Which was the whole reason I wanted to compile my own FFMPEG... Is there a way to modify the script to include exactly what libraries I want compiled into the FFMPEG?

**Comment by stickman561** [comment]
Pretty sure nonfree builds are disabled by default. Make sure to enable nonfree during your configuration.
