### ISSUE TITLE
Build fails with "ERROR: amf requested but not found"

### ISSUE THREAD

**Issue by nschlia** [rdp/ffmpeg-windows-build-helpers#677]
Since rev. 2b392ad5afc305d45fb35321ca32d9f904771fc7 , the build fails with "ERROR: amf requested but not found". I installed the AMF headers as in https://ffmpeg.org/general.html#AMD-AMF_002fVCE, but to no avail.

I am cross compiling under Debian 11 (bullseye).

Build command:

./cross_compile_ffmpeg.sh --disable-nonfree=n --sandbox-ok=y --compiler-flavors=multi  --build-ffmpeg-static=n --build-ffmpeg-shared=y

Here the last lines of the log:

`
22:30:36 all touch files already_configured* touchname= already_configured_ca72159259d800d57a58a8abcb9d7331-
22:30:36 config options --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86 --target-os=mingw32 --cross-prefix=/var/lib/jenkins/workspace/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-gnutls --enable-libaom --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-shared --disable-static --prefix=/var/lib/jenkins/workspace/ffmpeg-windows-build-helpers/sandbox/win32/ffmpeg_git_with_fdk_aac_shared --enable-nonfree --enable-libfdk-aac --enable-decklink ./configure
22:32:09 ERROR: amf requested but not found
`
Sorry, I am at a loss... What can I do now?

**Comment by nschlia** [comment]
Additional info: I was able to successfully build by adding the parameter --build-amd-amf=n. But from the script code I suppose it should automatically download and install the AMF headers.

**Comment by rdp** [comment]
that's weird, was it a recent build? does amf_headers_git exist?

**Comment by nschlia** [comment]
> that's weird, was it a recent build? 

Yes. I am always using the latest build (you commits trigger a Jenkins build which pulls the current version)

> does amf_headers_git exist?

Yup.
```
$ ll */amf_headers_git
win32/amf_headers_git:
insgesamt 16K
-rw-r--r-- 1 jenkins jenkins    0  9. Dez 16:54 already_installed
drwxr-xr-x 4 jenkins jenkins 4,0K  9. Dez 16:54 amf
drwxr-xr-x 8 jenkins jenkins 4,0K 19. Feb 21:40 .git
-rw-r--r-- 1 jenkins jenkins 1,8K  9. Dez 16:54 LICENSE.txt
-rw-r--r-- 1 jenkins jenkins 2,7K  9. Dez 16:54 README.md

win64/amf_headers_git:
insgesamt 16K
-rw-r--r-- 1 jenkins jenkins    0  9. Dez 17:51 already_installed
drwxr-xr-x 4 jenkins jenkins 4,0K  9. Dez 17:51 amf
drwxr-xr-x 8 jenkins jenkins 4,0K 23. Dez 11:20 .git
-rw-r--r-- 1 jenkins jenkins 1,8K  9. Dez 17:51 LICENSE.txt
-rw-r--r-- 1 jenkins jenkins 2,7K  9. Dez 17:51 README.md
```

**Comment by MI2-2** [comment]
I got the same error when building n6.0.

`ERROR: amf requested but not found
`

**Comment by rdp** [comment]
Thanks for the fix description :)
