### ISSUE TITLE
rav1e >= 0.5.0 not found using pkg-config

### ISSUE THREAD

**Issue by stickman561** [rdp/ffmpeg-windows-build-helpers#678]
I saw in previous patches that librav1e was supported, however when I enable the flag in cross_compile_ffmpeg.sh I get "rav1e >= 0.5.0 not found using pkg-config"

I noticed that the library doesn't seem to be getting built in the current version, though many precompiled versions have it, so I made a helper method in my cross_compile_ffmpeg.sh file (though I'm not really sure what I'm doing) with the following block added (and called alongside the others during the build):

`build_librav1e() {
  do_git_checkout https://github.com/xiph/rav1e.git librav1e_git
  cd librav1e_git
  RUSTFLAGS="-C target-cpu="$host_target cargo build --release
  RUSTFLAGS="-C target-cpu="$host_target cargo cinstall --release
  cd ..
}`

If I run `pkg-config --modversion rav1e` from the Terminal, I get 0.6.1 as my output. However the build still fails with the same error message. Does anyone know what I'm doing wrong or if there's a better supported way to get the library?

**Comment by rdp** [comment]
check ffbuild/config.log?

**Comment by stickman561** [comment]
For the sake of consistency, I removed all customizations from the cross_compile_ffmpeg.sh file and built rav1e manually. rav1e.pc exists on the PKG_CONFIG_PATH with version 0.6.1. I also manually copied it into the ffmpeg/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig folder. Still the same error though.

As requested, here is my FFBuild Log: [https://pastebin.com/W2L2f6C6](url)

Due to the character limit on PasteBin, I had to compress the log file. You can decompress it using [http://www.unit-conversion.info/texttools/compress/](url)

**Comment by stickman561** [comment]
Closing since this was an attempt to add a custom parameter that looks like it's doomed to fail. If anything this might be more suited to a feature request.

**Comment by stickman561** [comment]
Closing issue since this was technically a request for help adding a new feature. If anything it would be better suited as a suggestion.
