### ISSUE TITLE
Heavy output build on Windows

### ISSUE THREAD

**Issue by RobinFrcd** [rdp/ffmpeg-windows-build-helpers#689]
Hi,
I successfully managed to compile a minimal standalone FFmpeg binary to create MP4 videos from JPG images encoded with x264. The binary is 100% functional and is **5.2MB**.

To do that, I used:
```bash
./configure \
--disable-everything \
--enable-decoder=mjpeg \
--enable-encoder=libx264 \
--enable-protocol=concat,file \
--enable-demuxer=image2 \
--enable-muxer=mp4 \
--enable-filter=scale \
--enable-gpl \
--enable-libx264 \
--extra-ldexeflags="-static" \
--pkg-config="pkg-config --static"
```

I now would like to build the macOS and windows binaries directly from my Linux machine. I tried the [quick_cross_compile_ffmpeg_fdk_aac_and_x264_using_packaged_mingw64][1] script and replaced the config args with mine, but the output exe is 30MB+.  Is there any reason why the windows build is 6x bigger than the linux one ?

Thanks

  [1]: https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/quick_build/quick_cross_compile_ffmpeg_fdk_aac_and_x264_using_packaged_mingw64.sh#L86

**Comment by rdp** [comment]
What does the ffmpeg.exe output look like?

**Comment by RobinFrcd** [comment]
Here's the output

```
Z:\>ffmpeg.exe
ffmpeg version git-2023-03-08-aca7ef7 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20220113
  configuration: --enable-gpl --enable-libx264 --enable-nonfree --enable-debug=3 --disable-optimizations --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --prefix=/home/robz/dev/tools/ffmpeg-windows-build-helpers/sandbox_quick/win64/quick_install/install_root/ffmpeg_simple_installed
  libavutil      58.  3.100 / 58.  3.100
  libavcodec     60.  6.100 / 60.  6.100
  libavformat    60.  4.100 / 60.  4.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  4.100 /  9.  4.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Hyper fast Audio and Video encoder
```

**Comment by rdp** [comment]
Disable optimizations make a difference?

On Friday, March 17, 2023, Robin Fourcade ***@***.***> wrote:
> Here's the output
>
> Z:\>ffmpeg.exe
> ffmpeg version git-2023-03-08-aca7ef7 Copyright (c) 2000-2023 the FFmpeg
developers
> built with gcc 10-win32 (GCC) 20220113
> configuration: --enable-gpl --enable-libx264 --enable-nonfree
--enable-debug=3 --disable-optimizations --arch=x86_64 --target-os=mingw32
--cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config
--prefix=/home/robz/dev/tools/ffmpeg-windows-build-helpers/sandbox_quick/win64/quick_install/install_root/ffmpeg_simple_installed
> libavutil 58. 3.100 / 58. 3.100
> libavcodec 60. 6.100 / 60. 6.100
> libavformat 60. 4.100 / 60. 4.100
> libavdevice 60. 2.100 / 60. 2.100
> libavfilter 9. 4.100 / 9. 4.100
> libswscale 7. 2.100 / 7. 2.100
> libswresample 4. 11.100 / 4. 11.100
> libpostproc 57. 2.100 / 57. 2.100
> Hyper fast Audio and Video encoder
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.<
https://ci4.googleusercontent.com/proxy/3CulxI3ZyLjCx1CJf2O-vLLogXYPMePYjVQADGHVOiFehkF5-n_hkkqalGJ99ZP09CupLs-6Y3p5GS-YJu5vrGtFiOvu_H6ICthSyz3D9oN7JxVkZ93pFvvs_LYW73jroCGWCa_XhUzQQby7JdzA1-B9BLPXFQTbtC_OFV22nak_e2NHPiBdW1s5PK1193yjCKS3gNtA-XrMFaJArI5kzjkJTLQHtnIfCgto5nkJOmrN9aQsgw=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUCMEYRUPXGOQGOUOY3W4RHPXA5CNFSM6AAAAAAVVMZKTWWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSX25OXQ.gif>Message
ID: ***@***.***>

**Comment by rdp** [comment]
It's not in your linux build?

**Comment by RobinFrcd** [comment]
Oh, I tried to fully delete the `sandbox_quick` folder and now it works ! `3.9MB` is far better ! 
I guess I had some cache from the previous run.

Thanks for your help !

**Comment by rdp** [comment]
So same configure settings?

On Monday, March 20, 2023, Robin Fourcade ***@***.***> wrote:
> Oh, I tried to fully delete the sandbox_quick folder and now it works !
3.9MB is far better !
> I guess I had some cache from the previous run.
>
> Thanks for your help !
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci4.googleusercontent.com/proxy/tezuQCPKwS5OD7akEFPSp75bWhWzBsCb4AQ_2Ind-wmsLMOh5jb0gS_z7w-SwKoUp8mFwC628l4JP6ZanLEcZ0VjTjkTvwOHvXCHHW5coswNB98NqpN__s--mL3b50o1DLhOLaKn5SjPn8qJJ2WglaWdpTeulfKP7cqpxlnlAQa7ZcBrhsxTuyFjrE8oHW2XBEw5B9geuPgE5oYf7oDrRCLxFf1lHFuSsMiv2dWAuXvsxixMfQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUB5P5NHD3PQDMTOSSLW5CFTDA5CNFSM6AAAAAAVVMZKTWWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSYAOD56.gif>Message
ID: ***@***.***>

**Comment by RobinFrcd** [comment]
Yes, actually it's 4.4MB with this. And 3.9MB if I add `--enable-small`

```
cd $ffmpeg_dir
  # not ready for this since we don't reconfigure after changes: # git pull
  if [[ ! -f ffbuild/config.mak ]]; then
    # shouldn't really ever need these?
    ./configure --disable-everything \
      --enable-decoder=mjpeg \
      --enable-encoder=libx264 \
      --enable-protocol=concat,file \
      --enable-demuxer=image2 \
      --enable-muxer=mp4 \
      --enable-filter=scale \
      --enable-gpl \
      --enable-libx264 \
      --extra-ldexeflags="-static" \
      --pkg-config="pkg-config --static" \
      --arch=$arch --target-os=mingw32 \
      --cross-prefix=$host- --pkg-config=pkg-config --prefix=$prefix/ffmpeg_simple_installed || exit 1
  fi
  rm **/*.a # attempt force a kind of rebuild...
  make -j$cpu_count && make install && echo "done installing it $prefix/ffmpeg_simple_installed"
cd ..
```
