### ISSUE TITLE
high-bitdepth=y doesn't cause x265 to be rebuilt

### ISSUE THREAD

**Issue by kaefert** [rdp/ffmpeg-windows-build-helpers#69]
Hi there!

First: Thanks for this really nicely done build script, really easy to produce a ffmpeg windows binary with it.

Now to what I've experienced: when first running your script without any options, and afterwards trying to rebuild with the `high-bitdepth=y` parameter set it detects that it needs to run cmake again but somehow the old x265 binaries still stick around, and get reused.

I was able to work around the issue by manually browsing to `sandbox/x86_64/x265/source/` and calling `make clean`, and deleting all the already_ran_make_* files before running your script again (with the `high-bitdepth=y` parameter set)

**Comment by rdp** [comment]
good find, hopefully fixed, give it  whirl, thanks!
