### ISSUE TITLE
IMPORTED_IMPLIB not set for imported target "SDL2::SDL2"

### ISSUE THREAD

**Issue by mysteryx93** [rdp/ffmpeg-windows-build-helpers#691]
Running the script on Linux to build for Win64 gives me this error

```
VGM/GYM: Nuked OPN2 emulator will be used
** ZLib library located, compressed file formats will be supported
** SDL 2 library located, player demo is available to be built in the /player directory
-- Configuring done
CMake Error in player/CMakeLists.txt:
IMPORTED_IMPLIB not set for imported target "SDL2::SDL2".
```

How can I get past that?

OS: Garuda Linux (arch-based)

**Comment by mysteryx93** [comment]
I flushed the Sandbox folder and tried again with the default script. Got the same error.

For Win32, got this error

> make: *** [config/common_make_rules:133: build/i386-mingw32/obj//.make_build_dirs] Error 2

**Comment by rdp** [comment]
Which OS/environment?

**Comment by mysteryx93** [comment]
Garuda Linux (arch-based)

**Comment by rdp** [comment]
Hmm does the docker version work?  Maybe it's an arch thing?

**Comment by mysteryx93** [comment]
Dunno. Ended up commenting most builds in the script; I wanted a minimal build for muxing only. Got it done.

2.9mb ffmpeg

I don't need to get broken packages to work after all; but I'm curious why that fails.

**Comment by rdp** [comment]
Feel free to dive in, PR's welcome :)
