### ISSUE TITLE
[Feature Request] add `--enable-libaribcaption` flag (or replace the `--enable-libaribb24` by it)

### ISSUE THREAD

**Issue by li-yifei** [rdp/ffmpeg-windows-build-helpers#693]
Hello rdp, recently I found that `libaribcaption` is merged into ffmpeg master branch, and I would like to promote this library that's able to convert the arib subtitle format (which is widely used in Japan DTB streaming) into well formed ASS or bitmaps.

I've made some local changes to build both x64 and linux native binaries with this flag, will PR soon if you would like to.

### Backgrounds
- [libaribcaption](https://github.com/xqq/libaribcaption)
- [ffmpeg commit](https://github.com/FFmpeg/FFmpeg/commit/b6138633cdf2ecae22c4c02029e91245c430c4fe)

### Yet to be checked
- [x] Win32 capability
- [ ] WinXP capability (?)
- [ ] To replace `--enable-libaribb24` or not to (can be both enabled, and libaribcaption will be the default arib parser)

**Comment by rdp** [comment]
Was this closed?
