### ISSUE TITLE
libmysofa 

### ISSUE THREAD

**Issue by cherrynechou** [rdp/ffmpeg-windows-build-helpers#696]
sudo ./cross_compile_ffmpeg.sh --build-ffmpeg-static=y --build-ffmpeg-shared=y --ffmpeg-git-checkout-version=n4.2.9 --disable-nonfree=n --enable-gpl=y

![QQ浏览器截图20230524131025](https://github.com/rdp/ffmpeg-windows-build-helpers/assets/4892608/fd90f036-7d08-4182-93e4-efb282259b7f)

**Comment by rdp** [comment]
Does it work with newer ffmpeg versions?

**Comment by cherrynechou** [comment]
> Does it work with newer ffmpeg versions?

use old ffmpeg versions?I use old version test

**Comment by rdp** [comment]
probably remove the --enable-libmysofa option if you want older...

**Comment by rdp** [comment]
Closing no response...
