### ISSUE TITLE
Multiple libraries (libbluray, fontconfig, freetype) can't be found in pkg-config

### ISSUE THREAD

**Issue by stickman561** [rdp/ffmpeg-windows-build-helpers#697]
Totally clean system install and fresh pull from git less than 2 hours ago. No other previous files on machine. Running Ubuntu 23.04. Build fails with "ERROR: libbluray not found in pkg-config". Disabling libbluray causes fail with "ERROR: fontconfig not found in pkg-config". Same with freetype. Tried manually installing each package using apt to no avail.
Edit: Forgot to mention, running 64-bit only build. (Option 3)

**Comment by insomnimus** [comment]
I've been having this problem as well.

**Comment by Biswa96** [comment]
Please try to look into the config.log file in the build directory. It may provide some hints why those libraries can't be found.

**Comment by stickman561** [comment]
Build worked perfectly fine on version 22.04. Seems version 23.04 breaks those particular libraries for some reason. Perhaps something that should be looked into, but for now that seems to be the workaround for anyone experiencing the error.
