### ISSUE TITLE
fatal: https://github.com/dlfcn-win32/dlfcn-win32.git/info/refs download error - The requested URL returned error: 403

### ISSUE THREAD

**Issue by misses-proper** [rdp/ffmpeg-windows-build-helpers#70]
Hi there,

I am trying to crosscompile ffmpeg with your script, but running into this error: 

fatal: https://github.com/dlfcn-win32/dlfcn-win32.git/info/refs download error - The requested URL returned error: 403

I can not see exactly where this url is needed (and what for), so i do not dare to change the script to make it run.

Thanks for any help!
Ruth

**Comment by rdp** [comment]
What git version are you running?

**Comment by misses-proper** [comment]
apparently git version 1.6.0.2 (answer for  'git --version).

**Comment by rdp** [comment]
could you try a newer git version for me by chance?

**Comment by misses-proper** [comment]
sorry, it is the latest available in my repositories...

**Comment by misses-proper** [comment]
found remedy. currently trying with git version 2.3.3....

**Comment by misses-proper** [comment]
did it! running into a new error though... i'll open a new issue for that one, ok? thanks a lot.

**Comment by rdp** [comment]
glad it worked
