### ISSUE TITLE
win64 build fails on Ubuntu server 22.04

### ISSUE THREAD

**Issue by pjt-15e** [rdp/ffmpeg-windows-build-helpers#705]
This issue may be related to #703 and #704 as the failure is the same but in this case the operating system is "real" Ubuntu server 22.04 and not the WSL version.  This is using "./cross_compile_ffmpeg.sh" either directly in bash or via the docker version.

I've done some digging through the logs and it appears to me that the failure may be due to the x264 win64 build output, but I'm only a beginner at understanding the Linux compile / make process so perhaps I'm wrong.

Cross compiling a win32 version of ffmpeg.exe, etc., using "./cross_compile_ffmpeg.sh" appears to work, as does "./quick_cross_compile_ffmpeg_fdk_aac_and_x264_using_packaged_mingw64.sh"

**Comment by rdp** [comment]
Does it still fail?

**Comment by pjt-15e** [comment]
I used the script last night and appear to have a win64 successful build.  I didn't use any command line options, only selecting to build win64 when prompted by the script.

Thanks for fixing.
