### ISSUE TITLE
ERROR: nvenc requested but not found

### ISSUE THREAD

**Issue by xengine-qyt** [rdp/ffmpeg-windows-build-helpers#708]
fitst error:unknow option --enable-libaribcaption
delete config_options+=" --enable-libaribcaption" # libaribcatption (MIT licensed) in cross_compile_ffmpeg.sh 
/cross_compile_ffmpeg.sh --build-ffmpeg-shared=y --build-ffmpeg-static=n --ffmpeg-git-checkout-version=n5.1.3

tips:ERROR: nvenc requested but not found

fetched no code changes, not forcing reconfigure for that...
configuring ffmpeg_git_n5.1.3_shared (/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/win32/ffmpeg_git_n5.1.3_shared) as $ PKG_CONFIG_PATH=/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/pkgconfig PATH=/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin:$PATH ./configure --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86 --target-os=mingw32 --cross-prefix=/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg  --enable-libopenh264  --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm  --enable-gnutls --enable-libvpx --enable-libaom --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-shared --disable-static --prefix=/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/win32/ffmpeg_git_n5.1.3_shared 
all touch files already_configured* touchname= already_configured_552a06495c01f4120aa496a5ad8e1e58-
config options --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86 --target-os=mingw32 --cross-prefix=/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-gnutls --enable-libvpx --enable-libaom --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs --extra-cflags=-mtune=generic --extra-cflags=-O3 --enable-shared --disable-static --prefix=/home/ubuntu/ffmpeg-windows-build-helpers/sandbox/win32/ffmpeg_git_n5.1.3_shared ./configure
ERROR: nvenc requested but not found

**Comment by rdp** [comment]
you could check ffbuild/config.log if you want, but it may be some weird version discrepancy, I'd say just manually remove --enable-nvenc for now, good luck!

**Comment by xengine-qyt** [comment]
is this nvidia encoder ?if i remove it.then nvidia coder does not enable?

**Comment by rdp** [comment]
It's an older nvidia encoder nobody uses anymore...

**Comment by JoshJarabek7** [comment]
> I have the same problem, I get `ERROR: nvenc requested but not found` when trying to compile ffmpeg 4.3.x or 5.1.x with `--enable-nvenc`. What API should I use instead of NVENC? I don't see any deprecation of NVENC in NVidia docs.

Did you ever figure this out? I'm unsure of what else I'd use in 6.0 to have NVIDIA accelerated encoding...

**Comment by rdp** [comment]
it should work with 6.0?
I'm guessing with earlier versions you'd need an earlier versions of nvenc?
