### ISSUE TITLE
avisynth not building and libgme.dll required in output

### ISSUE THREAD

**Issue by KonajuGames** [rdp/ffmpeg-windows-build-helpers#71]
Fresh Ubuntu 14.10 64-bit in a Hyper-V instance.
Installed all suggested packages using `sudo apt-get`.
Building for Windows 64-bit with non-free packages.

`avisynth` fails to build due to compile errors.  Not wanting to dive into their code to fix it, this was easily worked around by removing `--enable-avisynth` from script and running it again.

Now the cross-compile succeeds.  Copy the executables to the Windows box.

Even though it is built as a static executable, `ffmpeg.exe` requires `libgme.dll` which is not copied to `sandbox/x86_64/ffmpeg_git`.  It can be found in `sandbox/x86_64/game-music-emu-0.6.0`.

Aside from those minor issues, many thanks for this wonderful script. It took a long time to build, but it was magnitudes quicker and far less stressful than if I had tried to build it myself.  This is how cross-compile should be done.  Great job.

**Comment by rdp** [comment]
OK fixed GME and disabled avisynth until they get their act together.  You may need to delete your find . -name libgme*dll*a files

**Comment by KonajuGames** [comment]
Thanks for the quick response. Much appreciated.

**Comment by Warblefly** [comment]
Compiling AviSynth+ from latest source (64-bit, VC2013) and marrying it
with FFmpeg from latest source (64-bit, gcc-4.9.2) now works without
trouble as far as I can test this evening, Saturday 28th March. This is
using a fairly complex AviSynth script.

If anyone wants my AviSynth binary and plugins (recent versions of the
64-bit version are hard to find), please go here:

https://github.com/Warblefly/multimediaWin64/tree/master/AviSynth%2B%20x64%20binaries



On Wed, Mar 25, 2015 at 4:19 PM, KonajuGames <notifications@github.com>
wrote:

> Thanks for the quick response. Much appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rdp/ffmpeg-windows-build-helpers/issues/71#issuecomment-86102394>
> .
>



-- 
t: 07964 588487 (011447964588487 from the USA)
Skype: josephratzinger
