### ISSUE TITLE
Multiple libraries (libbluray, fontconfig, freetype) can't be found in pkg-config

### ISSUE THREAD

**Issue by SmoochySix4** [rdp/ffmpeg-windows-build-helpers#710]
When the script hits the build_ffmpeg section, pkg-config can't find libbluray. After removing --enable-libbluray, it then can not find fontconfig. After removing --enable-fontconfig, it can't find freetype.

System Information:
`Linux DebDev 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux`
[config.log](https://github.com/rdp/ffmpeg-windows-build-helpers/files/12509470/config.log)

**Comment by nschlia** [comment]
Any progress on this one? I also can't build for 2 months now.

**Comment by nschlia** [comment]
[Build.log](https://github.com/rdp/ffmpeg-windows-build-helpers/files/13276370/Build.log)

Still no way. Can't build. The pc file is clearly there.

prefix=/var/lib/jenkins/workspace/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libbluray
Description: library supporting Blu-ray playback
Version: 1.3.4
Libs: -L${libdir} -lbluray
Libs.private:   -lgdi32
Requires.private:  libxml-2.0 >= 2.6 freetype2
Cflags: -I${includedir}

Would it be possible to disable these libraries optionally? I could get by without. But so far I could not build for amost half a year now.

**Comment by nschlia** [comment]
I have deleted sandbox several times and rebuild. All up to the same result. libbluray not found.

**Comment by rdp** [comment]
What does ffbuild/config.log say at the bottom?  I only test in Ubuntu
usually FWIW...

**Comment by nschlia** [comment]
> What does ffbuild/config.log say at the bottom? I only test in Ubuntu usually FWIW...

```
/var/lib/jenkins/workspace/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld: /var/lib/jenkins/workspace/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/libharfbuzz.a(libharfbuzz_la-hb-ft.o):/var/lib/jenkins/workspace/ffmpeg-windows-build-helpers/sandbox/win32/harfbuzz_git/src/hb-ft.cc:1306: undefined reference to `FT_Get_MM_Var'
/var/lib/jenkins/workspace/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld: /var/lib/jenkins/workspace/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/lib/libharfbuzz.a(libharfbuzz_la-hb-ft.o): in function `hb_ft_font_changed':
/var/lib/jenkins/workspace/ffmpeg-windows-build-helpers/sandbox/win32/harfbuzz_git/src/hb-ft.cc:1312: undefined reference to `FT_Get_Var_Blend_Coordinates'
/var/lib/jenkins/workspace/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld: /var/lib/jenkins/workspace/ffmpeg-windows-build-helpers/sandbox/win32/harfbuzz_git/src/hb-ft.cc:1331: undefined reference to `FT_Done_MM_Var'
collect2: error: ld returned 1 exit status
ERROR: libbluray not found using pkg-config

```
Here's the complete log:
[config.log](https://github.com/rdp/ffmpeg-windows-build-helpers/files/13307981/config.log)

**Comment by nschlia** [comment]
I use Debian:
```

Distributor ID: Debian                                                                                                                                                
Description:    Debian GNU/Linux 12 (bookworm)                                                                                                                        
Release:        12                                                                                                                                                    
Codename:       bookworm                                                                                                                                              
```

**Comment by rdp** [comment]
I am not sure what the issue is, maybe could try a docker?

**Comment by hydra3333** [comment]
Interestingly, the first few link errors in config.log are along the lines
```
/home/richard/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /home/richard/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x58f6): undefined reference to `png_create_read_struct'
/home/richard/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /home/richard/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x590b): undefined reference to `png_create_info_struct'
/home/richard/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: /home/richard/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0x592e): undefined reference to `png_set_longjmp_fn'
```

followed by issues with harfbuzz etc
sort of suggesting something in that arena.

Cheers

**Comment by SmoochySix4** [comment]
Re-opening as the issue is still present in Debian.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

**Comment by SolenoidMan** [comment]
Can confirm, ERROR: libbluray not found using pkg-config occurs with a brand new Ubuntu install. Tried several recent versions of Ubuntu as well as Debian, the libblurray error occurs on every environment I test it on.

**Comment by rdp** [comment]
I just had it work on Ubuntu WSL?

**Comment by Anacondo** [comment]
Confirmed: it's working perfectly on WSL Ubuntu, but for some reason it's broken on Debian 12 (non-WSL)

**Comment by bigdude9** [comment]
Also fails this way in openSuse. Any ideas ?

**Comment by bigdude9** [comment]
Several dev sites I visited mentioned that pkg-config does not follow symlinks. the png library went to creating a 32 and 64 bit pc file and using a symlink to set one as primary. As a result pkg-conf does not find the png library when trying to link the test for libbluray which uses then png library (a dependency).. not sure why gnutls failed when I replaced the link with a file, but the gnutls problem was also a pkg-conf failure so I will look for any symlinks that may use..

**Comment by bigdude9** [comment]
Beyond the symlink problem I found that the test for bluray is also failing due to recursive dependencies within the libraries used in the generated link command. There are two solutions, but I'm not certain how to embed them in the build system. The most flexible solution is to precede the library list with -Wl,--start_group and follow it with -Wl,--end-group so that ld will recurse on its own. That is the solution that is probably most easily integrated into the build system. The second solution is to repeat several of the libraries png, bz2, and freetype. Does anyone here know the build helpers well enough to know where to add linker commands to its generation templates ?

**Comment by rdp** [comment]
A funky version of ld?

**Comment by bigdude9** [comment]
I'm rooting around, but it looks like it may be that some subcomponents do not have exec_prefix set and end up using the platform installed cross tools rather than the ones built from scratch. gnutls for example seemed to call mingw ranlib out of /usr/bin and failed because it was a relative symlink rather than a file (seems like a shockingly bad idea). Chances are if the cross tools built by the script were installed on the host platform this kind of thing would be completely masked. That said, how could the cross tools built by the script be fully installed into host ?

**Comment by bigdude9** [comment]
Failed on OpenSuse, failed on WSL-Debian, but seems to work fine on WSL-Ubuntu. For now I gave up on the other platforms for building, but maybe adding export PGK_CONFIG_PATH .. to the build script would help with the library issues on other platforms ? Any advice on getting VLC player to build ?

**Comment by jam365** [comment]
I managed to make a [win64 build](https://github.com/jam365/ffmpeg-windows-build-helpers) work on a couple of WSL distros Ubuntu 23.10, Debian 12 (bookworm), Ubuntu 22.04 also builds fine although I can confirm it was working before. 

It required changing the script that builds the mingw-w64 to one that builds gcc v13.2.0, that newer gcc made me have to update some libraries like libsrt, libtesseract and freetype2.

Another change is in build_harfbuzz(), almost at the end I commented these two lines:
`#sed -i.bak 's/-lfreetype.*/-lfreetype -lharfbuzz -lpthread/' "$PKG_CONFIG_PATH/freetype2.pc" # for some reason it lists harfbuzz as Requires.private only??`
`#sed -i.bak 's/-lharfbuzz.*/-lharfbuzz -lfreetype/' "$PKG_CONFIG_PATH/harfbuzz.pc" # does anything even use this?`

Those two commented lines are the ones that got rid of the "libbluray not found using pkg-config" error.

The build command line I'm using is:
`./cross_compile_ffmpeg.sh --gcc-cpu-count=$(nproc) --disable-nonfree=n --compiler-flavors=win64`

May be someone can test this [forked ](https://github.com/jam365/ffmpeg-windows-build-helpers) branch and if it works fine for you too we can work on a pull request to bring the changes here.

**Comment by SmoochySix4** [comment]
Thanks for the fixes on Ubuntu, but they are still not working on Arch Linux. Not sure where the problem would be with that as setting PKG_CONFIG_PATH to the location and listing all the libraries shows that they are, indeed, installed and pkg-config sees them. Other than that, when ffmpeg configure runs, those three fail to be found. Would compiling a version of pkg-config that has the correct path hardcoded to the tool, and setting pkg-config to equal the newly compiled tool, help ffmpeg detect the libraries on systems that are not Debian/Ubuntu?

**Comment by SmoochySix4** [comment]
> I managed to make a [win64 build](https://github.com/jam365/ffmpeg-windows-build-helpers) work on a couple of WSL distros Ubuntu 23.10, Debian 12 (bookworm), Ubuntu 22.04 also builds fine although I can confirm it was working before.
> 
> It required changing the script that builds the mingw-w64 to one that builds gcc v13.2.0, that newer gcc made me have to update some libraries like libsrt, libtesseract and freetype2.
> 
> Another change is in build_harfbuzz(), almost at the end I commented these two lines: `#sed -i.bak 's/-lfreetype.*/-lfreetype -lharfbuzz -lpthread/' "$PKG_CONFIG_PATH/freetype2.pc" # for some reason it lists harfbuzz as Requires.private only??` `#sed -i.bak 's/-lharfbuzz.*/-lharfbuzz -lfreetype/' "$PKG_CONFIG_PATH/harfbuzz.pc" # does anything even use this?`
> 
> Those two commented lines are the ones that got rid of the "libbluray not found using pkg-config" error.
> 
> The build command line I'm using is: `./cross_compile_ffmpeg.sh --gcc-cpu-count=$(nproc) --disable-nonfree=n --compiler-flavors=win64`
> 
> May be someone can test this [forked ](https://github.com/jam365/ffmpeg-windows-build-helpers) branch and if it works fine for you too we can work on a pull request to bring the changes here.

Thank you very much. It compiled without issue in Arch Linux!

**Comment by rdp** [comment]
ffbuild/config.log file should tell you what it thinks went wrong?
