### ISSUE TITLE
Using docker makes an error when building shared version

### ISSUE THREAD

**Issue by syehoonkim** [rdp/ffmpeg-windows-build-helpers#711]
Dear,
When I try to build docker with do-docker-build.sh file, cp in docker returns error message saying that there is no dir "ffmpeg_git_with_fdk_aac_shared".
I have figured out shared version's output dir is "ffmpeg_git_with_fdk_aac_master_shared".
After modifying docker-entry.sh, everything is okay.
Having tried to find why "_master" is inserted, but I couldn't do with my poor ability, that's why I don't make PR resolving this.
It will be great if you solve this problem.
Thank you.

**Comment by rdp** [comment]
OK so you didn't figure it out is that right?  Sorry I missed this!

**Comment by syehoonkim** [comment]
Dear,
I always appreciate you!!
For now, I am doing build job without docker, and so I haven't figured out what is happening in the script.
If you can find the problem and fix it, that will be great.
Thank you again!!
