### ISSUE TITLE
ffmpeg won't build using the  --ffmpeg-git-checkout-version flag

### ISSUE THREAD

**Issue by echoxxzz** [rdp/ffmpeg-windows-build-helpers#712]
If I try and build ffmpeg using the --ffmpeg-git-checkout-version flag the ffmpeg build fails with the following error:

ERROR: nvenc requested but not found.

**Comment by hydra3333** [comment]
eek.  what does the configure log say about it ?

**Comment by echoxxzz** [comment]
Here are my logs.
I included the logs using both ffmpeg n6.1-dev and n6.0.

[config.logs.zip](https://github.com/rdp/ffmpeg-windows-build-helpers/files/12773056/config.logs.zip)

**Comment by hydra3333** [comment]
Unfortunately the log does not seem very helpful.
Is there another log, say in the ffbuild folder or something ?

**Comment by rdp** [comment]
Full command line please?

**Comment by echoxxzz** [comment]
The full command I was using was: 

`cross_compile_ffmpeg.sh --disable-nonfree=n --compiler-flavors=win64 --prefer-stable=y --ffmpeg-git-checkout-version=n6.0`

After a bit of trial and error I was able to narrow it down to commit: _03823ac0c6a38bd6ba972539e3203a592579792f_.

If I use that commit or after it works fine but if I use any commit before it the build script fails with the nvenc requested but not found error.

This kind of makes sense since this was a change to the configure script related to nvenc.

**Comment by rdp** [comment]
it's working now?

**Comment by echoxxzz** [comment]
No it still only works using any ffmpeg commit after 03823ac0c6a38bd6ba972539e3203a592579792f. I think it has something to do with the new nvenc headers SDK 12.1 and it probably can't be fixed since the versions of the nvenc headers seem to have to match the  ffmpeg configure script.

**Comment by rdp** [comment]
gotcha, yeah you'd probably want to just disable nvenc for older builds
then (manually), sorry for the confusion

**Comment by FREEWING-JP** [comment]
This is Solution for nvenc  error .
https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/extra/wsl_patch_2023_10_for_n4_4_x.sh#L28
