### ISSUE TITLE
libaribcaption version not updating automatically

### ISSUE THREAD

**Issue by syehoonkim** [rdp/ffmpeg-windows-build-helpers#718]
Dear,
Thank you for your fascinating script.
I recently did git pull and tried to build, but it said that libaribcaption version was 1.0.1 rather than 1.1.1, so the configuring process didn't finish.
After manually building and installing libaribcaption, I could config and build.
Please check it out.
Thank you again.

**Comment by rdp** [comment]
if you nuke sandbox and try again still fails?

**Comment by syehoonkim** [comment]
Ah, maybe remaining sandbox directory has caused the problem. Let me check.

**Comment by syehoonkim** [comment]
Dear,
Sorry for being late.
It seems fine. I should add a command (rm -rf sandbox) in my periodic build shell script.
Thank you again!!

**Comment by rdp** [comment]
As long as you specify --git-get-latest=y (default) it should pull and recompile the latest...thanks for testing! :)
