### ISSUE TITLE
dcadec build stops with error

### ISSUE THREAD

**Issue by abarbieri** [rdp/ffmpeg-windows-build-helpers#73]
dcadec revision 6b08f4a stops with error:
make: *** No rule to make target `libdcadec/idct_fixed.h', needed by `libdcadec/idct_fixed.o'.  Stop.

previous revision e03e382 build did complete successfully.

**Comment by rdp** [comment]
if you nuke win32/dcadec_git and try again does it work?

**Comment by abarbieri** [comment]
yes, following that course of action makes the dcadec component build successfully.

worth adding a step to remove config when a git update is needed?

**Comment by rdp** [comment]
Oops I believe I did just that once but it appears that somehow the commit
never made it to github [and was reverted locally too].  OK pushed
something to try and fix it now.  Thanks for the note.

**Comment by rdp** [comment]
hopefully fixed now...
