### ISSUE TITLE
frei0r filter fix: requires libdlfcn and libpsapi

### ISSUE THREAD

**Issue by Warblefly** [rdp/ffmpeg-windows-build-helpers#74]
Running configure with parameters --enable-frei0r and --enable-filter=frei0r fails silently (other than posting a reference to an unlocatable function in config.log), and therefore the frei0r filter interface is not incorporated into libavfilter and FFmpeg.

The runtime symptom is "No such filter: frei0r"

Adding --extra-libs=-lpsapi cures the problem.

This problem has arisen in the last six or so months, possibly due to a change in libdlfcn whose README has contained this fix for a while. I've only just spotted it because we needed to use a frei0r filter.

**Comment by rdp** [comment]
OK try the latest, thanks for the note.  I also wrote a note to FFmpeg
informing them of the configure weirdness.
Cheers.
-r

**Comment by rdp** [comment]
should be fixed...

**Comment by SumitMarwha** [comment]
where i can find requires libdlfcn and libpsapi and how to use it

**Comment by rdp** [comment]
psapi is a "built in windows" dll libdlfcn is a library
https://github.com/dlfcn-win32
