### ISSUE TITLE
vamp-plugin-sdk offline (with workaround)

### ISSUE THREAD

**Issue by Codex-** [rdp/ffmpeg-windows-build-helpers#744]
The current URL used for acquiring `vamp-plugin-sdk-2.10.0.tar.gz` is offline:

Reference: https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/cross_compile_ffmpeg.sh#L1566C87-L1566C102

[![image](https://github.com/rdp/ffmpeg-windows-build-helpers/assets/8297838/d6f7b451-7382-434f-be71-365283b309a7)](https://www.isitdownrightnow.com/code.soundsoftware.ac.uk.html)

### Workaround

- Download from: https://wayback-api.archive.org/web/20211003163428/https://code.soundsoftware.ac.uk/attachments/download/2691/vamp-plugin-sdk-2.10.0.tar.gz
- Place at the top-level
- Update line referenced above: 
  - Before: `download_and_unpack_file https://code.soundsoftware.ac.uk/attachments/download/2691/vamp-plugin-sdk-2.10.0.tar.gz`
  - After: `download_and_unpack_file file://$top_dir/vamp-plugin-sdk-2.10.0.tar.gz`

### Thoughts

A few ways to remedy this

- Since this project is on github, could this fetch from here: https://github.com/vamp-plugins/vamp-plugin-sdk/releases/tag/vamp-plugin-sdk-v2.10
- Clone the repo at `tags/vamp-plugin-sdk-v2.10`
  - There appears to be some active development still on the build side of things, check out [`master`](https://github.com/vamp-plugins/vamp-plugin-sdk/commits/master/)

**Comment by rdp** [comment]
working OK now? happy to switch to a more reliable url...

**Comment by Codex-** [comment]
Seems to be working again now, cheers
