### ISSUE TITLE
harfbuzz configure error (with workaround)

### ISSUE THREAD

**Issue by Codex-** [rdp/ffmpeg-windows-build-helpers#745]
The new `9.0` release of `harfbuzz` has removed `autogen.sh` which is depended on for configuration here: https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/cross_compile_ffmpeg.sh#L1050

For now you can work around this by targeting the last 8.x tag when checking out the repository, until such a time as this block can be updated to use `Meson` for configuration.

## Workaround
- Update line referenced referenced above:
  - Before: `do_git_checkout https://github.com/harfbuzz/harfbuzz.git harfbuzz_git "origin/main"`
  - After: `do_git_checkout https://github.com/harfbuzz/harfbuzz.git harfbuzz_git "tags/8.5.0"`

**Comment by Codex-** [comment]
In devcontainers, on windows I didn't have an issue building harfbuzz with the workaround I posted above, however on mac I encountered that when trying to build using `8.5.0` there were some changes required `main`, namely some additions of `unsigned` that were added:

- `_double_parser_index_offsets`
  - https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-number-parser.hh#L45
- `_use_syllable_machine_indicies`
  - https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-ot-shaper-use-machine.hh#L160
- `_inds` in `find_syllables_use`
  - https://github.com/harfbuzz/harfbuzz/blob/8.5.0/src/hb-ot-shaper-use-machine.hh#L941
- `_indic_syllable_machine_indicies`
  - https://github.com/harfbuzz/harfbuzz/blob/8.5.0/src/hb-ot-shaper-indic-machine.hh#L143
- `_inds` in `find_syllables_indic`
  - https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-ot-shaper-indic-machine.hh#L484
- `_indic_syllable_machine_trans_targs`
  - https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-ot-shaper-indic-machine.hh#L326

Hope this helps someone 🙏

**Comment by rdp** [comment]
does  93930fb1c49b85 work on both?

**Comment by Codex-** [comment]
> does 93930fb1c49b85 work on both?

Sure does!

**Comment by rdp** [comment]
Thanks for the report!
