### ISSUE TITLE
eXtra-fast Essential Video Encoder (XEVE) support plan?

### ISSUE THREAD

**Issue by syehoonkim** [rdp/ffmpeg-windows-build-helpers#750]
Hello
I always thank you for this great work.
Today, I found that ffmpeg from this repo doesn't support eXtra-fast Essential Video Encoder (XEVE).
According to the FFmpeg doc(https://www.ffmpeg.org/ffmpeg-codecs.html#libxeve), I have to pass <code>--enable-libxeve</code> argument and have libxeve(https://github.com/mpeg5/xeve).
Do you have plan to support this?

**Comment by rdp** [comment]
Possibly someday, a PR would help speed it up :)

**Comment by syehoonkim** [comment]
I was able to build ffmpeg with XEVE and XEVD, but I needed to copy dlls such as libxeve.dll. I don't know how to integrate the dlls into ffmpeg binary.
How can I do it? If I succeed, I will make a PR.

**Comment by rdp** [comment]
Hmm you'll want to build it as a "static" library...does it have that build
option? Or show me what you have...

**Comment by syehoonkim** [comment]
I checked out, but there is no static library option.
I assume I must have the dll files to use these codecs, so I am gonna give up.
Thank you!!
