### ISSUE TITLE
[filter] add drawtext filter support

### ISSUE THREAD

**Issue by xengine-qyt** [rdp/ffmpeg-windows-build-helpers#755]
[AVFilterGraph @ 0000020f4dbfbf80] No such filter: 'drawtext'
[AVFilterGraph @ 0000020f4dbfbf80] Error processing filtergraph: Filter not found

ffmpeg 6.1.2 win64...not drawtext filter ...

ffmpeg doc:
```
Draw a text string or text from a specified file on top of a video, using the libfreetype library.

To enable compilation of this filter, you need to configure FFmpeg with --enable-libfreetype and --enable-libharfbuzz. To enable default font fallback and the font option you need to configure FFmpeg with --enable-libfontconfig. To enable the text_shaping option, you need to configure FFmpeg with --enable-libfribidi.
```

lost libfontconfig and libharfbuzz?

**Comment by rdp** [comment]
this "used" to work hmm

**Comment by xengine-qyt** [comment]
> this "used" to work hmm

a?what is used mean?

**Comment by k-yaegashi** [comment]
Surely, `--enable-libharfbuzz` is missing. You have only to add
```
--- a/cross_compile_ffmpeg.sh
+++ b/cross_compile_ffmpeg.sh
@@ -2431,6 +2471,7 @@ build_ffmpeg() {
     config_options+=" --enable-libflite"
     config_options+=" --enable-libfreetype"
     config_options+=" --enable-libfribidi"
+    config_options+=" --enable-libharfbuzz"
     config_options+=" --enable-libgme"
     config_options+=" --enable-libgsm"
     config_options+=" --enable-libilbc"
```
and `drawtext` is available back again.

**Comment by xengine-qyt** [comment]
> Surely, `--enable-libharfbuzz` is missing. You have only to add
> 
> ```
> --- a/cross_compile_ffmpeg.sh
> +++ b/cross_compile_ffmpeg.sh
> @@ -2431,6 +2471,7 @@ build_ffmpeg() {
>      config_options+=" --enable-libflite"
>      config_options+=" --enable-libfreetype"
>      config_options+=" --enable-libfribidi"
> +    config_options+=" --enable-libharfbuzz"
>      config_options+=" --enable-libgme"
>      config_options+=" --enable-libgsm"
>      config_options+=" --enable-libilbc"
> ```
> 
> and `drawtext` is available back again.

thanks.
