### ISSUE TITLE
QSV not working

### ISSUE THREAD

**Issue by rboy1** [rdp/ffmpeg-windows-build-helpers#76]
when trying to use the intel h264 qsv codec with the built version of ffmpeg it doesn't work. am wondering if this has something to do with the build script (I don't see any compiler flags for it).
Also not sure if this is the right place to post this since I can't find a forum.
Handbrake runs fine with the qsv codec, ffmpeg gives this error

ffmpeg -i test.ts -vcodec h264_qsv -b:v 4000k -an test.mp4

Stream mapping:
  Stream #0:2 -> #0:0 (mpeg2video (native) -> h264 (h264_qsv))
  Stream #0:0 -> #0:1 (ac3 (native) -> aac (libfaac))
Press [q] to stop, [?] for help
Video encoding failed

**Comment by rdp** [comment]
the fact that it "knows about h264_qsv" means the encoder is in place.  I don't know anything else about it, maybe ask on the ffmpeg-user mailing list?

**Comment by crapulent** [comment]
hello
I understand it probably is not the right place to ask this question, btw
@rboy1 did you find the solution to your problem?
I expirience same one: build ffmpeg with this (awesome) helpers with two lines containing qsv uncommented and recieve same error when trying to encode with h264_qsv. same time decoding with h264_qsv works great.

**Comment by rboy1** [comment]
No I didn't get any response from anyone. I also see that the dev reported:
Please try to set lover features version into the /libavcodec/qsv_internal.h:
change
#define QSV_VERSION_MINOR 9
to
#define QSV_VERSION_MINOR 6
and recompile the ffmpeg.

**Comment by rdp** [comment]
any updates here, or does it still fail (with the latest)? Do you have a
link to where the dev recommends changing something/

**Comment by rdp** [comment]
See also http://trac.ffmpeg.org/ticket/4736
