### ISSUE TITLE
--disable-decoder=aac breaks ffmpeg

### ISSUE THREAD

**Issue by rboy1** [rdp/ffmpeg-windows-build-helpers#77]
With the newer script, --disable-decoder=aac has been enabled, this breaks the ability of ffmpeg to use LATM tracks in files.

This is output from ffmpeg

    Stream #0:0[0x100](eng): Audio: aac_latm ([17][0][0][0] / 0x0011), 0 channels (hearing impaired)
    Stream #0:1[0x101](eng): Audio: aac_latm ([17][0][0][0] / 0x0011), 0 channels

Checked without the flag and it works fine

anyone have an idea why was this flag included?

**Comment by rdp** [comment]
Looks like it was to "force VLC to use fdk-aac" but I've removed it as per your request, thanks for the note.
