### ISSUE TITLE
VP9

### ISSUE THREAD

**Issue by CoolOppo** [rdp/ffmpeg-windows-build-helpers#78]
There doesn't appear to be any support for VP9. I don't know what to do to make this happen, or I would have made a pull request. I've been trying for like an hour to compile it with MXE and everything, and haven't yet succeeded in my efforts.

**Comment by rdp** [comment]
there "should" be support for vp9 already (it uses libvpx v1.3.0) does it
not work for you?
http://wiki.webmproject.org/ffmpeg/vp9-encoding-guide
Anyway I also bumped the libvpx version to 1.4.0 while I was looking at
this, enjoy!
-roger-

**Comment by CoolOppo** [comment]
I'll give it a try as soon as I can!

**Comment by rdp** [comment]
I'll assume it worked out :)
