### ISSUE TITLE
h264_qsv and hevc_qsv crashes on windows 8.1

### ISSUE THREAD

**Issue by rmkimathi** [rdp/ffmpeg-windows-build-helpers#81]
I use the cross_compile_ffmpeg.sh to build my ffmpeg. I have enabled –enable-libmfx and build_intel_quicksync_mfx. However h264_qsv and hevc_qsv crashes on windows 8.1 x64

**Comment by rdp** [comment]
When you use them you mean?

**Comment by rmkimathi** [comment]
Yes sir when i use ffmpeg to convert video. This worked on an earlier build a few weeks ago

**Comment by rdp** [comment]
I know there have been some changes to the qsv stuff recently [?] so I
doubt it's actually a problem with the build per se...hmm...maybe file an
ffmpeg trac with the failure on it?

**Comment by rmkimathi** [comment]
I do not know how to file an ffmpeg trac .. however the encoding report indicates q=-0.0 in previous encodes that value is q=0.0
frame=  130 fps=0.0 q=-0.0 size=     564kB time=00:00:05.34 bitrate= 865.3kbits/s    
frame=  330 fps=330 q=-0.0 size=    1703kB time=00:00:13.63 bitrate=1023.7kbits/s

**Comment by rdp** [comment]
Or maybe report it to ffmpeg-user mailing list
http://trac.ffmpeg.org is where they get filed.

**Comment by rmkimathi** [comment]
Thanks rdp. I registered at http://trac.ffmpeg.org/ and created a ticket for the bug.

**Comment by rdp** [comment]
thanks!

**Comment by rdp** [comment]
link to bug please? :)

**Comment by rmkimathi** [comment]
Latest ffmpeg build has been fixed.


Sent from my Samsung device

-------- Original message --------

**Comment by rmkimathi** [comment]
Thank you!


Sent from my Samsung device

-------- Original message --------

**Comment by rmkimathi** [comment]
http://trac.ffmpeg.org/ticket/4736
