### ISSUE TITLE
DeckLinkAPIVersion.h needed

### ISSUE THREAD

**Issue by Warblefly** [rdp/ffmpeg-windows-build-helpers#84]
Hello,

After some very recent changes to FFmpeg's interaction with Blackmagic Design's products, FFmpeg now needs to see the header DeckLinkAPIVersion.h

Today, I'm using the version 10.3 header. I tried 10.4 but it didn't work with the headers as they are in the ffmpeg-windows-build-helpers project.

There's a copy of the version 10.3 header here:

https://raw.githubusercontent.com/jp9000/obs-studio/master/plugins/decklink/mac/decklink-sdk/DeckLinkAPIVersion.h

With a bit more effort I can probably get this from BlackMagic directly.

I do not yet have a DeckLink card so have not tested whether this build works at all. Nor am I sure which version of the SDK was used to generate the exceedingly helpful DeckLink headers available from the ffmpeg-windows-build-helpers project.

Putting this header (adding it to your "build_decklink" section in the shell script) allows FFmpeg to build once more.

```c
#ifndef __DeckLink_API_Version_h__
#define __DeckLink_API_Version_h__

#define BLACKMAGIC_DECKLINK_API_VERSION					0x0a030100
#define BLACKMAGIC_DECKLINK_API_VERSION_STRING			"10.3.1"

#endif	// __DeckLink_API_Version_h__
```

**Comment by rdp** [comment]
thanks for the tip, hopefully working now :)
-roger-
