### ISSUE TITLE
libcaca error

### ISSUE THREAD

**Issue by MadMarty** [rdp/ffmpeg-windows-build-helpers#87]
downloading https://distfiles.macports.org/libcaca/libcaca-0.99.beta18.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   309  100   309    0     0    427      0 --:--:-- --:--:-- --:--:--   427
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Archive:  libcaca-0.99.beta18.tar.gz
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of libcaca-0.99.beta18.tar.gz or
        libcaca-0.99.beta18.tar.gz.zip, and cannot find libcaca-0.99.beta18.tar.gz.ZIP, period.

**Comment by MadMarty** [comment]
it works if you update to libcaca-0.99.beta19.tar.gz

**Comment by MadMarty** [comment]
if you update to libcaca-0.99.beta19.tar.gz you will get:

Makefile:800: recipe for target 'libcaca_la-string.lo' failed
make[2]: *** [libcaca_la-string.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/usr/pkg/sandbox/win32/libcaca-0.99.beta19/caca'
Makefile:530: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/pkg/sandbox/win32/libcaca-0.99.beta19'
Makefile:424: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MadMarty** [comment]
workaround: change source_path to

http://ffmpeg.zeranoe.com/builds/source/external_libraries/libcaca-0.99.beta18.tar.xz

**Comment by rdp** [comment]
OK hopefully overcame this now:
3650b87 and reported it here: https://github.com/cacalabs/libcaca/issues/8
