### ISSUE TITLE
uncomment :  --enable-libmfx #[not windows xp friendly] does not work

### ISSUE THREAD

**Issue by rmkimathi** [rdp/ffmpeg-windows-build-helpers#88]
... and also this line uncomment :

--enable-libmfx #[not windows xp friendly]

This did not work. I had to add --enable-libmfx to the config_options. May be:

config_options="$config_options --enable-libmfx" #[not windows xp friendly]

**Comment by rdp** [comment]
OK I tried to make it more clear in https://github.com/rdp/ffmpeg-windows-build-helpers/commit/2932ebf29fad8253dea108e0cb0b3d3fe7ae8b5b

**Comment by rmkimathi** [comment]
I am referring to line 2 --enable-libmfx, compile skips with error that command is not found

**Comment by rdp** [comment]
Oops you're right.  Maybe I should make it into a config parameter...

**Comment by rmkimathi** [comment]
Thank you for identifying that small oversight. I love your script! I have learnt how to cross compile by dissecting and tearing your script apart plus a lot of Googling. However when you are free please show me how to cross compile SDL and get it to work.

**Comment by rdp** [comment]
the only thing I know about it is this:
https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/cross_compile_ffmpeg.sh#L1007
Which is quite a bit and annoying LOL :)

**Comment by rmkimathi** [comment]
Okay. I get it. Thanks
