### ISSUE TITLE
libx265 missing <stdbool.h>

### ISSUE THREAD

**Issue by Warblefly** [rdp/ffmpeg-windows-build-helpers#89]
As of a couple of days ago, on compiling libx265 followed by FFmpeg, the configure tests in FFmpeg show the new `bool` for `bScenecut` in x265.h to be an "unknown type name". Adding <stdbool.h> to the headers fixes this for me, with the patch given below.

Environment: cross-compiling using mingw32-w64-x86_64-gcc version 5.2.0 with mingw-w64 version 4.0.4

```diff
--- source/x265.h.orig  2015-08-31 14:39:07.197126527 +0000
+++ source/x265.h       2015-08-31 14:39:26.953126527 +0000
@@ -25,6 +25,7 @@
 #define X265_H

 #include <stdint.h>
+#include <stdbool.h>
 #include "x265_config.h"

 #ifdef __cplusplus
```

**Comment by rdp** [comment]
I think this is working now [possibly x265 fixed it upstream?]
