### ISSUE TITLE
cmake stuck on "CMakeDetermineSystem.cmake(48)"

### ISSUE THREAD

**Issue by tjeh** [rdp/ffmpeg-windows-build-helpers#94]
Hi,

I am trying to build ffmpeg on a Windows machine using cygwin. However building seems to fail / get stuck at anytime "cmake" is used in the script. Using the debug and trace parameters the following log is generated. Trying to compile ffmpeg without the plugin below (frei0r) will not help as the script will get stuck on the next cmake with the same error.

Furthermore the **"curl"** package is not automatically installed within cygwin when using the *build_locally_with_various_option_prompts.bat*. It seems to be missing in the [parameters passed] (https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/native_build/build_locally_with_various_option_prompts.bat#L26) to the *setup-x86.exe*.

**Log Output**
[...]
Running with debug output on.
Running with trace output on.
/cygdrive/c/apps/ffmpegqsv/native_build/ffmpeg_local_builds/sandbox/win32/frei0r
-plugins-1.4/CMakeLists.txt(1):  cmake_minimum_required(VERSION 2.8 )
   Called from: [1]     /cygdrive/c/apps/ffmpegqsv/native_build/ffmpeg_local_builds/sandbox/win32/frei0r-plugins-1.4/CMakeLists.txt
/cygdrive/c/apps/ffmpegqsv/native_build/ffmpeg_local_builds/sandbox/win32/frei0r-plugins-1.4/CMakeLists.txt(3):  list(APPEND CMAKE_MODULE_PATH {CMAKE_SOURCE_DIR}/cmake/modules )
   Called from: [1]     /cygdrive/c/apps/ffmpegqsv/native_build/ffmpeg_local_builds/sandbox/win32/frei0r-plugins-1.4/CMakeLists.txt
/cygdrive/c/apps/ffmpegqsv/native_build/ffmpeg_local_builds/sandbox/win32/frei0r-plugins-1.4/CMakeLists.txt(5):  project(frei0r )
   Called from: [1]     /cygdrive/c/apps/ffmpegqsv/native_build/ffmpeg_local_builds/sandbox/win32/frei0r-plugins-1.4/CMakeLists.txt
/usr/share/cmake-3.3.1/Modules/CMakeUnixFindMake.cmake(15):  find_program(CMAKE_MAKE_PROGRAM NAMES gmake make smake )
   Called from: [2]     /usr/share/cmake-3.3.1/Modules/CMakeUnixFindMake.cmake
                [1]     /cygdrive/c/apps/ffmpegqsv/native_build/ffmpeg_local_builds/sandbox/win32/frei0r-plugins-1.4/CMakeLists.txt
/usr/share/cmake-3.3.1/Modules/CMakeUnixFindMake.cmake(16):  mark_as_advanced(CMAKE_MAKE_PROGRAM )
   Called from: [2]     /usr/share/cmake-3.3.1/Modules/CMakeUnixFindMake.cmake
                [1]     /cygdrive/c/apps/ffmpegqsv/native_build/ffmpeg_local_builds/sandbox/win32/frei0r-plugins-1.4/CMakeLists.txt
/usr/share/cmake-3.3.1/Modules/CMakeUnixFindMake.cmake(19):  if(NOT CMAKE_MAKE_PROGRAM AND CMAKE_HOST_APPLE )
   Called from: [2]     /usr/share/cmake-3.3.1/Modules/CMakeUnixFindMake.cmake
                [1]     /cygdrive/c/apps/ffmpegqsv/native_build/ffmpeg_local_builds/sandbox/win32/frei0r-plugins-1.4/CMakeLists.txt
/usr/share/cmake-3.3.1/Modules/CMakeDetermineSystem.cmake(45):  if(CMAKE_HOST_UNIX )
   Called from: [2]     /usr/share/cmake-3.3.1/Modules/CMakeDetermineSystem.cmake
                [1]     /cygdrive/c/apps/ffmpegqsv/native_build/ffmpeg_local_builds/sandbox/win32/frei0r-plugins-1.4/CMakeLists.txt
/usr/share/cmake-3.3.1/Modules/CMakeDetermineSystem.cmake(46):  find_program(CMAKE_UNAME uname /bin /usr/bin /usr/local/bin )
   Called from: [2]     /usr/share/cmake-3.3.1/Modules/CMakeDetermineSystem.cmake
                [1]     /cygdrive/c/apps/ffmpegqsv/native_build/ffmpeg_local_builds/sandbox/win32/frei0r-plugins-1.4/CMakeLists.txt
/usr/share/cmake-3.3.1/Modules/CMakeDetermineSystem.cmake(47):  if(CMAKE_UNAME )
   Called from: [2]     /usr/share/cmake-3.3.1/Modules/CMakeDetermineSystem.cmake
                [1]     /cygdrive/c/apps/ffmpegqsv/native_build/ffmpeg_local_builds/sandbox/win32/frei0r-plugins-1.4/CMakeLists.txt
**/usr/share/cmake-3.3.1/Modules/CMakeDetermineSystem.cmake(48):  exec_program(uname ARGS -s OUTPUT_VARIABLE CMAKE_HOST_SYSTEM_NAME )
   Called from: [2]     /usr/share/cmake-3.3.1/Modules/CMakeDetermineSystem.cmake
                [1]     /cygdrive/c/apps/ffmpegqsv/native_build/ffmpeg_local_builds/sandbox/win32/frei0r-plugins-1.4/CMakeLists.txt**

Regards
tjeh

**Comment by rdp** [comment]
that is odd, it does use curl and curl is required, yet it seems to work without it being called out (possibly a dependency of the other things it does install?) anyway called it out explicitly now.  I did a full rebuild (at least on my windows vista box) and everything seemed to work OK could you try opening native_build\ffmpeg_local_builds\cygwin_local_install\cygwin.bat and see if uname works there...

**Comment by rdp** [comment]
I am still unable to repro this, reopen if it's still the case, cheers!

**Comment by rdp** [comment]
oops that was meant for a different issue LOL.  I'm going to try and repro this one.

**Comment by rdp** [comment]
seems to work OK here...virus scan issue?
