### ISSUE TITLE
enable Intel QSV for Windows

### ISSUE THREAD

**Issue by SanteR1** [rdp/ffmpeg-windows-build-helpers#96]
"to enable Intel QSV (vista+ compatible only) Modify the script so the following two lines aren't commented out: # build_intel_quicksync_mfx and this one: # config_options="$config_options --enable-libmfx""

Please! Help me...
What file I need to edit for windows build (for enable QSV)
1) I run cross_compile_ffmpeg.sh, but not work in Windows (swap error) 
then I run script in "native_build" folder ...
And i dont find where uncomment this -# build_intel_quicksync_mfx and this one: # config_options="$config_options --enable-libmfx"

Help me correctly build ffmpeg + QSV for Windows.
thanks (p.s. excuse me for my bad English)

**Comment by rdp** [comment]
OK added a command line parameter to make it easier (run with -h to see what it is)
