### ISSUE TITLE
downloading ftp://xmlsoft.org/libxml2/libxml2-2.9.0.tar.gz failed .and can I get it by other ways?

### ISSUE THREAD

**Issue by makefriend8** [rdp/ffmpeg-windows-build-helpers#98]
first I do
sudo ./cross_compile_ffmpeg.sh
but download ftp://xmlsoft.org/libxml2/libxml2-2.9.0.tar.gz  failed(becasue of some internet reason)

so  I get the    libxml2-2.9.0.tar.gz(from http://xmlsoft.org/sources/ibxml2-2.9.0.tar.gz),  and put it into sandbox/win32 ,
and then run  sudo ./cross_compile_ffmpeg.sh
but  the command still downloading ftp://xmlsoft.org/libxml2/libxml2-2.9.0.tar.gz  and then delete my libxml2-2.9.0.tar.gz .

so what should I do ?

**Comment by rdp** [comment]
OK made an untested attempt at it, could you try it again please?

**Comment by rdp** [comment]
seems the new path works ok, thanks for the note
